// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t pad_int8_1_output[50] = {
    -128, -128, -128, -128, -128, -128, -35,  83,   -128, -128,
    -128, 120,  115,  -128, -128, -128, -128, -128, -128, -128,
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    -128, 23,   -123, -128, -128, -128, -66,  -103, -128, -128,
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128};
