var searchData=
[
  ['nmsis_5fnn_5factivation_321',['nmsis_nn_activation',['../structnmsis__nn__activation.html',1,'']]],
  ['nmsis_5fnn_5fcontext_322',['nmsis_nn_context',['../structnmsis__nn__context.html',1,'']]],
  ['nmsis_5fnn_5fconv_5fparams_323',['nmsis_nn_conv_params',['../structnmsis__nn__conv__params.html',1,'']]],
  ['nmsis_5fnn_5fdims_324',['nmsis_nn_dims',['../structnmsis__nn__dims.html',1,'']]],
  ['nmsis_5fnn_5fdw_5fconv_5fparams_325',['nmsis_nn_dw_conv_params',['../structnmsis__nn__dw__conv__params.html',1,'']]],
  ['nmsis_5fnn_5ffc_5fparams_326',['nmsis_nn_fc_params',['../structnmsis__nn__fc__params.html',1,'']]],
  ['nmsis_5fnn_5flayer_5fnorm_327',['nmsis_nn_layer_norm',['../structnmsis__nn__layer__norm.html',1,'']]],
  ['nmsis_5fnn_5flstm_5fclip_5fparams_328',['nmsis_nn_lstm_clip_params',['../structnmsis__nn__lstm__clip__params.html',1,'']]],
  ['nmsis_5fnn_5flstm_5fcontext_329',['nmsis_nn_lstm_context',['../structnmsis__nn__lstm__context.html',1,'']]],
  ['nmsis_5fnn_5flstm_5fdims_330',['nmsis_nn_lstm_dims',['../structnmsis__nn__lstm__dims.html',1,'']]],
  ['nmsis_5fnn_5flstm_5fguard_5fparams_331',['nmsis_nn_lstm_guard_params',['../structnmsis__nn__lstm__guard__params.html',1,'']]],
  ['nmsis_5fnn_5flstm_5fparams_332',['nmsis_nn_lstm_params',['../structnmsis__nn__lstm__params.html',1,'']]],
  ['nmsis_5fnn_5fper_5fchannel_5fquant_5fparams_333',['nmsis_nn_per_channel_quant_params',['../structnmsis__nn__per__channel__quant__params.html',1,'']]],
  ['nmsis_5fnn_5fper_5ftensor_5fquant_5fparams_334',['nmsis_nn_per_tensor_quant_params',['../structnmsis__nn__per__tensor__quant__params.html',1,'']]],
  ['nmsis_5fnn_5fpool_5fparams_335',['nmsis_nn_pool_params',['../structnmsis__nn__pool__params.html',1,'']]],
  ['nmsis_5fnn_5fscaling_336',['nmsis_nn_scaling',['../structnmsis__nn__scaling.html',1,'']]],
  ['nmsis_5fnn_5fsoftmax_5flut_5fs16_337',['nmsis_nn_softmax_lut_s16',['../structnmsis__nn__softmax__lut__s16.html',1,'']]],
  ['nmsis_5fnn_5fsvdf_5fparams_338',['nmsis_nn_svdf_params',['../structnmsis__nn__svdf__params.html',1,'']]],
  ['nmsis_5fnn_5ftile_339',['nmsis_nn_tile',['../structnmsis__nn__tile.html',1,'']]],
  ['nmsis_5fnn_5ftranspose_5fconv_5fparams_340',['nmsis_nn_transpose_conv_params',['../structnmsis__nn__transpose__conv__params.html',1,'']]]
];
