// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_3_output_multiplier[8] = {
    1203522048, 1109409152, 1180960768, 1181181184,
    1201816960, 1206275968, 1127534080, 1167379584};

const int32_t *const int16xint8xint32_3_output_mult = int16xint8xint32_3_output_multiplier;
