// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t avgpooling_int16_1_output[30] = {
    9225,   -23673, -27724, -30787, 23331,  6814,  3929,   -21102,
    17856,  -7733,  -26727, -15837, -21983, -4912, -19541, 12234,
    -20034, -27338, 21008,  6216,   -6611,  23906, -4144,  -7321,
    -27541, 31869,  -24106, -26406, 30230,  13929};
