// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maximum_broadcast_width_int8_input_tensor_2[38] = {
    -75,  53,  -103, 13,   102, 91,   -119, -125, -109, 23,   42,  123, -122,
    -126, -61, -116, -68,  97,  -35,  -9,   -86,  -40,  -31,  -78, 66,  64,
    -49,  54,  -121, -128, 111, -110, 18,   -18,  28,   -125, 61,  -92};
