// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_cell_gate_input_weights[42] = {
    39,  127,  39, -40, 45,   -2, 88, -75,  46,  12,   -29, 116, 24,   -85,
    -42, -101, 89, -60, -44,  32, 0,  -108, -65, 90,   -10, -77, 93,   115,
    57,  -31,  82, 48,  -121, 10, 58, -59,  66,  -121, 0,   -71, -116, -20};
