// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_cell_gate_hidden_weights[49] = {
    13,   104, -19,  114, 92, -7,   51,   -110, -54, 47,  115,  -73, 77,
    -89,  -27, 83,   -70, 79, 109,  -125, -123, 11,  31,  -116, 17,  -22,
    -103, -82, -127, 60,  59, 101,  103,  -93,  67,  -17, 84,   -26, 108,
    -7,   -19, 110,  68,  39, -124, 104,  -47,  74,  -115};
