// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_forget_gate_hidden_weights[49] = {
    68,  103,  9,   114, 1,   127, -2,  21,  33,  -49, 87, 5,  -29,
    58,  -115, -11, -33, 85,  -19, 120, -31, 87,  77,  85, 14, -95,
    -79, -52,  -28, 119, -46, 89,  58,  66,  -1,  67,  10, 58, -5,
    -75, 3,    65,  53,  -59, -67, 43,  91,  -41, 119};
