// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_forget_gate_input_weights[42] = {
    -12, -91, -69, -77,  97,  100, -26, -71, 113, 107, -115, -41, -58, 126,
    -82, 96,  -74, -108, 8,   -69, 49,  96,  -9,  51,  119,  -28, 127, -10,
    9,   31,  13,  125,  127, -13, -64, -86, -33, 89,  81,   -64, -44, 69};
