// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_tensor[54] = {
    -72, -49, -51, -63,  -115, -43, 27,   -66, 35,   -87, -103, -97, 40,  -62,
    15,  -19, 109, -120, 111,  -11, -101, -37, -128, -89, 115,  16,  41,  105,
    -39, -64, 33,  -112, -102, 120, -128, -80, 31,   -21, -85,  44,  -48, 43,
    -67, 84,  -91, 43,   -79,  111, 20,   61,  69,   -26, -81,  -127};
