// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_gate_input_weights[42] = {
    -34, 104, -114, 103, 28,  -98,  5,   44,  -58, -96, -29, -60, 61, -52,
    52,  1,   127,  121, 69,  -49,  11,  28,  -15, 103, -76, -11, 67, -34,
    -65, -79, 115,  114, -45, -124, 116, -13, -4,  -4,  -56, -84, 63, 126};
