// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_gate_hidden_weights[49] = {
    -36, -121, 93,  -59, 18, -3,  67,  -59, -104, -77,  -76,  -51,  -54,
    112, 63,   119, -50, -4, 74,  -16, 36,  104,  52,   -50,  -71,  48,
    46,  -124, -88, 113, 24, -58, -42, -92, 5,    -101, -107, -103, 27,
    0,   -46,  39,  -83, 10, -16, 81,  98,  110,  127};
