// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_output_gate_hidden_weights[49] = {
    -53,  -57,  43,  66,  92, -63, -98, 127,  28,  -3,  60, -80, -125,
    -122, -120, -24, -50, 23, 106, 6,   40,   -92, 124, 75, -39, -54,
    -119, -61,  112, -52, 1,  -98, 114, -124, 106, 91,  0,  -28, -81,
    34,   -83,  -42, 6,   32, 76,  -19, -82,  -84, 118};
