// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_output_gate_input_weights[42] = {
    22, 24,  -6,   117, 118,  50,   -64, 103, -11, -117, 18,  15, -37,  -19,
    30, -70, -124, -91, -126, -125, 115, -35, 116, 20,   -99, 70, -1,   -9,
    60, -47, 41,   55,  3,    -64,  -91, 123, -81, -117, -2,  73, -127, -76};
