// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_output[63] = {
    -9,  -21, -83, -44, -32,  -58,  -68,  7,   -6,  -71, -47, -17,  -68,
    -51, 71,  -26, -31, -120, 24,   -11,  -66, 48,  -34, -70, -73,  -19,
    29,  -64, 80,  -28, -85,  -102, -13,  12,  -65, -2,  -30, -102, -101,
    -17, -10, -62, 32,  -17,  -91,  -109, -24, -11, -69, 65,  -18,  -88,
    -74, -47, -45, -81, 50,   -37,  -115, -79, -46, -58, -85};
