// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t basic_2_int4_input_bias[15] = {
    44, 95, 27, -47, 73, 5, -44, -87, 18, 28, -127, 71, 38, 69, -36};

const int32_t *const basic_2_int4_biases = basic_2_int4_input_bias;
