// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t basic_2_int4_output_multiplier[15] = {
    1206637952, 1392225408, 1413578496, 1520117248, 1649040768,
    1532603520, 1577627904, 1530419968, 1330665472, 1747133952,
    1426428032, 1590278272, 1538383744, 1258375168, 1454332288};

const int32_t *const basic_2_int4_output_mult = basic_2_int4_output_multiplier;
