// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t basic_2_int4_output_shift[15] = {-6, -6, -9, -7, -6, -6, -6, -6,
                                               -7, -6, -7, -7, -7, -7, -6};
