// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t stride2pad1_int4_input_tensor[49] = {
    -46,  -106, 20,  38,  107, -37, 1,   -113, 112, 23, 67, -17, 108,
    126,  -35,  46,  -89, 94,  28,  -65, -109, -53, -3, 75, -59, 64,
    112,  -53,  -41, 70,  -93, -9,  2,   101,  104, 17, -3, 23,  -104,
    -122, -35,  -92, -30, 60,  51,  -15, -93,  -82, -44};

const int8_t *const stride2pad1_int4_input = stride2pad1_int4_input_tensor;
