// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t stride2pad1_int4_input_bias[1] = {126};

const int32_t *const stride2pad1_int4_biases = stride2pad1_int4_input_bias;
