// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t stride2pad1_int4_output[16] = {-3, -8, -7, -5, -9, -7, -9, 2,
                                            -6, -1, -6, 0,  -2, 1,  -2, 1};

const int8_t *const stride2pad1_int4_output_ref = stride2pad1_int4_output;
