// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_CHWN_IN_DIM                                                  \
    {                                                                          \
        5, 4, 12, 17,                                                          \
    }
#define TRANSPOSE_CHWN_PERM                                                    \
    {                                                                          \
        3, 1, 2, 0,                                                            \
    }
#define TRANSPOSE_CHWN_SIZE 4080
#define TRANSPOSE_CHWN_PERM_SIZE 4
#define TRANSPOSE_CHWN_OUT_DIM                                                 \
    {                                                                          \
        17, 4, 12, 5,                                                          \
    }
