// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_cell_gate_bias[11] = {
    32189, 2339, 24472, 16151, 21566, 7767, 30003, 3696, 28753, 959, 30780};
