// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_forget_gate_bias[11] = {
    28934, 1302, 10756, 13944, 16467, 3785, 20297, 15370, 24563, 4232, 21372};
