// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_input_gate_bias[11] = {
    13122, 20026, 13504, 18066, 28982, 4654, 17630, 14767, 5425, 29604, 10742};
