// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_output_gate_bias[11] = {
    29441, 24671, 25705, 11109, 4450, 17562, 1604, 5374, 13712, 24672, 17224};
