// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int64_t int16xint8_spill2_bias[9] = {-1280449, -744504,  2087647,
                                           1583873,  -3551994, -1573004,
                                           4044830,  -2425928, -1942254};

const int64_t *const int16xint8_spill2_biases = int16xint8_spill2_bias;
