// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill2_output_multiplier[9] = {
    1185187968, 1183517824, 1186874240, 1177924608, 1186972160,
    1179519488, 1184324992, 1182297472, 1183417856};

const int32_t *const int16xint8_spill2_output_mult = int16xint8_spill2_output_multiplier;
