variables:
  NUCLEI_SDK: git@gito:software/library/nuclei-sdk.git
  SDK_BRANCH: develop
  SOC: evalsoc
  RUNTARGET: qemu
  IMAGE: rego.corp.nucleisys.com/software/sdkbuild
  IMAGE_TAG: "2025.10"

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /draft|wip|stash/i
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /master|develop/ && $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH =~ /master|develop/
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG

default:
  tags:
    - env::docker
    - net::outside
    # when testing sdkbuild temp version
    # uncomment it to make jobs run on a fixed machine
    #- host::whml1
  image: $IMAGE:$IMAGE_TAG
  before_script:
    - free -g
    - uname -a
    - lscpu
  after_script:
    - free -g
    - ps aux | grep qemu

stages:
  - build
  - test
  - release

build_doc:
  stage: build
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
    changes:
      - NMSIS/doc/source/**/**/**/*
      - .gitlab-ci.yml
      - NMSIS/Core/
      - NMSIS/DSP/
      - NMSIS/NN/
  artifacts:
    when: always
    name: "nmsis_doc-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/doc/build
    expire_in: 2 day
  script:
    - cd NMSIS/doc
    - make clean
    - mkdir build
    - make all > build/build.log 2>&1
    - make latexpdf >> build/build.log 2>&1
    - make clean_xml
    - cp build/latex/*.pdf build/html/

build_library:
  stage: build
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    when: always
    name: "nmsis_library_nuclei_gnu-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/gen
      - NMSIS/build/*/*/build.log
      - NMSIS/build_gnu.log
    expire_in: 2 day
  variables:
    PARALLEL_OPTS: "-j8"
  script:
    - cd NMSIS
    - echo "Generate NMSIS Library for Nuclei RISC-V Processors with Nuclei GNU Toolchain"
    - make gen 2>&1 | tee build_gnu.log | grep -E "^Build\ Library|^\+|^\|"
    - buildsts=${PIPESTATUS[0]}
    - mkdir -p gen/
    - mv Library gen/
    - exit $buildsts

build_library_terapines:
  stage: build
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
  tags:
    - env::docker
    - env::nfs
    # - host::whml1
    - net::outside
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    when: always
    name: "nmsis_lib_terapines-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/gen_terapines
      - NMSIS/build_terapines.log
    expire_in: 2 day
  script:
    - cd NMSIS
    - echo "Setup Zcc toolchain PATH"
    - export PATH=/home/share/devtools/zcc/linux64/latest/bin/:$PATH
    - zcc -v
    - echo "Generate NMSIS Library for Nuclei RISC-V Processors with Terapines ZCC Toolchain"
    - make gen TOOLCHAIN=terapines 2>&1 | tee build_terapines.log | grep -E "^Build\ Library|^\+|^\|"
    - buildsts=${PIPESTATUS[0]}
    - mkdir -p gen_terapines/
    - |
      if [ -d "Library" ]; then
        mv Library gen_terapines/Library
      fi
    - exit $buildsts

build_library_llvm:
  stage: build
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
  tags:
    - env::docker
    - host::whml1
    - net::outside
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    when: always
    name: "nmsis_lib_nuclei_llvm-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/gen_nuclei_llvm
      - NMSIS/build_llvm.log
    expire_in: 2 day
  script:
    - cd NMSIS
    - echo "Setup llvm toolchain PATH"
    - export PATH=/home/share/devtools/toolchain/nuclei_gnu/linux64/newlibc/nuclei-2025/gcc/bin:$PATH
    - which riscv64-unknown-elf-clang
    - echo "Generate NMSIS Library for Nuclei RISC-V Processors with Nuclei LLVM Toolchain"
    - make gen TOOLCHAIN=nuclei_llvm 2>&1 | tee build_llvm.log | grep -E "^Build\ Library|^\+|^\|"
    - buildsts=${PIPESTATUS[0]}
    - mkdir -p gen_nuclei_llvm/
    - |
      if [ -d "Library" ]; then
        mv Library gen_nuclei_llvm/Library
      fi
    - exit $buildsts

build_align_library:
  stage: build
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    when: always
    name: "nmsis_align_library-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/Library
      - NMSIS/build.log
    expire_in: 2 day
  script:
    - cd NMSIS
    - echo "Generate NMSIS Library(Memory access without unalign R/W) for Nuclei RISC-V Processors"
    - make gen_unalign > build.log 2>&1

.test_job_template: &test_job_template_default
  stage: test
  timeout: 4h
  interruptible: true
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  before_script:
    - free -g
    - uname -a
    - lscpu
    # prepare for docker ssh environment
    ## https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # important: need to avoid git ssh asking yes/no when clone
    # https://serverfault.com/questions/469052/ssh-failing-from-script-working-on-command-line-git
    - ssh-keyscan gito > ~/.ssh/known_hosts
    - export SDK_COPY_OBJECTS="elf,map"
  dependencies:
    - build_library

test_nn_library:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_nn_test_cycles_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "rv32e"]
  script:
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen/Library .
    - make gen_nnref_lib
    - export SDK_VERB_BUILDMSG=0
    # generate test runner
    - python3 NN/Tests/UnitTest/Scripts/generate_test_runner.py
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_nn_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_nn --parallel=-j --make_options "SIMU=$RUNTARGET" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_nn_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_nn_library_terapines:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_nn_test_terapines_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  tags:
    - env::docker
    - env::nfs
    - net::outside
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "rv32e"]
  dependencies:
    - build_library_terapines
  script:
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    - echo "Setup Zcc toolchain PATH"
    - export PATH=/home/share/devtools/zcc/linux64/latest/bin/:$PATH
    - zcc -v
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen_terapines/Library .
    - make gen_nnref_lib
    - export SDK_VERB_BUILDMSG=0
    # generate test runner
    - python3 NN/Tests/UnitTest/Scripts/generate_test_runner.py
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_nn_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_nn_terapines --parallel=-j --make_options "SIMU=$RUNTARGET TOOLCHAIN=terapines" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_nn_terapines_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_nn_library_llvm:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_nn_test_llvm_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "rv32e"]
  dependencies:
    - build_library_llvm
  script:
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen_nuclei_llvm/Library .
    - make gen_nnref_lib
    - export SDK_VERB_BUILDMSG=0
    # generate test runner
    - python3 NN/Tests/UnitTest/Scripts/generate_test_runner.py
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_nn_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_nn_llvm --parallel=-j --make_options "SIMU=$RUNTARGET TOOLCHAIN=nuclei_llvm" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_nn_llvm_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_dsp_library:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_dsp_test_cycles_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "f16", "rv32e"]
  script:
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen/Library .
    - export SDK_VERB_BUILDMSG=0
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_dsp_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_dsp --parallel=-j --make_options "SIMU=$RUNTARGET" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_dsp_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_dsp_library_v2:
  <<: *test_job_template_default
  tags:
    - env::docker
    - net::outside
    - host::whml1
  artifacts:
    when: always
    name: "nmsis_dsp_test_cycles_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  parallel:
    matrix:
      - NUCLEI_DSP:
        - "testv2_q7"
        - "testv2_q15"
        - "testv2_q31"
        - "testv2_f16"
        - "testv2_f32"
        - "testv2_f64"
  script:
    - export PATH=/home/share/devtools/qemu/linux64/2025.11.12/bin:$PATH
    - which qemu-system-riscv32
    - pip install pyparsing
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen/Library .
    - export SDK_VERB_BUILDMSG=0
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_dsp_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_dsp --parallel=-j --make_options "SIMU=$RUNTARGET" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_dsp_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_dsp_library_terapines:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_dsp_test_terapines_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "f16", "rv32e"]
  tags:
    - env::docker
    - env::nfs
    - net::outside
  dependencies:
    - build_library_terapines
  script:
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    - echo "Setup Zcc toolchain PATH"
    - export PATH=/home/share/devtools/zcc/linux64/latest/bin/:$PATH
    - zcc -v
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen_terapines/Library .
    - export SDK_VERB_BUILDMSG=0
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_dsp_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_dsp_terapines --parallel=-j --make_options "SIMU=$RUNTARGET TOOLCHAIN=terapines" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_dsp_terapines_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

test_dsp_library_llvm:
  <<: *test_job_template_default
  artifacts:
    when: always
    name: "nmsis_dsp_test_llvm_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis_*.zip
      - NMSIS/Logs
    expire_in: 2 day
  tags:
    - env::docker
    - host::whml1
    - net::outside
  parallel:
    matrix:
      - NUCLEI_DSP: ["rv32_NO", "rv64_NO", "N1", "N2", "N3", "f16", "rv32e"]
  dependencies:
    - build_library_llvm
  script:
    - echo "Setup llvm toolchain PATH"
    - export PATH=/home/share/devtools/toolchain/nuclei_gnu/linux64/newlibc/nuclei-2025/gcc/bin:$PATH
    - which riscv64-unknown-elf-clang
    - git clone -b $SDK_BRANCH $NUCLEI_SDK NMSIS/nuclei_sdk
    - export NUCLEI_SDK_ROOT=$(readlink -f NMSIS/nuclei_sdk)
    - export NUCLEI_SDK_NMSIS=$(readlink -f NMSIS)
    - export NMSIS_LOGS=$NUCLEI_SDK_NMSIS/Logs
    # change ilm/dlm size from 64K to 1M for ${SOC}
    - sed -i "s/64K/1M/g" $NUCLEI_SDK_ROOT/SoC/${SOC}/Board/nuclei_fpga_eval/Source/GCC/gcc_${SOC}_ilm.ld
    # change ilm/dlm size from 64K to 1M for evalsoc from Nuclei SDK 0.6.0
    - |
      EVALSOC_MEMORY=$NUCLEI_SDK_ROOT/SoC/evalsoc/Board/nuclei_fpga_eval/Source/GCC/evalsoc.memory
      if [ -f $EVALSOC_MEMORY ] ; then
        echo "Maybe you are using >= Nuclei SDK 0.6.0, will sed and replace ilm/dlm memory size in $EVALSOC_MEMORY"
        sed -i 's/\([ID]LM_MEMORY_SIZE\).*/\1 = 0x100000;/' $EVALSOC_MEMORY
      fi
    - mkdir $NMSIS_LOGS
    - source NMSIS/env.sh
    - export SILENT=1
    - cd NMSIS
    - rm -rf Library
    - ln -s gen_nuclei_llvm/Library .
    - export SDK_VERB_BUILDMSG=0
    - python3 $NUCLEI_SDK_ROOT/tools/scripts/nsdk_cli/nsdk_bench.py --appcfg Scripts/Runner/nmsis_dsp_${NUCLEI_DSP}.json --logdir $NMSIS_LOGS/${NUCLEI_DSP}/nmsis_dsp_llvm --parallel=-j --make_options "SIMU=$RUNTARGET TOOLCHAIN=nuclei_llvm" --run_target $RUNTARGET --run
    # zip logs
    - cd -
    - zip -q -r log_nmsis_dsp_llvm_${NUCLEI_DSP}.zip NMSIS/Logs
    - rm -rf NMSIS/Logs

release_benchmark:
  stage: release
  interruptible: true
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    name: "nmsis_test_logs-job${CI_JOB_ID}-${CI_COMMIT_SHA::8}"
    paths:
      - log_nmsis.zip
    expire_in: 2 day
  dependencies:
    - test_nn_library
    - test_dsp_library
    - test_nn_library_terapines
    - test_dsp_library_terapines
    - test_nn_library_llvm
    - test_dsp_library_llvm
  script:
    # unzip all log_nmsis_*.zip files
    - for zf in `find . -name "log_nmsis*.zip"` ; do unzip -qo $zf ; done
    - ls -lh NMSIS/Logs
    - rm -f log_nmsis_*.zip
    - zip -q -r log_nmsis.zip NMSIS/Logs

release_nmsis:
  stage: release
  interruptible: true
  only:
    refs:
      - master
      - develop
      - /^feature\/.*/
      - merge_requests
  artifacts:
    name: "nmsis_release-$job${CI_JOB_ID}-{CI_COMMIT_SHA::8}"
    paths:
      - NMSIS/Core
      - NMSIS/DSP/Include
      - NMSIS/DSP/PrivateInclude
      - NMSIS/NN/Include
      - NMSIS/Library
      - NMSIS/npk.yml
      - NMSIS/build.mk
    expire_in: 2 day
  dependencies:
    - build_library
  script:
    - ls -lh NMSIS/gen/
    # choose proper built library to release
    - rm -rf NMSIS/Library
    - mv NMSIS/gen/Library NMSIS/
    - ls -lh NMSIS/Library
    - cat NMSIS/npk.yml

deploy_website:
  stage: release
  only:
    refs:
      - master
    changes:
      - NMSIS/doc/source/**/**/**/*
      - .gitlab-ci.yml
      - NMSIS/Core/
      - NMSIS/DSP/
      - NMSIS/NN/
  dependencies:
    - build_doc
  tags:
    - env::shell
    - host::whss1
  script:
    - ./.ci/ftp_deploy.sh $FTPUSER $FTPPWD $FTPSERVER NMSIS/doc/build/html nmsis

