// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_cell_gate_input_weights[66] = {
    34,   -103, 125,  -106, -114, -63,  -105, 2,    -127, 104, 106,
    -117, -59,  -114, 106,  -59,  77,   82,   17,   -6,   101, 12,
    10,   -87,  -75,  104,  -61,  70,   -113, -123, -37,  22,  -40,
    -59,  -30,  126,  -4,   123,  63,   125,  127,  33,   58,  19,
    25,   21,   56,   22,   65,   -116, 111,  27,   109,  126, -119,
    29,   -94,  85,   -60,  39,   99,   -53,  -50,  -124, 64,  -100};
