// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_cell_gate_hidden_weights[9] = {
    116, -99, 120, -20, -70, 11, 78, 7, -127};
