// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_forget_gate_input_weights[66] = {
    92,  -122, -64, 30,  -56, -127, -84, -38, 24,   54,   -67, 66,   -85, 72,
    83,  72,   46,  118, 42,  69,   -83, 35,  -68,  -78,  91,  -110, 17,  35,
    71,  50,   48,  -35, 84,  20,   127, 15,  33,   3,    -21, -56,  121, 84,
    113, -39,  -55, -65, 60,  30,   42,  41,  62,   -112, -20, 75,   75,  -11,
    -84, -45,  88,  -84, -21, 57,   -67, 34,  -127, -97};
