// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_tensor[66] = {
    -121, -4, -13,  -125, 119, 82,  -58, 91,   -33,  74,  -71, -51, 44,  67,
    65,   29, -27,  109,  -72, 66,  -5,  55,   -101, 95,  -67, 34,  -28, 13,
    -7,   3,  36,   79,   71,  -96, -42, -104, 57,   120, 24,  -46, 43,  -17,
    9,    34, 120,  -41,  54,  18,  107, 101,  30,   81,  85,  -30, 69,  -123,
    -37,  29, -103, 119,  -24, -38, 75,  -68,  46,   8};
