// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_gate_input_weights[66] = {
    85,  71,   -41,  -96, 87,   60,  -120, -49,  -71,  20,  8,   57,  -35, -27,
    18,  -5,   -107, 44,  33,   107, 77,   -106, 54,   125, -86, -24, 9,   -104,
    -90, -77,  36,   116, -5,   98,  45,   42,   -109, -58, 110, -10, 123, 43,
    13,  -123, -120, 121, -127, -9,  -63,  21,   84,   -17, -50, -50, 105, -4,
    -83, 22,   -54,  1,   -82,  -89, -98,  -61,  41,   93};
