// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_output_gate_input_weights[66] = {
    -24, -89, 38,   30,  15,   -108, -46, -104, -6,   -91,  61,
    -6,  69,  45,   90,  103,  93,   -11, -43,  -42,  20,   -45,
    15,  -23, 110,  121, 2,    -116, 23,  56,   -103, 7,    87,
    70,  9,   -127, 110, -15,  -9,   82,  -69,  -81,  51,   -52,
    5,   118, 89,   59,  -106, 79,   -24, -126, 12,   106,  82,
    102, -26, -124, -66, -56,  -96,  -78, 99,   62,   -127, 1};
