// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2_int4_input_weights[36] = {
    159, 210, 93,  102, 252, 132, 222, 118, 193, 16,  185, 83,
    25,  82,  158, 170, 204, 84,  210, 202, 26,  1,   216, 114,
    20,  82,  203, 104, 110, 221, 221, 176, 49,  101, 214, 245};

const int8_t *const conv_2_int4_weights = conv_2_int4_input_weights;
