// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2_int4_input_tensor[36] = {
    -104, 96,  -51, 27,   121,  -81,  100, 51, -105, 104, 102, -42,
    3,    116, 48,  72,   -65,  -17,  119, 88, 42,   75,  -5,  -32,
    -80,  81,  -52, -116, -109, -113, -91, -3, 100,  82,  -45, 5};

const int8_t *const conv_2_int4_input = conv_2_int4_input_tensor;
