// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2_int4_output[72] = {
    3,   1,   0,   1,   15,  -12, 2,  10, -3, -9,  -2, 19,  5,  -13, 0,
    9,   19,  -19, 4,   10,  5,   -9, -1, 8,  0,   -5, -1,  1,  -11, -9,
    -7,  8,   1,   -10, -4,  -8,  -2, -3, -7, -11, 6,  -12, -5, -2,  3,
    -23, -3,  14,  -1,  1,   -7,  -5, -3, -5, -6,  0,  -10, -1, -3,  -6,
    -7,  -10, -4,  0,   -16, -4,  -8, -9, 3,  -7,  -5, -11};

const int8_t *const conv_2_int4_output_ref = conv_2_int4_output;
