// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_2_int4_output_multiplier[4] = {1524012288, 1139776000,
                                                  1123113088, 1719687552};

const int32_t *const conv_2_int4_output_mult = conv_2_int4_output_multiplier;
