NMSIS-Core: Interrupt and Exception and NMI Handling
Interrupt and Exception and NMI Handling
System Device Configuration
Functions for interrupt, exception and nmi handle available in system_<device>.c.
Macros
#define MAX_SYSTEM_EXCEPTION_NUM 20
Max exception handler number, don't include the NMI(0xFFF) one.
#define SYSTEM_CORE_INTNUM 16
Typedefs
typedef void(* EXC_HANDLER) (unsigned long cause, unsigned long sp)
Exception Handler Function Typedef.
typedef void(* INT_HANDLER) (unsigned long cause, unsigned long sp)
Functions
static void system_mmode_extirq_handler (unsigned long exccode, unsigned long sp)
M-Mode external interrupt handler common entry for plic interrupt mode.
static void core_interrupt_handler (unsigned long exccode, unsigned long sp)
M-Mode Common Interrupt handler entry when in clint/plic mode.
uint32_t core_exception_handler (unsigned long mcause, unsigned long sp)
M-Mode Common NMI/Exception/Interrupt handler entry.
static void system_default_interrupt_handler_s (unsigned long scause, unsigned long sp)
s-mode System Default Interrupt Handler for CLINT/PLIC Interrupt Mode
static void system_smode_extirq_handler (unsigned long exccode, unsigned long sp)
S-Mode external interrupt handler common entry for plic interrupt mode.
static void core_interrupt_handler_s (unsigned long exccode, unsigned long sp)
S-Mode Common Interrupt handler entry when in clint/plic mode.
void Exception_DumpFrame (unsigned long sp, uint8_t mode)
Dump Exception Frame.
static void system_default_interrupt_handler (unsigned long mcause, unsigned long sp)
M-Mode System Default Interrupt Handler for CLINT/PLIC Interrupt Mode.
void Interrupt_Register_CoreIRQ (uint32_t irqn, unsigned long int_handler)
Register a m-mode core interrupt handler for core interrupt number.
unsigned long Interrupt_Get_CoreIRQ (uint32_t irqn)
Get a m-mode core interrupt handler for core interrupt number.
void Interrupt_Register_ExtIRQ (uint32_t irqn, unsigned long int_handler)
Register a m-mode external interrupt handler for plic external interrupt number.
unsigned long Interrupt_Get_ExtIRQ (uint32_t irqn)
Get a m-mode external interrupt handler for external interrupt number.
void Exception_Register_EXC (uint32_t EXCn, unsigned long exc_handler)
Register a m-mode exception handler for exception code EXCn.
unsigned long Exception_Get_EXC (uint32_t EXCn)
Get current m-mode exception handler for exception code EXCn.
static void Exception_Init (void)
Initialize all the default core exception handlers.
uint32_t core_exception_handler_s (unsigned long scause, unsigned long sp)
common Exception handler entry of supervisor mode
void Exception_Register_EXC_S (uint32_t EXCn, unsigned long exc_handler)
Register an exception handler for exception code EXCn of supervisor mode.
unsigned long Exception_Get_EXC_S (uint32_t EXCn)
Get current exception handler for exception code EXCn of supervisor mode.
void Interrupt_Register_CoreIRQ_S (uint32_t irqn, unsigned long int_handler)
Register an s-mode core interrupt handler for core interrupt number.
unsigned long Interrupt_Get_CoreIRQ_S (uint32_t irqn)
Get a s-mode core interrupt handler for core interrupt number.
void Interrupt_Register_ExtIRQ_S (uint32_t irqn, unsigned long int_handler)
Register an s-mode external interrupt handler for plic external interrupt number.
unsigned long Interrupt_Get_ExtIRQ_S (uint32_t irqn)
Get an s-mode external interrupt handler for external interrupt number.
static void system_default_exception_handler (unsigned long mcause, unsigned long sp)
M-Mode System Default Exception Handler.
static void system_default_exception_handler_s (unsigned long scause, unsigned long sp)
Supervisor mode system Default Exception Handler.
Variables
static unsigned long SystemExceptionHandlers [MAX_SYSTEM_EXCEPTION_NUM+1]
Store the exception handlers for each exception ID.
static unsigned long SystemMExtInterruptHandlers [__PLIC_INTNUM]
static unsigned long SystemCoreInterruptHandlers [SYSTEM_CORE_INTNUM]
static INT_HANDLER system_core_interrupt_handler = NULL
static unsigned long SystemExceptionHandlers_S [MAX_SYSTEM_EXCEPTION_NUM]
Store the exception handlers for each exception ID in supervisor mode.
static INT_HANDLER system_core_interrupt_handler_s = NULL
static unsigned long SystemCoreInterruptHandlers_S [SYSTEM_CORE_INTNUM]
static unsigned long SystemSExtInterruptHandlers [__PLIC_INTNUM]
Detailed Description
Functions for interrupt, exception and nmi handle available in system_<device>.c.
Nuclei provide a template for interrupt, exception and NMI handling. Silicon Vendor could adapat according to their requirement. Silicon vendor could implement interface for different exception code and replace current implementation.
Macro Definition Documentation
MAX_SYSTEM_EXCEPTION_NUM
#define MAX_SYSTEM_EXCEPTION_NUM 20
Max exception handler number, don't include the NMI(0xFFF) one.
Definition at line 243 of file system_Device.c.
SYSTEM_CORE_INTNUM
#define SYSTEM_CORE_INTNUM 16
Definition at line 258 of file system_Device.c.
Typedef Documentation
EXC_HANDLER
typedef void(* EXC_HANDLER) (unsigned long cause, unsigned long sp)
Exception Handler Function Typedef.
Note
This typedef is only used internal in this system_<Device>.c file. It is used to do type conversion for registered exception handler before calling it.
Definition at line 239 of file system_Device.c.
INT_HANDLER
typedef void(* INT_HANDLER) (unsigned long cause, unsigned long sp)
Definition at line 240 of file system_Device.c.
Function Documentation
core_exception_handler()
uint32_t core_exception_handler (unsigned long mcause, unsigned long sp)
M-Mode Common NMI/Exception/Interrupt handler entry.
This function provided a command entry for NMI and exception. Silicon Vendor could modify this template implementation according to requirement.
Parameters
[in] mcause code indicating the reason that caused the trap in machine mode
[in] sp stack pointer
Remarks
RISCV provided common entry for all types of exception and interrupt if not in eclic mode. This is proposed code template for exception entry function, Silicon Vendor could modify the implementation.
For the core_exception_handler template, we provided exception register function Exception_Register_EXC which can help developer to register your exception handler for specific exception number.
If you are in eclic interrupt mode, please use ECLIC_Register_IRQ to register both internal and external interrupt
If you are not in eclic interrupt mode, please use please use Interrupt_Register_CoreIRQ to register internal interrupt and use Interrupt_Register_ExtIRQ to register external interrupt
Definition at line 406 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
     // TODO when CODESIZE macro is defined
     // Exception_xxx APIs will not be used, all the m-mode exception handlers
     // will goto this function, and you can handle it here by yourself
     while (1);
 #else
     unsigned long exccode = (mcause & MCAUSE_CAUSE);
     EXC_HANDLER exc_handler;
     if (mcause & MCAUSE_INTR) {
         if (system_core_interrupt_handler != NULL) {
             system_core_interrupt_handler(exccode, sp);
         }
     } else {
         if (exccode < MAX_SYSTEM_EXCEPTION_NUM) {
             exc_handler = (EXC_HANDLER)SystemExceptionHandlers[exccode];
         } else if (exccode == NMI_EXCn) {
             exc_handler = (EXC_HANDLER)SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM];
         } else {
             exc_handler = (EXC_HANDLER)system_default_exception_handler;
         }
         if (exc_handler != NULL) {
             exc_handler(mcause, sp);
         }
     }
     return 0;
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, MCAUSE_CAUSE, MCAUSE_INTR, system_core_interrupt_handler, system_default_exception_handler(), and SystemExceptionHandlers.
core_exception_handler_s()
uint32_t core_exception_handler_s (unsigned long scause, unsigned long sp)
common Exception handler entry of supervisor mode
This function provided a supervisor mode common entry for exception. Silicon Vendor could modify this template implementation according to requirement.
Parameters
[in] scause code indicating the reason that caused the trap in supervisor mode
[in] sp stack pointer
Remarks
RISCV provided supervisor mode common entry for all types of exception. This is proposed code template for exception entry function, Silicon Vendor could modify the implementation.
For the core_exception_handler_s template, we provided exception register function Exception_Register_EXC_S which can help developer to register your exception handler for specific exception number.
Definition at line 704 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
     // TODO when CODESIZE macro is defined
     // Exception_xxx_S APIs will not be used, all the s-mode exception handlers
     // will goto this function, and you can handle it here by yourself
     while(1);
 #else
     unsigned long exccode = (scause & SCAUSE_CAUSE);
     EXC_HANDLER exc_handler;
     if (scause & MCAUSE_INTR) {
         if (system_core_interrupt_handler_s != NULL) {
             system_core_interrupt_handler_s(exccode, sp);
         }
     } else {
         if (exccode < MAX_SYSTEM_EXCEPTION_NUM) {
             exc_handler = (EXC_HANDLER)SystemExceptionHandlers_S[exccode];
         } else {
             exc_handler = (EXC_HANDLER)system_default_exception_handler_s;
         }
         if (exc_handler != NULL) {
             exc_handler(scause, sp);
         }
     }
     return 0;
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, MCAUSE_INTR, SCAUSE_CAUSE, system_core_interrupt_handler_s, system_default_exception_handler_s(), and SystemExceptionHandlers_S.
core_interrupt_handler()
static void core_interrupt_handler (unsigned long exccode, unsigned long sp) static
M-Mode Common Interrupt handler entry when in clint/plic mode.
This function provided a command entry for interrupt in clint/plic mode
Parameters
[in] exccode Exception Code
[in] sp stack pointer
Remarks
This is not used for clic interrupt mode, which is only used for clint/plic interrupt mode, you should call CLINT_Interrupt_Init or PLIC_Interrupt_Init first to make sure this handler entry registered
If you are not in eclic interrupt mode, please use please use Interrupt_Register_CoreIRQ to register internal interrupt and use Interrupt_Register_ExtIRQ to register external interrupt
Definition at line 381 of file system_Device.c.
 {
     INT_HANDLER int_handler = NULL;
     int_handler = (INT_HANDLER)(SystemCoreInterruptHandlers[exccode]);
     if (int_handler != NULL) {
         int_handler(exccode, sp);
     }
 }
References SystemCoreInterruptHandlers.
Referenced by CLINT_Interrupt_Init().
core_interrupt_handler_s()
static void core_interrupt_handler_s (unsigned long exccode, unsigned long sp) static
S-Mode Common Interrupt handler entry when in clint/plic mode.
This function provided a command entry for interrupt in clint/plic mode
Parameters
[in] exccode Exception Code
[in] sp stack pointer
Remarks
This is not used for clic interrupt mode, which is only used for clint/plic interrupt mode, you should call CLINT_Interrupt_Init or PLIC_Interrupt_Init first to make sure this handler entry registered
If you are not in eclic interrupt mode, please use please use Interrupt_Register_CoreIRQ to register internal interrupt and use Interrupt_Register_ExtIRQ to register external interrupt
Definition at line 658 of file system_Device.c.
 {
 #if defined(__SMODE_PRESENT) && (__SMODE_PRESENT == 1)
     INT_HANDLER int_handler = NULL;
     int_handler = (INT_HANDLER)(SystemCoreInterruptHandlers_S[exccode]);
     if (int_handler != NULL) {
         int_handler(exccode, sp);
     }
 #endif
 }
References SystemCoreInterruptHandlers_S.
Referenced by CLINT_Interrupt_Init().
Exception_DumpFrame()
void Exception_DumpFrame (unsigned long sp, uint8_t mode)
Dump Exception Frame.
This function provided feature to dump exception frame stored in stack.
Parameters
[in] sp stackpoint
[in] mode privileged mode to decide whether to dump msubm CSR
Definition at line 294 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     EXC_Frame_Type *exc_frame = (EXC_Frame_Type *)sp;
 #ifndef __riscv_32e
     NSDK_DEBUG("ra: 0x%lx, tp: 0x%lx, t0: 0x%lx, t1: 0x%lx, t2: 0x%lx, t3: 0x%lx, t4: 0x%lx, t5: 0x%lx, t6: 0x%lx\n" \
            "a0: 0x%lx, a1: 0x%lx, a2: 0x%lx, a3: 0x%lx, a4: 0x%lx, a5: 0x%lx, a6: 0x%lx, a7: 0x%lx\n" \
            "cause: 0x%lx, epc: 0x%lx\n", exc_frame->ra, exc_frame->tp, exc_frame->t0, \
            exc_frame->t1, exc_frame->t2, exc_frame->t3, exc_frame->t4, exc_frame->t5, exc_frame->t6, \
            exc_frame->a0, exc_frame->a1, exc_frame->a2, exc_frame->a3, exc_frame->a4, exc_frame->a5, \
            exc_frame->a6, exc_frame->a7, exc_frame->cause, exc_frame->epc);
 #else
     NSDK_DEBUG("ra: 0x%lx, tp: 0x%lx, t0: 0x%lx, t1: 0x%lx, t2: 0x%lx\n" \
            "a0: 0x%lx, a1: 0x%lx, a2: 0x%lx, a3: 0x%lx, a4: 0x%lx, a5: 0x%lx\n" \
            "cause: 0x%lx, epc: 0x%lx\n", exc_frame->ra, exc_frame->tp, exc_frame->t0, \
            exc_frame->t1, exc_frame->t2, exc_frame->a0, exc_frame->a1, exc_frame->a2, exc_frame->a3, \
            exc_frame->a4, exc_frame->a5, exc_frame->cause, exc_frame->epc);
 #endif
     if (PRV_M == mode) {
         /* msubm is exclusive to machine mode */
         NSDK_DEBUG("msubm: 0x%lx\n", exc_frame->msubm);
     }
 #endif
 }
References PRV_M.
Referenced by system_default_exception_handler(), and system_default_exception_handler_s().
Exception_Get_EXC()
unsigned long Exception_Get_EXC (uint32_t EXCn)
Get current m-mode exception handler for exception code EXCn.
For EXCn < MAX_SYSTEM_EXCEPTION_NUM, it will return SystemExceptionHandlers[EXCn-1].
For EXCn == NMI_EXCn, it will return SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM].
Parameters
[in] EXCn See EXCn_Type
Returns
Current exception handler for exception code EXCn, if not found, return 0.
Definition at line 559 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
     return 0;
 #else
     if (EXCn < MAX_SYSTEM_EXCEPTION_NUM) {
         return SystemExceptionHandlers[EXCn];
     } else if (EXCn == NMI_EXCn) {
         return SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM];
     } else {
         return 0;
     }
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, and SystemExceptionHandlers.
Exception_Get_EXC_S()
unsigned long Exception_Get_EXC_S (uint32_t EXCn)
Get current exception handler for exception code EXCn of supervisor mode.
For EXCn < MAX_SYSTEM_EXCEPTION_NUM, it will return SystemExceptionHandlers_S[EXCn-1].
Parameters
[in] EXCn See EXCn_Type
Returns
Current exception handler for exception code EXCn, if not found, return 0.
Definition at line 758 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
     return 0;
 #else
     if (EXCn < MAX_SYSTEM_EXCEPTION_NUM) {
         return SystemExceptionHandlers_S[EXCn];
     } else {
         return 0;
     }
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, and SystemExceptionHandlers_S.
Exception_Init()
static void Exception_Init (void) static
Initialize all the default core exception handlers.
The core exception handler for each exception id will be initialized to system_default_exception_handler.
Note
Called in _init function, used to initialize default exception handlers for all exception IDs SystemExceptionHandlers contains NMI, but SystemExceptionHandlers_S not, because NMI can't be delegated to S-mode.
Definition at line 582 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
     // TODO when CODESIZE macro is defined
     // the exception handler table for m/s mode will not be initialized
     // since all the exception handlers will not be classified, and just
     // goto core_exception_handler or core_exception_handler_s for m/s exception
 #else
     for (int i = 0; i < MAX_SYSTEM_EXCEPTION_NUM; i++) {
         SystemExceptionHandlers[i] = (unsigned long)system_default_exception_handler;
 #if (defined(__SMODE_PRESENT) && (__SMODE_PRESENT == 1))
         SystemExceptionHandlers_S[i] = (unsigned long)system_default_exception_handler_s;
 #endif
     }
     SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM] = (unsigned long)system_default_exception_handler;
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, system_default_exception_handler(), system_default_exception_handler_s(), SystemExceptionHandlers, and SystemExceptionHandlers_S.
Referenced by _premain_init().
Exception_Register_EXC()
void Exception_Register_EXC (uint32_t EXCn, unsigned long exc_handler)
Register a m-mode exception handler for exception code EXCn.
For EXCn < MAX_SYSTEM_EXCEPTION_NUM, it will be registered into SystemExceptionHandlers[EXCn-1].
For EXCn == NMI_EXCn, it will be registered into SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM].
Parameters
[in] EXCn See EXCn_Type
[in] exc_handler The exception handler for this exception code EXCn
Definition at line 538 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     if (EXCn < MAX_SYSTEM_EXCEPTION_NUM) {
         SystemExceptionHandlers[EXCn] = exc_handler;
     } else if (EXCn == NMI_EXCn) {
         SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM] = exc_handler;
     }
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, and SystemExceptionHandlers.
Exception_Register_EXC_S()
void Exception_Register_EXC_S (uint32_t EXCn, unsigned long exc_handler)
Register an exception handler for exception code EXCn of supervisor mode.
-For EXCn < MAX_SYSTEM_EXCEPTION_NUM, it will be registered into SystemExceptionHandlers_S[EXCn-1]. -For EXCn == NMI_EXCn, The NMI (Non-maskable-interrupt) cannot be trapped to the supervisor-mode or user-mode for any configuration, so NMI won't be registered into SystemExceptionHandlers_S.
Parameters
[in] EXCn See EXCn_Type
[in] exc_handler The exception handler for this exception code EXCn
Definition at line 741 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     if (EXCn < MAX_SYSTEM_EXCEPTION_NUM) {
         SystemExceptionHandlers_S[EXCn] = exc_handler;
     }
 #endif
 }
References MAX_SYSTEM_EXCEPTION_NUM, and SystemExceptionHandlers_S.
Interrupt_Get_CoreIRQ()
unsigned long Interrupt_Get_CoreIRQ (uint32_t irqn)
Get a m-mode core interrupt handler for core interrupt number.
Parameters
irqn See IRQn
Returns
The core interrupt handler for this interrupt code irqn, only used in non-eclic mode.
Remarks
You can only use it when you are not in ECLIC interrupt mode.
Definition at line 485 of file system_Device.c.
 {
     if ((irqn < SYSTEM_CORE_INTNUM) && (irqn >= 0)) {
         return SystemCoreInterruptHandlers[irqn];
     }
     return 0;
 }
References SYSTEM_CORE_INTNUM, and SystemCoreInterruptHandlers.
Interrupt_Get_CoreIRQ_S()
unsigned long Interrupt_Get_CoreIRQ_S (uint32_t irqn)
Get a s-mode core interrupt handler for core interrupt number.
Parameters
irqn See IRQn
Returns
The core interrupt handler for this interrupt code irqn, only used in non-eclic mode.
Remarks
You can only use it when you are not in ECLIC interrupt mode.
Definition at line 795 of file system_Device.c.
 {
     if ((irqn < SYSTEM_CORE_INTNUM) && (irqn >= 0)) {
         return SystemCoreInterruptHandlers_S[irqn];
     }
     return 0;
 }
References SYSTEM_CORE_INTNUM, and SystemCoreInterruptHandlers_S.
Interrupt_Get_ExtIRQ()
unsigned long Interrupt_Get_ExtIRQ (uint32_t irqn)
Get a m-mode external interrupt handler for external interrupt number.
Parameters
irqn See IRQn
Returns
The external interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are in PLIC interrupt mode.
Definition at line 519 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
     if ((irqn < __PLIC_INTNUM) && (irqn >= 0)) {
         return SystemMExtInterruptHandlers[irqn];
     }
 #endif
     return 0;
 }
References SystemMExtInterruptHandlers.
Interrupt_Get_ExtIRQ_S()
unsigned long Interrupt_Get_ExtIRQ_S (uint32_t irqn)
Get an s-mode external interrupt handler for external interrupt number.
Parameters
irqn See IRQn
Returns
The external interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are in PLIC interrupt mode.
Definition at line 831 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
 #if defined(__SMODE_PRESENT) && (__SMODE_PRESENT == 1)
     if ((irqn < __PLIC_INTNUM) && (irqn >= 0)) {
         return SystemSExtInterruptHandlers[irqn];
     }
 #endif
 #endif
     return 0;
 }
References SystemSExtInterruptHandlers.
Interrupt_Register_CoreIRQ()
void Interrupt_Register_CoreIRQ (uint32_t irqn, unsigned long int_handler)
Register a m-mode core interrupt handler for core interrupt number.
For irqn <= SYSTEM_CORE_INTNUM, it will be registered into SystemCoreInterruptHandlers[irqn-1], only used in non-eclic mode.
Parameters
irqn See IRQn
int_handler The core interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are not in ECLIC interrupt mode.
Definition at line 470 of file system_Device.c.
 {
     if ((irqn < SYSTEM_CORE_INTNUM) && (irqn >= 0)) {
         SystemCoreInterruptHandlers[irqn] = int_handler;
     }
 }
References SYSTEM_CORE_INTNUM, and SystemCoreInterruptHandlers.
Referenced by Core_Register_IRQ().
Interrupt_Register_CoreIRQ_S()
void Interrupt_Register_CoreIRQ_S (uint32_t irqn, unsigned long int_handler)
Register an s-mode core interrupt handler for core interrupt number.
For irqn <= SYSTEM_CORE_INTNUM, it will be registered into SystemCoreInterruptHandlers[irqn-1], only used in non-eclic mode.
Parameters
irqn See IRQn
int_handler The core interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are not in ECLIC interrupt mode.
Definition at line 780 of file system_Device.c.
 {
     if ((irqn < SYSTEM_CORE_INTNUM) && (irqn >= 0)) {
         SystemCoreInterruptHandlers_S[irqn] = int_handler;
     }
 }
References SYSTEM_CORE_INTNUM, and SystemCoreInterruptHandlers_S.
Referenced by Core_Register_IRQ_S().
Interrupt_Register_ExtIRQ()
void Interrupt_Register_ExtIRQ (uint32_t irqn, unsigned long int_handler)
Register a m-mode external interrupt handler for plic external interrupt number.
For irqn <= __PLIC_INTNUM, it will be registered into SystemMExtInterruptHandlers[irqn-1].
Parameters
irqn See IRQn
int_handler The external interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are in PLIC interrupt mode.
Definition at line 502 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
     if ((irqn < __PLIC_INTNUM) && (irqn >= 0)) {
         SystemMExtInterruptHandlers[irqn] = int_handler;
     }
 #endif
 }
References SystemMExtInterruptHandlers.
Referenced by PLIC_Register_IRQ().
Interrupt_Register_ExtIRQ_S()
void Interrupt_Register_ExtIRQ_S (uint32_t irqn, unsigned long int_handler)
Register an s-mode external interrupt handler for plic external interrupt number.
For irqn <= __PLIC_INTNUM, it will be registered into SystemSExtInterruptHandlers[irqn-1].
Parameters
irqn See IRQn
int_handler The external interrupt handler for this interrupt code irqn
Remarks
You can only use it when you are in PLIC interrupt mode.
Definition at line 812 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
 #if defined(__SMODE_PRESENT) && (__SMODE_PRESENT == 1)
     if ((irqn < __PLIC_INTNUM) && (irqn >= 0)) {
         SystemSExtInterruptHandlers[irqn] = int_handler;
     }
 #endif
 #endif
 }
References SystemSExtInterruptHandlers.
Referenced by PLIC_Register_IRQ_S().
system_default_exception_handler()
static void system_default_exception_handler (unsigned long mcause, unsigned long sp) static
M-Mode System Default Exception Handler.
This function provides a default exception and NMI handler for all exception ids. By default, It will just print some information for debug, Vendor can customize it according to its requirements.
Parameters
[in] mcause code indicating the reason that caused the trap in machine mode
[in] sp stack pointer
Definition at line 331 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     NSDK_DEBUG("MCAUSE : 0x%lx\r\n", mcause);
     NSDK_DEBUG("MDCAUSE: 0x%lx\r\n", __RV_CSR_READ(CSR_MDCAUSE));
     NSDK_DEBUG("MEPC   : 0x%lx\r\n", __RV_CSR_READ(CSR_MEPC));
     NSDK_DEBUG("MTVAL  : 0x%lx\r\n", __RV_CSR_READ(CSR_MTVAL));
     NSDK_DEBUG("HARTID : %u\r\n", (unsigned int)__get_hart_id());
     Exception_DumpFrame(sp, PRV_M);
 #if defined(SIMULATION_MODE)
     // directly exit if in SIMULATION
     extern void simulation_exit(int status);
     simulation_exit(1);
 #else
     while (1);
 #endif
 #endif
 }
References __get_hart_id(), __RV_CSR_READ, CSR_MDCAUSE, CSR_MEPC, CSR_MTVAL, Exception_DumpFrame(), and PRV_M.
Referenced by core_exception_handler(), and Exception_Init().
system_default_exception_handler_s()
static void system_default_exception_handler_s (unsigned long scause, unsigned long sp) static
Supervisor mode system Default Exception Handler.
This function provided a default supervisor mode exception and NMI handling code for all exception ids. By default, It will just print some information for debug, Vendor can customize it according to its requirements.
Parameters
[in] scause code indicating the reason that caused the trap in supervisor mode
[in] sp stack pointer
Definition at line 609 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     /* TODO: Uncomment this if you have implement NSDK_DEBUG function */
     NSDK_DEBUG("SCAUSE : 0x%lx\r\n", scause);
     NSDK_DEBUG("SDCAUSE: 0x%lx\r\n", __RV_CSR_READ(CSR_SDCAUSE));
     NSDK_DEBUG("SEPC   : 0x%lx\r\n", __RV_CSR_READ(CSR_SEPC));
     NSDK_DEBUG("STVAL  : 0x%lx\r\n", __RV_CSR_READ(CSR_STVAL));
     Exception_DumpFrame(sp, PRV_S);
 #if defined(SIMULATION_MODE)
     // directly exit if in SIMULATION
     extern void simulation_exit(int status);
     simulation_exit(1);
 #else
     while (1);
 #endif
 #endif
 }
References __RV_CSR_READ, CSR_SDCAUSE, CSR_SEPC, CSR_STVAL, Exception_DumpFrame(), and PRV_S.
Referenced by core_exception_handler_s(), and Exception_Init().
system_default_interrupt_handler()
static void system_default_interrupt_handler (unsigned long mcause, unsigned long sp) static
M-Mode System Default Interrupt Handler for CLINT/PLIC Interrupt Mode.
This function provided a default interrupt handling code for all interrupt ids.
Definition at line 357 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     NSDK_DEBUG("Trap in Interrupt\r\n");
     NSDK_DEBUG("MCAUSE: 0x%lx\r\n", mcause);
     NSDK_DEBUG("MEPC  : 0x%lx\r\n", __RV_CSR_READ(CSR_MEPC));
     NSDK_DEBUG("MTVAL : 0x%lx\r\n", __RV_CSR_READ(CSR_MTVAL));
 #endif
 }
References __RV_CSR_READ, CSR_MEPC, and CSR_MTVAL.
Referenced by CLINT_Interrupt_Init(), and PLIC_Interrupt_Init().
system_default_interrupt_handler_s()
static void system_default_interrupt_handler_s (unsigned long scause, unsigned long sp) static
s-mode System Default Interrupt Handler for CLINT/PLIC Interrupt Mode
This function provided a default interrupt handling code for all interrupt ids.
Definition at line 634 of file system_Device.c.
 {
 #if defined(CODESIZE) && (CODESIZE == 1)
 #else
     NSDK_DEBUG("Trap in S-Mode Interrupt\r\n");
     NSDK_DEBUG("SCAUSE: 0x%lx\r\n", scause);
     NSDK_DEBUG("SEPC  : 0x%lx\r\n", __RV_CSR_READ(CSR_SEPC));
     NSDK_DEBUG("STVAL : 0x%lx\r\n", __RV_CSR_READ(CSR_STVAL));
 #endif
 }
References __RV_CSR_READ, CSR_SEPC, and CSR_STVAL.
Referenced by CLINT_Interrupt_Init(), and PLIC_Interrupt_Init().
system_mmode_extirq_handler()
static void system_mmode_extirq_handler (unsigned long exccode, unsigned long sp) static
M-Mode external interrupt handler common entry for plic interrupt mode.
This function provide common entry for m-mode external interrupt for plic interrupt mode.
Parameters
[in] exccode exception code indicating the reason that caused the trap in machine mode
[in] sp stack pointer
Definition at line 446 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
     uint32_t irqn = PLIC_ClaimInterrupt();
     INT_HANDLER int_handler = NULL;
     if (irqn < __PLIC_INTNUM) {
         int_handler = (INT_HANDLER)(SystemMExtInterruptHandlers[irqn]);
         if (int_handler != NULL) {
             int_handler(exccode, sp);
         }
     }
     PLIC_CompleteInterrupt(irqn);
 #endif
 }
References PLIC_ClaimInterrupt, PLIC_CompleteInterrupt, and SystemMExtInterruptHandlers.
Referenced by PLIC_Interrupt_Init().
system_smode_extirq_handler()
static void system_smode_extirq_handler (unsigned long exccode, unsigned long sp) static
S-Mode external interrupt handler common entry for plic interrupt mode.
This function provide common entry for s-mode external interrupt for plic interrupt mode.
Parameters
[in] exccode exception code indicating the reason that caused the trap in supervisor mode
[in] sp stack pointer
Definition at line 676 of file system_Device.c.
 {
 #if defined(__PLIC_PRESENT) && (__PLIC_PRESENT == 1)
     uint32_t irqn = PLIC_ClaimInterrupt_S();
     INT_HANDLER int_handler = NULL;
     if (irqn < __PLIC_INTNUM) {
         int_handler = (INT_HANDLER)(SystemSExtInterruptHandlers[irqn]);
         if (int_handler != NULL) {
             int_handler(exccode, sp);
         }
     }
     PLIC_CompleteInterrupt_S(irqn);
 #endif
 }
References PLIC_ClaimInterrupt_S, PLIC_CompleteInterrupt_S, and SystemSExtInterruptHandlers.
Referenced by PLIC_Interrupt_Init().
Variable Documentation
system_core_interrupt_handler
INT_HANDLER system_core_interrupt_handler = NULL static
Definition at line 265 of file system_Device.c.
Referenced by CLINT_Interrupt_Init(), and core_exception_handler().
system_core_interrupt_handler_s
INT_HANDLER system_core_interrupt_handler_s = NULL static
Definition at line 280 of file system_Device.c.
Referenced by CLINT_Interrupt_Init(), and core_exception_handler_s().
SystemCoreInterruptHandlers
unsigned long SystemCoreInterruptHandlers[SYSTEM_CORE_INTNUM] static
Definition at line 262 of file system_Device.c.
Referenced by CLINT_Interrupt_Init(), core_interrupt_handler(), Interrupt_Get_CoreIRQ(), Interrupt_Register_CoreIRQ(), and PLIC_Interrupt_Init().
SystemCoreInterruptHandlers_S
unsigned long SystemCoreInterruptHandlers_S[SYSTEM_CORE_INTNUM] static
Definition at line 281 of file system_Device.c.
Referenced by CLINT_Interrupt_Init(), core_interrupt_handler_s(), Interrupt_Get_CoreIRQ_S(), Interrupt_Register_CoreIRQ_S(), and PLIC_Interrupt_Init().
SystemExceptionHandlers
unsigned long SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM+1] static
Store the exception handlers for each exception ID.
Note
This SystemExceptionHandlers are used to store all the handlers for all the exception codes Nuclei N/NX core provided.
Exception code 0 - 19, totally 20 exceptions are mapped to SystemExceptionHandlers[0:19]
Exception for NMI is also re-routed to exception handling(exception code 0xFFF) in startup code configuration, the handler itself is mapped to SystemExceptionHandlers[MAX_SYSTEM_EXCEPTION_NUM]
Definition at line 252 of file system_Device.c.
Referenced by core_exception_handler(), Exception_Get_EXC(), Exception_Init(), and Exception_Register_EXC().
SystemExceptionHandlers_S
unsigned long SystemExceptionHandlers_S[MAX_SYSTEM_EXCEPTION_NUM] static
Store the exception handlers for each exception ID in supervisor mode.
Note
This SystemExceptionHandlers_S are used to store all the handlers for all the exception codes Nuclei N/NX core provided.
Exception code 0 - 19, totally 20 exceptions are mapped to SystemExceptionHandlers_S[0:19]
Definition at line 275 of file system_Device.c.
Referenced by core_exception_handler_s(), Exception_Get_EXC_S(), Exception_Init(), and Exception_Register_EXC_S().
SystemMExtInterruptHandlers
unsigned long SystemMExtInterruptHandlers[__PLIC_INTNUM] static
Definition at line 255 of file system_Device.c.
Referenced by Interrupt_Get_ExtIRQ(), Interrupt_Register_ExtIRQ(), PLIC_Interrupt_Init(), and system_mmode_extirq_handler().
SystemSExtInterruptHandlers
unsigned long SystemSExtInterruptHandlers[__PLIC_INTNUM] static
Definition at line 283 of file system_Device.c.
Referenced by Interrupt_Get_ExtIRQ_S(), Interrupt_Register_ExtIRQ_S(), PLIC_Interrupt_Init(), and system_smode_extirq_handler().