NMSIS-Core: Interrupts and Exceptions
Interrupts and Exceptions
Functions that manage interrupts and exceptions via the ECLIC.
Macros
#define ECLIC_SetCfgNlbits __ECLIC_SetCfgNlbits
#define ECLIC_GetCfgNlbits __ECLIC_GetCfgNlbits
#define ECLIC_GetInfoVer __ECLIC_GetInfoVer
#define ECLIC_GetInfoCtlbits __ECLIC_GetInfoCtlbits
#define ECLIC_GetInfoNum __ECLIC_GetInfoNum
#define ECLIC_GetInfoShadowNum __ECLIC_GetInfoShadowNum
#define ECLIC_SetMth __ECLIC_SetMth
#define ECLIC_GetMth __ECLIC_GetMth
#define ECLIC_EnableIRQ __ECLIC_EnableIRQ
#define ECLIC_GetEnableIRQ __ECLIC_GetEnableIRQ
#define ECLIC_DisableIRQ __ECLIC_DisableIRQ
#define ECLIC_SetPendingIRQ __ECLIC_SetPendingIRQ
#define ECLIC_GetPendingIRQ __ECLIC_GetPendingIRQ
#define ECLIC_ClearPendingIRQ __ECLIC_ClearPendingIRQ
#define ECLIC_SetTrigIRQ __ECLIC_SetTrigIRQ
#define ECLIC_GetTrigIRQ __ECLIC_GetTrigIRQ
#define ECLIC_SetShvIRQ __ECLIC_SetShvIRQ
#define ECLIC_GetShvIRQ __ECLIC_GetShvIRQ
#define ECLIC_SetCtrlIRQ __ECLIC_SetCtrlIRQ
#define ECLIC_GetCtrlIRQ __ECLIC_GetCtrlIRQ
#define ECLIC_SetLevelIRQ __ECLIC_SetLevelIRQ
#define ECLIC_GetLevelIRQ __ECLIC_GetLevelIRQ
#define ECLIC_SetPriorityIRQ __ECLIC_SetPriorityIRQ
#define ECLIC_GetPriorityIRQ __ECLIC_GetPriorityIRQ
#define ECLIC_SetModeIRQ __ECLIC_SetModeIRQ
#define ECLIC_SetSth __ECLIC_SetSth
#define ECLIC_GetSth __ECLIC_GetSth
#define ECLIC_SetPendingIRQ_S __ECLIC_SetPendingIRQ_S
#define ECLIC_GetPendingIRQ_S __ECLIC_GetPendingIRQ_S
#define ECLIC_ClearPendingIRQ_S __ECLIC_ClearPendingIRQ_S
#define ECLIC_SetTrigIRQ_S __ECLIC_SetTrigIRQ_S
#define ECLIC_GetTrigIRQ_S __ECLIC_GetTrigIRQ_S
#define ECLIC_SetShvIRQ_S __ECLIC_SetShvIRQ_S
#define ECLIC_GetShvIRQ_S __ECLIC_GetShvIRQ_S
#define ECLIC_SetCtrlIRQ_S __ECLIC_SetCtrlIRQ_S
#define ECLIC_GetCtrlIRQ_S __ECLIC_GetCtrlIRQ_S
#define ECLIC_SetLevelIRQ_S __ECLIC_SetLevelIRQ_S
#define ECLIC_GetLevelIRQ_S __ECLIC_GetLevelIRQ_S
#define ECLIC_SetPriorityIRQ_S __ECLIC_SetPriorityIRQ_S
#define ECLIC_GetPriorityIRQ_S __ECLIC_GetPriorityIRQ_S
#define ECLIC_EnableIRQ_S __ECLIC_EnableIRQ_S
#define ECLIC_GetEnableIRQ_S __ECLIC_GetEnableIRQ_S
#define ECLIC_DisableIRQ_S __ECLIC_DisableIRQ_S
#define ECLIC_SetVector __ECLIC_SetVector
#define ECLIC_GetVector __ECLIC_GetVector
#define ECLIC_SetVector_S __ECLIC_SetVector_S
#define ECLIC_GetVector_S __ECLIC_GetVector_S
#define SAVE_SSUBM_VAR()
#define RESTORE_SSUBM_VAR()
#define SAVE_IRQ_CSR_CONTEXT()
Save necessary CSRs into variables for vector interrupt nesting.
#define SAVE_IRQ_CSR_CONTEXT_S()
Save necessary CSRs into variables for vector interrupt nesting in supervisor mode.
#define RESTORE_IRQ_CSR_CONTEXT()
Restore necessary CSRs from variables for vector interrupt nesting.
#define RESTORE_IRQ_CSR_CONTEXT_S()
Restore necessary CSRs from variables for vector interrupt nesting in supervisor mode.
Enumerations
enum IRQn_Type {
Reserved0_IRQn = 0 ,
Reserved1_IRQn = 1 ,
Reserved2_IRQn = 2 ,
SysTimerSW_IRQn = 3 ,
Reserved3_IRQn = 4 ,
Reserved4_IRQn = 5 ,
Reserved5_IRQn = 6 ,
SysTimer_IRQn = 7 ,
Reserved6_IRQn = 8 ,
Reserved7_IRQn = 9 ,
Reserved8_IRQn = 10 ,
Reserved9_IRQn = 11 ,
Reserved10_IRQn = 12 ,
Reserved11_IRQn = 13 ,
Reserved12_IRQn = 14 ,
Reserved13_IRQn = 15 ,
Reserved14_IRQn = 16 ,
Reserved15_IRQn = 17 ,
Reserved16_IRQn = 18 ,
FirstDeviceSpecificInterrupt_IRQn = 19 ,
SOC_INT_MAX
}
Definition of IRQn numbers.
Functions
__STATIC_FORCEINLINE void __ECLIC_SetCfgNlbits (uint32_t nlbits)
Set nlbits value.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetCfgNlbits (void)
Get nlbits value.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoVer (void)
Get the ECLIC version number.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoCtlbits (void)
Get CLICINTCTLBITS.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoNum (void)
Get number of maximum interrupt inputs supported.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoShadowNum (void)
Get number of shadow register groups.
__STATIC_FORCEINLINE void __ECLIC_SetMth (uint8_t mth)
Set Machine Mode Interrupt Level Threshold.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetMth (void)
Get Machine Mode Interrupt Level Threshold.
__STATIC_FORCEINLINE void __ECLIC_EnableIRQ (IRQn_Type IRQn)
Enable a specific interrupt.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetEnableIRQ (IRQn_Type IRQn)
Get a specific interrupt enable status.
__STATIC_FORCEINLINE void __ECLIC_DisableIRQ (IRQn_Type IRQn)
Disable a specific interrupt.
__STATIC_FORCEINLINE int32_t __ECLIC_GetPendingIRQ (IRQn_Type IRQn)
Get the pending specific interrupt.
__STATIC_FORCEINLINE void __ECLIC_SetPendingIRQ (IRQn_Type IRQn)
Set a specific interrupt to pending.
__STATIC_FORCEINLINE void __ECLIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear a specific interrupt from pending.
__STATIC_FORCEINLINE void __ECLIC_SetTrigIRQ (IRQn_Type IRQn, uint32_t trig)
Set trigger mode and polarity for a specific interrupt.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetTrigIRQ (IRQn_Type IRQn)
Get trigger mode and polarity for a specific interrupt.
__STATIC_FORCEINLINE void __ECLIC_SetShvIRQ (IRQn_Type IRQn, uint32_t shv)
Set interrupt working mode for a specific interrupt.
__STATIC_FORCEINLINE uint32_t __ECLIC_GetShvIRQ (IRQn_Type IRQn)
Get interrupt working mode for a specific interrupt.
__STATIC_FORCEINLINE void __ECLIC_SetCtrlIRQ (IRQn_Type IRQn, uint8_t intctrl)
Modify ECLIC Interrupt Input Control Register for a specific interrupt.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetCtrlIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt Input Control Register value for a specific interrupt.
__STATIC_INLINE void __ECLIC_SetLevelIRQ (IRQn_Type IRQn, uint8_t lvl_abs)
Set ECLIC Interrupt level of a specific interrupt.
__STATIC_INLINE uint8_t __ECLIC_GetLevelIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt level of a specific interrupt.
__STATIC_INLINE void __ECLIC_SetPriorityIRQ (IRQn_Type IRQn, uint8_t pri)
Get ECLIC Interrupt priority of a specific interrupt.
__STATIC_INLINE uint8_t __ECLIC_GetPriorityIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt priority of a specific interrupt.
__STATIC_INLINE void __ECLIC_SetVector (IRQn_Type IRQn, rv_csr_t vector)
Set Interrupt Vector of a specific interrupt.
__STATIC_FORCEINLINE rv_csr_t __ECLIC_GetVector (IRQn_Type IRQn)
Get Interrupt Vector of a specific interrupt.
__STATIC_FORCEINLINE void __ECLIC_SetModeIRQ (IRQn_Type IRQn, uint32_t mode)
Set privilege mode of a specific interrupt.
__STATIC_FORCEINLINE void __ECLIC_SetSth (uint8_t sth)
Set supervisor-mode Interrupt Level Threshold in supervisor mode.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetSth (void)
Get supervisor-mode Interrupt Level Threshold in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_SetPendingIRQ_S (IRQn_Type IRQn)
Set a specific interrupt to pending in supervisor mode.
__STATIC_FORCEINLINE int32_t __ECLIC_GetPendingIRQ_S (IRQn_Type IRQn)
Get the pending specific interrupt in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_ClearPendingIRQ_S (IRQn_Type IRQn)
Clear a specific interrupt from pending in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_SetTrigIRQ_S (IRQn_Type IRQn, uint32_t trig)
Set trigger mode and polarity for a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetTrigIRQ_S (IRQn_Type IRQn)
Get trigger mode and polarity for a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_SetShvIRQ_S (IRQn_Type IRQn, uint32_t shv)
Set interrupt working mode for a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetShvIRQ_S (IRQn_Type IRQn)
Get interrupt working mode for a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_SetCtrlIRQ_S (IRQn_Type IRQn, uint8_t intctrl)
Modify ECLIC Interrupt Input Control Register for a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetCtrlIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt Input Control Register value for a specific interrupt in supervisor mode.
__STATIC_INLINE void __ECLIC_SetLevelIRQ_S (IRQn_Type IRQn, uint8_t lvl_abs)
Set ECLIC Interrupt level of a specific interrupt in supervisor mode.
__STATIC_INLINE uint8_t __ECLIC_GetLevelIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt level of a specific interrupt.
__STATIC_INLINE void __ECLIC_SetPriorityIRQ_S (IRQn_Type IRQn, uint8_t pri)
Set ECLIC Interrupt priority of a specific interrupt in supervisor mode.
__STATIC_INLINE uint8_t __ECLIC_GetPriorityIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt priority of a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_EnableIRQ_S (IRQn_Type IRQn)
Enable a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE uint8_t __ECLIC_GetEnableIRQ_S (IRQn_Type IRQn)
Get a specific interrupt enable status in supervisor mode.
__STATIC_FORCEINLINE void __ECLIC_DisableIRQ_S (IRQn_Type IRQn)
Disable a specific interrupt in supervisor mode.
__STATIC_INLINE void __ECLIC_SetVector_S (IRQn_Type IRQn, rv_csr_t vector)
Set Interrupt Vector of a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE rv_csr_t __ECLIC_GetVector_S (IRQn_Type IRQn)
Get Interrupt Vector of a specific interrupt in supervisor mode.
__STATIC_FORCEINLINE void __set_exc_entry (rv_csr_t addr)
Set Exception entry address.
__STATIC_FORCEINLINE rv_csr_t __get_exc_entry (void)
Get Exception entry address.
__STATIC_INLINE void __set_nonvec_entry (rv_csr_t addr)
Set Non-vector interrupt entry address.
__STATIC_INLINE rv_csr_t __get_nonvec_entry (void)
Get Non-vector interrupt entry address.
__STATIC_FORCEINLINE rv_csr_t __get_nmi_entry (void)
Get NMI interrupt entry from 'CSR_MNVEC'.
Detailed Description
Functions that manage interrupts and exceptions via the ECLIC.
Macro Definition Documentation
ECLIC_ClearPendingIRQ
#define ECLIC_ClearPendingIRQ __ECLIC_ClearPendingIRQ
Definition at line 259 of file core_feature_eclic.h.
ECLIC_ClearPendingIRQ_S
#define ECLIC_ClearPendingIRQ_S __ECLIC_ClearPendingIRQ_S
Definition at line 286 of file core_feature_eclic.h.
ECLIC_DisableIRQ
#define ECLIC_DisableIRQ __ECLIC_DisableIRQ
Definition at line 256 of file core_feature_eclic.h.
ECLIC_DisableIRQ_S
#define ECLIC_DisableIRQ_S __ECLIC_DisableIRQ_S
Definition at line 299 of file core_feature_eclic.h.
ECLIC_EnableIRQ
#define ECLIC_EnableIRQ __ECLIC_EnableIRQ
Definition at line 254 of file core_feature_eclic.h.
ECLIC_EnableIRQ_S
#define ECLIC_EnableIRQ_S __ECLIC_EnableIRQ_S
Definition at line 297 of file core_feature_eclic.h.
ECLIC_GetCfgNlbits
#define ECLIC_GetCfgNlbits __ECLIC_GetCfgNlbits
Definition at line 247 of file core_feature_eclic.h.
ECLIC_GetCtrlIRQ
#define ECLIC_GetCtrlIRQ __ECLIC_GetCtrlIRQ
Definition at line 265 of file core_feature_eclic.h.
ECLIC_GetCtrlIRQ_S
#define ECLIC_GetCtrlIRQ_S __ECLIC_GetCtrlIRQ_S
Definition at line 292 of file core_feature_eclic.h.
ECLIC_GetEnableIRQ
#define ECLIC_GetEnableIRQ __ECLIC_GetEnableIRQ
Definition at line 255 of file core_feature_eclic.h.
ECLIC_GetEnableIRQ_S
#define ECLIC_GetEnableIRQ_S __ECLIC_GetEnableIRQ_S
Definition at line 298 of file core_feature_eclic.h.
ECLIC_GetInfoCtlbits
#define ECLIC_GetInfoCtlbits __ECLIC_GetInfoCtlbits
Definition at line 249 of file core_feature_eclic.h.
ECLIC_GetInfoNum
#define ECLIC_GetInfoNum __ECLIC_GetInfoNum
Definition at line 250 of file core_feature_eclic.h.
ECLIC_GetInfoShadowNum
#define ECLIC_GetInfoShadowNum __ECLIC_GetInfoShadowNum
Definition at line 251 of file core_feature_eclic.h.
ECLIC_GetInfoVer
#define ECLIC_GetInfoVer __ECLIC_GetInfoVer
Definition at line 248 of file core_feature_eclic.h.
ECLIC_GetLevelIRQ
#define ECLIC_GetLevelIRQ __ECLIC_GetLevelIRQ
Definition at line 267 of file core_feature_eclic.h.
ECLIC_GetLevelIRQ_S
#define ECLIC_GetLevelIRQ_S __ECLIC_GetLevelIRQ_S
Definition at line 294 of file core_feature_eclic.h.
ECLIC_GetMth
#define ECLIC_GetMth __ECLIC_GetMth
Definition at line 253 of file core_feature_eclic.h.
ECLIC_GetPendingIRQ
#define ECLIC_GetPendingIRQ __ECLIC_GetPendingIRQ
Definition at line 258 of file core_feature_eclic.h.
ECLIC_GetPendingIRQ_S
#define ECLIC_GetPendingIRQ_S __ECLIC_GetPendingIRQ_S
Definition at line 285 of file core_feature_eclic.h.
ECLIC_GetPriorityIRQ
#define ECLIC_GetPriorityIRQ __ECLIC_GetPriorityIRQ
Definition at line 269 of file core_feature_eclic.h.
ECLIC_GetPriorityIRQ_S
#define ECLIC_GetPriorityIRQ_S __ECLIC_GetPriorityIRQ_S
Definition at line 296 of file core_feature_eclic.h.
ECLIC_GetShvIRQ
#define ECLIC_GetShvIRQ __ECLIC_GetShvIRQ
Definition at line 263 of file core_feature_eclic.h.
ECLIC_GetShvIRQ_S
#define ECLIC_GetShvIRQ_S __ECLIC_GetShvIRQ_S
Definition at line 290 of file core_feature_eclic.h.
ECLIC_GetSth
#define ECLIC_GetSth __ECLIC_GetSth
Definition at line 283 of file core_feature_eclic.h.
ECLIC_GetTrigIRQ
#define ECLIC_GetTrigIRQ __ECLIC_GetTrigIRQ
Definition at line 261 of file core_feature_eclic.h.
ECLIC_GetTrigIRQ_S
#define ECLIC_GetTrigIRQ_S __ECLIC_GetTrigIRQ_S
Definition at line 288 of file core_feature_eclic.h.
ECLIC_GetVector
#define ECLIC_GetVector __ECLIC_GetVector
Definition at line 319 of file core_feature_eclic.h.
ECLIC_GetVector_S
#define ECLIC_GetVector_S __ECLIC_GetVector_S
Definition at line 323 of file core_feature_eclic.h.
ECLIC_SetCfgNlbits
#define ECLIC_SetCfgNlbits __ECLIC_SetCfgNlbits
Definition at line 246 of file core_feature_eclic.h.
ECLIC_SetCtrlIRQ
#define ECLIC_SetCtrlIRQ __ECLIC_SetCtrlIRQ
Definition at line 264 of file core_feature_eclic.h.
ECLIC_SetCtrlIRQ_S
#define ECLIC_SetCtrlIRQ_S __ECLIC_SetCtrlIRQ_S
Definition at line 291 of file core_feature_eclic.h.
ECLIC_SetLevelIRQ
#define ECLIC_SetLevelIRQ __ECLIC_SetLevelIRQ
Definition at line 266 of file core_feature_eclic.h.
ECLIC_SetLevelIRQ_S
#define ECLIC_SetLevelIRQ_S __ECLIC_SetLevelIRQ_S
Definition at line 293 of file core_feature_eclic.h.
ECLIC_SetModeIRQ
#define ECLIC_SetModeIRQ __ECLIC_SetModeIRQ
Definition at line 281 of file core_feature_eclic.h.
ECLIC_SetMth
#define ECLIC_SetMth __ECLIC_SetMth
Definition at line 252 of file core_feature_eclic.h.
ECLIC_SetPendingIRQ
#define ECLIC_SetPendingIRQ __ECLIC_SetPendingIRQ
Definition at line 257 of file core_feature_eclic.h.
ECLIC_SetPendingIRQ_S
#define ECLIC_SetPendingIRQ_S __ECLIC_SetPendingIRQ_S
Definition at line 284 of file core_feature_eclic.h.
ECLIC_SetPriorityIRQ
#define ECLIC_SetPriorityIRQ __ECLIC_SetPriorityIRQ
Definition at line 268 of file core_feature_eclic.h.
ECLIC_SetPriorityIRQ_S
#define ECLIC_SetPriorityIRQ_S __ECLIC_SetPriorityIRQ_S
Definition at line 295 of file core_feature_eclic.h.
ECLIC_SetShvIRQ
#define ECLIC_SetShvIRQ __ECLIC_SetShvIRQ
Definition at line 262 of file core_feature_eclic.h.
ECLIC_SetShvIRQ_S
#define ECLIC_SetShvIRQ_S __ECLIC_SetShvIRQ_S
Definition at line 289 of file core_feature_eclic.h.
ECLIC_SetSth
#define ECLIC_SetSth __ECLIC_SetSth
Definition at line 282 of file core_feature_eclic.h.
ECLIC_SetTrigIRQ
#define ECLIC_SetTrigIRQ __ECLIC_SetTrigIRQ
Definition at line 260 of file core_feature_eclic.h.
ECLIC_SetTrigIRQ_S
#define ECLIC_SetTrigIRQ_S __ECLIC_SetTrigIRQ_S
Definition at line 287 of file core_feature_eclic.h.
ECLIC_SetVector
#define ECLIC_SetVector __ECLIC_SetVector
Definition at line 318 of file core_feature_eclic.h.
ECLIC_SetVector_S
#define ECLIC_SetVector_S __ECLIC_SetVector_S
Definition at line 322 of file core_feature_eclic.h.
RESTORE_IRQ_CSR_CONTEXT
#define RESTORE_IRQ_CSR_CONTEXT ()
Restore necessary CSRs from variables for vector interrupt nesting.
This macro is used restore CSRs(MCAUSE, MEPC, MSUB) from pre-defined variables in SAVE_IRQ_CSR_CONTEXT macro.
Remarks
Interrupt will be disabled after this macro is called
It need to be used together with SAVE_IRQ_CSR_CONTEXT
Definition at line 1903 of file core_feature_eclic.h.
RESTORE_IRQ_CSR_CONTEXT_S
#define RESTORE_IRQ_CSR_CONTEXT_S ()
Restore necessary CSRs from variables for vector interrupt nesting in supervisor mode.
Definition at line 1910 of file core_feature_eclic.h.
RESTORE_SSUBM_VAR
#define RESTORE_SSUBM_VAR ()
Definition at line 1847 of file core_feature_eclic.h.
SAVE_IRQ_CSR_CONTEXT
#define SAVE_IRQ_CSR_CONTEXT ()
Save necessary CSRs into variables for vector interrupt nesting.
This macro is used to declare variables which are used for saving CSRs(MCAUSE, MEPC, MSUB), and it will read these CSR content into these variables, it need to be used in a vector-interrupt if nesting is required.
Remarks
Interrupt will be enabled after this macro is called
It need to be used together with RESTORE_IRQ_CSR_CONTEXT
Don't use variable names __mcause, __mpec, __msubm in your ISR code
If you want to enable interrupt nesting feature for vector interrupt, you can do it like this:
// __INTERRUPT attribute will generates function entry and exit sequences suitable
// for use in an interrupt handler when this attribute is present
__INTERRUPT void eclic_mtip_handler(void)
{
    // Must call this to save CSRs
    SAVE_IRQ_CSR_CONTEXT();
    // !!!Interrupt is enabled here!!!
    // !!!Higher priority interrupt could nest it!!!
    // put you own interrupt handling code here
    // Must call this to restore CSRs
    RESTORE_IRQ_CSR_CONTEXT();
}
Definition at line 1880 of file core_feature_eclic.h.
SAVE_IRQ_CSR_CONTEXT_S
#define SAVE_IRQ_CSR_CONTEXT_S ()
Save necessary CSRs into variables for vector interrupt nesting in supervisor mode.
Definition at line 1887 of file core_feature_eclic.h.
SAVE_SSUBM_VAR
#define SAVE_SSUBM_VAR ()
Definition at line 1846 of file core_feature_eclic.h.
Enumeration Type Documentation
IRQn_Type
enum IRQn_Type
Definition of IRQn numbers.
The core interrupt enumeration names for IRQn values are defined in the file <Device>.h.
Interrupt ID(IRQn) from 0 to 18 are reserved for core internal interrupts.
Interrupt ID(IRQn) start from 19 represent device-specific external interrupts.
The first device-specific interrupt has the IRQn value 19.
The table below describes the core interrupt names and their availability in various Nuclei Cores.
Enumerator
Reserved0_IRQn
Internal reserved.
Reserved1_IRQn
Internal reserved.
Reserved2_IRQn
Internal reserved.
SysTimerSW_IRQn
System Timer SW interrupt.
Reserved3_IRQn
Internal reserved.
Reserved4_IRQn
Internal reserved.
Reserved5_IRQn
Internal reserved.
SysTimer_IRQn
System Timer Interrupt.
Reserved6_IRQn
Internal reserved.
Reserved7_IRQn
Internal reserved.
Reserved8_IRQn
Internal reserved.
Reserved9_IRQn
Internal reserved.
Reserved10_IRQn
Internal reserved.
Reserved11_IRQn
Internal reserved.
Reserved12_IRQn
Internal reserved.
Reserved13_IRQn
Internal reserved.
Reserved14_IRQn
Internal reserved.
Reserved15_IRQn
Internal reserved.
Reserved16_IRQn
Internal reserved.
FirstDeviceSpecificInterrupt_IRQn
First Device Specific Interrupt.
SOC_INT_MAX
Number of total interrupts.
Definition at line 206 of file core_feature_eclic.h.
                   {
     /* ========= Nuclei N/NX Core Specific Interrupt Numbers  =========== */
     /* Core Internal Interrupt IRQn definitions */
     Reserved0_IRQn            =   0,
     Reserved1_IRQn            =   1,
     Reserved2_IRQn            =   2,
     SysTimerSW_IRQn           =   3,
     Reserved3_IRQn            =   4,
     Reserved4_IRQn            =   5,
     Reserved5_IRQn            =   6,
     SysTimer_IRQn             =   7,
     Reserved6_IRQn            =   8,
     Reserved7_IRQn            =   9,
     Reserved8_IRQn            =  10,
     Reserved9_IRQn            =  11,
     Reserved10_IRQn           =  12,
     Reserved11_IRQn           =  13,
     Reserved12_IRQn           =  14,
     Reserved13_IRQn           =  15,
     Reserved14_IRQn           =  16,
     Reserved15_IRQn           =  17,
     Reserved16_IRQn           =  18,
     /* ========= Device Specific Interrupt Numbers  =================== */
     /* ToDo: add here your device specific external interrupt numbers.
      * 19~max(NUM_INTERRUPT, 1023) is reserved number for user.
      * Maxmum interrupt supported could get from clicinfo.NUM_INTERRUPT.
      * According the interrupt handlers defined in startup_Device.S
      * eg.: Interrupt for Timer#1       eclic_tim1_handler   ->   TIM1_IRQn */
     FirstDeviceSpecificInterrupt_IRQn    = 19,
     SOC_INT_MAX,
 } IRQn_Type;
Function Documentation
__ECLIC_ClearPendingIRQ()
__STATIC_FORCEINLINE void __ECLIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear a specific interrupt from pending.
This function removes the pending state of the specific interrupt IRQn. IRQn cannot be a negative number.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_SetPendingIRQ
ECLIC_GetPendingIRQ
Definition at line 555 of file core_feature_eclic.h.
 {
     ECLIC->CTRL[IRQn].INTIP &= ~CLIC_INTIP_IP_Msk;
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_ClearPendingIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_ClearPendingIRQ_S (IRQn_Type IRQn)
Clear a specific interrupt from pending in supervisor mode.
This function removes the pending state of the specific interrupt IRQn in supervisor mode. IRQn cannot be a negative number.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_SetPendingIRQ_S
ECLIC_GetPendingIRQ_S
Definition at line 1177 of file core_feature_eclic.h.
 {
     ECLIC->SCTRL[IRQn].INTIP &= ~CLIC_INTIP_IP_Msk;
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_DisableIRQ()
__STATIC_FORCEINLINE void __ECLIC_DisableIRQ (IRQn_Type IRQn)
Disable a specific interrupt.
This function disables the specific interrupt IRQn.
Parameters
[in] IRQn Number of the external interrupt to disable
Remarks
IRQn must not be negative.
See also
ECLIC_EnableIRQ
Definition at line 503 of file core_feature_eclic.h.
 {
     ECLIC->CTRL[IRQn].INTIE &= ~CLIC_INTIE_IE_Msk;
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_DisableIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_DisableIRQ_S (IRQn_Type IRQn)
Disable a specific interrupt in supervisor mode.
This function disables the specific interrupt IRQn.
Parameters
[in] IRQn Number of the external interrupt to disable
Remarks
IRQn must not be negative.
See also
ECLIC_EnableIRQ
Definition at line 1468 of file core_feature_eclic.h.
 {
     ECLIC->SCTRL[IRQn].INTIE &= ~CLIC_INTIE_IE_Msk;
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_EnableIRQ()
__STATIC_FORCEINLINE void __ECLIC_EnableIRQ (IRQn_Type IRQn)
Enable a specific interrupt.
This function enables the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_DisableIRQ
Definition at line 469 of file core_feature_eclic.h.
 {
     ECLIC->CTRL[IRQn].INTIE |= CLIC_INTIE_IE_Msk;
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_EnableIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_EnableIRQ_S (IRQn_Type IRQn)
Enable a specific interrupt in supervisor mode.
This function enables the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_DisableIRQ
Definition at line 1434 of file core_feature_eclic.h.
 {
     ECLIC->SCTRL[IRQn].INTIE |= CLIC_INTIE_IE_Msk;
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_GetCfgNlbits()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetCfgNlbits (void)
Get nlbits value.
This function get the nlbits value of CLICCFG register.
Returns
nlbits value of CLICCFG register
Remarks
nlbits is used to set the width of level in the CLICINTCTL[i].
See also
ECLIC_SetCfgNlbits
Definition at line 355 of file core_feature_eclic.h.
 {
     return ((uint32_t)((ECLIC->CFG & CLIC_CLICCFG_NLBIT_Msk) >> CLIC_CLICCFG_NLBIT_Pos));
 }
References CLIC_CLICCFG_NLBIT_Msk, CLIC_CLICCFG_NLBIT_Pos, and ECLIC.
Referenced by __ECLIC_GetLevelIRQ(), __ECLIC_GetLevelIRQ_S(), __ECLIC_GetPriorityIRQ(), __ECLIC_GetPriorityIRQ_S(), __ECLIC_SetLevelIRQ(), __ECLIC_SetLevelIRQ_S(), __ECLIC_SetPriorityIRQ(), and __ECLIC_SetPriorityIRQ_S().
__ECLIC_GetCtrlIRQ()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetCtrlIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt Input Control Register value for a specific interrupt.
This function modify ECLIC Interrupt Input Control register of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
value of ECLIC Interrupt Input Control register
Remarks
IRQn must not be negative.
See also
ECLIC_SetCtrlIRQ
Definition at line 670 of file core_feature_eclic.h.
 {
     return (ECLIC->CTRL[IRQn].INTCTRL);
 }
References ECLIC.
Referenced by __ECLIC_GetLevelIRQ(), __ECLIC_GetPriorityIRQ(), __ECLIC_SetLevelIRQ(), and __ECLIC_SetPriorityIRQ().
__ECLIC_GetCtrlIRQ_S()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetCtrlIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt Input Control Register value for a specific interrupt in supervisor mode.
This function modify ECLIC Interrupt Input Control register of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
value of ECLIC Interrupt Input Control register
Remarks
IRQn must not be negative.
See also
ECLIC_SetCtrlIRQ_S
Definition at line 1293 of file core_feature_eclic.h.
 {
     return (ECLIC->SCTRL[IRQn].INTCTRL);
 }
References ECLIC.
Referenced by __ECLIC_GetLevelIRQ_S(), __ECLIC_GetPriorityIRQ_S(), __ECLIC_SetLevelIRQ_S(), and __ECLIC_SetPriorityIRQ_S().
__ECLIC_GetEnableIRQ()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetEnableIRQ (IRQn_Type IRQn)
Get a specific interrupt enable status.
This function returns the interrupt enable status for the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
0 Interrupt is not enabled
1 Interrupt is pending
Remarks
IRQn must not be negative.
See also
ECLIC_EnableIRQ
ECLIC_DisableIRQ
Definition at line 488 of file core_feature_eclic.h.
 {
     return ((uint32_t) (ECLIC->CTRL[IRQn].INTIE) & CLIC_INTIE_IE_Msk);
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_GetEnableIRQ_S()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetEnableIRQ_S (IRQn_Type IRQn)
Get a specific interrupt enable status in supervisor mode.
This function returns the interrupt enable status for the specific interrupt IRQn in S MODE.
Parameters
[in] IRQn Interrupt number
Returns
0 Interrupt is not masked
1 Interrupt is enabled
Remarks
IRQn must not be negative.
See also
ECLIC_EnableIRQ_S
ECLIC_DisableIRQ_S
Definition at line 1453 of file core_feature_eclic.h.
 {
     return ((uint8_t) (ECLIC->SCTRL[IRQn].INTIE) & CLIC_INTIE_IE_Msk);
 }
References CLIC_INTIE_IE_Msk, and ECLIC.
__ECLIC_GetInfoCtlbits()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoCtlbits (void)
Get CLICINTCTLBITS.
This function gets CLICINTCTLBITS from CLICINFO register.
Returns
CLICINTCTLBITS from CLICINFO register.
Remarks
In the CLICINTCTL[i] registers, with 2 <= CLICINTCTLBITS <= 8.
The implemented bits are kept left-justified in the most-significant bits of each 8-bit CLICINTCTL[I] register, with the lower unimplemented bits hardwired to 1.
See also
ECLIC_GetInfoNum
Definition at line 388 of file core_feature_eclic.h.
 {
     return ((uint32_t)((ECLIC->INFO & CLIC_CLICINFO_CTLBIT_Msk) >> CLIC_CLICINFO_CTLBIT_Pos));
 }
References CLIC_CLICINFO_CTLBIT_Msk, CLIC_CLICINFO_CTLBIT_Pos, and ECLIC.
__ECLIC_GetInfoNum()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoNum (void)
Get number of maximum interrupt inputs supported.
This function gets number of maximum interrupt inputs supported from CLICINFO register.
Returns
number of maximum interrupt inputs supported from CLICINFO register.
Remarks
This function gets number of maximum interrupt inputs supported from CLICINFO register.
The num_interrupt field specifies the actual number of maximum interrupt inputs supported in this implementation.
See also
ECLIC_GetInfoCtlbits
Definition at line 404 of file core_feature_eclic.h.
 {
     return ((uint32_t)((ECLIC->INFO & CLIC_CLICINFO_NUM_Msk) >> CLIC_CLICINFO_NUM_Pos));
 }
References CLIC_CLICINFO_NUM_Msk, CLIC_CLICINFO_NUM_Pos, and ECLIC.
__ECLIC_GetInfoShadowNum()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoShadowNum (void)
Get number of shadow register groups.
This function gets the number of shadow register groups from the CLICINFO register. This includes both the first-come-first-served dedicated interrupt shadow registers and the shadow registers designed for different interrupt levels. This number represents the total count for M mode; if S Mode is present, the number is the same as M Mode. Note that shadow register 0 is fixed for first-come-first-served m/s-mode interrupt and cannot be configured.
Returns
number of shadow register groups from the CLICINFO register.
Remarks
This function is only valid for ECLICv2
This function gets the number of shadow register groups from the CLICINFO register.
See also
ECLIC_GetInfoNum
Definition at line 424 of file core_feature_eclic.h.
 {
     return ((uint32_t)((ECLIC->INFO & (CLIC_CLICINFO_SHD_NUM_Msk)) >> CLIC_CLICINFO_SHD_NUM_Pos));
 }
References CLIC_CLICINFO_SHD_NUM_Msk, CLIC_CLICINFO_SHD_NUM_Pos, and ECLIC.
__ECLIC_GetInfoVer()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetInfoVer (void)
Get the ECLIC version number.
This function gets the hardware version information from CLICINFO register.
Returns
hardware version number in CLICINFO register.
Remarks
This function gets harware version information from CLICINFO register.
Bit 20:17 for architecture version, bit 16:13 for implementation version.
See also
ECLIC_GetInfoNum
Definition at line 371 of file core_feature_eclic.h.
 {
     return ((uint32_t)((ECLIC->INFO & CLIC_CLICINFO_VER_Msk) >> CLIC_CLICINFO_VER_Pos));
 }
References CLIC_CLICINFO_VER_Msk, CLIC_CLICINFO_VER_Pos, and ECLIC.
__ECLIC_GetLevelIRQ()
__STATIC_INLINE uint8_t __ECLIC_GetLevelIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt level of a specific interrupt.
This function get interrupt level of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt level
Remarks
IRQn must not be negative.
See also
ECLIC_SetLevelIRQ
Definition at line 724 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits == 0) {
         return 0;
     }
     if (nlbits > intctlbits) {
         nlbits = intctlbits;
     }
     uint8_t intctrl = __ECLIC_GetCtrlIRQ(IRQn);
     uint8_t lvl_abs = intctrl >> (ECLIC_MAX_NLBITS - nlbits);
     return lvl_abs;
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ(), and ECLIC_MAX_NLBITS.
__ECLIC_GetLevelIRQ_S()
__STATIC_INLINE uint8_t __ECLIC_GetLevelIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt level of a specific interrupt.
This function get interrupt level of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt level
Remarks
IRQn must not be negative.
See also
ECLIC_SetLevelIRQ_S
Definition at line 1348 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits == 0) {
         return 0;
     }
     if (nlbits > intctlbits) {
         nlbits = intctlbits;
     }
     uint8_t intctrl = __ECLIC_GetCtrlIRQ_S(IRQn);
     uint8_t lvl_abs = intctrl >> (ECLIC_MAX_NLBITS - nlbits);
     return lvl_abs;
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ_S(), and ECLIC_MAX_NLBITS.
__ECLIC_GetMth()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetMth (void)
Get Machine Mode Interrupt Level Threshold.
This function gets machine mode interrupt level threshold.
Returns
Interrupt Level Threshold.
See also
ECLIC_SetMth
Definition at line 453 of file core_feature_eclic.h.
 {
     return (ECLIC->MTH);
 }
References ECLIC.
__ECLIC_GetPendingIRQ()
__STATIC_FORCEINLINE int32_t __ECLIC_GetPendingIRQ (IRQn_Type IRQn)
Get the pending specific interrupt.
This function returns the pending status of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
0 Interrupt is not pending
1 Interrupt is pending
Remarks
IRQn must not be negative.
See also
ECLIC_SetPendingIRQ
ECLIC_ClearPendingIRQ
Definition at line 522 of file core_feature_eclic.h.
 {
     return ((uint32_t)(ECLIC->CTRL[IRQn].INTIP) & CLIC_INTIP_IP_Msk);
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_GetPendingIRQ_S()
__STATIC_FORCEINLINE int32_t __ECLIC_GetPendingIRQ_S (IRQn_Type IRQn)
Get the pending specific interrupt in supervisor mode.
This function returns the pending status of the specific interrupt IRQn in supervisor mode.
Parameters
[in] IRQn Interrupt number
Returns
0 Interrupt is not pending
1 Interrupt is pending
Remarks
IRQn must not be negative.
See also
ECLIC_SetPendingIRQ_S
ECLIC_ClearPendingIRQ_S
Definition at line 1160 of file core_feature_eclic.h.
 {
     return ((uint32_t)(ECLIC->SCTRL[IRQn].INTIP) & CLIC_INTIP_IP_Msk);
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_GetPriorityIRQ()
__STATIC_INLINE uint8_t __ECLIC_GetPriorityIRQ (IRQn_Type IRQn)
Get ECLIC Interrupt priority of a specific interrupt.
This function get interrupt priority of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt priority
Remarks
IRQn must not be negative.
See also
ECLIC_SetPriorityIRQ
Definition at line 785 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits < intctlbits) {
         uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ(IRQn);
         uint8_t pri = cur_ctrl << nlbits;
         pri = pri >> nlbits;
         pri = pri >> (ECLIC_MAX_NLBITS - intctlbits);
         return pri;
     } else {
         return 0;
     }
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ(), and ECLIC_MAX_NLBITS.
__ECLIC_GetPriorityIRQ_S()
__STATIC_INLINE uint8_t __ECLIC_GetPriorityIRQ_S (IRQn_Type IRQn)
Get ECLIC Interrupt priority of a specific interrupt in supervisor mode.
This function get interrupt priority of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt priority
Remarks
IRQn must not be negative.
See also
ECLIC_SetPriorityIRQ_S
Definition at line 1409 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits < intctlbits) {
         uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ_S(IRQn);
         uint8_t pri = cur_ctrl << nlbits;
         pri = pri >> nlbits;
         pri = pri >> (ECLIC_MAX_NLBITS - intctlbits);
         return pri;
     } else {
         return 0;
     }
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ_S(), and ECLIC_MAX_NLBITS.
__ECLIC_GetShvIRQ()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetShvIRQ (IRQn_Type IRQn)
Get interrupt working mode for a specific interrupt.
This function get selective hardware vector or non-vector working mode of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
shv
0 non-vector mode, ECLIC_NON_VECTOR_INTERRUPT
1 vector mode, ECLIC_VECTOR_INTERRUPT
Remarks
IRQn must not be negative.
See also
ECLIC_SetShvIRQ
Definition at line 638 of file core_feature_eclic.h.
 {
     return ((uint32_t)(((ECLIC->CTRL[IRQn].INTATTR) & CLIC_INTATTR_SHV_Msk) >> CLIC_INTATTR_SHV_Pos));
 }
References CLIC_INTATTR_SHV_Msk, CLIC_INTATTR_SHV_Pos, and ECLIC.
__ECLIC_GetShvIRQ_S()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetShvIRQ_S (IRQn_Type IRQn)
Get interrupt working mode for a specific interrupt in supervisor mode.
This function get selective hardware vector or non-vector working mode of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
shv
0 non-vector mode, ECLIC_NON_VECTOR_INTERRUPT
1 vector mode, ECLIC_VECTOR_INTERRUPT
Remarks
IRQn must not be negative.
See also
ECLIC_SMODE_SetShvIRQ
Definition at line 1261 of file core_feature_eclic.h.
 {
     return ((uint8_t)(((ECLIC->SCTRL[IRQn].INTATTR) & CLIC_INTATTR_SHV_Msk) >> CLIC_INTATTR_SHV_Pos));
 }
References CLIC_INTATTR_SHV_Msk, CLIC_INTATTR_SHV_Pos, and ECLIC.
__ECLIC_GetSth()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetSth (void)
Get supervisor-mode Interrupt Level Threshold in supervisor mode.
This function gets supervisor mode interrupt level threshold.
Returns
Interrupt Level Threshold.
Remarks
S-mode ECLIC region sintthresh'sth is a mirror to M-mode ECLIC region's mintthresh.sth, and will be updated synchronously, here operate on mintthresh.sth.
See also
ECLIC_SetSth
Definition at line 1125 of file core_feature_eclic.h.
 {
     return (ECLIC->STH);
 }
References ECLIC.
__ECLIC_GetTrigIRQ()
__STATIC_FORCEINLINE uint32_t __ECLIC_GetTrigIRQ (IRQn_Type IRQn)
Get trigger mode and polarity for a specific interrupt.
This function get trigger mode and polarity of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
00 level trigger, ECLIC_LEVEL_TRIGGER
01 positive edge trigger, ECLIC_POSTIVE_EDGE_TRIGGER
02 level trigger, ECLIC_LEVEL_TRIGGER
03 negative edge trigger, ECLIC_NEGTIVE_EDGE_TRIGGER
Remarks
IRQn must not be negative.
See also
ECLIC_SetTrigIRQ
Definition at line 599 of file core_feature_eclic.h.
 {
     return ((uint32_t)(((ECLIC->CTRL[IRQn].INTATTR) & CLIC_INTATTR_TRIG_Msk) >> CLIC_INTATTR_TRIG_Pos));
 }
References CLIC_INTATTR_TRIG_Msk, CLIC_INTATTR_TRIG_Pos, and ECLIC.
__ECLIC_GetTrigIRQ_S()
__STATIC_FORCEINLINE uint8_t __ECLIC_GetTrigIRQ_S (IRQn_Type IRQn)
Get trigger mode and polarity for a specific interrupt in supervisor mode.
This function get trigger mode and polarity of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
00 level trigger, ECLIC_LEVEL_TRIGGER
01 positive edge trigger, ECLIC_POSTIVE_EDGE_TRIGGER
02 level trigger, ECLIC_LEVEL_TRIGGER
03 negative edge trigger, ECLIC_NEGTIVE_EDGE_TRIGGER
Remarks
IRQn must not be negative.
See also
ECLIC_SetTrigIRQ_S
Definition at line 1221 of file core_feature_eclic.h.
 {
     return ((uint8_t)(((ECLIC->SCTRL[IRQn].INTATTR) & CLIC_INTATTR_TRIG_Msk) >> CLIC_INTATTR_TRIG_Pos));
 }
References CLIC_INTATTR_TRIG_Msk, CLIC_INTATTR_TRIG_Pos, and ECLIC.
__ECLIC_GetVector()
__STATIC_FORCEINLINE rv_csr_t __ECLIC_GetVector (IRQn_Type IRQn)
Get Interrupt Vector of a specific interrupt.
This function get interrupt handler address of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt handler address
Remarks
IRQn must not be negative.
You can read CSR_CSR_MTVT to get interrupt vector table entry address.
See also
ECLIC_SetVector
Definition at line 1060 of file core_feature_eclic.h.
 {
 #if __RISCV_XLEN == 32
     return (*(uint32_t *)(__RV_CSR_READ(CSR_MTVT) + IRQn * 4));
 #elif __RISCV_XLEN == 64
     return (*(uint64_t *)(__RV_CSR_READ(CSR_MTVT) + IRQn * 8));
 #else // TODO Need cover for XLEN=128 case in future
     return (*(uint64_t *)(__RV_CSR_READ(CSR_MTVT) + IRQn * 8));
 #endif
 }
References __RV_CSR_READ, and CSR_MTVT.
__ECLIC_GetVector_S()
__STATIC_FORCEINLINE rv_csr_t __ECLIC_GetVector_S (IRQn_Type IRQn)
Get Interrupt Vector of a specific interrupt in supervisor mode.
This function get interrupt handler address of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Returns
Interrupt handler address
Remarks
IRQn must not be negative.
You can read CSR_CSR_MTVT to get interrupt vector table entry address.
See also
ECLIC_SMODE_SetVector
Definition at line 1521 of file core_feature_eclic.h.
 {
 #if __RISCV_XLEN == 32
     return (*(uint32_t *)(__RV_CSR_READ(CSR_STVT) + IRQn * 4));
 #elif __RISCV_XLEN == 64
     return (*(uint64_t *)(__RV_CSR_READ(CSR_STVT) + IRQn * 8));
 #else // TODO Need cover for XLEN=128 case in future
     return (*(uint64_t *)(__RV_CSR_READ(CSR_STVT) + IRQn * 8));
 #endif
 }
References __RV_CSR_READ, and CSR_STVT.
__ECLIC_SetCfgNlbits()
__STATIC_FORCEINLINE void __ECLIC_SetCfgNlbits (uint32_t nlbits)
Set nlbits value.
This function set the nlbits value of CLICCFG register.
Parameters
[in] nlbits nlbits value
Remarks
nlbits is used to set the width of level in the CLICINTCTL[i].
See also
ECLIC_GetCfgNlbits
Definition at line 337 of file core_feature_eclic.h.
 {
     uint8_t temp = ECLIC->CFG;
     ECLIC->CFG = (temp & ~CLIC_CLICCFG_NLBIT_Msk) | \
                  ((uint8_t)((nlbits << CLIC_CLICCFG_NLBIT_Pos) & CLIC_CLICCFG_NLBIT_Msk));
 }
References CLIC_CLICCFG_NLBIT_Msk, CLIC_CLICCFG_NLBIT_Pos, and ECLIC.
__ECLIC_SetCtrlIRQ()
__STATIC_FORCEINLINE void __ECLIC_SetCtrlIRQ (IRQn_Type IRQn, uint8_t intctrl)
Modify ECLIC Interrupt Input Control Register for a specific interrupt.
This function modify ECLIC Interrupt Input Control(CLICINTCTL[i]) register of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] intctrl Set value for CLICINTCTL[i] register
Remarks
IRQn must not be negative.
See also
ECLIC_GetCtrlIRQ
Definition at line 654 of file core_feature_eclic.h.
 {
     ECLIC->CTRL[IRQn].INTCTRL = intctrl;
 }
References ECLIC.
Referenced by __ECLIC_SetLevelIRQ(), and __ECLIC_SetPriorityIRQ().
__ECLIC_SetCtrlIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_SetCtrlIRQ_S (IRQn_Type IRQn, uint8_t intctrl)
Modify ECLIC Interrupt Input Control Register for a specific interrupt in supervisor mode.
This function modify ECLIC Interrupt Input Control(CLICINTCTL[i]) register of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] intctrl Set value for CLICINTCTL[i] register
Remarks
IRQn must not be negative.
See also
ECLIC_GetCtrlIRQ_S
Definition at line 1277 of file core_feature_eclic.h.
 {
     ECLIC->SCTRL[IRQn].INTCTRL = intctrl;
 }
References ECLIC.
Referenced by __ECLIC_SetLevelIRQ_S(), and __ECLIC_SetPriorityIRQ_S().
__ECLIC_SetLevelIRQ()
__STATIC_INLINE void __ECLIC_SetLevelIRQ (IRQn_Type IRQn, uint8_t lvl_abs)
Set ECLIC Interrupt level of a specific interrupt.
This function set interrupt level of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] lvl_abs Interrupt level
Remarks
IRQn must not be negative.
If lvl_abs to be set is larger than the max level allowed, it will be force to be max level.
When you set level value you need use clciinfo.nlbits to get the width of level. Then we could know the maximum of level. CLICINTCTLBITS is how many total bits are present in the CLICINTCTL register.
See also
ECLIC_GetLevelIRQ
Definition at line 690 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits == 0) {
         return;
     }
     if (nlbits > intctlbits) {
         nlbits = intctlbits;
     }
     uint8_t maxlvl = ((1UL << nlbits) - 1);
     if (lvl_abs > maxlvl) {
         lvl_abs = maxlvl;
     }
     uint8_t lvl = lvl_abs << (ECLIC_MAX_NLBITS - nlbits);
     uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ(IRQn);
     cur_ctrl = cur_ctrl << nlbits;
     cur_ctrl = cur_ctrl >> nlbits;
     __ECLIC_SetCtrlIRQ(IRQn, (cur_ctrl | lvl));
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ(), __ECLIC_SetCtrlIRQ(), and ECLIC_MAX_NLBITS.
__ECLIC_SetLevelIRQ_S()
__STATIC_INLINE void __ECLIC_SetLevelIRQ_S (IRQn_Type IRQn, uint8_t lvl_abs)
Set ECLIC Interrupt level of a specific interrupt in supervisor mode.
This function set interrupt level of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] lvl_abs Interrupt level
Remarks
IRQn must not be negative.
If lvl_abs to be set is larger than the max level allowed, it will be force to be max level.
When you set level value you need use clciinfo.nlbits to get the width of level. Then we could know the maximum of level. CLICINTCTLBITS is how many total bits are present in the CLICINTCTL register.
See also
ECLIC_GetLevelIRQ_S
Definition at line 1313 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits == 0) {
         return;
     }
     if (nlbits > intctlbits) {
         nlbits = intctlbits;
     }
     uint8_t maxlvl = ((1UL << nlbits) - 1);
     if (lvl_abs > maxlvl) {
         lvl_abs = maxlvl;
     }
     uint8_t lvl = lvl_abs << (ECLIC_MAX_NLBITS - nlbits);
     uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ_S(IRQn);
     cur_ctrl = cur_ctrl << nlbits;
     cur_ctrl = cur_ctrl >> nlbits;
     __ECLIC_SetCtrlIRQ_S(IRQn, (cur_ctrl | lvl));
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ_S(), __ECLIC_SetCtrlIRQ_S(), and ECLIC_MAX_NLBITS.
__ECLIC_SetModeIRQ()
__STATIC_FORCEINLINE void __ECLIC_SetModeIRQ (IRQn_Type IRQn, uint32_t mode)
Set privilege mode of a specific interrupt.
This function set in which privilege mode the interrupts IRQn should be taken.
Parameters
[in] IRQn Interrupt number
[in] mode Privilege mode
Remarks
IRQn must not be negative.
mode must be 1(Supervisor Mode) or 3(Machine Mode), other values are ignored.
M-mode can R/W this field, but S-mode can only read. And ECLIC with S-Mode does not reply on CSR mideleg to delegate interrupts.
Mode of S-mode ECLIC region's clicintattr can be omitted to set, which is mirror to M-mode ECLIC region's. Only the low 6 bits of clicintattr [i] can be written via the S-mode memory region.
Definition at line 1086 of file core_feature_eclic.h.
 {
     /*
      * only 1 or 3 can be assigned to mode in one step.the default value of mode is 3,
      * which can't be clear to 0 firstly, then OR it to 1
      */
     ECLIC->CTRL[IRQn].INTATTR = (uint8_t)(mode << CLIC_INTATTR_MODE_Pos) + \
         (ECLIC->SCTRL[IRQn].INTATTR & (~CLIC_INTATTR_MODE_Msk));
 }
References CLIC_INTATTR_MODE_Msk, CLIC_INTATTR_MODE_Pos, and ECLIC.
__ECLIC_SetMth()
__STATIC_FORCEINLINE void __ECLIC_SetMth (uint8_t mth)
Set Machine Mode Interrupt Level Threshold.
This function sets machine mode interrupt level threshold. This threshold is not effective immediately, if you want to safely change it, you need to disable all interrupts first, and then change it, and do fence and then enable all interrupts.
Parameters
[in] mth Interrupt Level Threshold.
See also
ECLIC_GetMth
Definition at line 440 of file core_feature_eclic.h.
 {
     ECLIC->MTH = mth;
 }
References ECLIC.
__ECLIC_SetPendingIRQ()
__STATIC_FORCEINLINE void __ECLIC_SetPendingIRQ (IRQn_Type IRQn)
Set a specific interrupt to pending.
This function sets the pending bit for the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_GetPendingIRQ
ECLIC_ClearPendingIRQ
Definition at line 538 of file core_feature_eclic.h.
 {
     ECLIC->CTRL[IRQn].INTIP |= CLIC_INTIP_IP_Msk;
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_SetPendingIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_SetPendingIRQ_S (IRQn_Type IRQn)
Set a specific interrupt to pending in supervisor mode.
This function sets the pending bit for the specific interrupt IRQn in supervisor mode.
Parameters
[in] IRQn Interrupt number
Remarks
IRQn must not be negative.
See also
ECLIC_GetPendingIRQ_S
ECLIC_ClearPendingIRQ_S
Definition at line 1141 of file core_feature_eclic.h.
 {
     ECLIC->SCTRL[IRQn].INTIP |= CLIC_INTIP_IP_Msk;
 }
References CLIC_INTIP_IP_Msk, and ECLIC.
__ECLIC_SetPriorityIRQ()
__STATIC_INLINE void __ECLIC_SetPriorityIRQ (IRQn_Type IRQn, uint8_t pri)
Get ECLIC Interrupt priority of a specific interrupt.
This function get interrupt priority of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] pri Interrupt priority
Remarks
IRQn must not be negative.
If pri to be set is larger than the max priority allowed, it will be force to be max priority.
Priority width is CLICINTCTLBITS minus clciinfo.nlbits if clciinfo.nlbits is less than CLICINTCTLBITS. Otherwise priority width is 0.
See also
ECLIC_GetPriorityIRQ
Definition at line 755 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits < intctlbits) {
         uint8_t maxpri = ((1UL << (intctlbits - nlbits)) - 1);
         if (pri > maxpri) {
             pri = maxpri;
         }
         pri = pri << (ECLIC_MAX_NLBITS - intctlbits);
         uint8_t mask = ((uint8_t)(-1)) >> intctlbits;
         pri = pri | mask;
         uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ(IRQn);
         cur_ctrl = cur_ctrl >> (ECLIC_MAX_NLBITS - nlbits);
         cur_ctrl = cur_ctrl << (ECLIC_MAX_NLBITS - nlbits);
         __ECLIC_SetCtrlIRQ(IRQn, (cur_ctrl | pri));
     }
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ(), __ECLIC_SetCtrlIRQ(), and ECLIC_MAX_NLBITS.
__ECLIC_SetPriorityIRQ_S()
__STATIC_INLINE void __ECLIC_SetPriorityIRQ_S (IRQn_Type IRQn, uint8_t pri)
Set ECLIC Interrupt priority of a specific interrupt in supervisor mode.
This function get interrupt priority of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] pri Interrupt priority
Remarks
IRQn must not be negative.
If pri to be set is larger than the max priority allowed, it will be force to be max priority.
Priority width is CLICINTCTLBITS minus clciinfo.nlbits if clciinfo.nlbits is less than CLICINTCTLBITS. Otherwise priority width is 0.
See also
ECLIC_GetPriorityIRQ_S
Definition at line 1379 of file core_feature_eclic.h.
 {
     uint8_t nlbits = __ECLIC_GetCfgNlbits();
     uint8_t intctlbits = (uint8_t)__ECLIC_INTCTLBITS;
     if (nlbits < intctlbits) {
         uint8_t maxpri = ((1UL << (intctlbits - nlbits)) - 1);
         if (pri > maxpri) {
             pri = maxpri;
         }
         pri = pri << (ECLIC_MAX_NLBITS - intctlbits);
         uint8_t mask = ((uint8_t)(-1)) >> intctlbits;
         pri = pri | mask;
         uint8_t cur_ctrl = __ECLIC_GetCtrlIRQ_S(IRQn);
         cur_ctrl = cur_ctrl >> (ECLIC_MAX_NLBITS - nlbits);
         cur_ctrl = cur_ctrl << (ECLIC_MAX_NLBITS - nlbits);
         __ECLIC_SetCtrlIRQ_S(IRQn, (cur_ctrl | pri));
     }
 }
References __ECLIC_GetCfgNlbits(), __ECLIC_GetCtrlIRQ_S(), __ECLIC_SetCtrlIRQ_S(), and ECLIC_MAX_NLBITS.
__ECLIC_SetShvIRQ()
__STATIC_FORCEINLINE void __ECLIC_SetShvIRQ (IRQn_Type IRQn, uint32_t shv)
Set interrupt working mode for a specific interrupt.
This function set selective hardware vector or non-vector working mode of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] shv
0 non-vector mode, ECLIC_NON_VECTOR_INTERRUPT
1 vector mode, ECLIC_VECTOR_INTERRUPT
Remarks
IRQn must not be negative.
See also
ECLIC_GetShvIRQ
Definition at line 617 of file core_feature_eclic.h.
 {
     uint8_t temp = ECLIC->CTRL[IRQn].INTATTR;
     ECLIC->CTRL[IRQn].INTATTR = (temp & ~CLIC_INTATTR_SHV_Msk) | \
                                 ((uint8_t)(shv << CLIC_INTATTR_SHV_Pos));
 }
References CLIC_INTATTR_SHV_Msk, CLIC_INTATTR_SHV_Pos, and ECLIC.
__ECLIC_SetShvIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_SetShvIRQ_S (IRQn_Type IRQn, uint32_t shv)
Set interrupt working mode for a specific interrupt in supervisor mode.
This function set selective hardware vector or non-vector working mode of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] shv
0 non-vector mode, ECLIC_NON_VECTOR_INTERRUPT
1 vector mode, ECLIC_VECTOR_INTERRUPT
Remarks
IRQn must not be negative.
See also
ECLIC_GetShvIRQ_S
Definition at line 1240 of file core_feature_eclic.h.
 {
     uint8_t temp = ECLIC->SCTRL[IRQn].INTATTR;
     ECLIC->SCTRL[IRQn].INTATTR = (temp & ~CLIC_INTATTR_SHV_Msk) | \
                                  ((uint8_t)(shv << CLIC_INTATTR_SHV_Pos));
 }
References CLIC_INTATTR_SHV_Msk, CLIC_INTATTR_SHV_Pos, and ECLIC.
__ECLIC_SetSth()
__STATIC_FORCEINLINE void __ECLIC_SetSth (uint8_t sth)
Set supervisor-mode Interrupt Level Threshold in supervisor mode.
This function sets supervisor-mode interrupt level threshold.
Parameters
[in] sth Interrupt Level Threshold.
Remarks
S-mode ECLIC region sintthresh'sth is a mirror to M-mode ECLIC region's mintthresh.sth, and will be updated synchronously, here operate on mintthresh.sth.
Similiar to ECLIC_SetMth, also recommended to disable interrupts before setting interrupt level threshold.
See also
ECLIC_GetSth
Definition at line 1109 of file core_feature_eclic.h.
 {
     ECLIC->STH = sth;
 }
References ECLIC.
__ECLIC_SetTrigIRQ()
__STATIC_FORCEINLINE void __ECLIC_SetTrigIRQ (IRQn_Type IRQn, uint32_t trig)
Set trigger mode and polarity for a specific interrupt.
This function set trigger mode and polarity of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] trig
00 level trigger, ECLIC_LEVEL_TRIGGER
01 positive edge trigger, ECLIC_POSTIVE_EDGE_TRIGGER
02 level trigger, ECLIC_LEVEL_TRIGGER
03 negative edge trigger, ECLIC_NEGTIVE_EDGE_TRIGGER
Remarks
IRQn must not be negative.
See also
ECLIC_GetTrigIRQ
Definition at line 576 of file core_feature_eclic.h.
 {
     uint8_t temp = ECLIC->CTRL[IRQn].INTATTR;
     ECLIC->CTRL[IRQn].INTATTR = (temp & ~CLIC_INTATTR_TRIG_Msk) | \
                                 ((uint8_t)(trig << CLIC_INTATTR_TRIG_Pos));
 }
References CLIC_INTATTR_TRIG_Msk, CLIC_INTATTR_TRIG_Pos, and ECLIC.
__ECLIC_SetTrigIRQ_S()
__STATIC_FORCEINLINE void __ECLIC_SetTrigIRQ_S (IRQn_Type IRQn, uint32_t trig)
Set trigger mode and polarity for a specific interrupt in supervisor mode.
This function set trigger mode and polarity of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] trig
00 level trigger, ECLIC_LEVEL_TRIGGER
01 positive edge trigger, ECLIC_POSTIVE_EDGE_TRIGGER
02 level trigger, ECLIC_LEVEL_TRIGGER
03 negative edge trigger, ECLIC_NEGTIVE_EDGE_TRIGGER
Remarks
IRQn must not be negative.
See also
ECLIC_GetTrigIRQ_S
Definition at line 1198 of file core_feature_eclic.h.
 {
     uint8_t temp = ECLIC->SCTRL[IRQn].INTATTR;
     ECLIC->SCTRL[IRQn].INTATTR = (temp & ~CLIC_INTATTR_TRIG_Msk) | \
                                  ((uint8_t)(trig << CLIC_INTATTR_TRIG_Pos));
 }
References CLIC_INTATTR_TRIG_Msk, CLIC_INTATTR_TRIG_Pos, and ECLIC.
__ECLIC_SetVector()
__STATIC_INLINE void __ECLIC_SetVector (IRQn_Type IRQn, rv_csr_t vector)
Set Interrupt Vector of a specific interrupt.
This function set interrupt handler address of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] vector Interrupt handler address
Remarks
IRQn must not be negative.
You can set the CSR_CSR_MTVT to set interrupt vector table entry address.
If your vector table is placed in readonly section, the vector for IRQn will not be modified. For this case, you need to use the correct irq handler name defined in your vector table as your irq handler function name.
This function will only work correctly when the vector table is placed in an read-write enabled section.
See also
ECLIC_GetVector
Definition at line 1028 of file core_feature_eclic.h.
 {
     unsigned long vec_base;
     vec_base = ((unsigned long)__RV_CSR_READ(CSR_MTVT));
     vec_base += ((unsigned long)IRQn) * sizeof(unsigned long);
     (* (unsigned long *) vec_base) = vector;
 #if (defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1))
 #if (defined(__CCM_PRESENT) && (__CCM_PRESENT == 1))
     MFlushDCacheLine((unsigned long)vec_base);
 #endif
 #endif
 #if (defined(__ICACHE_PRESENT) && (__ICACHE_PRESENT == 1))
 #if (defined(__CCM_PRESENT) && (__CCM_PRESENT == 1))
     MInvalICacheLine((unsigned long)vec_base);
 #else
     __FENCE_I();
 #endif
 #endif
 }
References __FENCE_I(), __RV_CSR_READ, CSR_MTVT, MFlushDCacheLine(), and MInvalICacheLine().
__ECLIC_SetVector_S()
__STATIC_INLINE void __ECLIC_SetVector_S (IRQn_Type IRQn, rv_csr_t vector)
Set Interrupt Vector of a specific interrupt in supervisor mode.
This function set interrupt handler address of the specific interrupt IRQn.
Parameters
[in] IRQn Interrupt number
[in] vector Interrupt handler address
Remarks
IRQn must not be negative.
You can set the CSR_CSR_MTVT to set interrupt vector table entry address.
If your vector table is placed in readonly section, the vector for IRQn will not be modified. For this case, you need to use the correct irq handler name defined in your vector table as your irq handler function name.
This function will only work correctly when the vector table is placed in an read-write enabled section.
See also
ECLIC_GetVector_S
Definition at line 1489 of file core_feature_eclic.h.
 {
     volatile unsigned long vec_base;
     vec_base = ((unsigned long)__RV_CSR_READ(CSR_STVT));
     vec_base += ((unsigned long)IRQn) * sizeof(unsigned long);
     (* (unsigned long *) vec_base) = vector;
 #if (defined(__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1))
 #if (defined(__CCM_PRESENT) && (__CCM_PRESENT == 1))
     SFlushDCacheLine((unsigned long)vec_base);
 #endif
 #endif
 #if (defined(__ICACHE_PRESENT) && (__ICACHE_PRESENT == 1))
 #if (defined(__CCM_PRESENT) && (__CCM_PRESENT == 1))
     SInvalICacheLine((unsigned long)vec_base);
 #else
     __FENCE_I();
 #endif
 #endif
 }
References __FENCE_I(), __RV_CSR_READ, CSR_STVT, SFlushDCacheLine(), and SInvalICacheLine().
__get_exc_entry()
__STATIC_FORCEINLINE rv_csr_t __get_exc_entry (void)
Get Exception entry address.
This function get exception handler address from 'CSR_MTVEC'.
Returns
Exception handler address
Remarks
This function use to get exception handler address from 'CSR_MTVEC'. Address need to be aligned to 64 bytes.
See also
__set_exc_entry
Definition at line 1776 of file core_feature_eclic.h.
 {
     unsigned long addr = __RV_CSR_READ(CSR_MTVEC);
     return (addr & ~ECLIC_MODE_MTVEC_Msk);
 }
References __RV_CSR_READ, CSR_MTVEC, and ECLIC_MODE_MTVEC_Msk.
__get_nmi_entry()
__STATIC_FORCEINLINE rv_csr_t __get_nmi_entry (void)
Get NMI interrupt entry from 'CSR_MNVEC'.
This function get NMI interrupt address from 'CSR_MNVEC'.
Returns
NMI interrupt handler address
Remarks
This function use to get NMI interrupt handler address from 'CSR_MNVEC'. If CSR_MMISC_CTL[9] = 1 'CSR_MNVEC'
will be equal as mtvec. If CSR_MMISC_CTL[9] = 0 'CSR_MNVEC' will be equal as reset vector.
NMI entry is defined via CSR_MMISC_CTL, writing to CSR_MNVEC will be ignored.
Definition at line 1835 of file core_feature_eclic.h.
 {
     return __RV_CSR_READ(CSR_MNVEC);
 }
References __RV_CSR_READ, and CSR_MNVEC.
__get_nonvec_entry()
__STATIC_INLINE rv_csr_t __get_nonvec_entry (void)
Get Non-vector interrupt entry address.
This function get Non-vector interrupt address.
Returns
Non-vector interrupt handler address
Remarks
This function use to get non-vector interrupt entry address from 'CSR_MTVT2' if
CSR_MTVT2 bit0 is 1. If 'CSR_MTVT2' bit0 is 0 then get address from 'CSR_MTVEC'.
See also
__set_nonvec_entry
Definition at line 1815 of file core_feature_eclic.h.
 {
     if (__RV_CSR_READ(CSR_MTVT2) & 0x1) {
         return __RV_CSR_READ(CSR_MTVT2) & (~(rv_csr_t)(0x1));
     } else {
         rv_csr_t addr = __RV_CSR_READ(CSR_MTVEC);
         return (addr & ~ECLIC_MODE_MTVEC_Msk);
     }
 }
References __RV_CSR_READ, CSR_MTVEC, CSR_MTVT2, and ECLIC_MODE_MTVEC_Msk.
__set_exc_entry()
__STATIC_FORCEINLINE void __set_exc_entry (rv_csr_t addr)
Set Exception entry address.
This function set exception handler address to 'CSR_MTVEC'.
Parameters
[in] addr Exception handler address
Remarks
This function use to set exception handler address to 'CSR_MTVEC'. Address need to be aligned to 64 bytes.
See also
__get_exc_entry
Definition at line 1758 of file core_feature_eclic.h.
 {
     addr &= (rv_csr_t)(~0x3F);
     addr |= ECLIC_MODE_MTVEC_Msk;
     __RV_CSR_WRITE(CSR_MTVEC, addr);
 }
References __RV_CSR_WRITE, CSR_MTVEC, and ECLIC_MODE_MTVEC_Msk.
__set_nonvec_entry()
__STATIC_INLINE void __set_nonvec_entry (rv_csr_t addr)
Set Non-vector interrupt entry address.
This function set Non-vector interrupt address.
Parameters
[in] addr Non-vector interrupt entry address
Remarks
This function use to set non-vector interrupt entry address to 'CSR_MTVT2' if
CSR_MTVT2 bit0 is 1. If 'CSR_MTVT2' bit0 is 0 then set address to 'CSR_MTVEC'
See also
__get_nonvec_entry
Definition at line 1793 of file core_feature_eclic.h.
 {
     if (__RV_CSR_READ(CSR_MTVT2) & 0x1) {
         __RV_CSR_WRITE(CSR_MTVT2, addr | 0x01);
     } else {
         addr &= (rv_csr_t)(~0x3F);
         addr |= ECLIC_MODE_MTVEC_Msk;
         __RV_CSR_WRITE(CSR_MTVEC, addr);
     }
 }
References __RV_CSR_READ, __RV_CSR_WRITE, CSR_MTVEC, CSR_MTVT2, and ECLIC_MODE_MTVEC_Msk.