NMSIS-Core: External Interrupt Distribution Functions
External Interrupt Distribution Functions
CIDU Functions
Functions that distribute external interrupts to cores.
Functions
__STATIC_FORCEINLINE void CIDU_BroadcastExtInterrupt (uint32_t int_id, uint32_t to_cores)
Broadcast external interrupt to cores.
__STATIC_FORCEINLINE uint32_t CIDU_GetBroadcastModeStatus (uint32_t int_id)
get broadcast mode status
__STATIC_FORCEINLINE long CIDU_SetFirstClaimMode (uint32_t int_id, uint32_t core_id)
Let the first coming core to first claim the interrupt.
__STATIC_FORCEINLINE void CIDU_ResetFirstClaimMode (uint32_t int_id)
Reset the claim mode mask.
__STATIC_FORCEINLINE uint32_t CIDU_GetClaimStatus (uint32_t int_id)
Get the claim mask status.
Detailed Description
Functions that distribute external interrupts to cores.
Function Documentation
CIDU_BroadcastExtInterrupt()
__STATIC_FORCEINLINE void CIDU_BroadcastExtInterrupt (uint32_t int_id, uint32_t to_cores)
Broadcast external interrupt to cores.
This function broadcasts external interrupt which id is int_id to some/all target cores
Parameters
[in] int_id external interrupt id
[in] to_cores target cores which can receive interrupt, use bitwise inclusive or of CIDU_RECEIVE_INTERRUPT_EN(core_id)
Remarks
External IRQn ID(int_id) is from the hard-wired persperctive, which has an offset mapped to the ECLIC IRQn, see Interrupt Number Definition in <Device.h>
By default on reset, only core 0 can receive interrupt which id is int_id
Definition at line 143 of file core_feature_cidu.h.
 {
     uint32_t* addr = (uint32_t*)CIDU_INT_INDICATOR_ADDR(int_id);
     __SW(addr, (uint32_t)to_cores);
 }
References __SW(), and CIDU_INT_INDICATOR_ADDR.
CIDU_GetBroadcastModeStatus()
__STATIC_FORCEINLINE uint32_t CIDU_GetBroadcastModeStatus (uint32_t int_id)
get broadcast mode status
Just query the INTn_INDICATOR register value
Parameters
[in] int_id external interrupt id
Returns
INTn_INDICATOR register value
Remarks
External IRQn ID(int_id) is from the hard-wired persperctive, which has an offset mapped to the ECLIC IRQn, see Interrupt Number Definition in <Device.h>
By default on reset, only core 0 can receive interrupt which id is int_id
Definition at line 161 of file core_feature_cidu.h.
 {
     uint32_t val = 0;
     uint32_t* addr = (uint32_t*)CIDU_INT_INDICATOR_ADDR(int_id);
     val = __LW(addr);
     return val;
 }
References __LW(), and CIDU_INT_INDICATOR_ADDR.
CIDU_GetClaimStatus()
__STATIC_FORCEINLINE uint32_t CIDU_GetClaimStatus (uint32_t int_id)
Get the claim mask status.
Get the claim mode staus, each bit[n] indicates whether core n has claimed interrupt successfully, 1 means yes, 0 means no.
Parameters
[in] int_id external interrupt id
Returns
claim mode register INTn_MASK value
Remarks
External IRQn ID(int_id) is from the hard-wired persperctive, which has an offset mapped to the ECLIC IRQn, see Interrupt Number Definition in <Device.h>
See also
CIDU_ResetFirstClaimMode
CIDU_SetFirstClaimMode
Definition at line 235 of file core_feature_cidu.h.
 {
     uint32_t val = 0;
     uint32_t* addr = (uint32_t*)CIDU_INT_MASK_ADDR(int_id);
     val = __LW(addr);
     return val;
 }
References __LW(), and CIDU_INT_MASK_ADDR.
CIDU_ResetFirstClaimMode()
__STATIC_FORCEINLINE void CIDU_ResetFirstClaimMode (uint32_t int_id)
Reset the claim mode mask.
Reset the claim mode mask by Writing the reset value (all 1) to it
Parameters
[in] int_id external interrupt id
Remarks
External IRQn ID(int_id) is from the hard-wired persperctive, which has an offset mapped to the ECLIC IRQn, see Interrupt Number Definition in <Device.h>
When a core claims the interrupt successfully and handle it, it must call CIDU_ResetFirstClaimMode to reset the claim
See also
CIDU_SetFirstClaimMode
Definition at line 212 of file core_feature_cidu.h.
 {
     uint32_t val = 0;
     uint32_t* addr = (uint32_t*)CIDU_INT_MASK_ADDR(int_id);
     /* clear by writing all 1 */
     __SW(addr, 0xFFFFFFFF);
 }
References __SW(), and CIDU_INT_MASK_ADDR.
CIDU_SetFirstClaimMode()
__STATIC_FORCEINLINE long CIDU_SetFirstClaimMode (uint32_t int_id, uint32_t core_id)
Let the first coming core to first claim the interrupt.
In external interrupt broadcast mode, make the first coming core to claim this interrupt and then can handle it.
Parameters
[in] int_id external interrupt id
[in] core_id core id that receive the interrupt
Returns
-1 if it fails to claim the interrupt, else it can continue to handle the interrupt
Remarks
External IRQn ID(int_id) is from the hard-wired persperctive, which has an offset mapped to the ECLIC IRQn, see Interrupt Number Definition in <Device.h>.
If it fails to claim the interrupt, it should quit the interrupt n's handler of all cores
When a core claims the interrupt successfully and has handled it, it must call CIDU_ResetFirstClaimMode to reset the claim.
See also
CIDU_BroadcastExtInterrupt
CIDU_ResetFirstClaimMode
Definition at line 186 of file core_feature_cidu.h.
 {
     uint32_t val = 0;
     uint32_t* addr = (uint32_t*)CIDU_INT_MASK_ADDR(int_id);
     uint32_t mask = 1 << core_id;
     __SW(addr, mask);
     val = __LW(addr);
     if (mask == val) {
         return 0;
     }
     return -1;
 }
References __LW(), __SW(), and CIDU_INT_MASK_ADDR.