NMSIS-Core: SMPCC Functions
SMPCC Functions
SMPCC related functions.
Functions
__STATIC_FORCEINLINE SMP_VER_Type SMPCC_GetVersion (void)
Get the SMP version number.
__STATIC_FORCEINLINE uint8_t SMPCC_IsCCachePresent (void)
Check if cluster cache is present.
__STATIC_FORCEINLINE uint8_t SMPCC_GetCoreNum (void)
Get the number of cores in the cluster.
__STATIC_FORCEINLINE uint8_t SMPCC_GetIOCPNum (void)
Get the number of IO coherency ports.
__STATIC_FORCEINLINE uint8_t SMPCC_GetPMONNum (void)
Get the number of performance monitors.
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheSetNum (void)
Get the number of cache sets.
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheWayNum (void)
Get the number of cache ways.
__STATIC_FORCEINLINE uint8_t SMPCC_GetCCacheLineSize (void)
Get the cache line size.
__STATIC_FORCEINLINE uint8_t SMPCC_IsCCacheSupportECC (void)
Check if cluster cache supports ECC.
__STATIC_FORCEINLINE void SMPCC_EnableSnoop (uint16_t client_msk)
Enable snoop for specific clients.
__STATIC_FORCEINLINE void SMPCC_DisableSnoop (uint16_t client_msk)
Disable snoop for specific clients.
__STATIC_FORCEINLINE void SMPCC_EnableCCache (void)
Enable cluster cache.
__STATIC_FORCEINLINE void SMPCC_DisableCCache (void)
Disable cluster cache.
__STATIC_FORCEINLINE int32_t SMPCC_IsCCacheEnabled (void)
Get status of cluster cache.
__STATIC_FORCEINLINE uint8_t SMPCC_IsAnySnoopPending (uint32_t client_msk)
Check if any client is being snooped.
__STATIC_FORCEINLINE uint8_t SMPCC_IsAnyTransactionPending (uint32_t client_msk)
Check if any transaction is pending for clients.
__STATIC_FORCEINLINE void SMPCC_SetCLMAllWays (uint64_t addr)
Set Cluster Local Memory to use all ways.
__STATIC_FORCEINLINE void SMPCC_SetCLMNWays (uint64_t addr, uint32_t way_msk)
Set Cluster Local Memory to use specific ways.
__STATIC_FORCEINLINE void SMPCC_SetCLMNoWay (void)
Configure Cluster Local Memory to use no ways.
__STATIC_FORCEINLINE void SMPCC_SetCCacheControl (uint32_t val)
Set Cluster Cache Control register.
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheControl (void)
Get Cluster Cache Control register value.
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECC (void)
Enable Cluster Cache ECC.
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECC (void)
Disable Cluster Cache ECC.
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECCExcp (void)
Enable Cluster Cache ECC Exception.
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECCExcp (void)
Disable Cluster Cache ECC Exception.
__STATIC_FORCEINLINE void SMPCC_LockECCConfig (void)
Lock ECC Configuration.
__STATIC_FORCEINLINE void SMPCC_LockECCErrInjection (void)
Lock ECC Error Injection Register.
__STATIC_FORCEINLINE void SMPCC_EnableRecvErrIrq (void)
Enable Recoverable Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_DisableRecvErrIrq (void)
Disable Recoverable Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_EnableFatalErrIrq (void)
Enable Fatal Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_ClearBusErrPending (void)
Clear Bus Error Pending Status.
__STATIC_FORCEINLINE void SMPCC_DisableFatalErrIrq (void)
Disable Fatal Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_EnableBusErrIrq (void)
Enable Bus Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_DisableBusErrIrq (void)
Disable Bus Error Interrupt.
__STATIC_FORCEINLINE void SMPCC_EnableSModeCmd (void)
Enable Supervisor Mode Commands.
__STATIC_FORCEINLINE void SMPCC_DisableSModeCmd (void)
Disable Supervisor Mode Commands.
__STATIC_FORCEINLINE void SMPCC_EnableUModeCmd (void)
Enable User Mode Commands.
__STATIC_FORCEINLINE void SMPCC_DisableUModeCmd (void)
Disable User Mode Commands.
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECCCheck (void)
Enable Cluster Cache ECC Check.
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECCCheck (void)
Disable Cluster Cache ECC Check.
__STATIC_FORCEINLINE void SMPCC_EnableCLMECC (void)
Enable Cluster Local Memory ECC.
__STATIC_FORCEINLINE void SMPCC_DisableCLMECC (void)
Disable Cluster Local Memory ECC.
__STATIC_FORCEINLINE void SMPCC_EnableCLMECCCheck (void)
Enable Cluster Local Memory ECC Check.
__STATIC_FORCEINLINE void SMPCC_DisableCLMECCCheck (void)
Disable Cluster Local Memory ECC Check.
__STATIC_FORCEINLINE void SMPCC_EnableCLMECCExcp (void)
Enable Cluster Local Memory ECC Exception.
__STATIC_FORCEINLINE void SMPCC_DisableCLMECCExcp (void)
Disable Cluster Local Memory ECC Exception.
__STATIC_FORCEINLINE void SMPCC_EnableL1PrefetchShareCacheline (void)
Enable L1 Prefetch to Snoop and Share Cacheline.
__STATIC_FORCEINLINE void SMPCC_DisableL1PrefetchShareCacheline (void)
Disable L1 Prefetch to Snoop and Share Cacheline.
__STATIC_FORCEINLINE void SMPCC_EnableCCacheEarlyPrefetch (void)
Enable Cluster Cache Early Prefetch.
__STATIC_FORCEINLINE void SMPCC_DisableCCacheEarlyPrefetch (void)
Disable Cluster Cache Early Prefetch.
__STATIC_FORCEINLINE void SMPCC_LimitCCachePrefetchOutsNum (void)
Limit Cluster Cache Prefetch Outstanding Number.
__STATIC_FORCEINLINE void SMPCC_UnlimitCCachePrefetchOutsNum (void)
Unlimit Cluster Cache Prefetch Outstanding Number.
__STATIC_FORCEINLINE void SMPCC_EnableCCachePrefetchNoWb (void)
Enable Cluster Cache Prefetch to Avoid Write Back.
__STATIC_FORCEINLINE void SMPCC_DisableCCachePrefetchNoWb (void)
Disable Cluster Cache Prefetch to Avoid Write Back.
__STATIC_FORCEINLINE void SMPCC_EnableICacheSnoopDCache (void)
Enable ICache to Snoop DCache.
__STATIC_FORCEINLINE void SMPCC_DisableICacheSnoopDCache (void)
Disable ICache to Snoop DCache.
__STATIC_FORCEINLINE uint32_t SMPCC_GetRecvErrCount (void)
Get Recoverable Error Count.
__STATIC_FORCEINLINE void SMPCC_ClearRecvErrCount (void)
Clear Recoverable Error Count.
__STATIC_FORCEINLINE uint32_t SMPCC_GetFatalErrCount (void)
Get Fatal Error Count.
__STATIC_FORCEINLINE void SMPCC_ClearFatalErrCount (void)
Clear Fatal Error Count.
__STATIC_FORCEINLINE void SMPCC_SetRecvErrCntThreshold (uint16_t threshold)
Set Recoverable Error Count Threshold.
__STATIC_FORCEINLINE uint16_t SMPCC_GetRecvErrCntThreshold (void)
Get Recoverable Error Count Threshold.
__STATIC_FORCEINLINE void SMPCC_SetFatalErrCntThreshold (uint16_t threshold)
Set Fatal Error Count Threshold.
__STATIC_FORCEINLINE uint16_t SMPCC_GetFatalErrCntThreshold (void)
Get Fatal Error Count Threshold.
__STATIC_FORCEINLINE uint32_t SMPCC_GetClientErrStatus (uint8_t client_id)
Get Client Error Status.
__STATIC_FORCEINLINE void SMPCC_SetSTMControl (uint32_t val)
Set Stream Control Register.
__STATIC_FORCEINLINE uint32_t SMPCC_GetSTMControl (void)
Get Stream Control Register Value.
__STATIC_FORCEINLINE void SMPCC_EnableStreamRead (void)
Enable Stream Read.
__STATIC_FORCEINLINE void SMPCC_DisableStreamRead (void)
Disable Stream Read.
__STATIC_FORCEINLINE void SMPCC_EnableStreamWrite (void)
Enable Stream Write.
__STATIC_FORCEINLINE void SMPCC_DisableStreamWrite (void)
Disable Stream Write.
__STATIC_FORCEINLINE void SMPCC_EnableStreamTransAlloc (void)
Enable Stream Translate Allocate.
__STATIC_FORCEINLINE void SMPCC_DisableStreamTransAlloc (void)
Disable Stream Translate Allocate.
__STATIC_FORCEINLINE void SMPCC_EnableStreamMergeNCRead (void)
Enable Stream Merge Non-Cacheable Read.
__STATIC_FORCEINLINE void SMPCC_DisableStreamMergeNCRead (void)
Disable Stream Merge Non-Cacheable Read.
__STATIC_FORCEINLINE void SMPCC_EnableStreamReadCross4K (void)
Enable Stream Read Cross 4K Boundary.
__STATIC_FORCEINLINE void SMPCC_DisableStreamReadCross4K (void)
Disable Stream Read Cross 4K Boundary.
__STATIC_FORCEINLINE void SMPCC_SetNSRegionNACL (uint8_t region_id, uint64_t addr)
Set Non-Shareable Region to NACL.
__STATIC_FORCEINLINE void SMPCC_SetNSRegionNAPOT (uint8_t region_id, uint64_t addr)
Set Non-Shareable Region to NAPOT.
__STATIC_FORCEINLINE void SMPCC_DisableNSRegion (uint8_t region_id)
Disable Non-Shareable Region.
__STATIC_FORCEINLINE void SMPCC_SetPMONEventSelect (uint8_t idx, uint8_t client_id, uint8_t event)
Set Performance Monitor Event Selection.
__STATIC_FORCEINLINE uint32_t SMPCC_GetPMONEventSelect (uint8_t idx)
Get Performance Monitor Event Selection.
__STATIC_FORCEINLINE uint64_t SMPCC_GetPMONCount (uint8_t idx)
Get Performance Monitor Count.
__STATIC_FORCEINLINE void SMPCC_ClearPMONCount (uint8_t idx)
Clear Performance Monitor Count.
__STATIC_FORCEINLINE uint64_t SMPCC_GetClientErrAddr (uint8_t client_id)
Get Client Error Address.
__STATIC_FORCEINLINE void SMPCC_MaskClientCCacheWays (uint8_t client_id, uint32_t way_msk)
Mask Client Cluster Cache Ways.
__STATIC_FORCEINLINE int32_t SMPCC_IsXorErrorInjectMode (void)
Check if ECC error injection mode is XOR mode.
__STATIC_FORCEINLINE void SMPCC_SetECCCode (uint32_t ecc_code)
Set ECC code for error injection.
__STATIC_FORCEINLINE void SMPCC_CCacheTramErrInject (uint32_t ecc_code, uint32_t *addr, uint16_t way)
Inject ECC error to cluster cache tag RAM.
__STATIC_FORCEINLINE void SMPCC_CCacheDramErrInject (uint32_t ecc_code, uint32_t *addr, uint16_t way)
Inject ECC error to cluster cache data RAM.
__STATIC_FORCEINLINE void SMPCC_CLMErrInject (uint32_t ecc_code, uint32_t *addr)
Inject ECC error to CLM (Cluster Local Memory)
__STATIC_FORCEINLINE void SMPCC_CCacheErrRestore (void *addr)
Restore cluster cache after error injection.
Detailed Description
SMPCC related functions.
Function Documentation
SMPCC_CCacheDramErrInject()
__STATIC_FORCEINLINE void SMPCC_CCacheDramErrInject (uint32_t ecc_code, uint32_t * addr, uint16_t way)
Inject ECC error to cluster cache data RAM.
This function injects an ECC error into the cluster cache data RAM at the specified address.
Parameters
ecc_code ECC code to be injected
addr Address where the error should be injected
way Cache way number used for precise injection
Remarks
The 4-byte data pointed to by addr is used to refill the CCache line. The cache line is larger than 4 bytes, this data is replicated to fill the entire line.
The way value must be one-hot. For example, if the cache has 2 ways, valid values are 0x01 and 0x02; all other values are invalid.
Returns
None
Definition at line 1952 of file core_feature_smpcc.h.
 {
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ECC_INJ_ADDR = (unsigned long)addr;
         SMPCC->CC_ECC_INJ_WAY.b.num = way;
         SMPCC->CC_ECC_INJ_DATA = *addr;
     }
     SMPCC_SetECCCode(ecc_code);
     SMPCC_DisableCCacheECCCheck();
     MInvalICacheLine((unsigned long)addr);
     MFlushInvalDCacheCCacheLine((unsigned long)addr);
     __RWMB();
     SMPCC->CC_ERR_INJ.b.inj_data = SMPCC_ERR_INJ_INJDATA_ENABLE;
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ERR_INJ.b.cs = SMPCC_ERR_INJ_CS_START;
         /* Wait for the ECC injection to complete */
         while (SMPCC->CC_ERR_INJ.b.cs == SMPCC_ERR_INJ_CS_START);
     } else {
         MLockCCacheLine((unsigned long)addr);
     }
     SMPCC->CC_ERR_INJ.b.inj_data = SMPCC_ERR_INJ_INJDATA_DISABLE;
     __RWMB(); // To ensure the ECC error injection is finished
     SMPCC_EnableCCacheECCCheck();
     __RWMB(); // To ensure the ECC check is enabled
 }
References __RWMB, MFlushInvalDCacheCCacheLine, MInvalICacheLine(), MLockCCacheLine(), SMPCC, SMPCC_DisableCCacheECCCheck(), SMPCC_EnableCCacheECCCheck(), SMPCC_ERR_INJ_CS_START, SMPCC_ERR_INJ_INJDATA_DISABLE, SMPCC_ERR_INJ_INJDATA_ENABLE, and SMPCC_SetECCCode().
SMPCC_CCacheErrRestore()
__STATIC_FORCEINLINE void SMPCC_CCacheErrRestore (void * addr)
Restore cluster cache after error injection.
This function restores the cluster cache after an error injection operation.
Parameters
addr Address to be restored
Returns
None
Definition at line 2022 of file core_feature_smpcc.h.
 {
     SMPCC_DisableCCacheECCCheck();
     MInvalICacheLine((unsigned long)addr);
     MFlushInvalDCacheCCacheLine((unsigned long)addr);
     MLockCCacheLine((unsigned long)addr);
     SMPCC_EnableCCacheECCCheck();
 }
References MFlushInvalDCacheCCacheLine, MInvalICacheLine(), MLockCCacheLine(), SMPCC_DisableCCacheECCCheck(), and SMPCC_EnableCCacheECCCheck().
SMPCC_CCacheTramErrInject()
__STATIC_FORCEINLINE void SMPCC_CCacheTramErrInject (uint32_t ecc_code, uint32_t * addr, uint16_t way)
Inject ECC error to cluster cache tag RAM.
This function injects an ECC error into the cluster cache tag RAM at the specified address.
Parameters
ecc_code ECC code to be injected
addr Address where the error should be injected
way Cache way number used for precise injection
Remarks
The 4-byte data pointed to by addr is used to refill the CCache line. The cache line is larger than 4 bytes, this data is replicated to fill the entire line.
The way value must be one-hot. For example, if the cache has 2 ways, valid values are 0x01 and 0x02; all other values are invalid.
Returns
None
Definition at line 1913 of file core_feature_smpcc.h.
 {
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ECC_INJ_ADDR = (unsigned long)addr;
         SMPCC->CC_ECC_INJ_WAY.b.num = way;
         SMPCC->CC_ECC_INJ_DATA = *addr;
     }
     SMPCC_SetECCCode(ecc_code);
     SMPCC_DisableCCacheECCCheck();
     MInvalICacheLine((unsigned long)addr);
     MFlushInvalDCacheCCacheLine((unsigned long)addr);
     __RWMB();
     SMPCC->CC_ERR_INJ.b.inj_tag = SMPCC_ERR_INJ_INJTAG_ENABLE;
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ERR_INJ.b.cs = SMPCC_ERR_INJ_CS_START;
         /* Wait for the ECC injection to complete */
         while (SMPCC->CC_ERR_INJ.b.cs == SMPCC_ERR_INJ_CS_START);
     } else {
         MLockCCacheLine((unsigned long)addr);
     }
     SMPCC->CC_ERR_INJ.b.inj_tag = SMPCC_ERR_INJ_INJTAG_DISABLE;
     __RWMB(); // To ensure the ECC error injection is finished
     SMPCC_EnableCCacheECCCheck();
     __RWMB(); // To ensure the ECC check is enabled
 }
References __RWMB, MFlushInvalDCacheCCacheLine, MInvalICacheLine(), MLockCCacheLine(), SMPCC, SMPCC_DisableCCacheECCCheck(), SMPCC_EnableCCacheECCCheck(), SMPCC_ERR_INJ_CS_START, SMPCC_ERR_INJ_INJTAG_DISABLE, SMPCC_ERR_INJ_INJTAG_ENABLE, and SMPCC_SetECCCode().
SMPCC_ClearBusErrPending()
__STATIC_FORCEINLINE void SMPCC_ClearBusErrPending (void)
Clear Bus Error Pending Status.
This function clears the pending status for bus errors in cluster cache maintenance operations.
See also
SMPCC_EnableBusErrIrq
SMPCC_DisableBusErrIrq
Definition at line 1179 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.bus_err_pend = 0;
 }
References SMPCC.
SMPCC_ClearFatalErrCount()
__STATIC_FORCEINLINE void SMPCC_ClearFatalErrCount (void)
Clear Fatal Error Count.
This function clears the fatal error count register.
See also
SMPCC_GetFatalErrCount
Definition at line 1529 of file core_feature_smpcc.h.
 {
     SMPCC->CC_FATAL_CNT.w = 0;
 }
References SMPCC.
SMPCC_ClearPMONCount()
__STATIC_FORCEINLINE void SMPCC_ClearPMONCount (uint8_t idx)
Clear Performance Monitor Count.
This function clears the count value of a performance monitor.
Parameters
[in] idx Index of the performance monitor to clear
See also
SMPCC_SetPMONEventSelect
SMPCC_GetPMONEventSelect
SMPCC_GetPMONCount
Definition at line 1849 of file core_feature_smpcc.h.
 {
     SMPCC->SMP_PMON_CNT[idx] = 0;
 }
References SMPCC.
SMPCC_ClearRecvErrCount()
__STATIC_FORCEINLINE void SMPCC_ClearRecvErrCount (void)
Clear Recoverable Error Count.
This function clears the recoverable error count register.
See also
SMPCC_GetRecvErrCount
Definition at line 1504 of file core_feature_smpcc.h.
 {
     SMPCC->CC_RECV_CNT.w = 0;
 }
References SMPCC.
SMPCC_CLMErrInject()
__STATIC_FORCEINLINE void SMPCC_CLMErrInject (uint32_t ecc_code, uint32_t * addr)
Inject ECC error to CLM (Cluster Local Memory)
This function injects an ECC error into the CLM at the specified address. Only the ecc code can be injected, the data will keep as it is.
Parameters
ecc_code ECC code to be injected
addr Address where the error should be injected
Returns
None
Definition at line 1988 of file core_feature_smpcc.h.
 {
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ECC_INJ_ADDR = (unsigned long)addr;
         /* The way number should be one-hot, but not used for CLM error injection. */
         SMPCC->CC_ECC_INJ_WAY.b.num = 1;
         SMPCC->CC_ECC_INJ_DATA = *addr;
     }
     SMPCC_SetECCCode(ecc_code);
     SMPCC_DisableCCacheECCCheck();
     MFlushInvalDCacheCCacheLine((unsigned long)addr);
     __RWMB();
     SMPCC->CC_ERR_INJ.b.inj_clm = SMPCC_ERR_INJ_INJCLM_ENABLE;
     if (IINFO_IsPreciseECCInjSupported()) {
         SMPCC->CC_ERR_INJ.b.cs = SMPCC_ERR_INJ_CS_START;
         /* Wait for the ECC injection to complete */
         while (SMPCC->CC_ERR_INJ.b.cs == SMPCC_ERR_INJ_CS_START);
     } else {
         MLockCCacheLine((unsigned long)addr);
     }
     SMPCC->CC_ERR_INJ.b.inj_clm = SMPCC_ERR_INJ_INJCLM_DISABLE;
     __RWMB(); // To ensure the ECC error injection is finished
     SMPCC_EnableCCacheECCCheck();
     __RWMB(); // To ensure the ECC check is enabled
 }
References __RWMB, MFlushInvalDCacheCCacheLine, MLockCCacheLine(), SMPCC, SMPCC_DisableCCacheECCCheck(), SMPCC_EnableCCacheECCCheck(), SMPCC_ERR_INJ_CS_START, SMPCC_ERR_INJ_INJCLM_DISABLE, SMPCC_ERR_INJ_INJCLM_ENABLE, and SMPCC_SetECCCode().
SMPCC_DisableBusErrIrq()
__STATIC_FORCEINLINE void SMPCC_DisableBusErrIrq (void)
Disable Bus Error Interrupt.
This function disables interrupt generation for bus errors in cluster cache maintenance operations.
See also
SMPCC_EnableBusErrIrq
Definition at line 1215 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.bus_err_irq_en = SMPCC_CTRL_BUS_ERR_IRQ_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_BUS_ERR_IRQ_EN_DISABLE.
SMPCC_DisableCCache()
__STATIC_FORCEINLINE void SMPCC_DisableCCache (void)
Disable cluster cache.
This function disables the cluster cache.
See also
SMPCC_EnableCCache
Definition at line 914 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.cc_en = SMPCC_CTRL_CC_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_EN_DISABLE.
SMPCC_DisableCCacheEarlyPrefetch()
__STATIC_FORCEINLINE void SMPCC_DisableCCacheEarlyPrefetch (void)
Disable Cluster Cache Early Prefetch.
This function disables L2 prefetch to initialize external bus read access while looking up the cluster cache.
See also
SMPCC_EnableCCacheEarlyPrefetch
Definition at line 1407 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_l2_early_en = SMPCC_CTRL_PF_L2_EARLY_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_L2_EARLY_EN_DISABLE.
SMPCC_DisableCCacheECC()
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECC (void)
Disable Cluster Cache ECC.
This function disables ECC functionality for the cluster cache.
See also
SMPCC_EnableCCacheECC
Definition at line 1082 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.cc_ecc_en = SMPCC_CTRL_CC_ECC_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_ECC_EN_DISABLE.
SMPCC_DisableCCacheECCCheck()
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECCCheck (void)
Disable Cluster Cache ECC Check.
This function disables ECC check functionality for the cluster cache.
See also
SMPCC_EnableCCacheECCCheck
Definition at line 1287 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.ecc_chk_en = SMPCC_CTRL_ECC_CHK_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_ECC_CHK_EN_DISABLE.
Referenced by SMPCC_CCacheDramErrInject(), SMPCC_CCacheErrRestore(), SMPCC_CCacheTramErrInject(), and SMPCC_CLMErrInject().
SMPCC_DisableCCacheECCExcp()
__STATIC_FORCEINLINE void SMPCC_DisableCCacheECCExcp (void)
Disable Cluster Cache ECC Exception.
This function disables ECC exception handling for the cluster cache.
See also
SMPCC_EnableCCacheECCExcp
Definition at line 1106 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.ecc_excp_en = SMPCC_CTRL_CC_ECC_EXCP_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_ECC_EXCP_EN_DISABLE.
SMPCC_DisableCCachePrefetchNoWb()
__STATIC_FORCEINLINE void SMPCC_DisableCCachePrefetchNoWb (void)
Disable Cluster Cache Prefetch to Avoid Write Back.
This function disables L2 prefetch from aborting and avoiding dirty cacheline write back when filling the cluster cache.
See also
SMPCC_EnableCCachePrefetchNoWb
Definition at line 1455 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_no_wb = SMPCC_CTRL_PF_NO_WB_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_NO_WB_DISABLE.
SMPCC_DisableCLMECC()
__STATIC_FORCEINLINE void SMPCC_DisableCLMECC (void)
Disable Cluster Local Memory ECC.
This function disables ECC functionality for the Cluster Local Memory.
See also
SMPCC_EnableCLMECC
Definition at line 1311 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_ecc_en = SMPCC_CTRL_CLM_ECC_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_ECC_EN_DISABLE.
SMPCC_DisableCLMECCCheck()
__STATIC_FORCEINLINE void SMPCC_DisableCLMECCCheck (void)
Disable Cluster Local Memory ECC Check.
This function disables ECC check functionality for the Cluster Local Memory.
See also
SMPCC_EnableCLMECCCheck
Definition at line 1335 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_ecc_chk_en = SMPCC_CTRL_CLM_ECC_CHK_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_ECC_CHK_EN_DISABLE.
SMPCC_DisableCLMECCExcp()
__STATIC_FORCEINLINE void SMPCC_DisableCLMECCExcp (void)
Disable Cluster Local Memory ECC Exception.
This function disables ECC exception handling for the Cluster Local Memory.
See also
SMPCC_EnableCLMECCExcp
Definition at line 1359 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_excp_en = SMPCC_CTRL_CLM_EXCP_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_EXCP_EN_DISABLE.
SMPCC_DisableFatalErrIrq()
__STATIC_FORCEINLINE void SMPCC_DisableFatalErrIrq (void)
Disable Fatal Error Interrupt.
This function disables interrupt generation when fatal error count exceeds the threshold.
See also
SMPCC_EnableFatalErrIrq
Definition at line 1191 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.fatal_err_irq_en = SMPCC_CTRL_FATAL_ERR_IRQ_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_FATAL_ERR_IRQ_EN_DISABLE.
SMPCC_DisableICacheSnoopDCache()
__STATIC_FORCEINLINE void SMPCC_DisableICacheSnoopDCache (void)
Disable ICache to Snoop DCache.
This function disables snoop to dcache for icache refill reads.
See also
SMPCC_EnableICacheSnoopDCache
Definition at line 1479 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.i_snoop_d_en = SMPCC_CTRL_I_SNOOP_D_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_I_SNOOP_D_EN_DISABLE.
SMPCC_DisableL1PrefetchShareCacheline()
__STATIC_FORCEINLINE void SMPCC_DisableL1PrefetchShareCacheline (void)
Disable L1 Prefetch to Snoop and Share Cacheline.
This function disables L1 prefetch to snoop and share cacheline from other cores.
See also
SMPCC_EnableL1PrefetchShareCacheline
Definition at line 1383 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_sh_cl_en = SMPCC_CTRL_PF_SH_CL_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_SH_CL_EN_DISABLE.
SMPCC_DisableNSRegion()
__STATIC_FORCEINLINE void SMPCC_DisableNSRegion (uint8_t region_id)
Disable Non-Shareable Region.
This function disables a non-shareable region.
Parameters
[in] region_id ID of the region to disable
See also
SMPCC_SetNSRegionNAPOT
SMPCC_SetNSRegionNACL
Definition at line 1783 of file core_feature_smpcc.h.
 {
     SMPCC->NS_RG[region_id].dw = SMPCC_NS_RG_CFG_DISABLE;
 }
References SMPCC, and SMPCC_NS_RG_CFG_DISABLE.
SMPCC_DisableRecvErrIrq()
__STATIC_FORCEINLINE void SMPCC_DisableRecvErrIrq (void)
Disable Recoverable Error Interrupt.
This function disables interrupt generation when recoverable error count exceeds the threshold.
See also
SMPCC_EnableRecvErrIrq
Definition at line 1154 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.recv_err_irq_en = SMPCC_CTRL_RECV_ERR_IRQ_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_RECV_ERR_IRQ_EN_DISABLE.
SMPCC_DisableSModeCmd()
__STATIC_FORCEINLINE void SMPCC_DisableSModeCmd (void)
Disable Supervisor Mode Commands.
This function disables supervisor mode from operating CC_sCMD and SMP_PMON_SEL registers.
See also
SMPCC_EnableSModeCmd
Definition at line 1239 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.sup_cmd_en = SMPCC_CTRL_SUP_CMD_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_SUP_CMD_EN_DISABLE.
SMPCC_DisableSnoop()
__STATIC_FORCEINLINE void SMPCC_DisableSnoop (uint16_t client_msk)
Disable snoop for specific clients.
This function disables snoop functionality for specified client mask.
Parameters
[in] client_msk Client mask to disable snoop for
See also
SMPCC_EnableSnoop
Definition at line 890 of file core_feature_smpcc.h.
 {
     SMPCC->SMP_ENB.b.smp_enable &= ~client_msk;
 }
References SMPCC.
SMPCC_DisableStreamMergeNCRead()
__STATIC_FORCEINLINE void SMPCC_DisableStreamMergeNCRead (void)
Disable Stream Merge Non-Cacheable Read.
This function disables non-cacheable attribute read merge functionality.
See also
SMPCC_EnableStreamMergeNCRead
Definition at line 1715 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.rd_merge_en = SMPCC_STMCTRL_RD_MERGE_EN_DISABLE;
 }
References SMPCC, and SMPCC_STMCTRL_RD_MERGE_EN_DISABLE.
SMPCC_DisableStreamRead()
__STATIC_FORCEINLINE void SMPCC_DisableStreamRead (void)
Disable Stream Read.
This function disables stream read functionality.
See also
SMPCC_EnableStreamRead
Definition at line 1643 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.rd_stm_en = SMPCC_STMCTRL_RD_STM_EN_DISABLE;
 }
References SMPCC, and SMPCC_STMCTRL_RD_STM_EN_DISABLE.
SMPCC_DisableStreamReadCross4K()
__STATIC_FORCEINLINE void SMPCC_DisableStreamReadCross4K (void)
Disable Stream Read Cross 4K Boundary.
This function disables read stream from crossing 4K boundary.
See also
SMPCC_EnableStreamReadCross4K
Definition at line 1739 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.cross_en = SMPCC_STMCTRL_CROSS_EN_DISABLE;
 }
References SMPCC, and SMPCC_STMCTRL_CROSS_EN_DISABLE.
SMPCC_DisableStreamTransAlloc()
__STATIC_FORCEINLINE void SMPCC_DisableStreamTransAlloc (void)
Disable Stream Translate Allocate.
This function disables translation of allocate attribute to non-alloc attribute.
See also
SMPCC_EnableStreamTransAlloc
Definition at line 1691 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.trans_alloc = SMPCC_STMCTRL_TRANS_ALLOC_DISABLE;
 }
References SMPCC, and SMPCC_STMCTRL_TRANS_ALLOC_DISABLE.
SMPCC_DisableStreamWrite()
__STATIC_FORCEINLINE void SMPCC_DisableStreamWrite (void)
Disable Stream Write.
This function disables stream write functionality.
See also
SMPCC_EnableStreamWrite
Definition at line 1667 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.wr_stm_en = SMPCC_STMCTRL_WR_STM_EN_DISABLE;
 }
References SMPCC, and SMPCC_STMCTRL_WR_STM_EN_DISABLE.
SMPCC_DisableUModeCmd()
__STATIC_FORCEINLINE void SMPCC_DisableUModeCmd (void)
Disable User Mode Commands.
This function disables user mode from operating CC_uCMD and SMP_PMON_SEL registers.
See also
SMPCC_EnableUModeCmd
Definition at line 1263 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.use_cmd_en = SMPCC_CTRL_USE_CMD_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_USE_CMD_EN_DISABLE.
SMPCC_EnableBusErrIrq()
__STATIC_FORCEINLINE void SMPCC_EnableBusErrIrq (void)
Enable Bus Error Interrupt.
This function enables interrupt generation for bus errors in cluster cache maintenance operations.
See also
SMPCC_DisableBusErrIrq
Definition at line 1203 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.bus_err_irq_en = SMPCC_CTRL_BUS_ERR_IRQ_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_BUS_ERR_IRQ_EN_ENABLE.
SMPCC_EnableCCache()
__STATIC_FORCEINLINE void SMPCC_EnableCCache (void)
Enable cluster cache.
This function enables the cluster cache.
See also
SMPCC_DisableCCache
Definition at line 902 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.cc_en = SMPCC_CTRL_CC_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_EN_ENABLE.
SMPCC_EnableCCacheEarlyPrefetch()
__STATIC_FORCEINLINE void SMPCC_EnableCCacheEarlyPrefetch (void)
Enable Cluster Cache Early Prefetch.
This function enables L2 prefetch to initialize external bus read access while looking up the cluster cache.
See also
SMPCC_DisableCCacheEarlyPrefetch
Definition at line 1395 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_l2_early_en = SMPCC_CTRL_PF_L2_EARLY_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_L2_EARLY_EN_ENABLE.
SMPCC_EnableCCacheECC()
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECC (void)
Enable Cluster Cache ECC.
This function enables ECC functionality for the cluster cache.
See also
SMPCC_DisableCCacheECC
Definition at line 1070 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.cc_ecc_en = SMPCC_CTRL_CC_ECC_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_ECC_EN_ENABLE.
SMPCC_EnableCCacheECCCheck()
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECCCheck (void)
Enable Cluster Cache ECC Check.
This function enables ECC check functionality for the cluster cache.
See also
SMPCC_DisableCCacheECCCheck
Definition at line 1275 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.ecc_chk_en = SMPCC_CTRL_ECC_CHK_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_ECC_CHK_EN_ENABLE.
Referenced by SMPCC_CCacheDramErrInject(), SMPCC_CCacheErrRestore(), SMPCC_CCacheTramErrInject(), and SMPCC_CLMErrInject().
SMPCC_EnableCCacheECCExcp()
__STATIC_FORCEINLINE void SMPCC_EnableCCacheECCExcp (void)
Enable Cluster Cache ECC Exception.
This function enables ECC exception handling for the cluster cache.
See also
SMPCC_DisableCCacheECCExcp
Definition at line 1094 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.ecc_excp_en = SMPCC_CTRL_CC_ECC_EXCP_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CC_ECC_EXCP_EN_ENABLE.
SMPCC_EnableCCachePrefetchNoWb()
__STATIC_FORCEINLINE void SMPCC_EnableCCachePrefetchNoWb (void)
Enable Cluster Cache Prefetch to Avoid Write Back.
This function enables L2 prefetch to abort and avoid dirty cacheline write back when filling the cluster cache.
See also
SMPCC_DisableCCachePrefetchNoWb
Definition at line 1443 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_no_wb = SMPCC_CTRL_PF_NO_WB_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_NO_WB_ENABLE.
SMPCC_EnableCLMECC()
__STATIC_FORCEINLINE void SMPCC_EnableCLMECC (void)
Enable Cluster Local Memory ECC.
This function enables ECC functionality for the Cluster Local Memory.
See also
SMPCC_DisableCLMECC
Definition at line 1299 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_ecc_en = SMPCC_CTRL_CLM_ECC_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_ECC_EN_ENABLE.
SMPCC_EnableCLMECCCheck()
__STATIC_FORCEINLINE void SMPCC_EnableCLMECCCheck (void)
Enable Cluster Local Memory ECC Check.
This function enables ECC check functionality for the Cluster Local Memory.
See also
SMPCC_DisableCLMCCCheck
Definition at line 1323 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_ecc_chk_en = SMPCC_CTRL_CLM_ECC_CHK_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_ECC_CHK_EN_ENABLE.
SMPCC_EnableCLMECCExcp()
__STATIC_FORCEINLINE void SMPCC_EnableCLMECCExcp (void)
Enable Cluster Local Memory ECC Exception.
This function enables ECC exception handling for the Cluster Local Memory.
See also
SMPCC_DisableCLMECCExcp
Definition at line 1347 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.clm_excp_en = SMPCC_CTRL_CLM_EXCP_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_CLM_EXCP_EN_ENABLE.
SMPCC_EnableFatalErrIrq()
__STATIC_FORCEINLINE void SMPCC_EnableFatalErrIrq (void)
Enable Fatal Error Interrupt.
This function enables interrupt generation when fatal error count exceeds the threshold.
See also
SMPCC_DisableFatalErrIrq
Definition at line 1166 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.fatal_err_irq_en = SMPCC_CTRL_FATAL_ERR_IRQ_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_FATAL_ERR_IRQ_EN_ENABLE.
SMPCC_EnableICacheSnoopDCache()
__STATIC_FORCEINLINE void SMPCC_EnableICacheSnoopDCache (void)
Enable ICache to Snoop DCache.
This function enables snoop to dcache for icache refill reads.
See also
SMPCC_DisableICacheSnoopDCache
Definition at line 1467 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.i_snoop_d_en = SMPCC_CTRL_I_SNOOP_D_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_I_SNOOP_D_EN_ENABLE.
SMPCC_EnableL1PrefetchShareCacheline()
__STATIC_FORCEINLINE void SMPCC_EnableL1PrefetchShareCacheline (void)
Enable L1 Prefetch to Snoop and Share Cacheline.
This function enables L1 prefetch to snoop and share cacheline from other cores.
See also
SMPCC_DisableL1PrefetchShareCacheline
Definition at line 1371 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_sh_cl_en = SMPCC_CTRL_PF_SH_CL_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_SH_CL_EN_ENABLE.
SMPCC_EnableRecvErrIrq()
__STATIC_FORCEINLINE void SMPCC_EnableRecvErrIrq (void)
Enable Recoverable Error Interrupt.
This function enables interrupt generation when recoverable error count exceeds the threshold.
See also
SMPCC_DisableRecvErrIrq
Definition at line 1142 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.recv_err_irq_en = SMPCC_CTRL_RECV_ERR_IRQ_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_RECV_ERR_IRQ_EN_ENABLE.
SMPCC_EnableSModeCmd()
__STATIC_FORCEINLINE void SMPCC_EnableSModeCmd (void)
Enable Supervisor Mode Commands.
This function enables supervisor mode to operate CC_sCMD and SMP_PMON_SEL registers.
See also
SMPCC_DisableSModeCmd
Definition at line 1227 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.sup_cmd_en = SMPCC_CTRL_SUP_CMD_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_SUP_CMD_EN_ENABLE.
SMPCC_EnableSnoop()
__STATIC_FORCEINLINE void SMPCC_EnableSnoop (uint16_t client_msk)
Enable snoop for specific clients.
This function enables snoop functionality for specified client mask.
Parameters
[in] client_msk Client mask to enable snoop for
See also
SMPCC_DisableSnoop
Definition at line 877 of file core_feature_smpcc.h.
 {
     SMPCC->SMP_ENB.b.smp_enable |= client_msk;
 }
References SMPCC.
SMPCC_EnableStreamMergeNCRead()
__STATIC_FORCEINLINE void SMPCC_EnableStreamMergeNCRead (void)
Enable Stream Merge Non-Cacheable Read.
This function enables non-cacheable attribute read merge functionality.
See also
SMPCC_DisableStreamMergeNCRead
Definition at line 1703 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.rd_merge_en = SMPCC_STMCTRL_RD_MERGE_EN_ENABLE;
 }
References SMPCC, and SMPCC_STMCTRL_RD_MERGE_EN_ENABLE.
SMPCC_EnableStreamRead()
__STATIC_FORCEINLINE void SMPCC_EnableStreamRead (void)
Enable Stream Read.
This function enables stream read functionality.
See also
SMPCC_DisableStreamRead
Definition at line 1631 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.rd_stm_en = SMPCC_STMCTRL_RD_STM_EN_ENABLE;
 }
References SMPCC, and SMPCC_STMCTRL_RD_STM_EN_ENABLE.
SMPCC_EnableStreamReadCross4K()
__STATIC_FORCEINLINE void SMPCC_EnableStreamReadCross4K (void)
Enable Stream Read Cross 4K Boundary.
This function enables read stream to cross 4K boundary.
See also
SMPCC_DisableStreamReadCross4K
Definition at line 1727 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.cross_en = SMPCC_STMCTRL_CROSS_EN_ENABLE;
 }
References SMPCC, and SMPCC_STMCTRL_CROSS_EN_ENABLE.
SMPCC_EnableStreamTransAlloc()
__STATIC_FORCEINLINE void SMPCC_EnableStreamTransAlloc (void)
Enable Stream Translate Allocate.
This function enables translation of allocate attribute to non-alloc attribute.
See also
SMPCC_DisableStreamTransAlloc
Definition at line 1679 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.trans_alloc = SMPCC_STMCTRL_TRANS_ALLOC_ENABLE;
 }
References SMPCC, and SMPCC_STMCTRL_TRANS_ALLOC_ENABLE.
SMPCC_EnableStreamWrite()
__STATIC_FORCEINLINE void SMPCC_EnableStreamWrite (void)
Enable Stream Write.
This function enables stream write functionality.
See also
SMPCC_DisableStreamWrite
Definition at line 1655 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.b.wr_stm_en = SMPCC_STMCTRL_WR_STM_EN_ENABLE;
 }
References SMPCC, and SMPCC_STMCTRL_WR_STM_EN_ENABLE.
SMPCC_EnableUModeCmd()
__STATIC_FORCEINLINE void SMPCC_EnableUModeCmd (void)
Enable User Mode Commands.
This function enables user mode to operate CC_uCMD and SMP_PMON_SEL registers.
See also
SMPCC_DisableUModeCmd
Definition at line 1251 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.use_cmd_en = SMPCC_CTRL_USE_CMD_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_USE_CMD_EN_ENABLE.
SMPCC_GetCCacheControl()
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheControl (void)
Get Cluster Cache Control register value.
This function returns the current value of the Cluster Cache Control register.
Returns
Current value of the control register
See also
SMPCC_SetCCacheControl
Definition at line 1058 of file core_feature_smpcc.h.
 {
      return SMPCC->CC_CTRL.w;
 }
References SMPCC.
SMPCC_GetCCacheLineSize()
__STATIC_FORCEINLINE uint8_t SMPCC_GetCCacheLineSize (void)
Get the cache line size.
This function returns the cache line size in the cluster cache (2^(cc_lsize + 2)).
Returns
Cache line size in bytes
Definition at line 853 of file core_feature_smpcc.h.
 {
     return 1 << (SMPCC->CC_CFG.b.cc_lsize + 2);
 }
References SMPCC.
SMPCC_GetCCacheSetNum()
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheSetNum (void)
Get the number of cache sets.
This function returns the number of cache sets in the cluster cache (2^cc_set).
Returns
Number of cache sets
Definition at line 831 of file core_feature_smpcc.h.
 {
     return 1U << SMPCC->CC_CFG.b.cc_set;
 }
References SMPCC.
SMPCC_GetCCacheWayNum()
__STATIC_FORCEINLINE uint32_t SMPCC_GetCCacheWayNum (void)
Get the number of cache ways.
This function returns the number of cache ways in the cluster cache (cc_way + 1).
Returns
Number of cache ways
Definition at line 842 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_CFG.b.cc_way + 1;
 }
References SMPCC.
SMPCC_GetClientErrAddr()
__STATIC_FORCEINLINE uint64_t SMPCC_GetClientErrAddr (uint8_t client_id)
Get Client Error Address.
This function returns the error address for a specific client.
Parameters
[in] client_id ID of the client to get error address for
Returns
Error address of the specified client
Definition at line 1861 of file core_feature_smpcc.h.
 {
     return SMPCC->CLIENT_ERR_ADDR[client_id];
 }
References SMPCC.
SMPCC_GetClientErrStatus()
__STATIC_FORCEINLINE uint32_t SMPCC_GetClientErrStatus (uint8_t client_id)
Get Client Error Status.
This function returns the error status for a specific client.
Parameters
[in] client_id ID of the client to get error status for
Returns
Error status of the specified client
Definition at line 1593 of file core_feature_smpcc.h.
 {
     return SMPCC->CLIENT_ERR_STATUS[client_id].w;
 }
References SMPCC.
SMPCC_GetCoreNum()
__STATIC_FORCEINLINE uint8_t SMPCC_GetCoreNum (void)
Get the number of cores in the cluster.
This function returns the number of cores in the SMP cluster.
Returns
Number of cores in the cluster
Definition at line 798 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_CFG.b.smp_core_num + 1;
 }
References SMPCC.
SMPCC_GetFatalErrCntThreshold()
__STATIC_FORCEINLINE uint16_t SMPCC_GetFatalErrCntThreshold (void)
Get Fatal Error Count Threshold.
This function returns the current threshold value for fatal error count.
Returns
Current threshold value for fatal error count
See also
SMPCC_SetFatalErrCntThreshold
Definition at line 1581 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_FATAL_THV.b.cnt;
 }
References SMPCC.
SMPCC_GetFatalErrCount()
__STATIC_FORCEINLINE uint32_t SMPCC_GetFatalErrCount (void)
Get Fatal Error Count.
This function returns the current count of fatal errors.
Returns
Current count of fatal errors
See also
SMPCC_ClearFatalErrCount
Definition at line 1517 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_FATAL_CNT.b.cnt;
 }
References SMPCC.
SMPCC_GetIOCPNum()
__STATIC_FORCEINLINE uint8_t SMPCC_GetIOCPNum (void)
Get the number of IO coherency ports.
This function returns the number of IO coherency ports in the cluster.
Returns
Number of IO coherency ports
Definition at line 809 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_CFG.b.iocp_num;
 }
References SMPCC.
SMPCC_GetPMONCount()
__STATIC_FORCEINLINE uint64_t SMPCC_GetPMONCount (uint8_t idx)
Get Performance Monitor Count.
This function returns the current count value of a performance monitor.
Parameters
[in] idx Index of the performance monitor
Returns
Current count value of the performance monitor
See also
SMPCC_SetPMONEventSelect
SMPCC_GetPMONEventSelect
SMPCC_ClearPMONCount
Definition at line 1834 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_PMON_CNT[idx];
 }
References SMPCC.
SMPCC_GetPMONEventSelect()
__STATIC_FORCEINLINE uint32_t SMPCC_GetPMONEventSelect (uint8_t idx)
Get Performance Monitor Event Selection.
This function gets a performance monitor configuration value.
Parameters
[in] idx Index of the performance monitor
Returns
The performance monitor configuration value.
See also
SMPCC_SetPMONEventSelect
SMPCC_GetPMONCount
SMPCC_ClearPMONCount
Definition at line 1818 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_PMON_SEL[idx].w;
 }
References SMPCC.
SMPCC_GetPMONNum()
__STATIC_FORCEINLINE uint8_t SMPCC_GetPMONNum (void)
Get the number of performance monitors.
This function returns the number of performance monitors in the cluster.
Returns
Number of performance monitors
Definition at line 820 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_CFG.b.pmon_num;
 }
References SMPCC.
SMPCC_GetRecvErrCntThreshold()
__STATIC_FORCEINLINE uint16_t SMPCC_GetRecvErrCntThreshold (void)
Get Recoverable Error Count Threshold.
This function returns the current threshold value for recoverable error count.
Returns
Current threshold value for recoverable error count
See also
SMPCC_SetRecvErrCntThreshold
Definition at line 1555 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_RECV_THV.b.cnt;
 }
References SMPCC.
SMPCC_GetRecvErrCount()
__STATIC_FORCEINLINE uint32_t SMPCC_GetRecvErrCount (void)
Get Recoverable Error Count.
This function returns the current count of recoverable errors.
Returns
Current count of recoverable errors
See also
SMPCC_ClearRecvErrCount
Definition at line 1492 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_RECV_CNT.b.cnt;
 }
References SMPCC.
SMPCC_GetSTMControl()
__STATIC_FORCEINLINE uint32_t SMPCC_GetSTMControl (void)
Get Stream Control Register Value.
This function returns the current value of the Stream Control register.
Returns
Current value of the stream control register
See also
SMPCC_SetSTMControl
Definition at line 1619 of file core_feature_smpcc.h.
 {
     return SMPCC->STM_CTRL.w;
 }
References SMPCC.
SMPCC_GetVersion()
__STATIC_FORCEINLINE SMP_VER_Type SMPCC_GetVersion (void)
Get the SMP version number.
This function gets the hardware version information from SMP_VER register.
Returns
hardware version number in SMP_VER register.
Definition at line 776 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_VER;
 }
References SMPCC.
SMPCC_IsAnySnoopPending()
__STATIC_FORCEINLINE uint8_t SMPCC_IsAnySnoopPending (uint32_t client_msk)
Check if any client is being snooped.
This function checks if any client specified in the mask is currently being snooped.
Parameters
[in] client_msk Client mask to check
Returns
1 if any client is being snooped, 0 otherwise
Definition at line 939 of file core_feature_smpcc.h.
 {
     return (SMPCC->SNOOP_PENDING.b.snoop_pending & client_msk) != 0;
 }
References SMPCC.
SMPCC_IsAnyTransactionPending()
__STATIC_FORCEINLINE uint8_t SMPCC_IsAnyTransactionPending (uint32_t client_msk)
Check if any transaction is pending for clients.
This function checks if any transaction is pending for clients specified in the mask.
Parameters
[in] client_msk Client mask to check
Returns
1 if any transaction is pending, 0 otherwise
Definition at line 951 of file core_feature_smpcc.h.
 {
     return (SMPCC->TRANS_PENDING.b.trans_pending & client_msk) != 0;
 }
References SMPCC.
SMPCC_IsCCacheEnabled()
__STATIC_FORCEINLINE int32_t SMPCC_IsCCacheEnabled (void)
Get status of cluster cache.
This function returns the enable status of the cluster cache.
Returns
Return the status of cluster cache (1 - enabled, 0 - disabled)
See also
SMPCC_EnableCCache
Definition at line 927 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_CTRL.b.cc_en;
 }
References SMPCC.
SMPCC_IsCCachePresent()
__STATIC_FORCEINLINE uint8_t SMPCC_IsCCachePresent (void)
Check if cluster cache is present.
This function checks if the cluster cache is present in the system.
Returns
1 if cluster cache is present, 0 otherwise
Definition at line 787 of file core_feature_smpcc.h.
 {
     return SMPCC->SMP_CFG.b.cc_present;
 }
References SMPCC.
SMPCC_IsCCacheSupportECC()
__STATIC_FORCEINLINE uint8_t SMPCC_IsCCacheSupportECC (void)
Check if cluster cache supports ECC.
This function checks if the cluster cache supports ECC functionality.
Returns
1 if ECC is supported, 0 otherwise
Definition at line 864 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_CFG.b.cc_ecc;
 }
References SMPCC.
SMPCC_IsXorErrorInjectMode()
__STATIC_FORCEINLINE int32_t SMPCC_IsXorErrorInjectMode (void)
Check if ECC error injection mode is XOR mode.
This function checks which ECC error injection mode is supported. Returns 1 if XOR mode is supported, 0 if direct write mode is supported.
Returns
1 if XOR mode is supported, 0 if direct write mode is supported
Definition at line 1884 of file core_feature_smpcc.h.
 {
     return SMPCC->CC_ERR_INJ.b.inj_mode;
 }
References SMPCC.
SMPCC_LimitCCachePrefetchOutsNum()
__STATIC_FORCEINLINE void SMPCC_LimitCCachePrefetchOutsNum (void)
Limit Cluster Cache Prefetch Outstanding Number.
This function enables the limit of outstanding L2 prefetch to the number of L2 prefetch line-buffer.
See also
SMPCC_UnlimitCCachePrefetchOutsNum
Definition at line 1419 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_biu_outs_en = SMPCC_CTRL_PF_BIU_OUTS_EN_ENABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_BIU_OUTS_EN_ENABLE.
SMPCC_LockECCConfig()
__STATIC_FORCEINLINE void SMPCC_LockECCConfig (void)
Lock ECC Configuration.
This function locks the ECC configuration to prevent further changes.
See also
SMPCC_LockECCErrInjection
Definition at line 1118 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.lock_ecc_cfg = SMPCC_CTRL_LOCK_ECC_CFG_LOCK;
 }
References SMPCC, and SMPCC_CTRL_LOCK_ECC_CFG_LOCK.
SMPCC_LockECCErrInjection()
__STATIC_FORCEINLINE void SMPCC_LockECCErrInjection (void)
Lock ECC Error Injection Register.
This function locks the ECC error injection register to prevent further changes.
See also
SMPCC_LockECCConfig
Definition at line 1130 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.b.lock_ecc_err_inj = SMPCC_CTRL_LOCK_ECC_ERR_INJ_LOCK;
 }
References SMPCC, and SMPCC_CTRL_LOCK_ECC_ERR_INJ_LOCK.
SMPCC_MaskClientCCacheWays()
__STATIC_FORCEINLINE void SMPCC_MaskClientCCacheWays (uint8_t client_id, uint32_t way_msk)
Mask Client Cluster Cache Ways.
This function masks specific ways in the cluster cache for a specific client.
Parameters
[in] client_id ID of the client
[in] way_msk Way mask to apply
Definition at line 1873 of file core_feature_smpcc.h.
 {
     SMPCC->CLIENT_WAY_MASK[client_id].w = way_msk;
 }
References SMPCC.
SMPCC_SetCCacheControl()
__STATIC_FORCEINLINE void SMPCC_SetCCacheControl (uint32_t val)
Set Cluster Cache Control register.
This function sets the value of the Cluster Cache Control register.
Parameters
[in] val Value to set in the control register
See also
SMPCC_GetCCacheControl
Definition at line 1045 of file core_feature_smpcc.h.
 {
      SMPCC->CC_CTRL.w = val;
 }
References SMPCC.
SMPCC_SetCLMAllWays()
__STATIC_FORCEINLINE void SMPCC_SetCLMAllWays (uint64_t addr)
Set Cluster Local Memory to use all ways.
This function configures the Cluster Local Memory to use all cache ways at the specified address.
Parameters
[in] addr Base address for Cluster Local Memory.
Remarks
Access to the CLM_ADDR_BASE register depends on the physical address (PA) size. If the PA size is not larger than 32 bits, only the low 32 bits of the address can be accessed.
Before changing the Cluster Cache to CLM mode, ensure that:
The Cluster Cache is disabled,
Its contents have been invalidated and flushed to memory.
Example usage:
SMPCC_DisableCCache();
MFlushInvalCCache();
SMPCC_SetCLMAllWays(addr);
See also
SMPCC_SetCLMNWays
SMPCC_SetCLMNoWay
Definition at line 979 of file core_feature_smpcc.h.
 {
 #if (__CPU_PA_SIZE > 32)
     SMPCC->CLM_ADDR_BASE.clm_base64 = addr;
 #else
     SMPCC->CLM_ADDR_BASE.clm32.clm_base32 = (uint32_t)addr;
 #endif
     SMPCC->CLM_WAY_EN = 0xFFFFU;
 }
References SMPCC.
SMPCC_SetCLMNoWay()
__STATIC_FORCEINLINE void SMPCC_SetCLMNoWay (void)
Configure Cluster Local Memory to use no ways.
This function configures the Cluster Local Memory to not use any cache ways.
See also
SMPCC_SetCLMAllWays
SMPCC_SetCLMNWays
Definition at line 1032 of file core_feature_smpcc.h.
 {
     SMPCC->CLM_WAY_EN = 0x0000U;
 }
References SMPCC.
SMPCC_SetCLMNWays()
__STATIC_FORCEINLINE void SMPCC_SetCLMNWays (uint64_t addr, uint32_t way_msk)
Set Cluster Local Memory to use specific ways.
This function configures the Cluster Local Memory to use specific cache ways at the specified address.
Parameters
[in] addr Base address for Cluster Local Memory
[in] way_msk Way mask to configure
Remarks
Access to the CLM_ADDR_BASE register depends on the physical address (PA) size. If the PA size is not larger than 32 bits, only the low 32 bits of the address can be accessed.
Before changing the Cluster Cache to CLM mode, ensure that:
The Cluster Cache is disabled,
Its contents have been invalidated and flushed to memory.
Example usage:
SMPCC_DisableCCache();
MFlushInvalCCache();
SMPCC_SetCLMNWays(addr, way_msk);
SMPCC_EnableCCache(); // Enable the remaining CCache
See also
SMPCC_SetCLMAllWays
SMPCC_SetCLMNoWay
Definition at line 1014 of file core_feature_smpcc.h.
 {
 #if (__CPU_PA_SIZE > 32)
     SMPCC->CLM_ADDR_BASE.clm_base64 = addr;
 #else
     SMPCC->CLM_ADDR_BASE.clm32.clm_base32 = (uint32_t)addr;
 #endif
     SMPCC->CLM_WAY_EN = way_msk;
 }
References SMPCC.
SMPCC_SetECCCode()
__STATIC_FORCEINLINE void SMPCC_SetECCCode (uint32_t ecc_code)
Set ECC code for error injection.
This function sets the ECC code to be used for error injection.
Parameters
ecc_code ECC code to be set for error injection
Returns
None
Definition at line 1895 of file core_feature_smpcc.h.
 {
     SMPCC->CC_ERR_INJ.w = (SMPCC->CC_ERR_INJ.w & ~SMPCC_ERR_INJ_INJECCCODE_Msk) |
                           _VAL2FLD(SMPCC_ERR_INJ_INJECCCODE, ecc_code);
 }
References _VAL2FLD, SMPCC, and SMPCC_ERR_INJ_INJECCCODE_Msk.
Referenced by SMPCC_CCacheDramErrInject(), SMPCC_CCacheTramErrInject(), and SMPCC_CLMErrInject().
SMPCC_SetFatalErrCntThreshold()
__STATIC_FORCEINLINE void SMPCC_SetFatalErrCntThreshold (uint16_t threshold)
Set Fatal Error Count Threshold.
This function sets the threshold value for fatal error count.
Parameters
[in] threshold Threshold value to set
See also
SMPCC_GetFatalErrCntThreshold
Definition at line 1568 of file core_feature_smpcc.h.
 {
     SMPCC->CC_FATAL_THV.b.cnt = threshold;
 }
References SMPCC.
SMPCC_SetNSRegionNACL()
__STATIC_FORCEINLINE void SMPCC_SetNSRegionNACL (uint8_t region_id, uint64_t addr)
Set Non-Shareable Region to NACL.
This function configures a non-shareable region as NACL (NAPOT/CA with length) at the specified address.
Parameters
[in] region_id ID of the region to configure
[in] addr Address for the region
See also
SMPCC_SetNSRegionNAPOT
SMPCC_DisableNSRegion
Definition at line 1754 of file core_feature_smpcc.h.
 {
     SMPCC->NS_RG[region_id].dw = SMPCC_NS_RG_CFG_NACL | addr;
 }
References SMPCC, and SMPCC_NS_RG_CFG_NACL.
SMPCC_SetNSRegionNAPOT()
__STATIC_FORCEINLINE void SMPCC_SetNSRegionNAPOT (uint8_t region_id, uint64_t addr)
Set Non-Shareable Region to NAPOT.
This function configures a non-shareable region as NAPOT (Naturally Aligned Power of Two) at the specified address.
Parameters
[in] region_id ID of the region to configure
[in] addr Address for the region
See also
SMPCC_SetNSRegionNACL
SMPCC_DisableNSRegion
Definition at line 1769 of file core_feature_smpcc.h.
 {
     SMPCC->NS_RG[region_id].dw = SMPCC_NS_RG_CFG_NAPOT | addr;
 }
References SMPCC, and SMPCC_NS_RG_CFG_NAPOT.
SMPCC_SetPMONEventSelect()
__STATIC_FORCEINLINE void SMPCC_SetPMONEventSelect (uint8_t idx, uint8_t client_id, uint8_t event)
Set Performance Monitor Event Selection.
This function configures a performance monitor to select a specific event and client.
Parameters
[in] idx Index of the performance monitor
[in] client_id ID of the client to monitor
[in] event Event to monitor
See also
SMPCC_GetPMONEventSelect
SMPCC_GetPMONCount
SMPCC_ClearPMONCount
Definition at line 1801 of file core_feature_smpcc.h.
 {
     SMPCC->SMP_PMON_SEL[idx].w = SMPCC_PMON_EVENT(event, client_id);
 }
References SMPCC, and SMPCC_PMON_EVENT.
SMPCC_SetRecvErrCntThreshold()
__STATIC_FORCEINLINE void SMPCC_SetRecvErrCntThreshold (uint16_t threshold)
Set Recoverable Error Count Threshold.
This function sets the threshold value for recoverable error count.
Parameters
[in] threshold Threshold value to set
See also
SMPCC_GetRecvErrCntThreshold
Definition at line 1542 of file core_feature_smpcc.h.
 {
     SMPCC->CC_RECV_THV.b.cnt = threshold;
 }
References SMPCC.
SMPCC_SetSTMControl()
__STATIC_FORCEINLINE void SMPCC_SetSTMControl (uint32_t val)
Set Stream Control Register.
This function sets the value of the Stream Control register.
Parameters
[in] val Value to set in the stream control register
See also
SMPCC_GetSTMControl
Definition at line 1606 of file core_feature_smpcc.h.
 {
     SMPCC->STM_CTRL.w = val;
 }
References SMPCC.
SMPCC_UnlimitCCachePrefetchOutsNum()
__STATIC_FORCEINLINE void SMPCC_UnlimitCCachePrefetchOutsNum (void)
Unlimit Cluster Cache Prefetch Outstanding Number.
This function disables the limit of outstanding L2 prefetch to the number of L2 prefetch line-buffer.
See also
SMPCC_LimitCCachePrefetchOutsNum
Definition at line 1431 of file core_feature_smpcc.h.
 {
     SMPCC->CC_CTRL.b.pf_biu_outs_en = SMPCC_CTRL_PF_BIU_OUTS_EN_DISABLE;
 }
References SMPCC, and SMPCC_CTRL_PF_BIU_OUTS_EN_DISABLE.