NMSIS-Core: I-Cache Functions
I-Cache Functions
Cache Functions
Functions that configure Instruction Cache.
Functions
__STATIC_INLINE int32_t ICachePresent (void)
Check ICache Unit Present or Not.
__STATIC_FORCEINLINE void EnableICache (void)
Enable ICache.
__STATIC_FORCEINLINE void DisableICache (void)
Disable ICache.
__STATIC_FORCEINLINE void EnableICacheECC (void)
Enable ICache ECC.
__STATIC_FORCEINLINE void DisableICacheECC (void)
Disable ICache ECC.
__STATIC_INLINE int32_t GetICacheInfo (CacheInfo_Type *info)
Get I-Cache Information.
__STATIC_INLINE void MInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in M-Mode.
__STATIC_INLINE void MInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in S-Mode.
__STATIC_INLINE void SInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in U-Mode.
__STATIC_INLINE void UInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in M-Mode.
__STATIC_INLINE void MInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in M-Mode.
__STATIC_INLINE void SInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in S-Mode.
__STATIC_INLINE void SInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in S-Mode.
__STATIC_INLINE void UInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in U-Mode.
__STATIC_INLINE void UInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in U-Mode.
__STATIC_INLINE unsigned long MLockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in M-Mode.
__STATIC_INLINE unsigned long MLockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in M-Mode.
__STATIC_INLINE unsigned long SLockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in S-Mode.
__STATIC_INLINE unsigned long SLockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in S-Mode.
__STATIC_INLINE unsigned long ULockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in U-Mode.
__STATIC_INLINE unsigned long ULockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in M-Mode.
__STATIC_INLINE void MUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in S-Mode.
__STATIC_INLINE void SUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in U-Mode.
__STATIC_INLINE void UUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MInvalICache (void)
Invalidate all I-Cache lines in M-Mode.
__STATIC_INLINE void SInvalICache (void)
Invalidate all I-Cache lines in S-Mode.
__STATIC_INLINE void UInvalICache (void)
Invalidate all I-Cache lines in U-Mode.
__STATIC_INLINE void MInvalCCache (void)
Invalidate all Cluster Cache in M-Mode.
__STATIC_INLINE void SInvalCCache (void)
Invalidate all Cluster Cache in S-Mode.
__STATIC_INLINE void UInvalCCache (void)
Invalidate all Cluster Cache in U-Mode.
__STATIC_INLINE void MInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in M-Mode.
__STATIC_INLINE void SInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in S-Mode.
__STATIC_INLINE void UInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in U-Mode.
Detailed Description
Functions that configure Instruction Cache.
Function Documentation
DisableICache()
__STATIC_FORCEINLINE void DisableICache (void)
Disable ICache.
This function Disable I-Cache
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control I Cache enable.
See also
EnableICache
Definition at line 575 of file core_feature_cache.h.
 {
     __RV_CSR_CLEAR(CSR_MCACHE_CTL, MCACHE_CTL_IC_EN);
 }
References __RV_CSR_CLEAR, CSR_MCACHE_CTL, and MCACHE_CTL_IC_EN.
DisableICacheECC()
__STATIC_FORCEINLINE void DisableICacheECC (void)
Disable ICache ECC.
This function disable I-Cache ECC
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control I Cache ECC enable.
See also
EnableICacheECC
Definition at line 605 of file core_feature_cache.h.
 {
     __RV_CSR_CLEAR(CSR_MCACHE_CTL, MCACHE_CTL_IC_ECC_EN);
 }
References __RV_CSR_CLEAR, CSR_MCACHE_CTL, and MCACHE_CTL_IC_ECC_EN.
EnableICache()
__STATIC_FORCEINLINE void EnableICache (void)
Enable ICache.
This function enable I-Cache
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control I Cache enable.
See also
DisableICache
Definition at line 560 of file core_feature_cache.h.
 {
     __RV_CSR_SET(CSR_MCACHE_CTL, MCACHE_CTL_IC_EN);
 }
References __RV_CSR_SET, CSR_MCACHE_CTL, and MCACHE_CTL_IC_EN.
Referenced by _premain_init().
EnableICacheECC()
__STATIC_FORCEINLINE void EnableICacheECC (void)
Enable ICache ECC.
This function enable I-Cache ECC
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control I Cache ECC enable.
See also
DisableICacheECC
Definition at line 590 of file core_feature_cache.h.
 {
     __RV_CSR_SET(CSR_MCACHE_CTL, MCACHE_CTL_IC_ECC_EN);
 }
References __RV_CSR_SET, CSR_MCACHE_CTL, and MCACHE_CTL_IC_ECC_EN.
GetICacheInfo()
__STATIC_INLINE int32_t GetICacheInfo (CacheInfo_Type * info)
Get I-Cache Information.
This function get I-Cache Information
Remarks
This function can be called in M-Mode only.
You can use this function in combination with cache lines operations
See also
GetDCacheInfo
Definition at line 621 of file core_feature_cache.h.
 {
     if (info == NULL) {
         return -1;
     }
     CSR_MICFGINFO_Type csr_ccfg;
     csr_ccfg.d = __RV_CSR_READ(CSR_MICFG_INFO);
     info->setperway = (1UL << csr_ccfg.b.set) << 3;
     info->ways = (1 + csr_ccfg.b.way);
     if (csr_ccfg.b.lsize == 0) {
         info->linesize = 0;
     } else {
         info->linesize = (1UL << (csr_ccfg.b.lsize - 1)) << 3;
     }
     info->size = info->setperway * info->ways * info->linesize;
     return 0;
 }
References __RV_CSR_READ, CSR_MICFGINFO_Type::b, CSR_MICFG_INFO, CSR_MICFGINFO_Type::d, CacheInfo_Type::linesize, CSR_MICFGINFO_Type::lsize, CSR_MICFGINFO_Type::set, CacheInfo_Type::setperway, CacheInfo_Type::size, CSR_MICFGINFO_Type::way, and CacheInfo_Type::ways.
ICachePresent()
__STATIC_INLINE int32_t ICachePresent (void)
Check ICache Unit Present or Not.
This function check icache unit present or not via mcfg_info csr
Remarks
This function might not work for some old nuclei processors
Please make sure the version of your nuclei processor contain ICACHE bit in mcfg_info
Returns
1 if present otherwise 0
Definition at line 542 of file core_feature_cache.h.
 {
     if (__RV_CSR_READ(CSR_MCFG_INFO) & MCFG_INFO_ICACHE) {
         return 1;
     }
     return 0;
 }
References __RV_CSR_READ, CSR_MCFG_INFO, and MCFG_INFO_ICACHE.
Referenced by _premain_init().
MInvalCCache()
__STATIC_INLINE void MInvalCCache (void)
Invalidate all Cluster Cache in M-Mode.
This function invalidate all Cluster Cache.
Remarks
This function must be executed in M-Mode only.
Definition at line 1234 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RWMB, _FLD2VAL, _VAL2FLD, and SMPCC_CMD.
MInvalICache()
__STATIC_INLINE void MInvalICache (void)
Invalidate all I-Cache lines in M-Mode.
This function invalidate all I-Cache lines. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1187 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL_ALL, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalICacheCCache()
__STATIC_INLINE void MInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in M-Mode.
This function unlock and invalidate all I-Cache and Cluster Cache. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Definition at line 1277 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_IC_INVAL_ALL, CSR_CCM_MCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
MInvalICacheCCacheLine()
__STATIC_INLINE void MInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in M-Mode.
This function unlock and invalidate one I-Cache line and corresponding Cluster Cache line specified by the address. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 776 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL);
     /* Trigger Cluster Cache invalidation by DC_INVAL */
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalICacheCCacheLines()
__STATIC_INLINE void MInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in M-Mode.
This function unlock and invalidate several I-Cache lines and corresponding Cluster Cache lines specified by the address and line count. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 797 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL);
             /* Trigger Cluster Cache invalidation by DC_INVAL */
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalICacheLine()
__STATIC_INLINE void MInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in M-Mode.
This function unlock and invalidate one I-Cache line specified by the address. Command CCM_IC_INVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 649 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
Referenced by __ECLIC_SetVector(), ECC_ICacheDRamErrInject(), ECC_ICacheErrRestore(), ECC_ICacheTRamErrInject(), SMPCC_CCacheDramErrInject(), SMPCC_CCacheErrRestore(), and SMPCC_CCacheTramErrInject().
MInvalICacheLines()
__STATIC_INLINE void MInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in M-Mode.
This function unlock and invalidate several I-Cache lines specified by the address and line count. Command CCM_IC_INVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 668 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MLockICacheLine()
__STATIC_INLINE unsigned long MLockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in M-Mode.
This function lock one I-Cache line specified by the address. Command CCM_IC_LOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 915 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_MDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, CSR_CCM_MDATA, and FlushPipeCCM().
Referenced by ECC_ICacheDRamErrInject(), ECC_ICacheErrRestore(), and ECC_ICacheTRamErrInject().
MLockICacheLines()
__STATIC_INLINE unsigned long MLockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in M-Mode.
This function lock several I-Cache lines specified by the address and line count. Command CCM_IC_LOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 936 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_MDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CCM_OP_SUCCESS, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, CSR_CCM_MDATA, and FlushPipeCCM().
MUnlockICacheLine()
__STATIC_INLINE void MUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in M-Mode.
This function unlock one I-Cache line specified by the address. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 1064 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MUnlockICacheLines()
__STATIC_INLINE void MUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in M-Mode.
This function unlock several I-Cache lines specified by the address and line count. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 1083 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_IC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
SInvalCCache()
__STATIC_INLINE void SInvalCCache (void)
Invalidate all Cluster Cache in S-Mode.
This function invalidate all Cluster Cache.
Remarks
This function must be executed in M/S-Mode only.
Definition at line 1248 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RWMB, _FLD2VAL, _VAL2FLD, and SMPCC_CMD.
SInvalICache()
__STATIC_INLINE void SInvalICache (void)
Invalidate all I-Cache lines in S-Mode.
This function invalidate all I-Cache lines. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1203 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL_ALL, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalICacheCCache()
__STATIC_INLINE void SInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in S-Mode.
This function unlock and invalidate all I-Cache and Cluster Cache. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Definition at line 1294 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_IC_INVAL_ALL, CSR_CCM_SCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
SInvalICacheCCacheLine()
__STATIC_INLINE void SInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in S-Mode.
This function unlock and invalidate one I-Cache line and corresponding Cluster Cache line specified by the address. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 822 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL);
     /* Trigger Cluster Cache invalidation by DC_INVAL */
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalICacheCCacheLines()
__STATIC_INLINE void SInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in S-Mode.
This function unlock and invalidate several I-Cache lines and corresponding Cluster Cache lines specified by the address and line count. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 843 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL);
             /* Trigger Cluster Cache invalidation by DC_INVAL */
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalICacheLine()
__STATIC_INLINE void SInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in S-Mode.
This function unlock and invalidate one I-Cache line specified by the address. Command CCM_IC_INVAL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 691 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
Referenced by __ECLIC_SetVector_S().
SInvalICacheLines()
__STATIC_INLINE void SInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in S-Mode.
This function unlock and invalidate several I-Cache lines specified by the address and line count. Command CCM_IC_INVAL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 710 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SLockICacheLine()
__STATIC_INLINE unsigned long SLockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in S-Mode.
This function lock one I-Cache line specified by the address. Command CCM_IC_LOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 965 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_SDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, CSR_CCM_SDATA, and FlushPipeCCM().
SLockICacheLines()
__STATIC_INLINE unsigned long SLockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in S-Mode.
This function lock several I-Cache lines specified by the address and line count. Command CCM_IC_LOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 986 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_SDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CCM_OP_SUCCESS, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, CSR_CCM_SDATA, and FlushPipeCCM().
SUnlockICacheLine()
__STATIC_INLINE void SUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in S-Mode.
This function unlock one I-Cache line specified by the address. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 1105 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SUnlockICacheLines()
__STATIC_INLINE void SUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in S-Mode.
This function unlock several I-Cache lines specified by the address and line count. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 1124 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_IC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
UInvalCCache()
__STATIC_INLINE void UInvalCCache (void)
Invalidate all Cluster Cache in U-Mode.
This function invalidate all Cluster Cache.
Remarks
This function must be executed in M/S/U-Mode only.
Definition at line 1262 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RWMB, _FLD2VAL, _VAL2FLD, and SMPCC_CMD.
UInvalICache()
__STATIC_INLINE void UInvalICache (void)
Invalidate all I-Cache lines in U-Mode.
This function invalidate all I-Cache lines. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1219 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL_ALL, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalICacheCCache()
__STATIC_INLINE void UInvalICacheCCache (void)
Invalidate all I-Cache and Cluster Cache in U-Mode.
This function unlock and invalidate all I-Cache and Cluster Cache. Command CCM_IC_INVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Definition at line 1311 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_IC_INVAL_ALL, CSR_CCM_UCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
UInvalICacheCCacheLine()
__STATIC_INLINE void UInvalICacheCCacheLine (unsigned long addr)
Invalidate one I-Cache and Cluster Cache line specified by address in U-Mode.
This function unlock and invalidate one I-Cache line and corresponding Cluster Cache line specified by the address. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 868 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL);
     /* Trigger Cluster Cache invalidation by DC_INVAL */
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalICacheCCacheLines()
__STATIC_INLINE void UInvalICacheCCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache and Cluster Cache lines specified by address in U-Mode.
This function unlock and invalidate several I-Cache lines and corresponding Cluster Cache lines specified by the address and line count. Commands CCM_IC_INVAL and CCM_DC_INVAL are written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 889 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL);
             /* Trigger Cluster Cache invalidation by DC_INVAL */
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CCM_IC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalICacheLine()
__STATIC_INLINE void UInvalICacheLine (unsigned long addr)
Invalidate one I-Cache line specified by address in U-Mode.
This function unlock and invalidate one I-Cache line specified by the address. Command CCM_IC_INVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 733 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalICacheLines()
__STATIC_INLINE void UInvalICacheLines (unsigned long addr, unsigned long cnt)
Invalidate several I-Cache lines specified by address in U-Mode.
This function unlock and invalidate several I-Cache lines specified by the address and line count. Command CCM_IC_INVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 752 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
ULockICacheLine()
__STATIC_INLINE unsigned long ULockICacheLine (unsigned long addr)
Lock one I-Cache line specified by address in U-Mode.
This function lock one I-Cache line specified by the address. Command CCM_IC_LOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 1015 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_UDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, CSR_CCM_UDATA, and FlushPipeCCM().
ULockICacheLines()
__STATIC_INLINE unsigned long ULockICacheLines (unsigned long addr, unsigned long cnt)
Lock several I-Cache lines specified by address in U-Mode.
This function lock several I-Cache lines specified by the address and line count. Command CCM_IC_LOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 1036 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_UDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_IC_LOCK, CCM_OP_SUCCESS, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, CSR_CCM_UDATA, and FlushPipeCCM().
UUnlockICacheLine()
__STATIC_INLINE void UUnlockICacheLine (unsigned long addr)
Unlock one I-Cache line specified by address in U-Mode.
This function unlock one I-Cache line specified by the address. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 1146 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UUnlockICacheLines()
__STATIC_INLINE void UUnlockICacheLines (unsigned long addr, unsigned long cnt)
Unlock several I-Cache lines specified by address in U-Mode.
This function unlock several I-Cache lines specified by the address and line count. Command CCM_IC_UNLOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 1165 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_IC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_IC_UNLOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().