NMSIS-Core: Semaphore Functions
Semaphore Functions
CIDU Functions
Functions that configure and use semaphoresSemaphore is very useful for multi-core cluster without SMP enable.
Functions
__STATIC_FORCEINLINE uint32_t CIDU_GetSemaphoreStatus (uint32_t semph_n)
Get SEMAPHOREn's value.
__STATIC_FORCEINLINE long CIDU_CheckSemaphoreAcquired (uint32_t semph_n, uint32_t core_id)
check SEMAPHOREn's acquired status
__STATIC_FORCEINLINE long CIDU_AcquireSemaphore (uint32_t semph_n, uint32_t core_id)
Acquire the SEMAPHOREn.
__STATIC_FORCEINLINE void CIDU_AcquireSemaphore_Block (uint32_t semph_n, uint32_t core_id)
Keep acquiring the SEMAPHOREn until it has acquired this semaphore successfully.
__STATIC_FORCEINLINE void CIDU_ReleaseSemaphore (uint32_t semph_n)
Release the SEMAPHOREn.
Detailed Description
Functions that configure and use semaphores
Semaphore is very useful for multi-core cluster without SMP enable.
All Cores in the cluster agree on using SEMAPHORE_n register to protect a critical resource (an UART device for example).
If Core n wants to access the critical resource, it should try to own the SEMPAPHORE_n register, or else it can’t access the critical resource.
When the Core n owns the register SEMPAPHORE_n and finishes the job related the critical resource, then it should release the register by writing all 1 to it.
Function Documentation
CIDU_AcquireSemaphore()
__STATIC_FORCEINLINE long CIDU_AcquireSemaphore (uint32_t semph_n, uint32_t core_id)
Acquire the SEMAPHOREn.
Acuqire the SEMAPHOREn, and check the acquired status
Parameters
[in] semph_n the semaphore id used to protect a critical resource
[in] core_id the core id that wants to access the critical resource
Returns
0 if core_id has acquired this semaphore successfully, or else -1 if failed
Remarks
When the core n owns the register SEMPAPHORE_n and finishes the job related the critical resource, it should call CIDU_ReleaseSemaphore to release it.
See also
CIDU_CheckSemaphoreAcquired
CIDU_ReleaseSemaphore
Definition at line 386 of file core_feature_cidu.h.
 {
     long semaphore_status = -1;
     uint32_t* addr = (uint32_t*)CIDU_SEMAPHORE_ADDR(semph_n);
     __SW(addr, core_id);
     semaphore_status = CIDU_CheckSemaphoreAcquired(semph_n, core_id);
     return semaphore_status;
 }
References __SW(), CIDU_CheckSemaphoreAcquired(), and CIDU_SEMAPHORE_ADDR.
Referenced by CIDU_AcquireSemaphore_Block().
CIDU_AcquireSemaphore_Block()
__STATIC_FORCEINLINE void CIDU_AcquireSemaphore_Block (uint32_t semph_n, uint32_t core_id)
Keep acquiring the SEMAPHOREn until it has acquired this semaphore successfully.
Query that whether SEMAPHOREn has been owned by one core successfully, if not, keep trying.
Parameters
[in] semph_n the semaphore id used to protect a critical resource
[in] core_id the core id that wants to access the critical resource
Remarks
Core n will block here acquiring, so take care that core should release the semaphore when related job done.
See also
CIDU_AcquireSemaphore
CIDU_ReleaseSemaphore
Definition at line 408 of file core_feature_cidu.h.
 {
     int32_t semaphore_status = -1;
     while(0 != semaphore_status) {
         semaphore_status = CIDU_AcquireSemaphore(semph_n, core_id);
     }
 }
References CIDU_AcquireSemaphore().
CIDU_CheckSemaphoreAcquired()
__STATIC_FORCEINLINE long CIDU_CheckSemaphoreAcquired (uint32_t semph_n, uint32_t core_id)
check SEMAPHOREn's acquired status
Query that whether SEMAPHOREn has been acquired by one core successfully.
Parameters
[in] semph_n the semaphore id used to protect a critical resource
[in] core_id the core id that wants to access the critical resource
Returns
0 if core_id has acquired this semaphore successfully, or else -1 if failed
Remarks
When the core n owns the register SEMPAPHORE_n and finishes the job related the critical resource, it should call CIDU_ReleaseSemaphore to release it.
See also
CIDU_GetSemaphoreStatus
CIDU_ReleaseSemaphore
Definition at line 362 of file core_feature_cidu.h.
 {
     uint32_t val;
     val = CIDU_GetSemaphoreStatus(semph_n);
     if (core_id != val) {
         return -1;
     }
     return 0;
 }
References CIDU_GetSemaphoreStatus().
Referenced by CIDU_AcquireSemaphore().
CIDU_GetSemaphoreStatus()
__STATIC_FORCEINLINE uint32_t CIDU_GetSemaphoreStatus (uint32_t semph_n)
Get SEMAPHOREn's value.
Just query the semaphore n's value
Parameters
[in] semph_n the semaphore id used to protect a critical resource
Returns
register SEMAPHOREn_STATUS value
Definition at line 339 of file core_feature_cidu.h.
 {
     uint32_t val;
     uint32_t* addr = (uint32_t*)CIDU_SEMAPHORE_ADDR(semph_n);
     val = __LW(addr);
     return val;
 }
References __LW(), and CIDU_SEMAPHORE_ADDR.
Referenced by CIDU_CheckSemaphoreAcquired().
CIDU_ReleaseSemaphore()
__STATIC_FORCEINLINE void CIDU_ReleaseSemaphore (uint32_t semph_n)
Release the SEMAPHOREn.
Release the SEMAPHOREn by writing all 1 to SEMAPHOREn register.
Parameters
[in] semph_n the semaphore id used to protect a critical resource
Remarks
When the core finishes the job related to the critical resource, it should release the corresponding semaphore.
See also
CIDU_AcquireSemaphore_Block
Definition at line 427 of file core_feature_cidu.h.
 {
     uint32_t* addr = (uint32_t*)CIDU_SEMAPHORE_ADDR(semph_n);
     /* Release by writing all 1 */
     __SW(addr, 0xFFFFFFFF);
 }
References __SW(), and CIDU_SEMAPHORE_ADDR.