NMSIS-Core: D-Cache Functions
D-Cache Functions
Cache Functions
Functions that configure Data Cache.
Macros
#define MInvalDCacheCCacheLine(addr) MInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in M-Mode.
#define MInvalDCacheCCacheLines(addr, cnt) MInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in M-Mode.
#define SInvalDCacheCCacheLine(addr) SInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in S-Mode.
#define SInvalDCacheCCacheLines(addr, cnt) SInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in S-Mode.
#define UInvalDCacheCCacheLine(addr) UInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in U-Mode.
#define UInvalDCacheCCacheLines(addr, cnt) UInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in U-Mode.
#define MFlushDCacheCCacheLine(addr) MFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in M-Mode.
#define MFlushDCacheCCacheLines(addr, cnt) MFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in M-Mode.
#define SFlushDCacheCCacheLine(addr) SFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in S-Mode.
#define SFlushDCacheCCacheLines(addr, cnt) SFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in S-Mode.
#define UFlushDCacheCCacheLine(addr) UFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in U-Mode.
#define UFlushDCacheCCacheLines(addr, cnt) UFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in U-Mode.
#define MFlushInvalDCacheCCacheLine(addr) MFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in M-Mode.
#define MFlushInvalDCacheCCacheLines(addr, cnt) MFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in M-Mode.
#define SFlushInvalDCacheCCacheLine(addr) SFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in S-Mode.
#define SFlushInvalDCacheCCacheLines(addr, cnt) SFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in S-Mode.
#define UFlushInvalDCacheCCacheLine(addr) UFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in U-Mode.
#define UFlushInvalDCacheCCacheLines(addr, cnt) UFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in U-Mode.
Functions
__STATIC_INLINE int32_t DCachePresent (void)
Check DCache Unit Present or Not.
__STATIC_FORCEINLINE void EnableDCache (void)
Enable DCache.
__STATIC_FORCEINLINE void DisableDCache (void)
Disable DCache.
__STATIC_FORCEINLINE void EnableDCacheECC (void)
Enable DCache ECC.
__STATIC_FORCEINLINE void DisableDCacheECC (void)
Disable DCache ECC.
__STATIC_INLINE int32_t GetDCacheInfo (CacheInfo_Type *info)
Get D-Cache Information.
__STATIC_INLINE void MInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in M-Mode.
__STATIC_INLINE void MInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in S-Mode.
__STATIC_INLINE void SInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in U-Mode.
__STATIC_INLINE void UInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in M-Mode.
__STATIC_INLINE void MFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in S-Mode.
__STATIC_INLINE void SFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in U-Mode.
__STATIC_INLINE void UFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in M-Mode.
__STATIC_INLINE void MFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in S-Mode.
__STATIC_INLINE void SFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in U-Mode.
__STATIC_INLINE void UFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in U-Mode.
__STATIC_INLINE unsigned long MLockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in M-Mode.
__STATIC_INLINE unsigned long MLockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in M-Mode.
__STATIC_INLINE unsigned long SLockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in S-Mode.
__STATIC_INLINE unsigned long SLockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in S-Mode.
__STATIC_INLINE unsigned long ULockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in U-Mode.
__STATIC_INLINE unsigned long ULockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in M-Mode.
__STATIC_INLINE void MUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in M-Mode.
__STATIC_INLINE void SUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in S-Mode.
__STATIC_INLINE void SUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in S-Mode.
__STATIC_INLINE void UUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in U-Mode.
__STATIC_INLINE void UUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in U-Mode.
__STATIC_INLINE void MInvalDCache (void)
Invalidate all D-Cache lines in M-Mode.
__STATIC_INLINE void SInvalDCache (void)
Invalidate all D-Cache lines in S-Mode.
__STATIC_INLINE void UInvalDCache (void)
Invalidate all D-Cache lines in U-Mode.
__STATIC_INLINE void MFlushDCache (void)
Flush all D-Cache lines in M-Mode.
__STATIC_INLINE void SFlushDCache (void)
Flush all D-Cache lines in S-Mode.
__STATIC_INLINE void UFlushDCache (void)
Flush all D-Cache lines in U-Mode.
__STATIC_INLINE void MFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in M-Mode.
__STATIC_INLINE void SFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in S-Mode.
__STATIC_INLINE void UFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in U-Mode.
__STATIC_INLINE int32_t MFlushCCache (void)
Flush all Cluster Cache in M-Mode.
__STATIC_INLINE int32_t SFlushCCache (void)
Flush all Cluster Cache in S-Mode.
__STATIC_INLINE int32_t UFlushCCache (void)
Flush all Cluster Cache in U-Mode.
__STATIC_INLINE int32_t MFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in M-Mode.
__STATIC_INLINE int32_t SFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in S-Mode.
__STATIC_INLINE int32_t UFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in U-Mode.
__STATIC_INLINE void MInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in M-Mode.
__STATIC_INLINE void SInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in S-Mode.
__STATIC_INLINE void UInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in U-Mode.
__STATIC_INLINE int32_t MFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in M-Mode.
__STATIC_INLINE int32_t SFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in S-Mode.
__STATIC_INLINE int32_t UFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in U-Mode.
__STATIC_INLINE int32_t MFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in M-Mode.
__STATIC_INLINE int32_t SFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in S-Mode.
__STATIC_INLINE int32_t UFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in U-Mode.
Detailed Description
Functions that configure Data Cache.
Macro Definition Documentation
MFlushDCacheCCacheLine
#define MFlushDCacheCCacheLine (addr) MFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in M-Mode.
This macro is an alias for MFlushDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1884 of file core_feature_cache.h.
MFlushDCacheCCacheLines
#define MFlushDCacheCCacheLines (addr, cnt) MFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in M-Mode.
This macro is an alias for MFlushDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1895 of file core_feature_cache.h.
MFlushInvalDCacheCCacheLine
#define MFlushInvalDCacheCCacheLine (addr) MFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in M-Mode.
This macro is an alias for MFlushInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1946 of file core_feature_cache.h.
MFlushInvalDCacheCCacheLines
#define MFlushInvalDCacheCCacheLines (addr, cnt) MFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in M-Mode.
This macro is an alias for MFlushInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1957 of file core_feature_cache.h.
MInvalDCacheCCacheLine
#define MInvalDCacheCCacheLine (addr) MInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in M-Mode.
This macro is an alias for MInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1822 of file core_feature_cache.h.
MInvalDCacheCCacheLines
#define MInvalDCacheCCacheLines (addr, cnt) MInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in M-Mode.
This macro is an alias for MInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1833 of file core_feature_cache.h.
SFlushDCacheCCacheLine
#define SFlushDCacheCCacheLine (addr) SFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in S-Mode.
This macro is an alias for SFlushDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1905 of file core_feature_cache.h.
SFlushDCacheCCacheLines
#define SFlushDCacheCCacheLines (addr, cnt) SFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in S-Mode.
This macro is an alias for SFlushDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1916 of file core_feature_cache.h.
SFlushInvalDCacheCCacheLine
#define SFlushInvalDCacheCCacheLine (addr) SFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in S-Mode.
This macro is an alias for SFlushInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1967 of file core_feature_cache.h.
SFlushInvalDCacheCCacheLines
#define SFlushInvalDCacheCCacheLines (addr, cnt) SFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in S-Mode.
This macro is an alias for SFlushInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1978 of file core_feature_cache.h.
SInvalDCacheCCacheLine
#define SInvalDCacheCCacheLine (addr) SInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in S-Mode.
This macro is an alias for SInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1843 of file core_feature_cache.h.
SInvalDCacheCCacheLines
#define SInvalDCacheCCacheLines (addr, cnt) SInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in S-Mode.
This macro is an alias for SInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1854 of file core_feature_cache.h.
UFlushDCacheCCacheLine
#define UFlushDCacheCCacheLine (addr) UFlushDCacheLine(addr)
Flush one D-Cache and Cluster Cache line specified by address in U-Mode.
This macro is an alias for UFlushDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1926 of file core_feature_cache.h.
UFlushDCacheCCacheLines
#define UFlushDCacheCCacheLines (addr, cnt) UFlushDCacheLines(addr, cnt)
Flush several D-Cache and Cluster Cache lines specified by address in U-Mode.
This macro is an alias for UFlushDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1937 of file core_feature_cache.h.
UFlushInvalDCacheCCacheLine
#define UFlushInvalDCacheCCacheLine (addr) UFlushInvalDCacheLine(addr)
Flush and invalidate one D-Cache and Cluster Cache line specified by address in U-Mode.
This macro is an alias for UFlushInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1988 of file core_feature_cache.h.
UFlushInvalDCacheCCacheLines
#define UFlushInvalDCacheCCacheLines (addr, cnt) UFlushInvalDCacheLines(addr, cnt)
Flush and invalidate several D-Cache and Cluster Cache lines specified by address in U-Mode.
This macro is an alias for UFlushInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1999 of file core_feature_cache.h.
UInvalDCacheCCacheLine
#define UInvalDCacheCCacheLine (addr) UInvalDCacheLine(addr)
Invalidate one D-Cache and Cluster Cache line specified by address in U-Mode.
This macro is an alias for UInvalDCacheLine. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1864 of file core_feature_cache.h.
UInvalDCacheCCacheLines
#define UInvalDCacheCCacheLines (addr, cnt) UInvalDCacheLines(addr, cnt)
Invalidate several D-Cache and Cluster Cache lines specified by address in U-Mode.
This macro is an alias for UInvalDCacheLines. D-Cache CCM operations are also effective for Cluster Cache.
Remarks
This macro must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1875 of file core_feature_cache.h.
Function Documentation
DCachePresent()
__STATIC_INLINE int32_t DCachePresent (void)
Check DCache Unit Present or Not.
This function check dcache unit present or not via mcfg_info csr
Remarks
This function might not work for some old nuclei processors
Please make sure the version of your nuclei processor contain DCACHE bit in mcfg_info
Returns
1 if present otherwise 0
Definition at line 1344 of file core_feature_cache.h.
 {
     if (__RV_CSR_READ(CSR_MCFG_INFO) & MCFG_INFO_DCACHE) {
         return 1;
     }
     return 0;
 }
References __RV_CSR_READ, CSR_MCFG_INFO, and MCFG_INFO_DCACHE.
Referenced by _premain_init().
DisableDCache()
__STATIC_FORCEINLINE void DisableDCache (void)
Disable DCache.
This function Disable D-Cache
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control D Cache enable.
See also
EnableDCache
Definition at line 1377 of file core_feature_cache.h.
 {
     __RV_CSR_CLEAR(CSR_MCACHE_CTL, MCACHE_CTL_DC_EN);
 }
References __RV_CSR_CLEAR, CSR_MCACHE_CTL, and MCACHE_CTL_DC_EN.
DisableDCacheECC()
__STATIC_FORCEINLINE void DisableDCacheECC (void)
Disable DCache ECC.
This function disable D-Cache ECC
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control D Cache ECC enable.
See also
EnableDCacheECC
Definition at line 1407 of file core_feature_cache.h.
 {
     __RV_CSR_CLEAR(CSR_MCACHE_CTL, MCACHE_CTL_DC_ECC_EN);
 }
References __RV_CSR_CLEAR, CSR_MCACHE_CTL, and MCACHE_CTL_DC_ECC_EN.
EnableDCache()
__STATIC_FORCEINLINE void EnableDCache (void)
Enable DCache.
This function enable D-Cache
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control D Cache enable.
See also
DisableDCache
Definition at line 1362 of file core_feature_cache.h.
 {
     __RV_CSR_SET(CSR_MCACHE_CTL, MCACHE_CTL_DC_EN);
 }
References __RV_CSR_SET, CSR_MCACHE_CTL, and MCACHE_CTL_DC_EN.
Referenced by _premain_init().
EnableDCacheECC()
__STATIC_FORCEINLINE void EnableDCacheECC (void)
Enable DCache ECC.
This function enable D-Cache ECC
Remarks
This function can be called in M-Mode only.
This CSR_MCACHE_CTL register control D Cache ECC enable.
See also
DisableDCacheECC
Definition at line 1392 of file core_feature_cache.h.
 {
     __RV_CSR_SET(CSR_MCACHE_CTL, MCACHE_CTL_DC_ECC_EN);
 }
References __RV_CSR_SET, CSR_MCACHE_CTL, and MCACHE_CTL_DC_ECC_EN.
GetDCacheInfo()
__STATIC_INLINE int32_t GetDCacheInfo (CacheInfo_Type * info)
Get D-Cache Information.
This function get D-Cache Information
Remarks
This function can be called in M-Mode only.
You can use this function in combination with cache lines operations
See also
GetICacheInfo
Definition at line 1423 of file core_feature_cache.h.
 {
     if (info == NULL) {
         return -1;
     }
     CSR_MDCFGINFO_Type csr_ccfg;
     csr_ccfg.d = __RV_CSR_READ(CSR_MDCFG_INFO);
     info->setperway = (1UL << csr_ccfg.b.set) << 3;
     info->ways = (1 + csr_ccfg.b.way);
     if (csr_ccfg.b.lsize == 0) {
         info->linesize = 0;
     } else {
         info->linesize = (1UL << (csr_ccfg.b.lsize - 1)) << 3;
     }
     info->size = info->setperway * info->ways * info->linesize;
     return 0;
 }
References __RV_CSR_READ, CSR_MDCFGINFO_Type::b, CSR_MDCFG_INFO, CSR_MDCFGINFO_Type::d, CacheInfo_Type::linesize, CSR_MDCFGINFO_Type::lsize, CSR_MDCFGINFO_Type::set, CacheInfo_Type::setperway, CacheInfo_Type::size, CSR_MDCFGINFO_Type::way, and CacheInfo_Type::ways.
MFlushCCache()
__STATIC_INLINE int32_t MFlushCCache (void)
Flush all Cluster Cache in M-Mode.
This function flush all Cluster Cache. Command SMPCC_CMD_WB_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2431 of file core_feature_cache.h.
 {
     /* Clear pending error status before issuing the Cluster Cache command.
      * RESC/FESC/BESC are write-1-to-clear bits, so read the status and write it back. */
     SMPCC_CMD->CC_mCMD = (SMPCC_CMD->CC_mCMD & SMPCC_CMD_xCMD_STATUS_Msk);
     SMPCC_CMD->CC_mCMD = (SMPCC_CMD->CC_mCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_mCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_mCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, SMPCC_CMD_xCMD_CMD_WB_ALL, and SMPCC_CMD_xCMD_STATUS_Msk.
MFlushDCache()
__STATIC_INLINE void MFlushDCache (void)
Flush all D-Cache lines in M-Mode.
This function flush all D-Cache lines. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 2334 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB_ALL, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MFlushDCacheCCache()
__STATIC_INLINE int32_t MFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in M-Mode.
This function flush all D-Cache and Cluster Cache. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2605 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_mCMD = (SMPCC_CMD->CC_mCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_mCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_mCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WB_ALL, CSR_CCM_MCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WB_ALL.
MFlushDCacheLine()
__STATIC_INLINE void MFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in M-Mode.
This function flush one D-Cache line specified by the address. Command CCM_DC_WB is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1576 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WB);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
Referenced by __ECLIC_SetVector().
MFlushDCacheLines()
__STATIC_INLINE void MFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in M-Mode.
This function flush several D-Cache lines specified by the address and line count. Command CCM_DC_WB is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1595 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WB);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MFlushInvalCCache()
__STATIC_INLINE int32_t MFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in M-Mode.
This function flush and invalidate all Cluster Cache. Command SMPCC_CMD_WBINVAL_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2497 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_mCMD = (SMPCC_CMD->CC_mCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_mCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_mCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
MFlushInvalDCache()
__STATIC_INLINE void MFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in M-Mode.
This function flush and invalidate all D-Cache lines. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed and locked
Definition at line 2382 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL_ALL, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MFlushInvalDCacheCCache()
__STATIC_INLINE int32_t MFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in M-Mode.
This function flush and invalidate all D-Cache and Cluster Cache. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2668 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_mCMD = (SMPCC_CMD->CC_mCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_mCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_mCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WBINVAL_ALL, CSR_CCM_MCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
MFlushInvalDCacheLine()
__STATIC_INLINE void MFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in M-Mode.
This function flush and invalidate one D-Cache line specified by the address. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1699 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WBINVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
Referenced by ECC_DCacheDRamErrInject(), ECC_DCacheErrRestore(), and ECC_DCacheTRamErrInject().
MFlushInvalDCacheLines()
__STATIC_INLINE void MFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in M-Mode.
This function flush and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1718 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_WBINVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalDCache()
__STATIC_INLINE void MInvalDCache (void)
Invalidate all D-Cache lines in M-Mode.
This function invalidate all D-Cache lines. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 2284 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL_ALL, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalDCacheCCache()
__STATIC_INLINE void MInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in M-Mode.
This function unlock and invalidate all D-Cache and Cluster Cache. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Definition at line 2553 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_INVAL_ALL, CSR_CCM_MCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
MInvalDCacheLine()
__STATIC_INLINE void MInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in M-Mode.
This function unlock and invalidate one D-Cache line specified by the address. Command CCM_DC_INVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1451 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MInvalDCacheLines()
__STATIC_INLINE void MInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in M-Mode.
This function unlock and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_INVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1470 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MLockDCacheLine()
__STATIC_INLINE unsigned long MLockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in M-Mode.
This function lock one D-Cache line specified by the address. Command CCM_DC_LOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2012 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_MDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, CSR_CCM_MDATA, and FlushPipeCCM().
Referenced by ECC_DCacheErrRestore().
MLockDCacheLines()
__STATIC_INLINE unsigned long MLockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in M-Mode.
This function lock several D-Cache lines specified by the address and line count. Command CCM_DC_LOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2033 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_MDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CCM_OP_SUCCESS, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, CSR_CCM_MDATA, and FlushPipeCCM().
MUnlockDCacheLine()
__STATIC_INLINE void MUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in M-Mode.
This function unlock one D-Cache line specified by the address. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 2161 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
MUnlockDCacheLines()
__STATIC_INLINE void MUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in M-Mode.
This function unlock several D-Cache lines specified by the address and line count. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 2180 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_MBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_MCOMMAND, CCM_DC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_MBEGINADDR, CSR_CCM_MCOMMAND, and FlushPipeCCM().
SFlushCCache()
__STATIC_INLINE int32_t SFlushCCache (void)
Flush all Cluster Cache in S-Mode.
This function flush all Cluster Cache. Command SMPCC_CMD_WB_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M/S-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2453 of file core_feature_cache.h.
 {
     /* Clear pending error status before issuing the Cluster Cache command.
      * RESC/FESC/BESC are write-1-to-clear bits, so read the status and write it back. */
     SMPCC_CMD->CC_sCMD = (SMPCC_CMD->CC_sCMD & SMPCC_CMD_xCMD_STATUS_Msk);
     SMPCC_CMD->CC_sCMD = (SMPCC_CMD->CC_sCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_sCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_sCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, SMPCC_CMD_xCMD_CMD_WB_ALL, and SMPCC_CMD_xCMD_STATUS_Msk.
SFlushDCache()
__STATIC_INLINE void SFlushDCache (void)
Flush all D-Cache lines in S-Mode.
This function flush all D-Cache lines. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 2350 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB_ALL, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SFlushDCacheCCache()
__STATIC_INLINE int32_t SFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in S-Mode.
This function flush all D-Cache and Cluster Cache. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2626 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_sCMD = (SMPCC_CMD->CC_sCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_sCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_sCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WB_ALL, CSR_CCM_SCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WB_ALL.
SFlushDCacheLine()
__STATIC_INLINE void SFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in S-Mode.
This function flush one D-Cache line specified by the address. Command CCM_DC_WB is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1617 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WB);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
Referenced by __ECLIC_SetVector_S().
SFlushDCacheLines()
__STATIC_INLINE void SFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in S-Mode.
This function flush several D-Cache lines specified by the address and line count. Command CCM_DC_WB is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1636 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WB);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SFlushInvalCCache()
__STATIC_INLINE int32_t SFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in S-Mode.
This function flush and invalidate all Cluster Cache. Command SMPCC_CMD_WBINVAL_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M/S-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2516 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_sCMD = (SMPCC_CMD->CC_sCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_sCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_sCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
SFlushInvalDCache()
__STATIC_INLINE void SFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in S-Mode.
This function flush and invalidate all D-Cache lines. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed and locked
Definition at line 2398 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL_ALL, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SFlushInvalDCacheCCache()
__STATIC_INLINE int32_t SFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in S-Mode.
This function flush and invalidate all D-Cache and Cluster Cache. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2689 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_sCMD = (SMPCC_CMD->CC_sCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_sCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_sCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WBINVAL_ALL, CSR_CCM_SCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
SFlushInvalDCacheLine()
__STATIC_INLINE void SFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in S-Mode.
This function flush and invalidate one D-Cache line specified by the address. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1740 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WBINVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SFlushInvalDCacheLines()
__STATIC_INLINE void SFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in S-Mode.
This function flush and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1759 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_WBINVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalDCache()
__STATIC_INLINE void SInvalDCache (void)
Invalidate all D-Cache lines in S-Mode.
This function invalidate all D-Cache lines. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 2300 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL_ALL, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalDCacheCCache()
__STATIC_INLINE void SInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in S-Mode.
This function unlock and invalidate all D-Cache and Cluster Cache. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Definition at line 2570 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_INVAL_ALL, CSR_CCM_SCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
SInvalDCacheLine()
__STATIC_INLINE void SInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in S-Mode.
This function unlock and invalidate one D-Cache line specified by the address. Command CCM_DC_INVAL is written to CSR CSR_CCM_MCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1493 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SInvalDCacheLines()
__STATIC_INLINE void SInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in S-Mode.
This function unlock and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_INVAL is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1512 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SLockDCacheLine()
__STATIC_INLINE unsigned long SLockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in S-Mode.
This function lock one D-Cache line specified by the address. Command CCM_DC_LOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2062 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_SDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, CSR_CCM_SDATA, and FlushPipeCCM().
SLockDCacheLines()
__STATIC_INLINE unsigned long SLockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in S-Mode.
This function lock several D-Cache lines specified by the address and line count. Command CCM_DC_LOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2083 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_SDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CCM_OP_SUCCESS, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, CSR_CCM_SDATA, and FlushPipeCCM().
SUnlockDCacheLine()
__STATIC_INLINE void SUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in S-Mode.
This function unlock one D-Cache line specified by the address. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 2202 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
SUnlockDCacheLines()
__STATIC_INLINE void SUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in S-Mode.
This function unlock several D-Cache lines specified by the address and line count. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_SCOMMAND.
Remarks
This function must be executed in M/S-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 2221 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_SBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_SCOMMAND, CCM_DC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_SBEGINADDR, CSR_CCM_SCOMMAND, and FlushPipeCCM().
UFlushCCache()
__STATIC_INLINE int32_t UFlushCCache (void)
Flush all Cluster Cache in U-Mode.
This function flush all Cluster Cache. Command SMPCC_CMD_WB_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M/S/U-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2475 of file core_feature_cache.h.
 {
     /* Clear pending error status before issuing the Cluster Cache command.
      * RESC/FESC/BESC are write-1-to-clear bits, so read the status and write it back. */
     SMPCC_CMD->CC_uCMD = (SMPCC_CMD->CC_uCMD & SMPCC_CMD_xCMD_STATUS_Msk);
     SMPCC_CMD->CC_uCMD = (SMPCC_CMD->CC_uCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_uCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_uCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, SMPCC_CMD_xCMD_CMD_WB_ALL, and SMPCC_CMD_xCMD_STATUS_Msk.
UFlushDCache()
__STATIC_INLINE void UFlushDCache (void)
Flush all D-Cache lines in U-Mode.
This function flush all D-Cache lines. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 2366 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB_ALL, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UFlushDCacheCCache()
__STATIC_INLINE int32_t UFlushDCacheCCache (void)
Flush all D-Cache and Cluster Cache in U-Mode.
This function flush all D-Cache and Cluster Cache. Command CCM_DC_WB_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2647 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WB_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_uCMD = (SMPCC_CMD->CC_uCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WB_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_uCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_uCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WB_ALL, CSR_CCM_UCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WB_ALL.
UFlushDCacheLine()
__STATIC_INLINE void UFlushDCacheLine (unsigned long addr)
Flush one D-Cache line specified by address in U-Mode.
This function flush one D-Cache line specified by the address. Command CCM_DC_WB is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed
Definition at line 1658 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WB);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UFlushDCacheLines()
__STATIC_INLINE void UFlushDCacheLines (unsigned long addr, unsigned long cnt)
Flush several D-Cache lines specified by address in U-Mode.
This function flush several D-Cache lines specified by the address and line count. Command CCM_DC_WB is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed
[in] cnt count of cache lines to be flushed
Definition at line 1677 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WB);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WB, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UFlushInvalCCache()
__STATIC_INLINE int32_t UFlushInvalCCache (void)
Flush and invalidate all Cluster Cache in U-Mode.
This function flush and invalidate all Cluster Cache. Command SMPCC_CMD_WBINVAL_ALL is written to SMPCC CMD register.
Remarks
This function must be executed in M/S/U-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2535 of file core_feature_cache.h.
 {
     SMPCC_CMD->CC_uCMD = (SMPCC_CMD->CC_uCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_uCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_uCMD);
     __RWMB();
     return res;
 }
References __RWMB, _FLD2VAL, _VAL2FLD, SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
UFlushInvalDCache()
__STATIC_INLINE void UFlushInvalDCache (void)
Flush and invalidate all D-Cache lines in U-Mode.
This function flush and invalidate all D-Cache lines. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed and locked
Definition at line 2414 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL_ALL, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UFlushInvalDCacheCCache()
__STATIC_INLINE int32_t UFlushInvalDCacheCCache (void)
Flush and invalidate all D-Cache and Cluster Cache in U-Mode.
This function flush and invalidate all D-Cache and Cluster Cache. Command CCM_DC_WBINVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Returns
Operation result, see enum SMPCC_CMD_RESULT
Definition at line 2710 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WBINVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_uCMD = (SMPCC_CMD->CC_uCMD & ~SMPCC_CMD_xCMD_CMD_Msk) |
                          _VAL2FLD(SMPCC_CMD_xCMD_CMD, SMPCC_CMD_xCMD_CMD_WBINVAL_ALL);
     while(_FLD2VAL(SMPCC_CMD_xCMD_COMPLETE, SMPCC_CMD->CC_uCMD) == 0);
     int32_t res = _FLD2VAL(SMPCC_CMD_xCMD_RESULT, SMPCC_CMD->CC_uCMD);
     __RWMB();
     return res;
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_WBINVAL_ALL, CSR_CCM_UCOMMAND, FlushPipeCCM(), SMPCC_CMD, SMPCC_CMD_xCMD_CMD_Msk, and SMPCC_CMD_xCMD_CMD_WBINVAL_ALL.
UFlushInvalDCacheLine()
__STATIC_INLINE void UFlushInvalDCacheLine (unsigned long addr)
Flush and invalidate one D-Cache line specified by address in U-Mode.
This function flush and invalidate one D-Cache line specified by the address. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
Definition at line 1781 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WBINVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UFlushInvalDCacheLines()
__STATIC_INLINE void UFlushInvalDCacheLines (unsigned long addr, unsigned long cnt)
Flush and invalidate several D-Cache lines specified by address in U-Mode.
This function flush and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_WBINVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be flushed and invalidated
[in] cnt count of cache lines to be flushed and invalidated
Definition at line 1800 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_WBINVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_WBINVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalDCache()
__STATIC_INLINE void UInvalDCache (void)
Invalidate all D-Cache lines in U-Mode.
This function invalidate all D-Cache lines. In U-Mode, this operation will be automatically translated to flush and invalidate operations by hardware. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 2318 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL_ALL, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalDCacheCCache()
__STATIC_INLINE void UInvalDCacheCCache (void)
Invalidate all D-Cache and Cluster Cache in U-Mode.
This function unlock and invalidate all D-Cache and Cluster Cache. Command CCM_DC_INVAL_ALL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Definition at line 2587 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL_ALL);
     FlushPipeCCM();
     SMPCC_CMD->CC_INVALID_ALL = _VAL2FLD(SMPCC_CMD_INVALID_ALL, 1);
     while(_FLD2VAL(SMPCC_CMD_INVALID_ALL, SMPCC_CMD->CC_INVALID_ALL));
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, _FLD2VAL, _VAL2FLD, CCM_DC_INVAL_ALL, CSR_CCM_UCOMMAND, FlushPipeCCM(), and SMPCC_CMD.
UInvalDCacheLine()
__STATIC_INLINE void UInvalDCacheLine (unsigned long addr)
Invalidate one D-Cache line specified by address in U-Mode.
This function unlock and invalidate one D-Cache line specified by the address. Command CCM_DC_INVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
Definition at line 1535 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UInvalDCacheLines()
__STATIC_INLINE void UInvalDCacheLines (unsigned long addr, unsigned long cnt)
Invalidate several D-Cache lines specified by address in U-Mode.
This function unlock and invalidate several D-Cache lines specified by the address and line count. Command CCM_DC_INVAL is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be invalidated
[in] cnt count of cache lines to be invalidated
Definition at line 1554 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_INVAL);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_INVAL, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
ULockDCacheLine()
__STATIC_INLINE unsigned long ULockDCacheLine (unsigned long addr)
Lock one D-Cache line specified by address in U-Mode.
This function lock one D-Cache line specified by the address. Command CCM_DC_LOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2112 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_LOCK);
     FlushPipeCCM();
     __RWMB();
     return __RV_CSR_READ(CSR_CCM_UDATA);
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, CSR_CCM_UDATA, and FlushPipeCCM().
ULockDCacheLines()
__STATIC_INLINE unsigned long ULockDCacheLines (unsigned long addr, unsigned long cnt)
Lock several D-Cache lines specified by address in U-Mode.
This function lock several D-Cache lines specified by the address and line count. Command CCM_DC_LOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be locked
[in] cnt count of cache lines to be locked
Returns
result of CCM lock operation, see enum CCM_OP_FINFO
Definition at line 2133 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         unsigned long fail_info = CCM_OP_SUCCESS;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_LOCK);
             FlushPipeCCM();
             __RWMB();
             fail_info = __RV_CSR_READ(CSR_CCM_UDATA);
             if (CCM_OP_SUCCESS != fail_info) {
                 return fail_info;
             }
         }
     }
     return CCM_OP_SUCCESS;
 }
References __RV_CSR_READ, __RV_CSR_WRITE, __RWMB, CCM_DC_LOCK, CCM_OP_SUCCESS, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, CSR_CCM_UDATA, and FlushPipeCCM().
UUnlockDCacheLine()
__STATIC_INLINE void UUnlockDCacheLine (unsigned long addr)
Unlock one D-Cache line specified by address in U-Mode.
This function unlock one D-Cache line specified by the address. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be unlocked
Definition at line 2243 of file core_feature_cache.h.
 {
     __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
     __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_UNLOCK);
     FlushPipeCCM();
     __RWMB();
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().
UUnlockDCacheLines()
__STATIC_INLINE void UUnlockDCacheLines (unsigned long addr, unsigned long cnt)
Unlock several D-Cache lines specified by address in U-Mode.
This function unlock several D-Cache lines specified by the address and line count. Command CCM_DC_UNLOCK is written to CSR CSR_CCM_UCOMMAND.
Remarks
This function must be executed in M/S/U-Mode only.
Parameters
[in] addr start address to be unlocked
[in] cnt count of cache lines to be unlocked
Definition at line 2262 of file core_feature_cache.h.
 {
     if (cnt > 0) {
         unsigned long i;
         __RV_CSR_WRITE(CSR_CCM_UBEGINADDR, addr);
         for (i = 0; i < cnt; i++) {
             __RV_CSR_WRITE(CSR_CCM_UCOMMAND, CCM_DC_UNLOCK);
         }
         FlushPipeCCM();
         __RWMB();
     }
 }
References __RV_CSR_WRITE, __RWMB, CCM_DC_UNLOCK, CSR_CCM_UBEGINADDR, CSR_CCM_UCOMMAND, and FlushPipeCCM().