NMSIS-Core: PMP Functions
PMP Functions
Functions that related to the RISCV Phyiscal Memory Protection.
Data Structures
struct pmp_config
Macros
#define PMPCFG_LIST_RV32_0_7 X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7)
PMPCFG list for RV32 (indices 0-7)
#define PMPCFG_LIST_RV32_8_15 X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15)
PMPCFG list for RV32 (indices 8-15)
#define PMPCFG_LIST_RV64_0_6 X(0) X(2) X(4) X(6)
PMPCFG list for RV64 (even indices 0-6)
#define PMPCFG_LIST_RV64_8_14 X(8) X(10) X(12) X(14)
PMPCFG list for RV64 (even indices 8-14)
#define PMPCFG_LIST PMPCFG_LIST_RV32_0_7
Select appropriate PMPCFG list based on architecture and PMP entry count.
#define PMPADDR_LIST_BASE X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7)
Base PMPADDR list (indices 0-7)
#define PMPADDR_LIST_8_15 X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15)
Extended PMPADDR list (indices 8-15)
#define PMPADDR_LIST_16_31
Extended PMPADDR list (indices 16-31)
#define PMPADDR_LIST_32_63
Extended PMPADDR list (indices 32-63)
#define PMPADDR_LIST PMPADDR_LIST_BASE PMPADDR_LIST_8_15
Select appropriate PMPADDR list based on PMP_ENTRY_NUM.
Functions
__STATIC_INLINE rv_csr_t __get_PMPCFGx (uint32_t csr_idx)
Get PMPCFGx Register by CSR index.
__STATIC_INLINE void __set_PMPCFGx (uint32_t csr_idx, rv_csr_t pmpcfg)
Set PMPCFGx by CSR index.
__STATIC_INLINE uint8_t __get_PMPxCFG (uint32_t entry_idx)
Get 8bit PMPxCFG Register by PMP entry index.
__STATIC_INLINE void __set_PMPxCFG (uint32_t entry_idx, uint8_t pmpxcfg)
Set 8bit PMPxCFG by pmp entry index.
__STATIC_INLINE rv_csr_t __get_PMPADDRx (uint32_t csr_idx)
Get PMPADDRx Register by CSR index.
__STATIC_INLINE void __set_PMPADDRx (uint32_t csr_idx, rv_csr_t pmpaddr)
Set PMPADDRx by CSR index.
__STATIC_INLINE void __set_PMPENTRYx (uint32_t entry_idx, const pmp_config *pmp_cfg)
Set PMP entry by entry idx.
__STATIC_INLINE int __get_PMPENTRYx (unsigned int entry_idx, pmp_config *pmp_cfg)
Get PMP entry by entry idx.
Detailed Description
Functions that related to the RISCV Phyiscal Memory Protection.
Optional physical memory protection (PMP) unit provides per-hart machine-mode control registers to allow physical memory access privileges (read, write, execute) to be specified for each physical memory region.
The PMP can supports region access control settings as small as four bytes.
Macro Definition Documentation
PMPADDR_LIST
#define PMPADDR_LIST PMPADDR_LIST_BASE PMPADDR_LIST_8_15
Select appropriate PMPADDR list based on PMP_ENTRY_NUM.
This macro defines the complete PMPADDR list by combining base and extended lists according to the configured number of PMP entries.
Note
The actual list is determined by the __PMP_ENTRY_NUM configuration:
<=8: Only base list (0-7)
<=16: Base + 8-15
<=32: Base + 8-15 + 16-31
<=64: Base + 8-15 + 16-31 + 32-63
Definition at line 325 of file core_feature_pmp.h.
PMPADDR_LIST_16_31
#define PMPADDR_LIST_16_31
Extended PMPADDR list (indices 16-31)
Definition at line 297 of file core_feature_pmp.h.
PMPADDR_LIST_32_63
#define PMPADDR_LIST_32_63
Extended PMPADDR list (indices 32-63)
Definition at line 304 of file core_feature_pmp.h.
PMPADDR_LIST_8_15
#define PMPADDR_LIST_8_15 X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15)
Extended PMPADDR list (indices 8-15)
Definition at line 291 of file core_feature_pmp.h.
PMPADDR_LIST_BASE
#define PMPADDR_LIST_BASE X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7)
Base PMPADDR list (indices 0-7)
Definition at line 285 of file core_feature_pmp.h.
PMPCFG_LIST
#define PMPCFG_LIST PMPCFG_LIST_RV32_0_7
Select appropriate PMPCFG list based on architecture and PMP entry count.
This macro defines the complete PMPCFG list according to:
RISC-V architecture (RV32/RV64)
Number of PMP entries (__PMP_ENTRY_NUM)
Note
Valid indices depend on configuration:
RV32:
<=32 entries: indices 0-7
<=64 entries: indices 0-15
RV64:
<=32 entries: indices 0,2,4,6
<=64 entries: indices 0,2,4,6,8,10,12,14
Definition at line 130 of file core_feature_pmp.h.
PMPCFG_LIST_RV32_0_7
#define PMPCFG_LIST_RV32_0_7 X(0) X(1) X(2) X(3) X(4) X(5) X(6) X(7)
PMPCFG list for RV32 (indices 0-7)
For RV32, each PMPCFG register holds 4 PMP entries. This list covers the first 32 entries (registers 0-7).
Definition at line 83 of file core_feature_pmp.h.
PMPCFG_LIST_RV32_8_15
#define PMPCFG_LIST_RV32_8_15 X(8) X(9) X(10) X(11) X(12) X(13) X(14) X(15)
PMPCFG list for RV32 (indices 8-15)
For RV32, each PMPCFG register holds 4 PMP entries. This list covers entries 33-64 (registers 8-15).
Definition at line 92 of file core_feature_pmp.h.
PMPCFG_LIST_RV64_0_6
#define PMPCFG_LIST_RV64_0_6 X(0) X(2) X(4) X(6)
PMPCFG list for RV64 (even indices 0-6)
For RV64, each PMPCFG register holds 8 PMP entries. This list covers the first 32 entries (registers 0,2,4,6).
Definition at line 101 of file core_feature_pmp.h.
PMPCFG_LIST_RV64_8_14
#define PMPCFG_LIST_RV64_8_14 X(8) X(10) X(12) X(14)
PMPCFG list for RV64 (even indices 8-14)
For RV64, each PMPCFG register holds 8 PMP entries. This list covers entries 33-64 (registers 8,10,12,14).
Definition at line 110 of file core_feature_pmp.h.
Function Documentation
__get_PMPADDRx()
__STATIC_INLINE rv_csr_t __get_PMPADDRx (uint32_t csr_idx)
Get PMPADDRx Register by CSR index.
Return the content of the PMPADDRx Register.
Parameters
[in] csr_idx PMP region CSR index(0-63)
Returns
PMPADDRx Register value
Definition at line 340 of file core_feature_pmp.h.
 {
     switch (csr_idx) {
     #define X(n) case n: return __RV_CSR_READ(CSR_PMPADDR##n);
         PMPADDR_LIST
     #undef X
         default: return 0;
     }
 }
References PMPADDR_LIST.
Referenced by __get_PMPENTRYx().
__get_PMPCFGx()
__STATIC_INLINE rv_csr_t __get_PMPCFGx (uint32_t csr_idx)
Get PMPCFGx Register by CSR index.
Return the content of the PMPCFGx Register.
Parameters
[in] csr_idx PMPCFG CSR index (0-15 for RV32, 0,2,4,6,8,10,12,14 for RV64)
Returns
PMPCFGx Register value
Note
Architecture-specific behavior:
RV32:
Each register holds 4 PMP entries
Valid indices: 0 to ceil(__PMP_ENTRY_NUM/4)-1
64 entries require indices 0-15
RV64:
Each register holds 8 PMP entries
Only even indices are valid
64 entries require indices 0,2,4,6,8,10,12,14
Remarks
The function returns 0 for invalid indices to prevent illegal accesses.
Definition at line 166 of file core_feature_pmp.h.
 {
     switch (csr_idx) {
     #define X(n) case n: return __RV_CSR_READ(CSR_PMPCFG##n);
         PMPCFG_LIST
     #undef X
         default: return 0;
     }
 }
References PMPCFG_LIST.
Referenced by __get_PMPENTRYx(), __get_PMPxCFG(), __set_PMPENTRYx(), and __set_PMPxCFG().
__get_PMPENTRYx()
__STATIC_INLINE int __get_PMPENTRYx (unsigned int entry_idx, pmp_config * pmp_cfg)
Get PMP entry by entry idx.
Write the given value to the PMPxCFG Register and PMPADDRx.
Parameters
[in] entry_idx PMP entry index(0-63)
[out] pmp_cfg structure of L, X, W, R, A field of PMP configuration register, memory region base address and size of memory region as power of 2
Returns
-1 failure, else 0 success
Remarks
If the size of memory region is 2^12(4KB) range, pmp_cfg->order makes 12, and the like.
TOR of A field in PMP configuration register is not considered here.
Definition at line 438 of file core_feature_pmp.h.
 {
     unsigned int cfg_shift, cfg_csr_idx, addr_csr_idx = 0;
     unsigned long cfgmask, pmpcfg, prot = 0;
     unsigned long t1, addr, pmpaddr, len = 0;
     uint8_t csr_cfg_num = 0;
     /* check parameters */
     if (entry_idx >= __PMP_ENTRY_NUM || !pmp_cfg) return -1;
     /* calculate PMP register and offset */
 #if __RISCV_XLEN == 32
     csr_cfg_num = 4;
     cfg_csr_idx = entry_idx >> 2;
 #elif __RISCV_XLEN == 64
     csr_cfg_num = 8;
     cfg_csr_idx = (entry_idx>> 2) & ~1;
 #else
     // TODO Add RV128 Handling
     return -1;
 #endif
     cfg_shift = (entry_idx & (csr_cfg_num - 1)) << 3;
     addr_csr_idx = entry_idx;
     /* decode PMP config */
     cfgmask = (0xFFUL << cfg_shift);
     pmpcfg = (__get_PMPCFGx(cfg_csr_idx) & cfgmask);
     prot = pmpcfg >> cfg_shift;
     /* decode PMP address */
     pmpaddr = __get_PMPADDRx(addr_csr_idx);
     if (PMP_A_NAPOT == (prot & PMP_A)) {
         t1 = __CTZ(~pmpaddr);
         addr = (pmpaddr & ~((1UL << t1) - 1)) << PMP_SHIFT;
         len = (t1 + PMP_SHIFT + 1);
     } else {
         addr = pmpaddr << PMP_SHIFT;
         len = PMP_SHIFT;
     }
     /* return details */
     pmp_cfg->protection = prot;
     pmp_cfg->base_addr = addr;
     pmp_cfg->order = len;
     return 0;
 }
References __CTZ(), __get_PMPADDRx(), __get_PMPCFGx(), pmp_config::base_addr, pmp_config::order, PMP_A, PMP_A_NAPOT, PMP_SHIFT, and pmp_config::protection.
__get_PMPxCFG()
__STATIC_INLINE uint8_t __get_PMPxCFG (uint32_t entry_idx)
Get 8bit PMPxCFG Register by PMP entry index.
Return the content of the PMPxCFG Register.
Parameters
[in] entry_idx PMP region index(0-63)
Returns
PMPxCFG Register value
Definition at line 210 of file core_feature_pmp.h.
 {
     rv_csr_t pmpcfgx = 0;
     uint8_t csr_cfg_num = 0;
     uint16_t csr_idx = 0;
     uint16_t cfg_shift = 0;
     if (entry_idx >= __PMP_ENTRY_NUM) return 0;
 #if __RISCV_XLEN == 32
     csr_cfg_num = 4;
     csr_idx = entry_idx >> 2;
 #elif __RISCV_XLEN == 64
     csr_cfg_num = 8;
     /* For RV64, each PMPCFG register (pmpcfg0, pmpcfg2, etc.) holds 8 PMP entries */
     /* Only even-numbered CSRs are used, so we align the index by clearing the LSB */
     csr_idx = (entry_idx >> 2) & ~1;
 #else
     // TODO Add RV128 Handling
     return 0;
 #endif
     pmpcfgx = __get_PMPCFGx(csr_idx);
     /*
      * first get specific pmpxcfg's order in one CSR composed of csr_cfg_num pmpxcfgs,
      * then get pmpxcfg's bit position in one CSR by left shift 3(each pmpxcfg size is one byte)
      */
     cfg_shift = (entry_idx & (csr_cfg_num - 1)) << 3;
     /* read specific pmpxcfg register value */
     return (uint8_t)(__RV_EXTRACT_FIELD(pmpcfgx, 0xFF << cfg_shift));
 }
References __get_PMPCFGx().
__set_PMPADDRx()
__STATIC_INLINE void __set_PMPADDRx (uint32_t csr_idx, rv_csr_t pmpaddr)
Set PMPADDRx by CSR index.
Write the given value to the PMPADDRx Register.
Parameters
[in] csr_idx PMP region CSR index(0-63)
[in] pmpaddr PMPADDRx Register value to set
Definition at line 356 of file core_feature_pmp.h.
 {
     switch (csr_idx) {
     #define X(n) case n: __RV_CSR_WRITE(CSR_PMPADDR##n, pmpaddr); break;
         PMPADDR_LIST
     #undef X
         default: return;
     }
 }
References PMPADDR_LIST.
Referenced by __set_PMPENTRYx().
__set_PMPCFGx()
__STATIC_INLINE void __set_PMPCFGx (uint32_t csr_idx, rv_csr_t pmpcfg)
Set PMPCFGx by CSR index.
Write the given value to the PMPCFGx Register.
Parameters
[in] csr_idx PMPCFG CSR index (0-15 for RV32, 0,2,4,6,8,10,12,14 for RV64)
[in] pmpcfg PMPCFGx Register value to set
Note
Architecture-specific behavior:
RV32:
Each register holds 4 PMP entries
Valid indices: 0 to ceil(__PMP_ENTRY_NUM/4)-1
64 entries require indices 0-15
RV64:
Each register holds 8 PMP entries
Only even indices are valid
64 entries require indices 0,2,4,6,8,10,12,14
Remarks
The function does nothing for invalid indices to prevent illegal accesses.
Definition at line 194 of file core_feature_pmp.h.
 {
     switch (csr_idx) {
     #define X(n) case n: __RV_CSR_WRITE(CSR_PMPCFG##n, pmpcfg); break;
         PMPCFG_LIST
     #undef X
         default: return;
     }
 }
References PMPCFG_LIST.
Referenced by __set_PMPENTRYx(), and __set_PMPxCFG().
__set_PMPENTRYx()
__STATIC_INLINE void __set_PMPENTRYx (uint32_t entry_idx, const pmp_config * pmp_cfg)
Set PMP entry by entry idx.
Write the given value to the PMPxCFG Register and PMPADDRx.
Parameters
[in] entry_idx PMP entry index(0-63)
[in] pmp_cfg structure of L, X, W, R field of PMP configuration register, memory region base address and size of memory region as power of 2
Remarks
If the size of memory region is 2^12(4KB) range, pmp_cfg->order makes 12, and the like.
Suppose the size of memory region is 2^X bytes range, if X >=3, the NA4 mode is not selectable, NAPOT is selected.
TOR of A field in PMP configuration register is not considered here.
Definition at line 377 of file core_feature_pmp.h.
 {
     unsigned int cfg_shift, cfg_csr_idx, addr_csr_idx = 0;
     unsigned long cfgmask, addrmask = 0;
     unsigned long pmpcfg, pmpaddr = 0;
     unsigned long protection, csr_cfg_num = 0;
     /* check parameters */
     if (entry_idx >= __PMP_ENTRY_NUM || pmp_cfg->order > __RISCV_XLEN || pmp_cfg->order < PMP_SHIFT) return;
     /* calculate PMP register and offset */
 #if __RISCV_XLEN == 32
     csr_cfg_num = 4;
     cfg_csr_idx = (entry_idx >> 2);
 #elif __RISCV_XLEN == 64
     csr_cfg_num = 8;
     cfg_csr_idx = ((entry_idx >> 2)) & ~1;
 #else
     // TODO Add RV128 Handling
     return;
 #endif
     /*
      * first get specific pmpxcfg's order in one CSR composed of csr_cfg_num pmpxcfgs,
      * then get pmpxcfg's bit position in one CSR by left shift 3, each pmpxcfg size is one byte
      */
     cfg_shift = (entry_idx & (csr_cfg_num - 1)) << 3;
     addr_csr_idx = entry_idx;
     /* encode PMP config */
     protection = (unsigned long)pmp_cfg->protection;
     protection |= (PMP_SHIFT == pmp_cfg->order) ? PMP_A_NA4 : PMP_A_NAPOT;
     cfgmask = ~(0xFFUL << cfg_shift);
     pmpcfg = (__get_PMPCFGx(cfg_csr_idx) & cfgmask);
     pmpcfg |= ((protection << cfg_shift) & ~cfgmask);
     /* encode PMP address */
     if (PMP_SHIFT == pmp_cfg->order) { /* NA4 */
         pmpaddr = (pmp_cfg->base_addr >> PMP_SHIFT);
     } else { /* NAPOT */
         addrmask = (1UL << (pmp_cfg->order - PMP_SHIFT)) - 1;
         pmpaddr = ((pmp_cfg->base_addr >> PMP_SHIFT) & ~addrmask);
         pmpaddr |= (addrmask >> 1);
     }
     /*
      * write csrs, update the address first, in case the entry is locked that
      * we won't be able to modify it after we set the config csr.
      */
     __set_PMPADDRx(addr_csr_idx, pmpaddr);
     __set_PMPCFGx(cfg_csr_idx, pmpcfg);
 }
References __get_PMPCFGx(), __RISCV_XLEN, __set_PMPADDRx(), __set_PMPCFGx(), pmp_config::base_addr, pmp_config::order, PMP_A_NA4, PMP_A_NAPOT, PMP_SHIFT, and pmp_config::protection.
__set_PMPxCFG()
__STATIC_INLINE void __set_PMPxCFG (uint32_t entry_idx, uint8_t pmpxcfg)
Set 8bit PMPxCFG by pmp entry index.
Set the given pmpxcfg value to the PMPxCFG Register.
Parameters
[in] entry_idx PMPx region index(0-63)
[in] pmpxcfg PMPxCFG register value to set
Remarks
For RV32, 4 pmpxcfgs are densely packed into one CSR in order For RV64, 8 pmpxcfgs are densely packed into one CSR in order
Definition at line 251 of file core_feature_pmp.h.
 {
     rv_csr_t pmpcfgx = 0;
     uint8_t csr_cfg_num = 0;
     uint16_t csr_idx = 0;
     uint16_t cfg_shift = 0;
     if (entry_idx >= __PMP_ENTRY_NUM) return;
 #if __RISCV_XLEN == 32
     csr_cfg_num = 4;
     csr_idx = entry_idx >> 2;
 #elif __RISCV_XLEN == 64
     csr_cfg_num = 8;
     /* For RV64, pmpcfg0 and pmpcfg2 each hold 8 PMP entries, align by 2 */
     csr_idx = (entry_idx >> 2) & ~1;
 #else
     // TODO Add RV128 Handling
     return;
 #endif
     /* read specific pmpcfgx register value */
     pmpcfgx = __get_PMPCFGx(csr_idx);
     /*
      * first get specific pmpxcfg's order in one CSR composed of csr_cfg_num pmpxcfgs,
      * then get pmpxcfg's bit position in one CSR by left shift 3(each pmpxcfg size is one byte)
      */
     cfg_shift = (entry_idx & (csr_cfg_num - 1)) << 3;
     pmpcfgx = __RV_INSERT_FIELD(pmpcfgx, 0xFFUL << cfg_shift, pmpxcfg);
     __set_PMPCFGx(csr_idx, pmpcfgx);
 }
References __get_PMPCFGx(), and __set_PMPCFGx().