NMSIS-Core: PLIC Interrupt
PLIC Interrupt
Functions that manage interrupts via the PLIC.
Macros
#define PLIC_Init(num_sources, enable, thresh) PLIC_Context_Init(PLIC_GetHartMContextID(), (num_sources), (enable), (thresh))
#define PLIC_Init_S(num_sources, enable, thresh) PLIC_Context_Init(PLIC_GetHartSContextID(), (num_sources), (enable), (thresh))
#define PLIC_ClaimInterrupt() PLIC_ClaimContextInterrupt(PLIC_GetHartMContextID())
#define PLIC_ClaimInterrupt_S() PLIC_ClaimContextInterrupt(PLIC_GetHartSContextID())
#define PLIC_CompleteInterrupt(source) PLIC_CompleteContextInterrupt(PLIC_GetHartMContextID(), (source))
#define PLIC_CompleteInterrupt_S(source) PLIC_CompleteContextInterrupt(PLIC_GetHartSContextID(), (source))
#define PLIC_GetInterruptEnable(source) PLIC_GetContextInterruptEnable(PLIC_GetHartMContextID(), (source))
#define PLIC_GetInterruptEnable_S(source) PLIC_GetContextInterruptEnable(PLIC_GetHartSContextID(), (source))
#define PLIC_EnableInterrupt(source) PLIC_EnableContextInterrupt(PLIC_GetHartMContextID(), (source))
#define PLIC_EnableInterrupt_S(source) PLIC_EnableContextInterrupt(PLIC_GetHartSContextID(), (source))
#define PLIC_DisableInterrupt(source) PLIC_DisableContextInterrupt(PLIC_GetHartMContextID(), (source))
#define PLIC_DisableInterrupt_S(source) PLIC_DisableContextInterrupt(PLIC_GetHartSContextID(), (source))
#define PLIC_SetThreshold(source, thresh) PLIC_SetContextThreshold(PLIC_GetHartMContextID(), (source), (thresh))
#define PLIC_SetThreshold_S(source, thresh) PLIC_SetContextThreshold(PLIC_GetHartSContextID(), (source), (thresh))
#define PLIC_GetThreshold() PLIC_GetContextThreshold(PLIC_GetHartMContextID())
#define PLIC_GetThreshold_S() PLIC_GetContextThreshold(PLIC_GetHartSContextID())
Functions
__STATIC_FORCEINLINE void PLIC_SetContextThreshold (uint32_t ctxid, uint32_t thresh)
Set priority threshold value of plic for selected context.
__STATIC_FORCEINLINE uint32_t PLIC_GetContextThreshold (uint32_t ctxid)
Get priority threshold value of plic for selected context.
__STATIC_FORCEINLINE void PLIC_EnableContextInterrupt (uint32_t ctxid, uint32_t source)
Enable interrupt of selected source plic for selected context.
__STATIC_FORCEINLINE void PLIC_DisableContextInterrupt (uint32_t ctxid, uint32_t source)
Disable interrupt of selected source plic for selected context.
__STATIC_FORCEINLINE uint32_t PLIC_GetContextInterruptEnable (uint32_t ctxid, uint32_t source)
Get interrupt enable status of selected source plic for selected context.
__STATIC_FORCEINLINE void PLIC_SetInterruptPending (uint32_t source)
Set interrupt pending of selected source plic.
__STATIC_FORCEINLINE void PLIC_ClearInterruptPending (uint32_t source)
Clear interrupt pending of selected source plic.
__STATIC_FORCEINLINE uint32_t PLIC_GetInterruptPending (uint32_t source)
Get interrupt pending status of selected source plic.
__STATIC_FORCEINLINE void PLIC_SetPriority (uint32_t source, uint32_t priority)
Set interrupt priority for selected source plic.
__STATIC_FORCEINLINE uint32_t PLIC_GetPriority (uint32_t source)
Get interrupt priority for selected source plic.
__STATIC_FORCEINLINE uint32_t PLIC_ClaimContextInterrupt (uint32_t ctxid)
Claim interrupt for plic for selected context.
__STATIC_FORCEINLINE void PLIC_CompleteContextInterrupt (uint32_t ctxid, uint32_t source)
Complete interrupt for plic for selected context.
__STATIC_FORCEINLINE void PLIC_Context_Init (uint32_t ctxid, uint32_t num_sources, uint32_t enable, uint32_t thresh)
Perform init for plic for selected context.
__STATIC_FORCEINLINE void __set_trap_entry (rv_csr_t addr)
Set Trap entry address.
__STATIC_FORCEINLINE rv_csr_t __get_trap_entry (void)
Get trap entry address.
Detailed Description
Functions that manage interrupts via the PLIC.
Macro Definition Documentation
PLIC_ClaimInterrupt
#define PLIC_ClaimInterrupt () PLIC_ClaimContextInterrupt(PLIC_GetHartMContextID())
Definition at line 368 of file core_feature_plic.h.
PLIC_ClaimInterrupt_S
#define PLIC_ClaimInterrupt_S () PLIC_ClaimContextInterrupt(PLIC_GetHartSContextID())
Definition at line 369 of file core_feature_plic.h.
PLIC_CompleteInterrupt
#define PLIC_CompleteInterrupt (source) PLIC_CompleteContextInterrupt(PLIC_GetHartMContextID(), (source))
Definition at line 371 of file core_feature_plic.h.
PLIC_CompleteInterrupt_S
#define PLIC_CompleteInterrupt_S (source) PLIC_CompleteContextInterrupt(PLIC_GetHartSContextID(), (source))
Definition at line 372 of file core_feature_plic.h.
PLIC_DisableInterrupt
#define PLIC_DisableInterrupt (source) PLIC_DisableContextInterrupt(PLIC_GetHartMContextID(), (source))
Definition at line 380 of file core_feature_plic.h.
PLIC_DisableInterrupt_S
#define PLIC_DisableInterrupt_S (source) PLIC_DisableContextInterrupt(PLIC_GetHartSContextID(), (source))
Definition at line 381 of file core_feature_plic.h.
PLIC_EnableInterrupt
#define PLIC_EnableInterrupt (source) PLIC_EnableContextInterrupt(PLIC_GetHartMContextID(), (source))
Definition at line 377 of file core_feature_plic.h.
PLIC_EnableInterrupt_S
#define PLIC_EnableInterrupt_S (source) PLIC_EnableContextInterrupt(PLIC_GetHartSContextID(), (source))
Definition at line 378 of file core_feature_plic.h.
PLIC_GetInterruptEnable
#define PLIC_GetInterruptEnable (source) PLIC_GetContextInterruptEnable(PLIC_GetHartMContextID(), (source))
Definition at line 374 of file core_feature_plic.h.
PLIC_GetInterruptEnable_S
#define PLIC_GetInterruptEnable_S (source) PLIC_GetContextInterruptEnable(PLIC_GetHartSContextID(), (source))
Definition at line 375 of file core_feature_plic.h.
PLIC_GetThreshold
#define PLIC_GetThreshold () PLIC_GetContextThreshold(PLIC_GetHartMContextID())
Definition at line 386 of file core_feature_plic.h.
PLIC_GetThreshold_S
#define PLIC_GetThreshold_S () PLIC_GetContextThreshold(PLIC_GetHartSContextID())
Definition at line 387 of file core_feature_plic.h.
PLIC_Init
#define PLIC_Init (num_sources, enable, thresh) PLIC_Context_Init(PLIC_GetHartMContextID(), (num_sources), (enable), (thresh))
Definition at line 365 of file core_feature_plic.h.
PLIC_Init_S
#define PLIC_Init_S (num_sources, enable, thresh) PLIC_Context_Init(PLIC_GetHartSContextID(), (num_sources), (enable), (thresh))
Definition at line 366 of file core_feature_plic.h.
PLIC_SetThreshold
#define PLIC_SetThreshold (source, thresh) PLIC_SetContextThreshold(PLIC_GetHartMContextID(), (source), (thresh))
Definition at line 383 of file core_feature_plic.h.
PLIC_SetThreshold_S
#define PLIC_SetThreshold_S (source, thresh) PLIC_SetContextThreshold(PLIC_GetHartSContextID(), (source), (thresh))
Definition at line 384 of file core_feature_plic.h.
Function Documentation
__get_trap_entry()
__STATIC_FORCEINLINE rv_csr_t __get_trap_entry (void)
Get trap entry address.
This function get trap entry address from 'CSR_MTVEC'.
Returns
trap entry address
Remarks
This function use to get trap entry address from 'CSR_MTVEC'.
See also
__set_trap_entry
Definition at line 415 of file core_feature_plic.h.
 {
     unsigned long addr = __RV_CSR_READ(CSR_MTVEC);
     return (addr);
 }
References __RV_CSR_READ, and CSR_MTVEC.
__set_trap_entry()
__STATIC_FORCEINLINE void __set_trap_entry (rv_csr_t addr)
Set Trap entry address.
This function set trap entry address to 'CSR_MTVEC'.
Parameters
[in] addr trap entry address
Remarks
This function use to set trap entry address to 'CSR_MTVEC'.
See also
__get_trap_entry
Definition at line 399 of file core_feature_plic.h.
 {
     addr &= (rv_csr_t)(~0x7);
     __RV_CSR_WRITE(CSR_MTVEC, addr);
 }
References __RV_CSR_WRITE, and CSR_MTVEC.
PLIC_ClaimContextInterrupt()
__STATIC_FORCEINLINE uint32_t PLIC_ClaimContextInterrupt (uint32_t ctxid)
Claim interrupt for plic for selected context.
This function claim interrupt for plic for selected context.
Parameters
[in] ctxid selected context id
Returns
the ID of the highest priority pending interrupt or zero if there is no pending interrupt
Remarks
A successful claim will also atomically clear the corresponding pending bit on the interrupt source. The PLIC can perform a claim at any time and the claim operation is not affected by the setting of the priority threshold register.
See also
PLIC_CompleteContextInterrupt
Definition at line 308 of file core_feature_plic.h.
 {
     volatile uint32_t *claim_reg = (uint32_t *)PLIC_CLAIM_REGADDR(ctxid);
     return (*claim_reg);
 }
References PLIC_CLAIM_REGADDR.
PLIC_ClearInterruptPending()
__STATIC_FORCEINLINE void PLIC_ClearInterruptPending (uint32_t source)
Clear interrupt pending of selected source plic.
This function clear interrupt pending of selected source plic
Parameters
[in] source interrupt source
Remarks
See also
PLIC_SetInterruptPending
PLIC_GetInterruptPending
Definition at line 231 of file core_feature_plic.h.
 {
     volatile uint32_t *pending_reg = (uint32_t *)PLIC_PENDING_REGADDR(source);
     uint32_t current = *pending_reg;
     current = current & (~(1 << (source & 0x1F)));
     *pending_reg = current;
 }
References PLIC_PENDING_REGADDR.
PLIC_CompleteContextInterrupt()
__STATIC_FORCEINLINE void PLIC_CompleteContextInterrupt (uint32_t ctxid, uint32_t source)
Complete interrupt for plic for selected context.
This function complete interrupt for plic for selected context.
Parameters
[in] ctxid selected context id
Returns
the ID of the highest priority pending interrupt or zero if there is no pending interrupt
Remarks
The PLIC signals it has completed executing an interrupt handler by writing the interrupt ID it received from the claim to the claim/complete register. The PLIC does not check whether the completion ID is the same as the last claim ID for that context. If the completion ID does not match an interrupt source that is currently enabled for the context, the completion is silently ignored.
See also
PLIC_ClaimContextInterrupt
Definition at line 332 of file core_feature_plic.h.
 {
     volatile uint32_t *complete_reg = (uint32_t *)PLIC_COMPLETE_REGADDR(ctxid);
     *complete_reg = source;
 }
References PLIC_COMPLETE_REGADDR.
PLIC_Context_Init()
__STATIC_FORCEINLINE void PLIC_Context_Init (uint32_t ctxid, uint32_t num_sources, uint32_t enable, uint32_t thresh)
Perform init for plic for selected context.
This function perform initialization steps for plic for selected context.
Parameters
[in] ctxid selected context id
[in] num_sources plic interrupt source count number
[in] enable plic interrupt enable or not
[in] thresh plic interrupt threshold
Remarks
Disable all interrupts
Set priority threshold to value specified by thresh
Definition at line 351 of file core_feature_plic.h.
 {
     uint32_t i;
     for (i = 0; i < num_sources; i ++) {
         if (enable) {
             PLIC_EnableContextInterrupt(ctxid, i);
         } else {
             PLIC_DisableContextInterrupt(ctxid, i);
         }
     }
     PLIC_SetContextThreshold(ctxid, thresh);
 }
References PLIC_DisableContextInterrupt(), PLIC_EnableContextInterrupt(), and PLIC_SetContextThreshold().
PLIC_DisableContextInterrupt()
__STATIC_FORCEINLINE void PLIC_DisableContextInterrupt (uint32_t ctxid, uint32_t source)
Disable interrupt of selected source plic for selected context.
This function disable interrupt of selected source plic for selected context
Parameters
[in] ctxid selected context id
[in] source interrupt source
Remarks
See also
PLIC_EnableContextInterrupt
Definition at line 172 of file core_feature_plic.h.
 {
     volatile uint32_t *enable_reg = (uint32_t *)PLIC_ENABLE_REGADDR(ctxid, source);
     uint32_t current = *enable_reg;
     current = current & (~(1 << (source & 0x1F)));
     *enable_reg = current;
 }
References PLIC_ENABLE_REGADDR.
Referenced by PLIC_Context_Init().
PLIC_EnableContextInterrupt()
__STATIC_FORCEINLINE void PLIC_EnableContextInterrupt (uint32_t ctxid, uint32_t source)
Enable interrupt of selected source plic for selected context.
This function enable interrupt of selected source plic for selected context.
Parameters
[in] ctxid selected context id
[in] source interrupt source
Remarks
See also
PLIC_DisableContextInterrupt
Definition at line 153 of file core_feature_plic.h.
 {
     volatile uint32_t *enable_reg = (uint32_t *)PLIC_ENABLE_REGADDR(ctxid, source);
     uint32_t current = *enable_reg;
     current = current | (1 << (source & 0x1F));
     *enable_reg = current;
 }
References PLIC_ENABLE_REGADDR.
Referenced by PLIC_Context_Init().
PLIC_GetContextInterruptEnable()
__STATIC_FORCEINLINE uint32_t PLIC_GetContextInterruptEnable (uint32_t ctxid, uint32_t source)
Get interrupt enable status of selected source plic for selected context.
This function get interrupt enable of selected source plic for selected context.
Parameters
[in] ctxid selected context id
[in] source interrupt source
Returns
enable status for selected interrupt source for selected context
Remarks
See also
PLIC_EnableContextInterrupt
PLIC_DisableContextInterrupt
Definition at line 193 of file core_feature_plic.h.
 {
     volatile uint32_t *enable_reg = (uint32_t *)PLIC_ENABLE_REGADDR(ctxid, source);
     uint32_t current = *enable_reg;
     current = (current >> (source & 0x1F)) & 0x1;
     return current;
 }
References PLIC_ENABLE_REGADDR.
PLIC_GetContextThreshold()
__STATIC_FORCEINLINE uint32_t PLIC_GetContextThreshold (uint32_t ctxid)
Get priority threshold value of plic for selected context.
This function get priority threshold value of plic for selected context.
Parameters
[in] ctxid selected context id
Returns
priority threshold value for selected context
Remarks
See also
PLIC_SetContextThreshold
Definition at line 136 of file core_feature_plic.h.
 {
     volatile uint32_t *thresh_reg = (uint32_t *)PLIC_THRESHOLD_REGADDR(ctxid);
     return (*thresh_reg);
 }
References PLIC_THRESHOLD_REGADDR.
PLIC_GetInterruptPending()
__STATIC_FORCEINLINE uint32_t PLIC_GetInterruptPending (uint32_t source)
Get interrupt pending status of selected source plic.
This function get interrupt pending of selected source plic
Parameters
[in] source interrupt source
Returns
interrupt pending status for selected interrupt source
Remarks
See also
PLIC_SetInterruptPending
PLIC_ClearInterruptPending
Definition at line 251 of file core_feature_plic.h.
 {
     volatile uint32_t *pending_reg = (uint32_t *)PLIC_PENDING_REGADDR(source);
     uint32_t current = *pending_reg;
     current = (current >> (source & 0x1F)) & 0x1;
     return current;
 }
References PLIC_PENDING_REGADDR.
PLIC_GetPriority()
__STATIC_FORCEINLINE uint32_t PLIC_GetPriority (uint32_t source)
Get interrupt priority for selected source plic.
This function get interrupt priority for selected source plic.
Parameters
[in] source interrupt source
[in] priority interrupt priority
Remarks
See also
PLIC_SetPriority
Definition at line 287 of file core_feature_plic.h.
 {
     volatile uint32_t *priority_reg = (uint32_t *)PLIC_PRIORITY_REGADDR(source);
     return (*priority_reg);
 }
References PLIC_PRIORITY_REGADDR.
PLIC_SetContextThreshold()
__STATIC_FORCEINLINE void PLIC_SetContextThreshold (uint32_t ctxid, uint32_t thresh)
Set priority threshold value of plic for selected context.
This function set priority threshold value of plic for selected context.
Parameters
[in] ctxid selected context id
[in] thresh threshold value
Remarks
See also
PLIC_GetContextThreshold
Definition at line 119 of file core_feature_plic.h.
 {
     volatile uint32_t *thresh_reg = (uint32_t *)PLIC_THRESHOLD_REGADDR(ctxid);
     *thresh_reg = thresh;
 }
References PLIC_THRESHOLD_REGADDR.
Referenced by PLIC_Context_Init().
PLIC_SetInterruptPending()
__STATIC_FORCEINLINE void PLIC_SetInterruptPending (uint32_t source)
Set interrupt pending of selected source plic.
This function set interrupt pending of selected source plic.
Parameters
[in] source interrupt source
Remarks
See also
PLIC_GetInterruptPending
PLIC_CLearInterruptPending
Definition at line 212 of file core_feature_plic.h.
 {
     volatile uint32_t *pending_reg = (uint32_t *)PLIC_PENDING_REGADDR(source);
     uint32_t current = *pending_reg;
     current = current | (1 << (source & 0x1F));
     *pending_reg = current;
 }
References PLIC_PENDING_REGADDR.
PLIC_SetPriority()
__STATIC_FORCEINLINE void PLIC_SetPriority (uint32_t source, uint32_t priority)
Set interrupt priority for selected source plic.
This function set interrupt priority for selected source plic.
Parameters
[in] source interrupt source
[in] priority interrupt priority
Remarks
See also
PLIC_GetPriority
Definition at line 270 of file core_feature_plic.h.
 {
     volatile uint32_t *priority_reg = (uint32_t *)PLIC_PRIORITY_REGADDR(source);
     *priority_reg = priority;
 }
References PLIC_PRIORITY_REGADDR.
Referenced by PLIC_Register_IRQ(), and PLIC_Register_IRQ_S().