NMSIS-Core: SysTimer Functions
SysTimer Functions
Functions that configure the Core System Timer.
Macros
#define SysTimer_GetHartID() (__get_hart_index())
SysTimer_GetHartID() is used to get timer hartid which might not be the same as cpu hart id, for example, cpu hartid may be 1, but timer hartid may be 0, then timer hartid offset is 1.
#define SysTimer_GetHartID_S() (__get_hart_index_s())
Functions
__STATIC_INLINE void SysTimer_SetLoadValue (rv_counter_t value)
Set system timer load value.
__STATIC_INLINE rv_counter_t SysTimer_GetLoadValue (void)
Get system timer load value.
__STATIC_INLINE void SysTimer_SetHartCompareValue (rv_counter_t value, unsigned long hartid)
Set system timer compare value by hartid.
__STATIC_FORCEINLINE void SysTimer_SetCompareValue (rv_counter_t value)
Set system timer compare value in machine mode.
__STATIC_INLINE rv_counter_t SysTimer_GetHartCompareValue (unsigned long hartid)
Get system timer compare value by hartid.
__STATIC_FORCEINLINE rv_counter_t SysTimer_GetCompareValue (void)
Get system timer compare value in machine mode.
__STATIC_FORCEINLINE void SysTimer_Start (void)
Enable system timer counter running.
__STATIC_FORCEINLINE void SysTimer_Stop (void)
Stop system timer counter running.
__STATIC_FORCEINLINE void SysTimer_SetControlValue (uint32_t mctl)
Set system timer control value.
__STATIC_FORCEINLINE uint32_t SysTimer_GetControlValue (void)
Get system timer control value.
__STATIC_FORCEINLINE void SysTimer_SetHartSWIRQ (unsigned long hartid)
Trigger or set software interrupt via system timer by hartid.
__STATIC_FORCEINLINE void SysTimer_SetSWIRQ (void)
Trigger or set software interrupt via system timer in machine mode.
__STATIC_FORCEINLINE void SysTimer_ClearHartSWIRQ (unsigned long hartid)
Clear system timer software interrupt pending request by hartid.
__STATIC_FORCEINLINE void SysTimer_ClearSWIRQ (void)
Clear system timer software interrupt pending request in machine mode.
__STATIC_FORCEINLINE uint32_t SysTimer_GetHartMsipValue (unsigned long hartid)
Get system timer MSIP register value by hartid.
__STATIC_FORCEINLINE uint32_t SysTimer_GetMsipValue (void)
Get system timer MSIP register value in machine mode.
__STATIC_FORCEINLINE void SysTimer_SetHartMsipValue (uint32_t msip, unsigned long hartid)
Set system timer MSIP register value by hartid.
__STATIC_FORCEINLINE void SysTimer_SetMsipValue (uint32_t msip)
Set system timer MSIP register value in machine mode.
__STATIC_INLINE void SysTimer_SetCompareValue_S (uint64_t value)
Set system timer smode compare value.
__STATIC_INLINE uint64_t SysTimer_GetCompareValue_S (void)
Get system timer smode compare value.
__STATIC_FORCEINLINE void SysTimer_SetHartSWIRQ_S (unsigned long hartid)
Trigger or set supervisor mode software interrupt via system timer by hartid.
__STATIC_FORCEINLINE void SysTimer_SetSWIRQ_S (void)
Trigger or set supervisor software interrupt via system timer.
__STATIC_FORCEINLINE void SysTimer_ClearHartSWIRQ_S (unsigned long hartid)
Clear system timer supervisor mode software interrupt pending request by hartid.
__STATIC_FORCEINLINE void SysTimer_ClearSWIRQ_S (void)
Clear system timer supervisor mode software interrupt pending request.
__STATIC_FORCEINLINE uint32_t SysTimer_GetHartSsipValue (unsigned long hartid)
Get system timer SSIP register value by hartid.
__STATIC_FORCEINLINE uint32_t SysTimer_GetSsipValue (void)
Get system timer SSIP register value.
__STATIC_FORCEINLINE void SysTimer_SetHartSsipValue (uint32_t ssip, unsigned long hartid)
Set system timer SSIP register value by hartid.
__STATIC_FORCEINLINE void SysTimer_SetSsipValue (uint32_t ssip)
Set system timer SSIP register value.
__STATIC_FORCEINLINE void SysTimer_SendIPI_S (unsigned long hartid)
send ipi to target hart using Systimer Clint SSIP
__STATIC_FORCEINLINE void SysTimer_ClearIPI_S (unsigned long hartid)
clear ipi to target hart using Systimer Clint SSIP
__STATIC_FORCEINLINE void SysTimer_EnableSSTC (void)
Enable SSTC access right for supervisor mode.
__STATIC_FORCEINLINE void SysTimer_DisableSSTC (void)
Disable SSTC stimecmp csr access right for supervisor mode.
__STATIC_FORCEINLINE void SysTimer_SoftwareReset (void)
Do software reset request.
__STATIC_FORCEINLINE void SysTimer_SendIPI (unsigned long hartid)
send ipi to target hart using Systimer Clint MSIP
__STATIC_FORCEINLINE void SysTimer_ClearIPI (unsigned long hartid)
clear ipi to target hart using Systimer Clint MSIP
__STATIC_FORCEINLINE void SysTimer_EnableSAccess (void)
Enable supervisor mode systimer register read/write access right.
__STATIC_FORCEINLINE void SysTimer_DisableSAccess (void)
Disable supervisor mode systimer register read/write access right.
__STATIC_INLINE uint32_t SysTick_Config (rv_counter_t ticks)
System Tick Configuration.
__STATIC_INLINE uint32_t SysTick_HartConfig (rv_counter_t ticks, unsigned long hartid)
System Tick Configuration By hartid.
__STATIC_INLINE uint32_t SysTick_Reload (rv_counter_t ticks)
System Tick Reload.
__STATIC_INLINE uint32_t SysTick_HartReload (rv_counter_t ticks, unsigned long hartid)
System Tick Reload By hartid.
__STATIC_INLINE uint32_t SysTick_Config_S (rv_counter_t ticks)
System Tick Configuration in supervisor mode.
__STATIC_INLINE uint32_t SysTick_Reload_S (rv_counter_t ticks)
System Tick Reload in supervisor mode.
Detailed Description
Functions that configure the Core System Timer.
Macro Definition Documentation
SysTimer_GetHartID
#define SysTimer_GetHartID () (__get_hart_index())
SysTimer_GetHartID() is used to get timer hartid which might not be the same as cpu hart id, for example, cpu hartid may be 1, but timer hartid may be 0, then timer hartid offset is 1.
If defined __SYSTIMER_HARTID, it will use __SYSTIMER_HARTID as timer hartid, otherwise, it will use __get_hart_index(). The cpu hartid is get by using __get_hart_id function
Definition at line 143 of file core_feature_timer.h.
SysTimer_GetHartID_S
#define SysTimer_GetHartID_S () (__get_hart_index_s())
Definition at line 150 of file core_feature_timer.h.
Function Documentation
SysTick_Config()
__STATIC_INLINE uint32_t SysTick_Config (rv_counter_t ticks)
System Tick Configuration.
Initializes the System Timer and its non-vector interrupt, and starts the System Tick Timer.
In our default implementation, the timer counter will be set to zero, and it will start a timer compare non-vector interrupt when it matchs the ticks user set, during the timer interrupt user should reload the system tick using SysTick_Reload function or similar function written by user, so it can produce period timer interrupt.
Parameters
[in] ticks Number of ticks between two interrupts.
Returns
0 Function succeeded.
1 Function failed.
Remarks
For __NUCLEI_N_REV >= 0x0104, the CMPCLREN bit in MTIMECTL is introduced, but we assume that the CMPCLREN bit is set to 0, so MTIMER register will not be auto cleared to 0 when MTIMER >= MTIMERCMP.
When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included.
In this case, the file <Device>.h must contain a vendor-specific implementation of this function.
If user need this function to start a period timer interrupt, then in timer interrupt handler routine code, user should call SysTick_Reload with ticks to reload the timer.
This function only available when __SYSTIMER_PRESENT == 1 and __ECLIC_PRESENT == 1 and __Vendor_SysTickConfig == 0
See also
SysTimer_SetCompareValue; SysTimer_SetLoadValue
Definition at line 906 of file core_feature_timer.h.
 {
     rv_counter_t loadticks = SysTimer_GetLoadValue();
     SysTimer_SetCompareValue(ticks + loadticks);
 #if defined(__ECLIC_PRESENT) && (__ECLIC_PRESENT == 1)
     ECLIC_SetShvIRQ(SysTimer_IRQn, ECLIC_NON_VECTOR_INTERRUPT);
     ECLIC_SetLevelIRQ(SysTimer_IRQn, 0);
     ECLIC_EnableIRQ(SysTimer_IRQn);
 #endif
     return (0UL);
 }
References ECLIC_EnableIRQ, ECLIC_NON_VECTOR_INTERRUPT, ECLIC_SetLevelIRQ, ECLIC_SetShvIRQ, SysTimer_GetLoadValue(), SysTimer_IRQn, and SysTimer_SetCompareValue().
SysTick_Config_S()
__STATIC_INLINE uint32_t SysTick_Config_S (rv_counter_t ticks)
System Tick Configuration in supervisor mode.
Initializes the system timer supervisor mode interrupt and registered as non-vector interrupt
The smode timecmp csr register will be set to proper value according to the ticks passed when it matchs the ticks user set, during the smode timer interrupt user should reload the system tick using SysTick_Reload_S function or similar function written by user, so it can produce period smode timer interrupt.
Parameters
[in] ticks Number of ticks between two interrupts.
Returns
0 Function succeeded.
Definition at line 1039 of file core_feature_timer.h.
 {
     rv_counter_t loadticks = __get_rv_time();
     SysTimer_SetCompareValue_S(ticks + loadticks);
 #if defined(__ECLIC_PRESENT) && (__ECLIC_PRESENT == 1)
 #if defined(__SMODE_PRESENT) && (__SMODE_PRESENT == 1)
     ECLIC_SetShvIRQ_S(SysTimer_S_IRQn, ECLIC_NON_VECTOR_INTERRUPT);
     ECLIC_SetLevelIRQ_S(SysTimer_S_IRQn, 0);
     ECLIC_EnableIRQ_S(SysTimer_S_IRQn);
 #endif
 #endif
     return (0UL);
 }
References __get_rv_time(), ECLIC_EnableIRQ_S, ECLIC_NON_VECTOR_INTERRUPT, ECLIC_SetLevelIRQ_S, ECLIC_SetShvIRQ_S, and SysTimer_SetCompareValue_S().
SysTick_HartConfig()
__STATIC_INLINE uint32_t SysTick_HartConfig (rv_counter_t ticks, unsigned long hartid)
System Tick Configuration By hartid.
Initializes the System Timer and its non-vector interrupt, and starts the System Tick Timer.
In our default implementation, the timer counter will be set to zero, and it will start a timer compare non-vector interrupt when it matchs the ticks user set, during the timer interrupt user should reload the system tick using SysTick_Reload function or similar function written by user, so it can produce period timer interrupt.
Parameters
[in] ticks Number of ticks between two interrupts.
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Returns
0 Function succeeded.
1 Function failed.
Remarks
For __NUCLEI_N_REV >= 0x0104, the CMPCLREN bit in MTIMECTL is introduced, but we assume that the CMPCLREN bit is set to 0, so MTIMER register will not be auto cleared to 0 when MTIMER >= MTIMERCMP.
When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included.
In this case, the file <Device>.h must contain a vendor-specific implementation of this function.
If user need this function to start a period timer interrupt, then in timer interrupt handler routine code, user should call SysTick_Reload with ticks to reload the timer.
This function only available __Vendor_SysTickConfig == 0
When ECLIC present, it will set eclic timer interrupt as non-vector mode, and level configured to 0, and enable it
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
See also
SysTimer_SetCompareValue; SysTimer_SetLoadValue
Definition at line 946 of file core_feature_timer.h.
 {
     rv_counter_t loadticks = SysTimer_GetLoadValue();
     SysTimer_SetHartCompareValue(ticks + loadticks, hartid);
 #if defined(__ECLIC_PRESENT) && (__ECLIC_PRESENT == 1)
     ECLIC_SetShvIRQ(SysTimer_IRQn, ECLIC_NON_VECTOR_INTERRUPT);
     ECLIC_SetLevelIRQ(SysTimer_IRQn, 0);
     ECLIC_EnableIRQ(SysTimer_IRQn);
 #endif
     return (0UL);
 }
References ECLIC_EnableIRQ, ECLIC_NON_VECTOR_INTERRUPT, ECLIC_SetLevelIRQ, ECLIC_SetShvIRQ, SysTimer_GetLoadValue(), SysTimer_IRQn, and SysTimer_SetHartCompareValue().
SysTick_HartReload()
__STATIC_INLINE uint32_t SysTick_HartReload (rv_counter_t ticks, unsigned long hartid)
System Tick Reload By hartid.
Reload the System Timer Tick when the MTIMECMP reached TIME value
Parameters
[in] ticks Number of ticks between two interrupts.
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Returns
0 Function succeeded.
1 Function failed.
Remarks
For __NUCLEI_N_REV >= 0x0104, the CMPCLREN bit in MTIMECTL is introduced, but for this SysTick_Config function, we assume this CMPCLREN bit is set to 0, so in interrupt handler function, user still need to set the MTIMERCMP or MTIMER to reload the system tick, if vendor want to use this timer's auto clear feature, they can define __Vendor_SysTickConfig to 1, and implement SysTick_Config and SysTick_Reload functions.
When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Reload is not included.
In this case, the file <Device>.h must contain a vendor-specific implementation of this function.
This function only available when __SYSTIMER_PRESENT == 1 and __ECLIC_PRESENT == 1 and __Vendor_SysTickConfig == 0
Since the MTIMERCMP value might overflow, if overflowed, MTIMER will be set to 0, and MTIMERCMP set to ticks
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
See also
SysTimer_SetCompareValue
SysTimer_SetLoadValue
Definition at line 1018 of file core_feature_timer.h.
 {
     rv_counter_t cur_ticks = SysTimer_GetLoadValue();
     rv_counter_t reload_ticks = ticks + cur_ticks;
     SysTimer_SetHartCompareValue(reload_ticks, hartid);
     return (0UL);
 }
References SysTimer_GetLoadValue(), and SysTimer_SetHartCompareValue().
SysTick_Reload()
__STATIC_INLINE uint32_t SysTick_Reload (rv_counter_t ticks)
System Tick Reload.
Reload the System Timer Tick when the MTIMECMP reached TIME value
Parameters
[in] ticks Number of ticks between two interrupts.
Returns
0 Function succeeded.
1 Function failed.
Remarks
For __NUCLEI_N_REV >= 0x0104, the CMPCLREN bit in MTIMECTL is introduced, but for this SysTick_Config function, we assume this CMPCLREN bit is set to 0, so in interrupt handler function, user still need to set the MTIMERCMP or MTIMER to reload the system tick, if vendor want to use this timer's auto clear feature, they can define __Vendor_SysTickConfig to 1, and implement SysTick_Config and SysTick_Reload functions.
When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Reload is not included.
In this case, the file <Device>.h must contain a vendor-specific implementation of this function.
This function only available when __SYSTIMER_PRESENT == 1
Since the MTIMERCMP value might overflow, if overflowed, MTIMER will be set to 0, and MTIMERCMP set to ticks
See also
SysTimer_SetCompareValue
SysTimer_SetLoadValue
Definition at line 982 of file core_feature_timer.h.
 {
     rv_counter_t cur_ticks = SysTimer_GetLoadValue();
     rv_counter_t reload_ticks = ticks + cur_ticks;
     SysTimer_SetCompareValue(reload_ticks);
     return (0UL);
 }
References SysTimer_GetLoadValue(), and SysTimer_SetCompareValue().
SysTick_Reload_S()
__STATIC_INLINE uint32_t SysTick_Reload_S (rv_counter_t ticks)
System Tick Reload in supervisor mode.
Reload the System Timer Tick when the STIMECMP CSR reached TIME value
Parameters
[in] ticks Number of ticks between two interrupts.
Returns
0 Function succeeded.
1 Function failed.
Definition at line 1062 of file core_feature_timer.h.
 {
     rv_counter_t cur_ticks = __get_rv_time();
     rv_counter_t reload_ticks = ticks + cur_ticks;
     SysTimer_SetCompareValue_S(reload_ticks);
     return (0UL);
 }
References __get_rv_time(), and SysTimer_SetCompareValue_S().
SysTimer_ClearHartSWIRQ()
__STATIC_FORCEINLINE void SysTimer_ClearHartSWIRQ (unsigned long hartid)
Clear system timer software interrupt pending request by hartid.
This function clear the system timer MSIP bit in MSIP register.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
Clear system timer MSIP bit in MSIP register to clear the software interrupt pending.
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
SysTimer_SetHartSWIRQ
SysTimer_GetHartMsipValue
Definition at line 436 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP &= ~SysTimer_MSIP_MSIP_Msk;
 #else
     if (hartid == 0) {
         SysTimer->MSIP &= ~SysTimer_MSIP_MSIP_Msk;
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
         __SW(addr, 0);
     }
 #endif
 }
References __SW(), SysTimer, SysTimer_CLINT_MSIP_BASE, and SysTimer_MSIP_MSIP_Msk.
Referenced by SysTimer_ClearSWIRQ().
SysTimer_ClearHartSWIRQ_S()
__STATIC_FORCEINLINE void SysTimer_ClearHartSWIRQ_S (unsigned long hartid)
Clear system timer supervisor mode software interrupt pending request by hartid.
This function clear the system timer SSIP bit in SSIP register.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
Clear system timer SSIP bit in SSIP register to clear the supervisor mode software interrupt pending.
SysTimer_SetHartSWIRQ_S
SysTimer_GetHartSsipValue
Definition at line 653 of file core_feature_timer.h.
 {
     if (hartid == 0) {
         SysTimer->SSIP &= ~SysTimer_SSIP_SSIP_Msk;
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
         __SW(addr, 0);
     }
 }
References __SW(), SysTimer, SysTimer_CLINT_SSIP_BASE, and SysTimer_SSIP_SSIP_Msk.
Referenced by SysTimer_ClearSWIRQ_S().
SysTimer_ClearIPI()
__STATIC_FORCEINLINE void SysTimer_ClearIPI (unsigned long hartid)
clear ipi to target hart using Systimer Clint MSIP
This function clear ipi using clint timer's MSIP register.
Parameters
[in] hart target hart
Definition at line 848 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP = 0;
 #else
     uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
     __SW(addr, 0);
 #endif
 }
References __SW(), SysTimer, and SysTimer_CLINT_MSIP_BASE.
SysTimer_ClearIPI_S()
__STATIC_FORCEINLINE void SysTimer_ClearIPI_S (unsigned long hartid)
clear ipi to target hart using Systimer Clint SSIP
This function clear ipi using clint timer's SSIP register.
Parameters
[in] hart target hart
Definition at line 769 of file core_feature_timer.h.
 {
     uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
     __SW(addr, 0);
 }
References __SW(), and SysTimer_CLINT_SSIP_BASE.
SysTimer_ClearSWIRQ()
__STATIC_FORCEINLINE void SysTimer_ClearSWIRQ (void)
Clear system timer software interrupt pending request in machine mode.
This function clear the system timer MSIP bit in MSIP register.
Remarks
Clear system timer MSIP bit in MSIP register to clear the software interrupt pending.
SysTimer_SetSWIRQ
SysTimer_GetMsipValue
Definition at line 459 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP &= ~SysTimer_MSIP_MSIP_Msk;
 #else
     unsigned long hartid = SysTimer_GetHartID();
     SysTimer_ClearHartSWIRQ(hartid);
 #endif
 }
References SysTimer, SysTimer_ClearHartSWIRQ(), SysTimer_GetHartID, and SysTimer_MSIP_MSIP_Msk.
SysTimer_ClearSWIRQ_S()
__STATIC_FORCEINLINE void SysTimer_ClearSWIRQ_S (void)
Clear system timer supervisor mode software interrupt pending request.
This function clear the system timer SSIP bit in SSIP register.
Remarks
Clear system timer SSIP bit in SSIP register to clear the supervisor mode software interrupt pending.
SysTimer_SetSWIRQ_S
SysTimer_GetSsipValue
Definition at line 672 of file core_feature_timer.h.
 {
     unsigned long hartid = SysTimer_GetHartID_S();
     SysTimer_ClearHartSWIRQ_S(hartid);
 }
References SysTimer_ClearHartSWIRQ_S(), and SysTimer_GetHartID_S.
SysTimer_DisableSAccess()
__STATIC_FORCEINLINE void SysTimer_DisableSAccess (void)
Disable supervisor mode systimer register read/write access right.
This will make some systimer registers can not be accessed in supervisor mode.
Attention
This can be only executed in machine mode
Definition at line 875 of file core_feature_timer.h.
 {
     SysTimer->MTIME_SRW_CTRL |= SysTimer_MTIME_SRW_CTRL_SRW_Msk;
 }
References SysTimer, and SysTimer_MTIME_SRW_CTRL_SRW_Msk.
SysTimer_DisableSSTC()
__STATIC_FORCEINLINE void SysTimer_DisableSSTC (void)
Disable SSTC stimecmp csr access right for supervisor mode.
This will disable SSTC stimecmp(h) csr register read/write access right in supervisor mode and make time(h) csr can not be read
Definition at line 798 of file core_feature_timer.h.
 {
     __RV_CSR_CLEAR(CSR_MCOUNTEREN, MCOUNTEREN_TIME);
 #if __RISCV_XLEN == 32
     __RV_CSR_CLEAR(CSR_MENVCFGH, MENVCFGH_STCE);
 #else
     __RV_CSR_CLEAR(CSR_MENVCFG, MENVCFG_STCE);
 #endif
 }
References __RV_CSR_CLEAR, CSR_MCOUNTEREN, CSR_MENVCFG, CSR_MENVCFGH, MCOUNTEREN_TIME, MENVCFG_STCE, and MENVCFGH_STCE.
SysTimer_EnableSAccess()
__STATIC_FORCEINLINE void SysTimer_EnableSAccess (void)
Enable supervisor mode systimer register read/write access right.
This will make some systimer registers can be accessed in supervisor mode, which is reset state.
Attention
This can be only executed in machine mode
Definition at line 864 of file core_feature_timer.h.
 {
     SysTimer->MTIME_SRW_CTRL &= ~SysTimer_MTIME_SRW_CTRL_SRW_Msk;
 }
References SysTimer, and SysTimer_MTIME_SRW_CTRL_SRW_Msk.
SysTimer_EnableSSTC()
__STATIC_FORCEINLINE void SysTimer_EnableSSTC (void)
Enable SSTC access right for supervisor mode.
This will enable SSTC stimecmp(h) csr register read/write access right in supervisor mode and make time(h) csr can be read
Attention
This can be only executed in machine mode
Definition at line 782 of file core_feature_timer.h.
 {
     __RV_CSR_SET(CSR_MCOUNTEREN, MCOUNTEREN_TIME);
 #if __RISCV_XLEN == 32
     __RV_CSR_SET(CSR_MENVCFGH, MENVCFGH_STCE);
 #else
     __RV_CSR_SET(CSR_MENVCFG, MENVCFG_STCE);
 #endif
 }
References __RV_CSR_SET, CSR_MCOUNTEREN, CSR_MENVCFG, CSR_MENVCFGH, MCOUNTEREN_TIME, MENVCFG_STCE, and MENVCFGH_STCE.
SysTimer_GetCompareValue()
__STATIC_FORCEINLINE rv_counter_t SysTimer_GetCompareValue (void)
Get system timer compare value in machine mode.
This function get the system timer compare value in MTIMERCMP register.
Returns
compare value of system timer MTIMERCMP register.
Remarks
Compare value is 64bits wide.
SysTimer_SetCompareValue
Definition at line 317 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     return SysTimer->MTIMERCMP;
 #else
     unsigned long hartid = SysTimer_GetHartID();
     return SysTimer_GetHartCompareValue(hartid);
 #endif
 }
References SysTimer, SysTimer_GetHartCompareValue(), and SysTimer_GetHartID.
SysTimer_GetCompareValue_S()
__STATIC_INLINE uint64_t SysTimer_GetCompareValue_S (void)
Get system timer smode compare value.
This function get the system timer smode compare value in STIMERCMP and STIMECMPH CSR register.
Returns
compare value of system timer smode compare csr register in 64bit.
Remarks
Compare value is 64bits wide.
SysTimer_SetCompareValue_S
Definition at line 593 of file core_feature_timer.h.
 {
     uint64_t full;
 #if __RISCV_XLEN == 32
     uint32_t high, low;
     high = __RV_CSR_READ(CSR_STIMECMPH);
     low = __RV_CSR_READ(CSR_STIMECMP);
     full = (((uint64_t)high) << 32) | low;
 #else
     full = __RV_CSR_READ(CSR_STIMECMP);
 #endif
     return full;
 }
References __RV_CSR_READ, CSR_STIMECMP, and CSR_STIMECMPH.
SysTimer_GetControlValue()
__STATIC_FORCEINLINE uint32_t SysTimer_GetControlValue (void)
Get system timer control value.
This function get the system timer MTIMECTL register value.
Returns
MTIMECTL register value
Remarks
SysTimer_SetControlValue
Definition at line 376 of file core_feature_timer.h.
 {
     return (SysTimer->MTIMECTL & SysTimer_MTIMECTL_Msk);
 }
References SysTimer, and SysTimer_MTIMECTL_Msk.
SysTimer_GetHartCompareValue()
__STATIC_INLINE rv_counter_t SysTimer_GetHartCompareValue (unsigned long hartid)
Get system timer compare value by hartid.
This function get the system timer compare value in MTIMERCMP register.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Returns
compare value of system timer MTIMERCMP register.
Remarks
Compare value is 64bits wide.
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
SysTimer_SetHartCompareValue
Definition at line 283 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     return SysTimer->MTIMERCMP;
 #else
     if (hartid == 0) {
         return SysTimer->MTIMERCMP;
     } else {
         uint64_t full;
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MTIMECMP_BASE(hartid));
 #if __RISCV_XLEN == 32
         // MTIMECMP didn't increase
         uint32_t high, low;
         high = __LW(addr + 4);
         low = __LW(addr);
         full = (((uint64_t)high) << 32) | low;
 #else
         full = __LD(addr);
 #endif
         return full;
     }
 #endif
 }
References __LW(), SysTimer, and SysTimer_CLINT_MTIMECMP_BASE.
Referenced by SysTimer_GetCompareValue().
SysTimer_GetHartMsipValue()
__STATIC_FORCEINLINE uint32_t SysTimer_GetHartMsipValue (unsigned long hartid)
Get system timer MSIP register value by hartid.
This function get the system timer MSIP register value.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Returns
Value of Timer MSIP register.
Remarks
Bit0 is SW interrupt flag. Bit0 is 1 then SW interrupt set. Bit0 is 0 then SW interrupt clear.
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
SysTimer_SetHartSWIRQ
SysTimer_ClearHartSWIRQ
SysTimer_SetHartMsipValue
Definition at line 483 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     return (uint32_t)(SysTimer->MSIP);
 #else
     if (hartid == 0) {
         return (uint32_t)(SysTimer->MSIP);
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
         return __LW(addr);
     }
 #endif
 }
References __LW(), SysTimer, and SysTimer_CLINT_MSIP_BASE.
Referenced by SysTimer_GetMsipValue().
SysTimer_GetHartSsipValue()
__STATIC_FORCEINLINE uint32_t SysTimer_GetHartSsipValue (unsigned long hartid)
Get system timer SSIP register value by hartid.
This function get the system timer SSIP register value.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Returns
Value of Timer SSIP register.
Remarks
Bit0 is SW interrupt flag. Bit0 is 1 then SW interrupt set. Bit0 is 0 then SW interrupt clear.
SysTimer_SetHartSWIRQ_S
SysTimer_ClearHartSWIRQ_S
SysTimer_SetHartSsipValue
Definition at line 691 of file core_feature_timer.h.
 {
     if (hartid == 0) {
         return (uint32_t)(SysTimer->SSIP);
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
         return __LW(addr);
     }
 }
References __LW(), SysTimer, and SysTimer_CLINT_SSIP_BASE.
Referenced by SysTimer_GetSsipValue().
SysTimer_GetLoadValue()
__STATIC_INLINE rv_counter_t SysTimer_GetLoadValue (void)
Get system timer load value.
This function get the system timer current value in MTIMER register.
Returns
current value(64bit) of system timer MTIMER register.
Remarks
Load value is 64bits wide.
SysTimer_SetLoadValue
Definition at line 187 of file core_feature_timer.h.
 {
 #if (__RISCV_XLEN == 32) && !(defined(CPU_SERIES) && CPU_SERIES == 100)
     volatile uint32_t high0, low, high;
     uint64_t full;
     uint8_t *addr;
     addr = (uint8_t *)(&(SysTimer->MTIMER));
     high0 = __LW(addr + 4);
     low = __LW(addr);
     high = __LW(addr + 4);
     if (high0 != high) {
         low = __LW(addr);
     }
     full = (((uint64_t)high) << 32) | low;
     return full;
 #else
     return SysTimer->MTIMER;
 #endif
 }
References __LW(), and SysTimer.
Referenced by SysTick_Config(), SysTick_HartConfig(), SysTick_HartReload(), and SysTick_Reload().
SysTimer_GetMsipValue()
__STATIC_FORCEINLINE uint32_t SysTimer_GetMsipValue (void)
Get system timer MSIP register value in machine mode.
This function get the system timer MSIP register value.
Returns
Value of Timer MSIP register.
Remarks
Bit0 is SW interrupt flag. Bit0 is 1 then SW interrupt set. Bit0 is 0 then SW interrupt clear.
SysTimer_SetSWIRQ
SysTimer_ClearSWIRQ
SysTimer_SetMsipValue
Definition at line 509 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     return (uint32_t)(SysTimer->MSIP);
 #else
     unsigned long hartid = SysTimer_GetHartID();
     return SysTimer_GetHartMsipValue(hartid);
 #endif
 }
References SysTimer, SysTimer_GetHartID, and SysTimer_GetHartMsipValue().
SysTimer_GetSsipValue()
__STATIC_FORCEINLINE uint32_t SysTimer_GetSsipValue (void)
Get system timer SSIP register value.
This function get the system timer MSIP register value.
Returns
Value of Timer MSIP register.
Remarks
Bit0 is SW interrupt flag. Bit0 is 1 then SW interrupt set. Bit0 is 0 then SW interrupt clear.
SysTimer_SetSWIRQ_S
SysTimer_ClearSWIRQ_S
SysTimer_SetSsipValue
Definition at line 713 of file core_feature_timer.h.
 {
     unsigned long hartid = SysTimer_GetHartID_S();
     return SysTimer_GetHartSsipValue(hartid);
 }
References SysTimer_GetHartID_S, and SysTimer_GetHartSsipValue().
SysTimer_SendIPI()
__STATIC_FORCEINLINE void SysTimer_SendIPI (unsigned long hartid)
send ipi to target hart using Systimer Clint MSIP
This function send ipi using clint timer's MSIP register.
Parameters
[in] hart target hart
Definition at line 832 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP = 1;
 #else
     uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
     __SW(addr, 1);
 #endif
 }
References __SW(), SysTimer, and SysTimer_CLINT_MSIP_BASE.
SysTimer_SendIPI_S()
__STATIC_FORCEINLINE void SysTimer_SendIPI_S (unsigned long hartid)
send ipi to target hart using Systimer Clint SSIP
This function send ipi using clint timer's sSIP register.
Parameters
[in] hart target hart
Definition at line 757 of file core_feature_timer.h.
 {
     uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
     __SW(addr, 1);
 }
References __SW(), and SysTimer_CLINT_SSIP_BASE.
SysTimer_SetCompareValue()
__STATIC_FORCEINLINE void SysTimer_SetCompareValue (rv_counter_t value)
Set system timer compare value in machine mode.
This function set the system Timer compare value in MTIMERCMP register.
Parameters
[in] value compare value to set system timer MTIMERCMP register.
Remarks
Compare value is 64bits wide.
If compare value is larger than current value timer interrupt generate.
Modify the load value or compare value less to clear the interrupt.
__get_hart_id function can only be accessed in machine mode, or else exception will occur.
SysTimer_GetCompareValue
Definition at line 262 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MTIMERCMP = value;
 #else
     unsigned long hartid = SysTimer_GetHartID();
     SysTimer_SetHartCompareValue(value, hartid);
 #endif
 }
References SysTimer, SysTimer_GetHartID, and SysTimer_SetHartCompareValue().
Referenced by SysTick_Config(), and SysTick_Reload().
SysTimer_SetCompareValue_S()
__STATIC_INLINE void SysTimer_SetCompareValue_S (uint64_t value)
Set system timer smode compare value.
This function set the system timer smode compare value in STIMECMP and STIMECMPH CSR register.
Parameters
[in] value compare value to set system timer smode compare register.
Remarks
smode timer compare regiser required the SSTC extension
smode timer compare value located in stimecmp/stimecmph for rv32 and stimecmp for rv64.
If compare value is larger than current value smode timer interrupt generate.
Modify the load value or compare value less to clear the interrupt.
SysTimer_GetCompareValue_S
Definition at line 573 of file core_feature_timer.h.
 {
 #if __RISCV_XLEN == 32
     __RV_CSR_WRITE(CSR_STIMECMP, -1U);      // prevent load > timecmp
     __RV_CSR_WRITE(CSR_STIMECMPH, (uint32_t)(value >> 32));
     __RV_CSR_WRITE(CSR_STIMECMP, (uint32_t)value);
 #else
     __RV_CSR_WRITE(CSR_STIMECMP, value);
 #endif
 }
References __RV_CSR_WRITE, CSR_STIMECMP, and CSR_STIMECMPH.
Referenced by SysTick_Config_S(), and SysTick_Reload_S().
SysTimer_SetControlValue()
__STATIC_FORCEINLINE void SysTimer_SetControlValue (uint32_t mctl)
Set system timer control value.
This function set the system timer MTIMECTL register value.
Parameters
[in] mctl value to set MTIMECTL register
Remarks
Bit TIMESTOP is used to start and stop timer. Clear TIMESTOP bit to 0 to start timer, otherwise to stop timer.
Bit CMPCLREN is used to enable auto MTIMER clear to zero when MTIMER >= MTIMERCMP. Clear CMPCLREN bit to 0 to stop auto clear MTIMER feature, otherwise to enable it.
Bit CLKSRC is used to select timer clock source. Clear CLKSRC bit to 0 to use mtime_toggle_a, otherwise use core_clk_aon
SysTimer_GetControlValue
Definition at line 363 of file core_feature_timer.h.
 {
     SysTimer->MTIMECTL = (mctl & SysTimer_MTIMECTL_Msk);
 }
References SysTimer, and SysTimer_MTIMECTL_Msk.
SysTimer_SetHartCompareValue()
__STATIC_INLINE void SysTimer_SetHartCompareValue (rv_counter_t value, unsigned long hartid)
Set system timer compare value by hartid.
This function set the system Timer compare value in MTIMERCMP register.
Parameters
[in] value compare value to set system timer MTIMERCMP register.
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
Compare value is 64bits wide.
If compare value is larger than current value timer interrupt generate.
Modify the load value or compare value less to clear the interrupt.
In S-mode, hartid can't be get by using __get_hart_id function, so this api suits S-mode particularly.
SysTimer_GetHartCompareValue
Definition at line 222 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MTIMERCMP = value;
 #else
     if (hartid == 0) {
 #if __RISCV_XLEN == 32
         uint8_t *addr;
         addr = (uint8_t *)(&(SysTimer->MTIMERCMP));
         __SW(addr, -1U);      // prevent load > timecmp
         __SW(addr + 4, (uint32_t)(value >> 32));
         __SW(addr, (uint32_t)(value));
 #else
         SysTimer->MTIMERCMP = value;
 #endif
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MTIMECMP_BASE(hartid));
 #if __RISCV_XLEN == 32
         __SW(addr, -1U);      // prevent load > timecmp
         __SW(addr + 4, (uint32_t)(value >> 32));
         __SW(addr, (uint32_t)value);
 #else
         __SD(addr, value);
 #endif
     }
 #endif
 }
References __SW(), SysTimer, and SysTimer_CLINT_MTIMECMP_BASE.
Referenced by SysTick_HartConfig(), SysTick_HartReload(), and SysTimer_SetCompareValue().
SysTimer_SetHartMsipValue()
__STATIC_FORCEINLINE void SysTimer_SetHartMsipValue (uint32_t msip, unsigned long hartid)
Set system timer MSIP register value by hartid.
This function set the system timer MSIP register value.
Parameters
[in] msip value to set MSIP register
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
In S-mode, hartid can't be get using __get_hart_id function, so this api suits S-mode particularly.
SysTimer_GetHartMsipValue
Definition at line 529 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP = (msip);
 #else
     if (hartid == 0) {
         SysTimer->MSIP = (msip);
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
         __SW(addr, msip);
     }
 #endif
 }
References __SW(), SysTimer, and SysTimer_CLINT_MSIP_BASE.
Referenced by SysTimer_SetMsipValue().
SysTimer_SetHartSsipValue()
__STATIC_FORCEINLINE void SysTimer_SetHartSsipValue (uint32_t ssip, unsigned long hartid)
Set system timer SSIP register value by hartid.
This function set the system timer SSIP register value.
Parameters
[in] msip value to set SSIP register
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
SysTimer_GetHartSsipValue
Definition at line 728 of file core_feature_timer.h.
 {
     if (hartid == 0) {
         SysTimer->SSIP = (ssip);
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
         __SW(addr, ssip);
     }
 }
References __SW(), SysTimer, and SysTimer_CLINT_SSIP_BASE.
Referenced by SysTimer_SetSsipValue().
SysTimer_SetHartSWIRQ()
__STATIC_FORCEINLINE void SysTimer_SetHartSWIRQ (unsigned long hartid)
Trigger or set software interrupt via system timer by hartid.
This function set the system timer MSIP bit in MSIP register.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
Set system timer MSIP bit and generate a machine mode software interrupt.
In S-mode, hartid can't be get by using __get_hart_id function, so this api suite S-mode particularly when MTIME_SRW_CTRL.SRW equal 0.
SysTimer_ClearHartSWIRQ
SysTimer_GetHartMsipValue
Definition at line 392 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP |= SysTimer_MSIP_MSIP_Msk;
 #else
     if (hartid == 0) {
         SysTimer->MSIP |= SysTimer_MSIP_MSIP_Msk;
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_MSIP_BASE(hartid));
         __SW(addr, SysTimer_MSIP_MSIP_Msk);
     }
 #endif
 }
References __SW(), SysTimer, SysTimer_CLINT_MSIP_BASE, and SysTimer_MSIP_MSIP_Msk.
Referenced by SysTimer_SetSWIRQ().
SysTimer_SetHartSWIRQ_S()
__STATIC_FORCEINLINE void SysTimer_SetHartSWIRQ_S (unsigned long hartid)
Trigger or set supervisor mode software interrupt via system timer by hartid.
This function set the system timer SSIP bit in SSIP register.
Parameters
[in] hartid hart ID, one hart is required to have a known hart ID of 0, other harts ID can be in 1~1023.
Remarks
Set system timer SSIP bit and generate a supervisor mode software interrupt.
SysTimer_ClearHartSWIRQ_S
SysTimer_GetHartSsipValue
Definition at line 618 of file core_feature_timer.h.
 {
     if (hartid == 0) {
         SysTimer->SSIP |= SysTimer_SSIP_SSIP_Msk;
     } else {
         uint8_t *addr = (uint8_t *)(SysTimer_CLINT_SSIP_BASE(hartid));
         __SW(addr, SysTimer_SSIP_SSIP_Msk);
     }
 }
References __SW(), SysTimer, SysTimer_CLINT_SSIP_BASE, and SysTimer_SSIP_SSIP_Msk.
Referenced by SysTimer_SetSWIRQ_S().
SysTimer_SetLoadValue()
__STATIC_INLINE void SysTimer_SetLoadValue (rv_counter_t value)
Set system timer load value.
This function set the system timer load value in MTIMER register.
Parameters
[in] value value to set system timer MTIMER register.
Remarks
Load value is 64bits wide for non-n100 cpu
SysTimer_GetLoadValue
Definition at line 165 of file core_feature_timer.h.
 {
 #if (__RISCV_XLEN == 32) && !(defined(CPU_SERIES) && CPU_SERIES == 100)
     uint8_t *addr;
     addr = (uint8_t *)(&(SysTimer->MTIMER));
     __SW(addr, 0);      // prevent carry
     __SW(addr + 4, (uint32_t)(value >> 32));
     __SW(addr, (uint32_t)(value));
 #else
     SysTimer->MTIMER = value;
 #endif
 }
References __SW(), and SysTimer.
SysTimer_SetMsipValue()
__STATIC_FORCEINLINE void SysTimer_SetMsipValue (uint32_t msip)
Set system timer MSIP register value in machine mode.
This function set the system timer MSIP register value.
Parameters
[in] msip value to set MSIP register
SysTimer_GetMsipValue
Definition at line 550 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP = (msip);
 #else
     unsigned long hartid = SysTimer_GetHartID();
     SysTimer_SetHartMsipValue(msip, hartid);
 #endif
 }
References SysTimer, SysTimer_GetHartID, and SysTimer_SetHartMsipValue().
SysTimer_SetSsipValue()
__STATIC_FORCEINLINE void SysTimer_SetSsipValue (uint32_t ssip)
Set system timer SSIP register value.
This function set the system timer SSIP register value.
Parameters
[in] msip value to set SSIP register
SysTimer_GetSsipValue
Definition at line 745 of file core_feature_timer.h.
 {
     unsigned long hartid = SysTimer_GetHartID();
     SysTimer_SetHartSsipValue(ssip, hartid);
 }
References SysTimer_GetHartID, and SysTimer_SetHartSsipValue().
SysTimer_SetSWIRQ()
__STATIC_FORCEINLINE void SysTimer_SetSWIRQ (void)
Trigger or set software interrupt via system timer in machine mode.
This function set the system timer MSIP bit in MSIP register.
Remarks
Set system timer MSIP bit and generate a SW interrupt.
SysTimer_ClearSWIRQ
SysTimer_GetMsipValue
Definition at line 415 of file core_feature_timer.h.
 {
 #if (defined(CPU_SERIES) && CPU_SERIES == 100)
     SysTimer->MSIP |= SysTimer_MSIP_MSIP_Msk;
 #else
     unsigned long hartid = SysTimer_GetHartID();
     SysTimer_SetHartSWIRQ(hartid);
 #endif
 }
References SysTimer, SysTimer_GetHartID, SysTimer_MSIP_MSIP_Msk, and SysTimer_SetHartSWIRQ().
SysTimer_SetSWIRQ_S()
__STATIC_FORCEINLINE void SysTimer_SetSWIRQ_S (void)
Trigger or set supervisor software interrupt via system timer.
This function set the system timer SSIP bit in SSIP register.
Remarks
Set system timer SSIP bit and generate a supervisor mode SW interrupt.
SysTimer_ClearSWIRQ_S
SysTimer_GetSsipValue
Definition at line 637 of file core_feature_timer.h.
 {
     unsigned long hartid = SysTimer_GetHartID_S();
     SysTimer_SetHartSWIRQ_S(hartid);
 }
References SysTimer_GetHartID_S, and SysTimer_SetHartSWIRQ_S().
SysTimer_SoftwareReset()
__STATIC_FORCEINLINE void SysTimer_SoftwareReset (void)
Do software reset request.
This function will do software reset request through MTIMER
Software need to write SysTimer_MSFRST_KEY to generate software reset request
The software request flag can be cleared by reset operation to clear
Remarks
The software reset is sent to SoC, SoC need to generate reset signal and send back to Core
This function will not return, it will do while(1) to wait the Core reset happened
Definition at line 819 of file core_feature_timer.h.
 {
     SysTimer->MSFTRST = SysTimer_MSFRST_KEY;
     // will reset cpu, never return
     while (1);
 }
References SysTimer, and SysTimer_MSFRST_KEY.
SysTimer_Start()
__STATIC_FORCEINLINE void SysTimer_Start (void)
Enable system timer counter running.
Enable system timer counter running by clear TIMESTOP bit in MTIMECTL register.
Definition at line 333 of file core_feature_timer.h.
 {
     SysTimer->MTIMECTL &= ~(SysTimer_MTIMECTL_TIMESTOP_Msk);
 }
References SysTimer, and SysTimer_MTIMECTL_TIMESTOP_Msk.
SysTimer_Stop()
__STATIC_FORCEINLINE void SysTimer_Stop (void)
Stop system timer counter running.
Stop system timer counter running by set TIMESTOP bit in MTIMECTL register.
Definition at line 344 of file core_feature_timer.h.
 {
     SysTimer->MTIMECTL |= SysTimer_MTIMECTL_TIMESTOP_Msk;
 }
References SysTimer, and SysTimer_MTIMECTL_TIMESTOP_Msk.