var modules =
[
    [ "Version Control", "group__NMSIS__Core__VersionControl.html", "group__NMSIS__Core__VersionControl" ],
    [ "Peripheral Access", "group__NMSIS__Core__PeriphAccess.html", "group__NMSIS__Core__PeriphAccess" ],
    [ "Compiler Control", "group__NMSIS__Core__CompilerControl.html", "group__NMSIS__Core__CompilerControl" ],
    [ "Core CSR Encodings", "group__NMSIS__Core__CSR__Encoding.html", "group__NMSIS__Core__CSR__Encoding" ],
    [ "NMSIS Bench and Test Related Helper Functions", "group__NMSIS__Core__Bench__Helpers.html", "group__NMSIS__Core__Bench__Helpers" ],
    [ "Register Define and Type Definitions", "group__NMSIS__Core__Registers.html", "group__NMSIS__Core__Registers" ],
    [ "Core CSR Register Access", "group__NMSIS__Core__CSR__Register__Access.html", "group__NMSIS__Core__CSR__Register__Access" ],
    [ "Intrinsic Functions for CPU Intructions", "group__NMSIS__Core__CPU__Intrinsic.html", "group__NMSIS__Core__CPU__Intrinsic" ],
    [ "Interrupts and Exceptions", "group__NMSIS__Core__IntExc.html", "group__NMSIS__Core__IntExc" ],
    [ "PLIC Interrupt", "group__NMSIS__Core__IntPlic.html", "group__NMSIS__Core__IntPlic" ],
    [ "CIDU Functions", "group__NMSIS__Core__CIDU.html", "group__NMSIS__Core__CIDU" ],
    [ "SysTimer Functions", "group__NMSIS__Core__SysTimer.html", "group__NMSIS__Core__SysTimer" ],
    [ "FPU Functions", "group__NMSIS__Core__FPU__Functions.html", "group__NMSIS__Core__FPU__Functions" ],
    [ "Intrinsic Functions for Vector Instructions", "group__NMSIS__Core__Vector__Intrinsic.html", "group__NMSIS__Core__Vector__Intrinsic" ],
    [ "Intrinsic Functions for Bitmanipulation Instructions", "group__NMSIS__Core__Bitmanip__Intrinsic.html", null ],
    [ "Intrinsic Functions for SIMD Instructions", "group__NMSIS__Core__DSP__Intrinsic.html", "group__NMSIS__Core__DSP__Intrinsic" ],
    [ "PMP Functions", "group__NMSIS__Core__PMP__Functions.html", "group__NMSIS__Core__PMP__Functions" ],
    [ "sPMP or sMPU Functions", "group__NMSIS__Core__SPMP.html", "group__NMSIS__Core__SPMP" ],
    [ "PMA Functions", "group__NMSIS__Core__PMA__Functions.html", "group__NMSIS__Core__PMA__Functions" ],
    [ "Cache Functions", "group__NMSIS__Core__Cache.html", "group__NMSIS__Core__Cache" ],
    [ "ARM Compatiable Functions", "group__NMSIS__Core__ARMCompatiable__Functions.html", "group__NMSIS__Core__ARMCompatiable__Functions" ],
    [ "System Device Configuration", "group__NMSIS__Core__SystemConfig.html", "group__NMSIS__Core__SystemConfig" ]
];