// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_cell_gate_hidden_weights[49] = {
    -95,  -128, -34, 68,  40,  65,   107, -68, 0,    69,  71,  -44, 41,
    111,  101,  107, -13, -25, -107, -18, 18,  -28,  7,   -13, -42, 33,
    -106, -79,  88,  -13, 68,  34,   -70, -71, 88,   103, 57,  76,  -46,
    7,    -31,  -23, -2,  85,  -114, 108, -41, -121, 121};
