// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_2_s16_cell_gate_bias[7] = {17103, 13290, 15964, 29579,
                                              27471, 289,   10364};
