// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_cell_gate_input_weights[42] = {
    40,  -67, -37, -76, 77,  14,  59,  -101, 84,  -25, -31, 18,  28,  -91,
    88,  -84, 87,  24,  -54, 125, -88, -75,  -17, 124, 32,  -87, 13,  -56,
    -50, -25, -24, -86, 80,  88,  -87, -94,  -80, -16, 21,  -53, -43, 51};
