// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_forget_gate_hidden_weights[49] = {
    -23, -104, 92,  -66,  -39, 7,    111, 112, 58,   -34, -36, -77, 37,
    -71, 10,   17,  -45,  40,  -114, 61,  -86, -76,  94,  31,  38,  -13,
    10,  -61,  85,  5,    -88, -16,  -31, 43,  -124, -47, -99, 98,  82,
    112, -45,  -22, -111, -30, -127, 22,  113, -94,  77};
