// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_forget_gate_input_weights[42] = {
    -20, 41,  57,  107, -11,  43, 41, -84, 59,  -96, 54, 119, -92, 47,
    -62, 103, 122, -25, -123, -4, 18, -12, -35, 60,  80, -33, 105, -111,
    18,  31,  -39, 97,  0,    -7, 12, -16, 64,  108, 79, 80,  17,  -12};
