// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_input_gate_hidden_weights[49] = {
    19,   -36, -121, 83,  121, -38, 98,   -72,  17,  -8,  -81, 63,  120,
    -121, 105, -120, -87, 24,  -43, -79,  89,   -74, -56, -94, -78, -103,
    24,   61,  -114, -77, -92, -16, -104, -114, -5,  -87, -16, -96, 32,
    123,  -59, -108, 67,  117, 80,  -43,  -116, -13, -74};
