// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_input_gate_input_weights[42] = {
    -97, -70, 92, 59,   -105, -109, -5,   -52, 122,  62,  119, -59, -89, -93,
    -48, 59,  47, -16,  47,   72,   -10,  -94, -44,  43,  -99, 67,  7,   12,
    -85, 119, 78, -109, 110,  -91,  -121, -17, -122, -47, 29,  101, 3,   -46};
