// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_output_gate_input_weights[42] = {
    -52,  26, -115, -73, -62, -55, 28,  5,   68,  77,  -35, -119, 42,  -78,
    -123, 45, -81,  11,  -14, 116, -69, 102, -32, -23, 122, 1,    -73, 27,
    23,   31, -106, -3,  43,  -53, -27, 111, -71, 103, -38, 30,   91,  122};
