// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int16_t lstm_2_s16_output[63] = {
    -245, 21,  -117, 242,  157,  145, 44,   -37, 479,  98,   55,   127, 88,
    -129, 5,   89,   37,   55,   226, -428, -49, -219, 317,  4,    -75, 84,
    65,   -59, -671, 32,   -188, 465, 64,   -28, 69,   -95,  -457, 1,   -75,
    34,   -17, -143, -70,  -419, 16,  -242, -28, -25,  -199, 5,    49,  108,
    -117, 94,  -164, -130, -45,  496, 412,  -92, 182,  246,  -13};
