// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_output_gate_hidden_weights[49] = {
    -55, 32,  -52, 76,  97,   69, -32, -92, 45,  126, 110,  -11,  -79,
    -16, -74, 70,  -48, -17,  -8, 93,  -51, -53, -32, -104, -21,  -2,
    -99, -69, 110, 21,  109,  74, 95,  64,  -25, -7,  -117, -124, 111,
    -99, 103, 105, -49, -101, 63, 13,  -36, 5,   0};
