// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_NCWH_IN_DIM                                                  \
    {                                                                          \
        5, 4, 3, 9,                                                            \
    }
#define TRANSPOSE_NCWH_PERM                                                    \
    {                                                                          \
        0, 3, 2, 1,                                                            \
    }
#define TRANSPOSE_NCWH_SIZE 540
#define TRANSPOSE_NCWH_PERM_SIZE 4
#define TRANSPOSE_NCWH_OUT_DIM                                                 \
    {                                                                          \
        5, 9, 3, 4,                                                            \
    }
