// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_4_input_tensor[85] = {
    -81, -120, 126,  8,   -24,  -109, 113, 34,  69,  -10,  25,  82,  45,
    24,  -106, -126, 30,  -3,   64,   94,  -91, 77,  77,   67,  -72, -50,
    -62, -15,  -36,  -48, -6,   -1,   21,  60,  -55, -78,  -79, 0,   -59,
    -43, 34,   4,    72,  102,  -65,  -3,  13,  -46, 56,   -78, 77,  10,
    41,  -109, -115, -19, -123, 77,   -28, 40,  -26, -67,  82,  83,  -113,
    42,  76,   -72,  77,  -23,  67,   -37, 112, -80, -106, -5,  -82, -111,
    101, 36,   4,    -77, -110, -93,  -14};

const int8_t *const fully_connected_int4_4_input = fully_connected_int4_4_input_tensor;
