// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t *const fully_connected_int4_4_input_bias = NULL;

const int32_t *const fully_connected_int4_4_biases = fully_connected_int4_4_input_bias;
