// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_4_output[19] = {
    18, 5, 2, -9, -3, -1, -12, -14, -16, 17, 9, -19, 4, 25, 7, -8, 13, 10, 10};

const int8_t *const fully_connected_int4_4_output_ref = fully_connected_int4_4_output;
