// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t basic_int4_input_weights[4] = {207, 101, 152, 38};

const int8_t *const basic_int4_weights = basic_int4_input_weights;
