// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t basic_int4_input_tensor[40] = {
    -84, 117, -23, 34, -101, 81,  -61, 124, 82,  108, 89, -7,  120, -111,
    -33, 33,  -80, 77, 108,  123, -22, -41, 113, -50, 99, -66, -82, 6,
    98,  48,  25,  17, 95,   100, 46,  115, 106, -16, 68, 43};

const int8_t *const basic_int4_input = basic_int4_input_tensor;
