// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t basic_int4_output[20] = {-7, -5, 11, 26, 5,  3,  -10, -24, -4, -10,
                                      8,  15, 9,  9,  -2, -5, 0,   -8,  -5, -2};

const int8_t *const basic_int4_output_ref = basic_int4_output;
