// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t minimum_broadcast_height_int8_input_tensor_1[68] = {
    -34, 3,    30,  24,  -80, 113, -81, 23,  -113, -121, 5,   31,  -31, 62,
    98,  16,   -24, 84,  77,  121, -95, -28, 71,   -7,   8,   101, 117, 8,
    64,  36,   16,  78,  50,  28,  -29, 107, 26,   49,   6,   95,  110, 43,
    -68, -117, 103, 20,  35,  -60, 89,  92,  8,    39,   -80, -82, 120, -23,
    26,  68,   109, -20, 43,  23,  92,  -89, -31,  -97,  3,   6};
