// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_int4_input_tensor[64] = {
    65,  -13, -85, -10,  -55, -12,  15,   45,  -63, -78,  111, -41, 113,
    -78, -32, 63,  -125, 77,  -21,  63,   70,  85,  -15,  106, 38,  37,
    106, 67,  -36, -30,  -89, -128, -113, -47, -2,  26,   41,  -6,  -65,
    -9,  -96, 82,  -18,  -24, 121,  69,   -99, 122, -47,  -44, -7,  11,
    -23, -32, 102, -32,  36,  -58,  -118, -91, 36,  -110, -39, -29};

const int8_t *const conv_1_x_n_4_int4_input = conv_1_x_n_4_int4_input_tensor;
