// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_int4_input_weights[24] = {
    171, 126, 116, 37,  226, 239, 245, 177, 22,  205, 126, 24,
    246, 9,   102, 201, 197, 100, 140, 179, 197, 15,  252, 147};

const int8_t *const conv_1_x_n_4_int4_weights = conv_1_x_n_4_int4_input_weights;
