// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_4_int4_output_multiplier[4] = {1367353600, 1822525952,
                                                        1409733632, 2040776832};

const int32_t *const conv_1_x_n_4_int4_output_mult = conv_1_x_n_4_int4_output_multiplier;
