// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_int4_output[32] = {
    9,  -25, 18, -19, 8,  17, -3, -5,  26, -23, 21, -28, -2, 2,  13, -23,
    17, 6,   3,  -11, 17, -3, 21, -19, 23, -6,  -4, -18, 4,  12, 9,  -5};

const int8_t *const conv_1_x_n_4_int4_output_ref = conv_1_x_n_4_int4_output;
