// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maximum_broadcast_ch_int8_input_tensor_1[16] = {
    33, 103, 28, -61, 97, 92, -124, 95, 117, 10, -80, 123, 48, 79, 124, 40};
