// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOL_INT16_BATCH_SIZE 3
#define MAXPOOL_INT16_INPUT_N 3
#define MAXPOOL_INT16_INPUT_W 4
#define MAXPOOL_INT16_INPUT_H 3
#define MAXPOOL_INT16_INPUT_C 2
#define MAXPOOL_INT16_FILTER_W 2
#define MAXPOOL_INT16_FILTER_H 2
#define MAXPOOL_INT16_STRIDE_W 2
#define MAXPOOL_INT16_STRIDE_H 2
#define MAXPOOL_INT16_PAD VALID
#define MAXPOOL_INT16_ACTIVATION_MAX 32767
#define MAXPOOL_INT16_ACTIVATION_MIN -32768
#define MAXPOOL_INT16_OUTPUT_C 2
#define MAXPOOL_INT16_OUTPUT_W 2
#define MAXPOOL_INT16_OUTPUT_H 1
#define MAXPOOL_INT16_PADDING_H 0
#define MAXPOOL_INT16_PADDING_W 0
