// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_output[12] = {8102,  25946, 29931, 27694,
                                          16798, 32220, 7701,  20803,
                                          28425, 15349, 6708,  28020};
