// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_input_tensor[60] = {
    -54, 72,   126,  -18,  -45,  112, -89,  -17, 49,  75,   99,  53,
    -70, -100, -107, 102,  86,   92,  114,  85,  68,  -120, 53,  -104,
    -20, 97,   34,   -116, -78,  -30, -126, -7,  -51, -71,  80,  -11,
    -66, 47,   -69,  -124, -61,  17,  79,   -29, -28, -17,  -16, -4,
    83,  -52,  120,  -109, -120, 11,  -90,  121, -61, -69,  -60, -25};
