// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t avgpooling_2_output[60] = {
    29,  -9,  55,  16,  15,  52,  12,  13,  -23, -26, 104, 17,  2,   21,  18,
    90,  6,   25,  -30, -14, 89,  0,   10,  -23, 12,  13,  -31, -38, -84, 10,
    -13, -13, -40, -73, -25, -66, -19, 25,  -56, -24, -30, -22, 41,  -5,  -68,
    14,  -36, -15, 22,  -57, 75,  -62, -64, 11,  -56, 121, -85, -95, -25, -58};
