// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_NWHC_IN_DIM                                                  \
    {                                                                          \
        1, 19, 3, 64,                                                          \
    }
#define TRANSPOSE_NWHC_PERM                                                    \
    {                                                                          \
        0, 2, 1, 3,                                                            \
    }
#define TRANSPOSE_NWHC_SIZE 3648
#define TRANSPOSE_NWHC_PERM_SIZE 4
#define TRANSPOSE_NWHC_OUT_DIM                                                 \
    {                                                                          \
        1, 3, 19, 64,                                                          \
    }
