// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_int4_input_weights[67] = {
    184, 129, 241, 79,  17,  218, 90,  255, 52,  57,  65,  52,  225, 141,
    31,  34,  44,  198, 156, 161, 11,  213, 217, 103, 226, 171, 204, 226,
    240, 50,  26,  200, 1,   164, 212, 27,  15,  250, 218, 34,  206, 46,
    101, 254, 132, 99,  74,  39,  244, 106, 151, 163, 199, 166, 40,  141,
    155, 147, 14,  213, 15,  88,  189, 21,  239, 20,  7};

const int8_t *const kernel1x1_int4_weights = kernel1x1_int4_input_weights;
