// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_input_bias[7] = {-104, 35,  -91, -123,
                                              32,   116, 126};

const int32_t *const kernel1x1_int4_biases = kernel1x1_int4_input_bias;
