// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_output_multiplier[7] = {
    1782153728, 1757547904, 1082640128, 1651282816,
    1117286272, 1535270016, 1348248064};

const int32_t *const kernel1x1_int4_output_mult = kernel1x1_int4_output_multiplier;
