// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_int4_input_weights[23] = {
    166, 193, 121, 177, 89,  108, 131, 9,  226, 206, 31, 227,
    62,  220, 195, 132, 187, 247, 20,  69, 170, 202, 8};

const int8_t *const kernel1x1_stride_x_int4_weights = kernel1x1_stride_x_int4_input_weights;
