// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_int4_output_multiplier[5] = {
    1942542976, 1679919744, 1099465472, 1973863296, 2118311296};

const int32_t *const kernel1x1_stride_x_int4_output_mult = kernel1x1_stride_x_int4_output_multiplier;
