// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_int4_output[60] = {
    -27, -6, -11, -20, -25, -16, 2,  -12, -18, -4,  -23, -1, -3,  -17, -10,
    -12, -2, -7,  1,   -8,  -11, 3,  -7,  -7,  -13, -5,  -7, -16, -18, -33,
    -3,  -2, -15, -13, -8,  -12, -6, 0,   -3,  -25, -3,  -2, -11, -20, -8,
    -6,  0,  -14, -11, -16, -27, -4, -8,  -15, -18, -15, -1, -3,  -13, -13};

const int8_t *const kernel1x1_stride_x_int4_output_ref = kernel1x1_stride_x_int4_output;
