// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_5_input_tensor[89] = {
    15,  66,  31,   -26,  105,  -23,  -24,  -85,  -19,  -20,  56,   -14,  -17,
    -93, 126, -33,  -120, 110,  -48,  10,   -115, -92,  -112, -52,  77,   44,
    -51, -90, -104, -41,  -118, -119, -103, 31,   6,    63,   -76,  -118, -124,
    -70, 119, -59,  3,    62,   -43,  -47,  -29,  -12,  -76,  -123, -33,  -94,
    65,  63,  -125, 57,   -50,  98,   -126, -5,   -23,  9,    -92,  -48,  -111,
    105, -75, -83,  -87,  75,   119,  107,  -85,  -108, 68,   90,   23,   -85,
    25,  56,  64,   99,   52,   55,   -104, 15,   26,   67,   -123};

const int8_t *const fully_connected_int4_5_input = fully_connected_int4_5_input_tensor;
