// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_5_input_bias[22] = {
    88,  115, 49, -123, 114, -123, 4,   81, 84, 46,  24,
    -54, 116, 18, 71,   -65, 104,  119, 17, -2, 120, 45};

const int32_t *const fully_connected_int4_5_biases = fully_connected_int4_5_input_bias;
