// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_5_output[22] = {
    28, 91, 57,  67, 66,  89, 67, 22, 90, 105, 52,
    5,  43, 127, 63, 107, 75, 58, 98, 73, 80,  66};

const int8_t *const fully_connected_int4_5_output_ref = fully_connected_int4_5_output;
