// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int64_t int16xint8_dilation_2_bias[4] = {-1758879, 3428679, 1648833,
                                               -4114115};

const int64_t *const int16xint8_dilation_2_biases = int16xint8_dilation_2_bias;
