// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8_dilation_2_output_multiplier[4] = {
    1784566912, 1692721024, 1811956096, 1706960512};

const int32_t *const int16xint8_dilation_2_output_mult = int16xint8_dilation_2_output_multiplier;
