// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOLING_BATCH_SIZE 2
#define MAXPOOLING_INPUT_N 2
#define MAXPOOLING_INPUT_W 22
#define MAXPOOLING_INPUT_H 12
#define MAXPOOLING_INPUT_C 8
#define MAXPOOLING_FILTER_W 6
#define MAXPOOLING_FILTER_H 5
#define MAXPOOLING_STRIDE_W 9
#define MAXPOOLING_STRIDE_H 5
#define MAXPOOLING_PAD SAME
#define MAXPOOLING_ACTIVATION_MAX 127
#define MAXPOOLING_ACTIVATION_MIN -128
#define MAXPOOLING_OUTPUT_C 8
#define MAXPOOLING_OUTPUT_W 3
#define MAXPOOLING_OUTPUT_H 3
#define MAXPOOLING_PADDING_H 1
#define MAXPOOLING_PADDING_W 1
