// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t avgpooling_3_input_tensor[18] = {19,  104, -51,  64,  124,  85,
                                              -4,  24,  -120, 111, -120, -83,
                                              -85, 86,  -77,  -78, -43,  -111};
