// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOL_INT16_2_BATCH_SIZE 1
#define MAXPOOL_INT16_2_INPUT_N 1
#define MAXPOOL_INT16_2_INPUT_W 7
#define MAXPOOL_INT16_2_INPUT_H 7
#define MAXPOOL_INT16_2_INPUT_C 3
#define MAXPOOL_INT16_2_FILTER_W 3
#define MAXPOOL_INT16_2_FILTER_H 3
#define MAXPOOL_INT16_2_STRIDE_W 1
#define MAXPOOL_INT16_2_STRIDE_H 1
#define MAXPOOL_INT16_2_PAD VALID
#define MAXPOOL_INT16_2_ACTIVATION_MAX 30000
#define MAXPOOL_INT16_2_ACTIVATION_MIN -30000
#define MAXPOOL_INT16_2_OUTPUT_C 3
#define MAXPOOL_INT16_2_OUTPUT_W 5
#define MAXPOOL_INT16_2_OUTPUT_H 5
#define MAXPOOL_INT16_2_PADDING_H 0
#define MAXPOOL_INT16_2_PADDING_W 0
