// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_input_tensor[18] = {-35, -114, -81, -81, 112, -17,
                                              -89, -115, 48,  70,  20,  -37,
                                              -70, -23,  79,  106, 43,  101};
