// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3_int4_input_weights[60] = {
    77,  220, 106, 44,  75,  189, 74,  117, 42, 12,  231, 55,  223, 136, 44,
    165, 217, 54,  225, 217, 23,  231, 186, 74, 116, 192, 221, 87,  234, 81,
    210, 118, 204, 51,  175, 140, 78,  86,  34, 241, 138, 157, 203, 70,  196,
    69,  31,  170, 104, 32,  201, 67,  174, 48, 194, 221, 162, 204, 126, 29};

const int8_t *const conv_3_int4_weights = conv_3_int4_input_weights;
