// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define PAD_INT8_2_INPUT_N 1
#define PAD_INT8_2_INPUT_W 2
#define PAD_INT8_2_INPUT_H 2
#define PAD_INT8_2_INPUT_C 2
#define PAD_INT8_2_PRE_PAD_N 0
#define PAD_INT8_2_PRE_PAD_H 2
#define PAD_INT8_2_PRE_PAD_W 2
#define PAD_INT8_2_PRE_PAD_C 0
#define PAD_INT8_2_POST_PAD_N 0
#define PAD_INT8_2_POST_PAD_H 1
#define PAD_INT8_2_POST_PAD_W 1
#define PAD_INT8_2_POST_PAD_C 0
#define PAD_INT8_2_PAD_VALUE -128
#define PAD_INT8_2_OUTPUT_SIZE 50
