// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t pad_int8_2_output[50] = {
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    -128, -128, -128, -128, 10,   112,  114,  30,   -128, -128,
    -128, -128, -128, -128, -50,  -82,  46,   -46,  -128, -128,
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128};
