// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_DEFAULT_IN_DIM                                               \
    {                                                                          \
        4, 3, 3, 22,                                                           \
    }
#define TRANSPOSE_DEFAULT_PERM                                                 \
    {                                                                          \
        3, 2, 1, 0,                                                            \
    }
#define TRANSPOSE_DEFAULT_SIZE 792
#define TRANSPOSE_DEFAULT_PERM_SIZE 4
#define TRANSPOSE_DEFAULT_OUT_DIM                                              \
    {                                                                          \
        22, 3, 3, 4,                                                           \
    }
