/*
 * SPDX-FileCopyrightText: Copyright 2010-2021, 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * Copyright (c) 2025 Nuclei Limited. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdint.h>

#include "../test_riscv_avgpool_s8.c"
#include "unity.h"

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void) {}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

void test_avgpooling_riscv_avgpool_s8(void) { avgpooling_riscv_avgpool_s8(); }

void test_avgpooling_1_riscv_avgpool_s8(void) { avgpooling_1_riscv_avgpool_s8(); }

void test_avgpooling_2_riscv_avgpool_s8(void) { avgpooling_2_riscv_avgpool_s8(); }

void test_avgpooling_3_riscv_avgpool_s8(void) { avgpooling_3_riscv_avgpool_s8(); }

void test_avgpooling_4_riscv_avgpool_s8(void) { avgpooling_4_riscv_avgpool_s8(); }

void test_avgpooling_5_riscv_avgpool_s8(void) { avgpooling_5_riscv_avgpool_s8(); }

void test_buffer_size_dsp_riscv_avgpool_s8(void) { buffer_size_dsp_riscv_avgpool_s8(); }

void test_avgpooling_param_fail_riscv_avgpool_s8(void) { avgpooling_param_fail_riscv_avgpool_s8(); }
