// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t minimum_broadcast_width_int8_input_tensor_2[38] = {
    -44, -68, 7,  28,  -36, 54,  68,   -116, -69, 71,  -50, -44, 75,
    -54, -26, 65, 2,   27,  -36, 79,   -69,  -47, -37, 20,  24,  78,
    -63, -15, 1,  -95, -36, 55,  -103, 9,    10,  126, 81,  4};
