// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#include "config_data.h"
#include "input_tensor_1.h"
#include "input_tensor_2.h"
#include "output.h"
