// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_int4_input_weights[18] = {
    236, 75,  194, 60,  101, 137, 202, 20,  16,
    144, 150, 209, 147, 87,  196, 90,  205, 217};

const int8_t *const conv_2x3_dilation_int4_weights = conv_2x3_dilation_int4_input_weights;
