// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_int4_input_tensor[18] = {
    49,  88, -55, 100, 25, -111, -55, -11, 94,
    122, 28, 33,  94,  36, -7,   -66, 118, 51};

const int8_t *const conv_2x3_dilation_int4_input = conv_2x3_dilation_int4_input_tensor;
