// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_int4_output[18] = {
    2, 16, 3, 10, 1, 2, -3, 6, 5, 16, 3, 8, -2, 15, 2, 7, 3, 12};

const int8_t *const conv_2x3_dilation_int4_output_ref = conv_2x3_dilation_int4_output;
