// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tflite_micro runtime version
// 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_gate_bias[11] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
