// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_int4_input_weights[18] = {
    65,  31, 204, 94, 88,  168, 188, 64,  42,
    148, 49, 216, 45, 189, 39,  86,  131, 47};

const int8_t *const conv_2x2_dilation_int4_weights = conv_2x2_dilation_int4_input_weights;
