// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_int4_output[72] = {
    -79, 2,   -48, -22, -62, -3,  -27, -3,  -18, -30, -36, 27,  -67, -17, -39,
    24,  -76, -12, -34, -35, -61, 10,  -29, -36, -38, -50, -62, 3,   -28, 20,
    -13, 7,   -31, -17, -24, -22, -59, 25,  -7,  -3,  -82, 0,   -59, 25,  -89,
    -10, -53, -8,  -33, 18,  -59, -21, -44, -22, -58, 19,  -65, -11, -12, -56,
    -69, -18, -15, -19, -29, -48, -30, -47, -74, 6,   -48, 28};

const int8_t *const conv_2x2_dilation_int4_output_ref = conv_2x2_dilation_int4_output;
