// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#include "config_data.h"
#include "input_bias.h"
#include "input_tensor.h"
#include "input_weights.h"
#include "output.h"
#include "output_multiplier.h"
#include "output_shift.h"
