// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_5x5_input_int4_input_tensor[50] = {
    -56, 26,  -22, -48, 7,   -119, -124, -116, 30,  -116, 88,   -18, -88,
    -66, -45, -11, 63,  92,  94,   6,    -83,  -22, 1,    88,   71,  9,
    4,   119, -78, 103, -59, 32,   80,   -24,  -34, -121, -107, -91, 19,
    -27, 112, 92,  37,  43,  20,   -126, -124, -12, 38,   56};

const int8_t *const conv_2x2_dilation_5x5_input_int4_input = conv_2x2_dilation_5x5_input_int4_input_tensor;
