// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_5x5_input_int4_input_weights[18] = {
    242, 188, 240, 82,  79,  143, 106, 169, 225,
    213, 104, 222, 110, 182, 128, 220, 147, 15};

const int8_t *const conv_2x2_dilation_5x5_input_int4_weights = conv_2x2_dilation_5x5_input_int4_input_weights;
