// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_5x5_input_int4_output[50] = {
    -9,  -14, -30, -13, -21, 5,   -16, -25, -23, -22, -26, -14, -46,
    -22, -3,  -18, 0,   -12, -14, 5,   -57, -25, -55, -37, -35, -39,
    17,  -12, -20, -26, -14, -22, -11, -7,  -11, 4,   -11, -1,  -13,
    -8,  -6,  -3,  -28, -17, -24, -16, -2,  5,   -4,  14};

const int8_t *const conv_2x2_dilation_5x5_input_int4_output_ref = conv_2x2_dilation_5x5_input_int4_output;
