// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_2x2_dilation_5x5_input_int4_output_multiplier[2] = {
    1589007616, 1460511360};

const int32_t *const conv_2x2_dilation_5x5_input_int4_output_mult = conv_2x2_dilation_5x5_input_int4_output_multiplier;
