/*
 * SPDX-FileCopyrightText: Copyright 2010-2021, 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * Copyright (c) 2025 Nuclei Limited. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdbool.h>
#include <stdint.h>

#include "../test_riscv_max_pool_s8.c"
#include "unity.h"

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void) {}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

void test_maxpooling_riscv_max_pool_s8(void) { maxpooling_riscv_max_pool_s8(); }

void test_maxpooling_1_riscv_max_pool_s8(void) { maxpooling_1_riscv_max_pool_s8(); }

void test_maxpooling_2_riscv_max_pool_s8(void) { maxpooling_2_riscv_max_pool_s8(); }

void test_maxpooling_3_riscv_max_pool_s8(void) { maxpooling_3_riscv_max_pool_s8(); }

void test_maxpooling_4_riscv_max_pool_s8(void) { maxpooling_4_riscv_max_pool_s8(); }

void test_maxpooling_5_riscv_max_pool_s8(void) { maxpooling_5_riscv_max_pool_s8(); }

void test_maxpooling_6_riscv_max_pool_s8(void) { maxpooling_6_riscv_max_pool_s8(); }

void test_maxpooling_7_riscv_max_pool_s8(void) { maxpooling_7_riscv_max_pool_s8(); }

void test_maxpooling_param_fail_riscv_max_pool_s8(void) { maxpooling_param_fail_riscv_max_pool_s8(); }
