// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_6_bias[4] = {-3684458, 2551162, -2113381,
                                            -2067306};

const int32_t *const int16xint8xint32_6_biases = int16xint8xint32_6_bias;
