// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_input_bias[21] = {
    -5,  -62,  -66,  -124, 47,  -40, 54, 99, -50, 3, -52,
    -54, -126, -127, 85,   108, 43,  53, 69, -67, 75};

const int32_t *const fully_connected_int4_biases = fully_connected_int4_input_bias;
