// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_input_tensor[82] = {
    -11, -3,  21,  97,  91,  -74,  -40,  31, 97,   -86, 110, 99,   -4,  -48,
    -38, -47, -61, 122, -89, -100, -61,  80, 122,  -55, -16, -93,  16,  -42,
    -29, -5,  92,  -83, -1,  104,  -114, 26, -125, 108, -24, -104, 95,  -28,
    83,  16,  41,  61,  120, -9,   68,   24, 101,  57,  35,  -81,  -14, 92,
    57,  -3,  -32, -29, 127, 51,   12,   41, 78,   97,  75,  -103, 114, 68,
    62,  122, -93, 71,  5,   -123, 107,  56, -7,   -11, 29,  -31};

const int8_t *const fully_connected_int4_input = fully_connected_int4_input_tensor;
