// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_output[21] = {4, 27,  -12, -8, 9,   -15, -15,
                                                2, -20, -9,  -8, -25, 10,  10,
                                                4, 9,   -12, 13, -8,  3,   -1};

const int8_t *const fully_connected_int4_output_ref = fully_connected_int4_output;
