var searchData=
[
  ['variance_2228',['Variance',['../group__variance.html',1,'']]],
  ['variance_20example_2229',['Variance Example',['../group__VarianceExample.html',1,'']]],
  ['vector_20absolute_20value_2230',['Vector Absolute Value',['../group__BasicAbs.html',1,'']]],
  ['vector_20addition_2231',['Vector Addition',['../group__BasicAdd.html',1,'']]],
  ['vector_20bitwise_20and_2232',['Vector bitwise AND',['../group__And.html',1,'']]],
  ['vector_20bitwise_20exclusive_20or_2233',['Vector bitwise exclusive OR',['../group__Xor.html',1,'']]],
  ['vector_20bitwise_20inclusive_20or_2234',['Vector bitwise inclusive OR',['../group__Or.html',1,'']]],
  ['vector_20bitwise_20not_2235',['Vector bitwise NOT',['../group__Not.html',1,'']]],
  ['vector_20clarke_20transform_2236',['Vector Clarke Transform',['../group__clarke.html',1,'']]],
  ['vector_20copy_2237',['Vector Copy',['../group__copy.html',1,'']]],
  ['vector_20dot_20product_2238',['Vector Dot Product',['../group__BasicDotProd.html',1,'']]],
  ['vector_20exponential_2239',['Vector Exponential',['../group__vexp.html',1,'']]],
  ['vector_20fill_2240',['Vector Fill',['../group__Fill.html',1,'']]],
  ['vector_20inverse_20clarke_20transform_2241',['Vector Inverse Clarke Transform',['../group__inv__clarke.html',1,'']]],
  ['vector_20inverse_20park_20transform_2242',['Vector Inverse Park transform',['../group__inv__park.html',1,'']]],
  ['vector_20log_2243',['Vector Log',['../group__vlog.html',1,'']]],
  ['vector_20multiplication_2244',['Vector Multiplication',['../group__BasicMult.html',1,'']]],
  ['vector_20negate_2245',['Vector Negate',['../group__BasicNegate.html',1,'']]],
  ['vector_20offset_2246',['Vector Offset',['../group__BasicOffset.html',1,'']]],
  ['vector_20park_20transform_2247',['Vector Park Transform',['../group__park.html',1,'']]],
  ['vector_20scale_2248',['Vector Scale',['../group__BasicScale.html',1,'']]],
  ['vector_20shift_2249',['Vector Shift',['../group__BasicShift.html',1,'']]],
  ['vector_20sorting_20algorithms_2250',['Vector sorting algorithms',['../group__Sorting.html',1,'']]],
  ['vector_20subtraction_2251',['Vector Subtraction',['../group__BasicSub.html',1,'']]]
];
