// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_2_output_multiplier[9] = {
    1733146752, 1731884928, 1733079680, 1732268928, 1733152896,
    1732986880, 1732107136, 1731676160, 1733000576};

const int32_t *const int16xint8xint32_2_output_mult = int16xint8xint32_2_output_multiplier;
