// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define AVGPOOLING_5_BATCH_SIZE 1
#define AVGPOOLING_5_INPUT_N 1
#define AVGPOOLING_5_INPUT_W 3
#define AVGPOOLING_5_INPUT_H 3
#define AVGPOOLING_5_INPUT_C 1
#define AVGPOOLING_5_FILTER_W 1
#define AVGPOOLING_5_FILTER_H 3
#define AVGPOOLING_5_STRIDE_W 1
#define AVGPOOLING_5_STRIDE_H 1
#define AVGPOOLING_5_PAD SAME
#define AVGPOOLING_5_ACTIVATION_MAX 6
#define AVGPOOLING_5_ACTIVATION_MIN 0
#define AVGPOOLING_5_OUTPUT_C 1
#define AVGPOOLING_5_OUTPUT_W 3
#define AVGPOOLING_5_OUTPUT_H 3
#define AVGPOOLING_5_PADDING_H 1
#define AVGPOOLING_5_PADDING_W 0
