// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t avgpooling_5_input_tensor[9] = {1,   39,  -31, 59, 1,
                                             105, -54, -30, 121};
