// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_int4_2_input_tensor[60] = {
    29,  0,   35,  -64,  32,  117, 122, -24,  31,  -49, -103, -112,
    36,  55,  120, -125, 25,  122, 40,  87,   104, -37, -16,  -109,
    124, -25, 103, -79,  -46, 117, 89,  -26,  123, 74,  25,   96,
    66,  38,  -42, -97,  -57, 82,  124, 4,    -81, 127, -17,  -94,
    25,  -50, -53, -17,  65,  31,  -7,  -113, -40, 109, -98,  20};

const int8_t *const kernel1x1_int4_2_input = kernel1x1_int4_2_input_tensor;
