// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_2_input_bias[60] = {
    27,  72,  27, -99, 101,  -98, 108, -91, 83,   -5,  -10, -66,
    50,  -43, 86, 123, -20,  31,  120, 24,  -114, -51, -96, 5,
    5,   49,  43, -93, -108, 0,   83,  75,  109,  5,   -23, 82,
    -98, 60,  -7, 86,  -87,  25,  -83, -76, -73,  126, -51, 68,
    71,  -44, 52, 76,  -39,  -90, -57, 66,  -79,  39,  99,  -67};

const int32_t *const kernel1x1_int4_2_biases = kernel1x1_int4_2_input_bias;
