// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_2_output_shift[60] = {
    -6, -8, -7, -7, -6, -5, -6, -7, -7, -5, -7, -5, -5, -5, -6,
    -6, -6, -6, -7, -8, -6, -7, -6, -7, -6, -6, -8, -6, -8, -5,
    -7, -6, -6, -7, -5, -6, -5, -6, -6, -5, -5, -6, -6, -5, -6,
    -5, -6, -7, -6, -7, -7, -5, -6, -5, -6, -6, -6, -6, -7, -5};
