// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_int4_2_output[60] = {
    -128, -49,  -70,  57,   -43, -85,  -128, -30,  -24, -128, -24,  -128,
    29,   -128, -128, -38,  -71, -84,  -5,   2,    -93, 68,   -128, 42,
    45,   -56,  -32,  -70,  -34, -128, -2,   65,   -43, -41,  41,   53,
    -104, -102, -76,  -128, 127, -48,  -12,  -121, -2,  -22,  -90,  -47,
    84,   -110, -47,  -89,  -93, -119, -80,  -128, -15, -108, 52,   -62};

const int8_t *const kernel1x1_int4_2_output_ref = kernel1x1_int4_2_output;
