// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_cell_gate_input_weights[66] = {
    -75, -52, 93,   73,  -36, 98, -47,  -32, -13, -113, -1,  -18, 90,   17,
    -2,  74,  -92,  -94, -57, 31, 34,   126, -68, -128, -71, -2,  -11,  -65,
    25,  -91, -115, -83, -89, 13, -115, 23,  65,  -119, -66, 104, -37,  33,
    -98, 40,  -10,  122, 59,  99, 76,   66,  122, -115, -34, -94, -114, 28,
    30,  -57, -64,  -1,  -78, 5,  -74,  67,  19,  42};
