// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_cell_gate_hidden_weights[9] = {
    -105, 7, -100, -2, -123, -68, 25, 101, 113};
