// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_forget_gate_input_weights[66] = {
    -121, 31,   0,   -87, -73,  -1,  -11, 86,  -72, 7,   7,   112, 126,  29,
    45,   -19,  64,  65,  -103, 7,   16,  -91, -83, -90, 94,  1,   20,   119,
    -12,  9,    -90, -5,  43,   -27, -26, -79, 30,  -10, -37, -67, -127, -48,
    -24,  -113, 27,  114, 20,   58,  31,  -17, -57, 57,  -88, 73,  115,  -104,
    -45,  -79,  89,  104, -127, 68,  14,  53,  44,  -33};
