// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int64_t lstm_one_time_step_s16_forget_gate_bias[3] = {10401, 19427,
                                                            18629};
