// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_input_gate_input_weights[66] = {
    -90, 84,   111,  110, -91,  50, 67,  81,   -88, 66,   -72, 48,  0,    -82,
    -38, -66,  -98,  -29, 46,   98, -54, -81,  -73, -105, 50,  -36, -61,  -105,
    84,  -82,  -110, 118, -113, 7,  14,  -115, -10, -119, -29, 25,  -119, -95,
    41,  -10,  46,   -59, 20,   87, -31, -10,  -87, 20,   -77, 26,  29,   -12,
    67,  -122, 53,   -15, 21,   50, 54,  -95,  22,  84};
