// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_output_gate_hidden_weights[9] = {
    -24, -90, 107, -88, 1, 97, -19, 25, 15};
