// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_output_gate_input_weights[66] = {
    -38, -6,  9,   36,  88,   66,  -9,   -70, -23, 69, -89, 30,  -38, 90,
    -64, 126, 90,  -94, 123,  72,  -36,  125, 47,  70, 107, -46, -70, 92,
    74,  80,  26,  -33, 68,   66,  -31,  -51, 37,  67, -49, -33, -87, -113,
    76,  -87, 47,  119, 126,  63,  -110, 88,  -5,  5,  66,  122, 39,  -3,
    13,  -21, -25, 42,  -106, -68, 10,   41,  -46, 122};
