// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3x3_dilation_5x5_input_int4_input_weights[45] = {
    173, 190, 47,  173, 166, 243, 58, 17,  227, 245, 248, 166, 25,  166, 151,
    103, 207, 24,  32,  31,  9,   50, 174, 93,  197, 46,  245, 247, 165, 121,
    182, 78,  148, 59,  176, 146, 70, 28,  112, 4,   79,  136, 198, 87,  169};

const int8_t *const conv_3x3_dilation_5x5_input_int4_weights = conv_3x3_dilation_5x5_input_int4_input_weights;
