// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3x3_dilation_5x5_input_int4_output[50] = {
    -11, -25, -7,  -30, -3,  -35, 5,   38,  2,   11,  0,   -94, -17,
    -46, -2,  -56, -4,  -15, 5,   20,  -7,  -14, -7,  -22, -5,  -18,
    -7,  -46, -2,  -8,  -15, -73, -17, -38, -13, -31, -9,  -22, -17,
    -24, -15, -19, -4,  -32, -7,  5,   -11, -8,  -20, -33};

const int8_t *const conv_3x3_dilation_5x5_input_int4_output_ref = conv_3x3_dilation_5x5_input_int4_output;
