// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_NCHW_IN_DIM                                                  \
    {                                                                          \
        4, 9, 3, 19,                                                           \
    }
#define TRANSPOSE_NCHW_PERM                                                    \
    {                                                                          \
        0, 3, 1, 2,                                                            \
    }
#define TRANSPOSE_NCHW_SIZE 2052
#define TRANSPOSE_NCHW_PERM_SIZE 4
#define TRANSPOSE_NCHW_OUT_DIM                                                 \
    {                                                                          \
        4, 19, 9, 3,                                                           \
    }
