// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_2_input_bias[23] = {
    87, -98, -62, -54, -54,  -78, -87, 71,   13,  54,  0, 98,
    76, -84, -22, 22,  -128, -6,  -49, -122, -29, -84, 93};

const int32_t *const fully_connected_int4_2_biases = fully_connected_int4_2_input_bias;
