// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_2_input_tensor[84] = {
    59,  65,  -23,  12,   105,  -74, -59,  54,  -101, -96, 44,   25,  117, -66,
    56,  -94, 17,   57,   80,   -54, -44,  -43, 35,   80,  63,   -67, -76, 1,
    72,  64,  0,    -57,  -106, 67,  113,  116, -8,   -77, -127, -91, 1,   121,
    -95, -73, -102, -96,  18,   9,   -107, 64,  82,   -69, 30,   35,  -81, -33,
    -54, -89, 117,  -122, -37,  27,  72,   -11, -24,  79,  -42,  -35, 23,  124,
    126, -78, 11,   -65,  -124, -57, -62,  80,  9,    -90, -117, -37, 103, 108};

const int8_t *const fully_connected_int4_2_input = fully_connected_int4_2_input_tensor;
