// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_2_output[23] = {
    11, 32, 19, 21,  9,  23, 12, -7, 20, -10, 0, -8,
    25, -4, 8,  -13, 13, 11, 26, 17, 0,  28,  31};

const int8_t *const fully_connected_int4_2_output_ref = fully_connected_int4_2_output;
