// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once

#define CONV_4_INT4_INPUT_BATCHES 1
#define CONV_4_INT4_IN_CH 3
#define CONV_4_INT4_OUT_CH 3
#define CONV_4_INT4_INPUT_W 5
#define CONV_4_INT4_INPUT_H 5
#define CONV_4_INT4_FILTER_X 2
#define CONV_4_INT4_FILTER_Y 3
#define CONV_4_INT4_STRIDE_X 2
#define CONV_4_INT4_STRIDE_Y 2
#define CONV_4_INT4_PADDING VALID
#define CONV_4_INT4_DILATION_X 1
#define CONV_4_INT4_DILATION_Y 1
#define CONV_4_INT4_BATCH_SIZE 1
#define CONV_4_INT4_OUT_ACTIVATION_MIN -128
#define CONV_4_INT4_OUT_ACTIVATION_MAX 127
#define CONV_4_INT4_DST_SIZE 12
#define CONV_4_INT4_OUTPUT_H 2
#define CONV_4_INT4_OUTPUT_W 2
#define CONV_4_INT4_INPUT_OFFSET 128
#define CONV_4_INT4_OUTPUT_OFFSET 0
#define CONV_4_INT4_PAD_X 0
#define CONV_4_INT4_PAD_Y 0
