// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_4_int4_input_weights[27] = {
    185, 101, 243, 15, 5,  109, 220, 204, 24, 148, 144, 221, 189, 90,
    37,  102, 159, 65, 64, 116, 120, 131, 48, 57,  228, 230, 126};

const int8_t *const conv_4_int4_weights = conv_4_int4_input_weights;
