// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_4_int4_input_tensor[75] = {
    -32, 86,   68,   -31, -50, -96,  -41,  43,   120,  6,    -52, 79,  13,
    95,  -88,  -96,  -45, -4,  -119, 38,   -7,   -75,  -25,  -80, -45, -17,
    3,   -105, 79,   2,   93,  -93,  -118, 79,   71,   -119, 26,  13,  22,
    -93, 100,  -119, -30, -44, 113,  -52,  -87,  -48,  -39,  33,  14,  -6,
    71,  63,   108,  -16, 10,  68,   -96,  -126, -90,  9,    -61, -95, -120,
    16,  -112, 105,  123, 95,  87,   23,   108,  -116, -45};

const int8_t *const conv_4_int4_input = conv_4_int4_input_tensor;
