// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_4_int4_output[12] = {-7, -11, 4, -7, -4, 19,
                                       0,  4,   4, -9, -7, 0};

const int8_t *const conv_4_int4_output_ref = conv_4_int4_output;
