// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_int4_input_weights[18] = {72,  31, 187, 250, 26,  248,
                                                    102, 95, 150, 231, 157, 246,
                                                    139, 72, 216, 226, 232, 7};

const int8_t *const conv_1_x_n_1_int4_weights = conv_1_x_n_1_int4_input_weights;
