// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_int4_input_tensor[8] = {39, 117, 40,  108,
                                                  76, 46,  -68, 71};

const int8_t *const conv_1_x_n_1_int4_input = conv_1_x_n_1_int4_input_tensor;
