// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_int4_output[6] = {-7, -7, -9, -4, 15, -13};

const int8_t *const conv_1_x_n_1_int4_output_ref = conv_1_x_n_1_int4_output;
