// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_1_int4_output_multiplier[3] = {1486862592, 1156905856,
                                                        1275947776};

const int32_t *const conv_1_x_n_1_int4_output_mult = conv_1_x_n_1_int4_output_multiplier;
