// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int64_t requantize_s64_bias[8] = {896291,  1260690, 529959,  365914,
                                        1463419, 1092762, 1944887, 3894114};

const int64_t *const requantize_s64_biases = requantize_s64_bias;
