// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t requantize_s64_output_multiplier[8] = {
    1758013824, 1800655360, 1793344640, 1814455168,
    1718523904, 1806338944, 1785668736, 1793234816};

const int32_t *const requantize_s64_output_mult = requantize_s64_output_multiplier;
