// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t requantize_s64_output[48] = {
    -1516,  -4064, -13576, 744,    -9819,  1878,   10851,  2293,   -5654, -2533,
    -6027,  -2615, 5005,   -16617, -9237,  4043,   -18823, 1710,   -6993, -2930,
    7260,   -7311, -1469,  27634,  23209,  2071,   8025,   -21532, -9863, -6113,
    -11874, 3743,  24418,  -3674,  -10930, 6566,   -10711, 9961,   16970, -7660,
    -12748, -6443, 12479,  -4353,  25204,  -23673, -11234, 3605};

const int16_t *const requantize_s64_output_ref = requantize_s64_output;
