// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t int16xint8xint32_4_weights[16] = {7,   58,  125, 127,  -104, 59,
                                               -61, -54, 92,  -107, -123, -107,
                                               127, 101, 33,  24};
