// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_6_input_tensor[85] = {
    42,   -19,  100, 101, 57,   -68,  -76, -42, -125, 27,   111, 0,   37,
    -114, -35,  39,  -83, 107,  74,   -98, 12,  12,   119,  29,  -62, 70,
    75,   -3,   97,  73,  103,  -103, -72, 3,   90,   121,  14,  124, 110,
    45,   72,   -36, -56, 69,   -107, 35,  -46, -108, 32,   53,  4,   -19,
    -82,  -106, 63,  118, 76,   -119, -3,  112, 32,   -69,  70,  6,   -36,
    57,   14,   32,  88,  -107, -9,   113, 24,  -87,  -116, 46,  -57, -115,
    -14,  105,  -58, 103, 60,   -33,  -25};
