// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_6_output[34] = {
    107, 121, 100, 124, 110, 119, 72,  -36, 70,  75,  111, 97,
    73,  103, 32,  53,  4,   90,  121, 14,  124, 118, 76,  72,
    46,  112, 69,  -14, 105, 6,   103, 60,  53,  32};
