// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_MATRIX_IN_DIM                                                \
    {                                                                          \
        5, 20, 0, 0,                                                           \
    }
#define TRANSPOSE_MATRIX_PERM                                                  \
    {                                                                          \
        1, 0,                                                                  \
    }
#define TRANSPOSE_MATRIX_SIZE 100
#define TRANSPOSE_MATRIX_PERM_SIZE 2
#define TRANSPOSE_MATRIX_OUT_DIM                                               \
    {                                                                          \
        20, 5, 0, 0,                                                           \
    }
