// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOLING_4_BATCH_SIZE 1
#define MAXPOOLING_4_INPUT_N 1
#define MAXPOOLING_4_INPUT_W 1
#define MAXPOOLING_4_INPUT_H 20
#define MAXPOOLING_4_INPUT_C 2
#define MAXPOOLING_4_FILTER_W 1
#define MAXPOOLING_4_FILTER_H 3
#define MAXPOOLING_4_STRIDE_W 1
#define MAXPOOLING_4_STRIDE_H 3
#define MAXPOOLING_4_PAD SAME
#define MAXPOOLING_4_ACTIVATION_MAX 127
#define MAXPOOLING_4_ACTIVATION_MIN -128
#define MAXPOOLING_4_OUTPUT_C 2
#define MAXPOOLING_4_OUTPUT_W 1
#define MAXPOOLING_4_OUTPUT_H 7
#define MAXPOOLING_4_PADDING_H 0
#define MAXPOOLING_4_PADDING_W 0
