// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_4_input_tensor[40] = {
    46,  -47,  69,  -100, 116, -80, 28,  103, -67,  115, -85, 122, 104, -104,
    -16, -108, 31,  105,  4,   14,  73,  -82, -115, -39, -72, -23, -60, 107,
    -14, 44,   -15, -44,  -67, 33,  -58, 48,  125,  118, 6,   23};
