// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_dilation_golden_int4_input_tensor[24] = {
    -73,  56,  43,  68,   -125, 23, 59,  87,  114, 66,  41, -79,
    -122, -11, -49, -121, -31,  73, 111, -35, 8,   -22, 4,  31};

const int8_t *const conv_dilation_golden_int4_input = conv_dilation_golden_int4_input_tensor;
