// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_dilation_golden_int4_input_weights[6] = {31, 158, 206,
                                                           83, 246, 139};

const int8_t *const conv_dilation_golden_int4_weights = conv_dilation_golden_int4_input_weights;
