// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_dilation_golden_int4_output[72] = {
    -3, 6,  -9, -3, 8,  -11, -3, 8,  -11, -1, 5,  -7, -1, 3,  -4, -1, 3,  -4,
    -1, -1, -4, 0,  -4, 0,   -2, 2,  -1,  -3, 2,  -5, 0,  -2, 5,  0,  1,  -2,
    -1, -1, -6, -2, 1,  -5,  -2, -1, -2,  -3, 3,  -3, -1, 0,  3,  -1, 0,  2,
    0,  -2, 0,  0,  0,  0,   0,  -3, 3,   0,  -5, 1,  0,  0,  0,  0,  -1, 3};

const int8_t *const conv_dilation_golden_int4_output_ref = conv_dilation_golden_int4_output;
