// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_dilation_golden_int4_output_multiplier[3] = {
    1978252672, 1412493056, 1249904768};

const int32_t *const conv_dilation_golden_int4_output_mult = conv_dilation_golden_int4_output_multiplier;
