// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t minimum_broadcast_ch_int8_input_tensor_1[16] = {
    51, 99, 4, -64, 25, 78, -115, -31, 8, -32, -76, 80, 111, 75, -39, 15};
