// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_int4_input_weights[18] = {
    3,   221, 155, 203, 198, 152, 238, 74,  139,
    168, 42,  53,  38,  92,  211, 123, 110, 41};

const int8_t *const conv_3x2_dilation_int4_weights = conv_3x2_dilation_int4_input_weights;
