// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_3x2_dilation_int4_input_bias[2] = {127, 70};

const int32_t *const conv_3x2_dilation_int4_biases = conv_3x2_dilation_int4_input_bias;
