// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_int4_input_tensor[18] = {
    -99,  72, -15, -6,  24,  99,  104,  -25, -16,
    -125, -7, 45,  116, -46, -93, -118, -97, -83};

const int8_t *const conv_3x2_dilation_int4_input = conv_3x2_dilation_int4_input_tensor;
