// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_int4_output[18] = {
    -10, 5, 1, 1, 1, 4, 7, -2, 5, -2, 1, 2, 4, -1, -3, -2, -6, -2};

const int8_t *const conv_3x2_dilation_int4_output_ref = conv_3x2_dilation_int4_output;
