// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOLING_2_BATCH_SIZE 1
#define MAXPOOLING_2_INPUT_N 1
#define MAXPOOLING_2_INPUT_W 12
#define MAXPOOLING_2_INPUT_H 1
#define MAXPOOLING_2_INPUT_C 5
#define MAXPOOLING_2_FILTER_W 3
#define MAXPOOLING_2_FILTER_H 1
#define MAXPOOLING_2_STRIDE_W 1
#define MAXPOOLING_2_STRIDE_H 2
#define MAXPOOLING_2_PAD SAME
#define MAXPOOLING_2_ACTIVATION_MAX 127
#define MAXPOOLING_2_ACTIVATION_MIN -128
#define MAXPOOLING_2_OUTPUT_C 5
#define MAXPOOLING_2_OUTPUT_W 12
#define MAXPOOLING_2_OUTPUT_H 1
#define MAXPOOLING_2_PADDING_H 0
#define MAXPOOLING_2_PADDING_W 1
