// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_2_input_tensor[60] = {
    62,  28, 121,  -97, -50, 75,   8,  -80, 42,   81, 74,  25,   60, -36,  58,
    -86, 83, 53,   -21, 100, 85,   32, 13,  -4,   33, 10,  -119, 67, -35,  -94,
    12,  5,  -72,  -26, 72,  -120, 99, 53,  97,   -7, 108, -62,  -5, -113, -127,
    -1,  81, -109, 115, -20, 124,  14, 95,  -112, 38, -99, 61,   -7, 60,   90};
