// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maxpooling_2_output[60] = {
    75,  28, 121, 42,  81,  75,  28, 121, 42,  81,  75,  83, 60, 42,  100,
    85,  83, 60,  -4,  100, 85,  83, 67,  -4,  100, 85,  32, 67, -4,  72,
    12,  99, 67,  97,  72,  108, 99, 53,  97,  72,  108, 99, 53, 115, -7,
    124, 81, 95,  115, 38,  124, 81, 95,  115, 90,  124, 61, 95, 60,  90};
