// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_3_int4_input_weights[96] = {
    100, 217, 173, 165, 53,  219, 139, 208, 42,  31,  111, 53,  8,   141,
    213, 133, 174, 102, 185, 157, 145, 231, 226, 134, 85,  19,  82,  134,
    179, 246, 144, 59,  255, 202, 208, 57,  113, 190, 183, 220, 160, 198,
    21,  19,  222, 222, 198, 17,  224, 142, 209, 233, 187, 65,  169, 253,
    100, 194, 139, 96,  166, 144, 85,  167, 84,  124, 250, 235, 50,  129,
    71,  20,  85,  67,  243, 153, 69,  224, 156, 153, 134, 0,   138, 77,
    35,  53,  179, 11,  140, 230, 77,  222, 35,  227, 64,  213};

const int8_t *const conv_1_x_n_3_int4_weights = conv_1_x_n_3_int4_input_weights;
