// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOLING_1_BATCH_SIZE 1
#define MAXPOOLING_1_INPUT_N 1
#define MAXPOOLING_1_INPUT_W 9
#define MAXPOOLING_1_INPUT_H 5
#define MAXPOOLING_1_INPUT_C 3
#define MAXPOOLING_1_FILTER_W 9
#define MAXPOOLING_1_FILTER_H 5
#define MAXPOOLING_1_STRIDE_W 1
#define MAXPOOLING_1_STRIDE_H 2
#define MAXPOOLING_1_PAD VALID
#define MAXPOOLING_1_ACTIVATION_MAX 127
#define MAXPOOLING_1_ACTIVATION_MIN -128
#define MAXPOOLING_1_OUTPUT_C 3
#define MAXPOOLING_1_OUTPUT_W 1
#define MAXPOOLING_1_OUTPUT_H 1
#define MAXPOOLING_1_PADDING_H 0
#define MAXPOOLING_1_PADDING_W 0
