// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_int4_input_tensor[80] = {
    59,  79,  105,  105, 12,   47,   87,  -1,   -22,  -46, 96,   21,  -21, 58,
    -86, -37, 75,   103, -102, -45,  99,  95,   -109, 73,  19,   31,  119, 64,
    87,  79,  80,   -1,  59,   -96,  -37, 114,  38,   -97, 5,    -30, -62, -30,
    63,  48,  17,   82,  -22,  -77,  -50, 124,  10,   113, -62,  -69, -28, -56,
    -46, 18,  -116, -78, 21,   -11,  -34, -82,  -88,  61,  -105, -97, 57,  108,
    27,  -45, -82,  58,  47,   -115, 2,   -113, 93,   6};

const int8_t *const kernel1x1_stride_x_y_2_int4_input = kernel1x1_stride_x_y_2_int4_input_tensor;
