// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_int4_input_weights[13] = {
    136, 31, 137, 198, 187, 109, 144, 124, 232, 177, 145, 187, 13};

const int8_t *const kernel1x1_stride_x_y_2_int4_weights = kernel1x1_stride_x_y_2_int4_input_weights;
