// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_2_int4_output_multiplier[5] = {
    1297389056, 1748626688, 1751327232, 1967611136, 1345937408};

const int32_t *const kernel1x1_stride_x_y_2_int4_output_mult = kernel1x1_stride_x_y_2_int4_output_multiplier;
