// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_int4_output[20] = {
    -5, -19, -10, -9, -20, -4, -6, 3,  -13, -14,
    -3, -8,  -1,  -2, -7,  -2, -7, -9, -10, -12};

const int8_t *const kernel1x1_stride_x_y_2_int4_output_ref = kernel1x1_stride_x_y_2_int4_output;
