// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_int4_input_bias[15] = {
    -58, 66, 87, -123, 84, -65, 43, -11, 51, 126, 96, 109, 53, 52, -76};

const int32_t *const kernel1x1_stride_x_y_int4_biases = kernel1x1_stride_x_y_int4_input_bias;
