// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_int4_output_multiplier[15] = {
    1255757568, 1321300864, 1634102400, 1583735168, 1773255808,
    1992901376, 1766555520, 1722447744, 1983046400, 2115597568,
    1242934912, 1150293120, 1781482368, 1286890368, 1815934080};

const int32_t *const kernel1x1_stride_x_y_int4_output_mult = kernel1x1_stride_x_y_int4_output_multiplier;
