// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#include "config_data.h"
#include "lhs_input_tensor.h"
#include "lhs_transposed_tensor.h"
#include "output.h"
#include "rhs_input_tensor.h"
#include "rhs_transposed_tensor.h"
