// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOLING_7_BATCH_SIZE 1
#define MAXPOOLING_7_INPUT_N 1
#define MAXPOOLING_7_INPUT_W 4
#define MAXPOOLING_7_INPUT_H 2
#define MAXPOOLING_7_INPUT_C 1
#define MAXPOOLING_7_FILTER_W 2
#define MAXPOOLING_7_FILTER_H 2
#define MAXPOOLING_7_STRIDE_W 2
#define MAXPOOLING_7_STRIDE_H 2
#define MAXPOOLING_7_PAD VALID
#define MAXPOOLING_7_ACTIVATION_MAX 6
#define MAXPOOLING_7_ACTIVATION_MIN 0
#define MAXPOOLING_7_OUTPUT_C 1
#define MAXPOOLING_7_OUTPUT_W 2
#define MAXPOOLING_7_OUTPUT_H 1
#define MAXPOOLING_7_PADDING_H 0
#define MAXPOOLING_7_PADDING_W 0
