// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_3DIM2_IN_DIM                                                 \
    {                                                                          \
        5, 4, 20, 0,                                                           \
    }
#define TRANSPOSE_3DIM2_PERM                                                   \
    {                                                                          \
        1, 2, 0,                                                               \
    }
#define TRANSPOSE_3DIM2_SIZE 400
#define TRANSPOSE_3DIM2_PERM_SIZE 3
#define TRANSPOSE_3DIM2_OUT_DIM                                                \
    {                                                                          \
        4, 20, 5, 0,                                                           \
    }
