TARGET ?= dsp_test

NUCLEI_SDK_ROOT ?= ../../$(BUILD_ROOT_DIR)
NUCLEI_SDK_NMSIS ?= $(NUCLEI_SDK_ROOT)/NMSIS

SRCDIRS = .

INCDIRS = .. . $(BUILD_ROOT_DIR) \
	$(NUCLEI_SDK_NMSIS)/DSP/Include \
	$(NUCLEI_SDK_NMSIS)/DSP/Include/dsp \
	$(NUCLEI_SDK_NMSIS)/DSP/PrivateInclude

LIBDIRS = $(NUCLEI_SDK_NMSIS)/Library/DSP/GCC

DSP_ENABLE ?= ON
RISCV_ALIGN ?= OFF
COMMON_FLAGS ?= -O2
BENCH_UNIT ?=
NEWLIB ?=

ifeq ($(BENCH_UNIT),instret)
$(warning "Benchmark by reading cpu instret")
COMMON_FLAGS += -DREAD_CYCLE=read_cpu_instret
else
$(warning "Benchmark by reading cpu cycle")
endif

ifeq ($(DSP_ENABLE),ON)
ifeq ($(VECTOR_ENABLE),ON)
$(warning "Use and link with RISC-V DSP enabled library")
COMMON_FLAGS += -D__RISCV_FEATURE_DSP=1 -D__RISCV_FEATURE_VECTOR=1 -D__RISCV_FEATURE_VECTOR=1
else
$(warning "Use and link with RISC-V DSP enabled library")
COMMON_FLAGS += -D__RISCV_FEATURE_DSP=1
endif
else
ifeq ($(VECTOR_ENABLE),ON)
$(warning "Use and link with RISC-V VECTOR enabled library")
COMMON_FLAGS += -D__RISCV_FEATURE_VECTOR=1 -D__RISCV_FEATURE_VECTOR=1
else
$(warning "Use and link with RISC-V DSP disabled library")
ifeq ($(RISCV_ALIGN),ON)
COMMON_FLAGS += -DRISCV_ALIGN_ACCESS
endif
endif
endif
LDLIBS = -lnmsis_dsp_$(RISCV_ARCH) -lm

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
