// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t maximum_broadcast_height_int8_input_tensor_1[68] = {
    -105, -61, -100, -91, 22,  55,  42,   66,  32,  -85,  -46, -22,  113, 12,
    4,    56,  -39,  70,  11,  53,  -110, 108, 113, -22,  31,  -127, 80,  102,
    125,  -8,  -48,  -76, -63, 32,  -119, 120, 15,  49,   -21, -127, 2,   -42,
    -59,  31,  79,   113, 2,   -68, -85,  -48, -46, 115,  -39, -19,  18,  63,
    51,   91,  -3,   -90, 57,  -12, 15,   80,  -16, -114, 114, -83};
