// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t avgpooling_4_output[42] = {
    65,  48,  9,   -75, 32,  9,  18, 70,  -74, 20,  -8,  105, -95, -52,
    -48, -5,  -52, -22, 15,  2,  -3, 40,  -8,  -65, -25, -40, 80,  25,
    27,  -66, 64,  -2,  -23, 22, 72, -30, 56,  10,  26,  16,  51,  20};
