// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define MAXPOOL_INT16_1_BATCH_SIZE 2
#define MAXPOOL_INT16_1_INPUT_N 4
#define MAXPOOL_INT16_1_INPUT_W 5
#define MAXPOOL_INT16_1_INPUT_H 1
#define MAXPOOL_INT16_1_INPUT_C 2
#define MAXPOOL_INT16_1_FILTER_W 3
#define MAXPOOL_INT16_1_FILTER_H 3
#define MAXPOOL_INT16_1_STRIDE_W 2
#define MAXPOOL_INT16_1_STRIDE_H 1
#define MAXPOOL_INT16_1_PAD SAME
#define MAXPOOL_INT16_1_ACTIVATION_MAX 30000
#define MAXPOOL_INT16_1_ACTIVATION_MIN -30000
#define MAXPOOL_INT16_1_OUTPUT_C 2
#define MAXPOOL_INT16_1_OUTPUT_W 3
#define MAXPOOL_INT16_1_OUTPUT_H 1
#define MAXPOOL_INT16_1_PADDING_H 1
#define MAXPOOL_INT16_1_PADDING_W 1
