// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_1_input_tensor[20] = {
    3814,   12231,  -10600, -18917, -9223, 657,   -16449, 9365, 17374,  6858,
    -25909, -11065, -15733, -11747, 1005,  -9356, -30365, 4781, -10724, 1655};
