// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_1_output[12] = {3814,  12231, -9223,  9365,
                                            17374, 9365,  -15733, -11065,
                                            1005,  4781,  -10724, 4781};
