// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill_output_multiplier[9] = {
    1702025856, 1702602112, 1702652928, 1701478784, 1702742912,
    1702644992, 1701978880, 1702839424, 1702276992};

const int32_t *const int16xint8_spill_output_mult = int16xint8_spill_output_multiplier;
