// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define AVGPOOLING_BATCH_SIZE 1
#define AVGPOOLING_INPUT_N 1
#define AVGPOOLING_INPUT_W 22
#define AVGPOOLING_INPUT_H 12
#define AVGPOOLING_INPUT_C 20
#define AVGPOOLING_FILTER_W 6
#define AVGPOOLING_FILTER_H 5
#define AVGPOOLING_STRIDE_W 9
#define AVGPOOLING_STRIDE_H 5
#define AVGPOOLING_PAD SAME
#define AVGPOOLING_ACTIVATION_MAX 127
#define AVGPOOLING_ACTIVATION_MIN -128
#define AVGPOOLING_OUTPUT_C 20
#define AVGPOOLING_OUTPUT_W 3
#define AVGPOOLING_OUTPUT_H 3
#define AVGPOOLING_PADDING_H 1
#define AVGPOOLING_PADDING_W 1
