// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_3_input_bias[47] = {
    -36, 127, -58, -25, -64,  125, -102, -87,  94,  -110, -1,   66,
    48,  30,  -18, 24,  -23,  73,  -10,  -56,  -71, -103, -103, 104,
    -16, -47, 62,  64,  67,   114, -43,  -107, -10, 113,  -101, 78,
    -58, 100, 12,  34,  -118, 97,  12,   -82,  -96, -51,  93};

const int32_t *const kernel1x1_int4_3_biases = kernel1x1_int4_3_input_bias;
