// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_int4_3_output_shift[47] = {
    -9, -7, -10, -8, -8, -7, -7, -8, -7, -8, -8, -6, -9, -7, -7, -7,
    -8, -8, -8,  -7, -7, -7, -7, -7, -6, -7, -7, -7, -9, -8, -9, -7,
    -8, -9, -8,  -7, -6, -9, -8, -7, -9, -7, -7, -7, -7, -7, -8};
