// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_5_int4_input_tensor[68] = {
    -73, -59, -50, -115, 62, -105, 121,  57,  116, -22, -119, 55,   -12, 105,
    -8,  39,  110, -121, 86, 11,   14,   -32, -69, 34,  -107, -87,  37,  126,
    94,  44,  -62, 45,   91, 67,   46,   -40, 58,  98,  -114, -100, -78, -80,
    48,  11,  89,  64,   95, -118, -106, 67,  109, 54,  97,   -38,  16,  -67,
    102, 67,  105, 110,  26, -15,  86,   -41, -44, 73,  -89,  20};

const int8_t *const conv_1_x_n_5_int4_input = conv_1_x_n_5_int4_input_tensor;
