// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_5_int4_input_weights[6] = {129, 209, 211, 182, 69, 49};

const int8_t *const conv_1_x_n_5_int4_weights = conv_1_x_n_5_int4_input_weights;
