// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t int16xint8_dilation_1_weights[16] = {
    -113, 110, 111, 26, -4, 13, 127, 2, -111, -8, 11, -105, -7, 119, -127, 51};
