// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_NHCW_IN_DIM                                                  \
    {                                                                          \
        1, 1, 128, 128,                                                        \
    }
#define TRANSPOSE_NHCW_PERM                                                    \
    {                                                                          \
        0, 1, 3, 2,                                                            \
    }
#define TRANSPOSE_NHCW_SIZE 16384
#define TRANSPOSE_NHCW_PERM_SIZE 4
#define TRANSPOSE_NHCW_OUT_DIM                                                 \
    {                                                                          \
        1, 1, 128, 128,                                                        \
    }
