// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t int16xint8_output[40] = {
    -8330, 32767,  -5926,  6098,   20700,  642,   1778,  -5364, 18416,  -16623,
    3652,  -22207, -26074, 16579,  -13948, 12701, 1890,  -597,  -14003, -18579,
    5214,  15197,  -17230, 23351,  22828,  -834,  19942, 18458, -14680, 508,
    5503,  1691,   10106,  -15704, -15940, -2921, -6253, 7869,  -14778, 21095};

const int16_t *const int16xint8_output_ref = int16xint8_output;
