// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_int4_input_weights[13] = {
    66, 146, 128, 220, 111, 44, 206, 87, 154, 57, 196, 5, 1};

const int8_t *const kernel1x1_stride_x_y_1_int4_weights = kernel1x1_stride_x_y_1_int4_input_weights;
