// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_int4_input_tensor[80] = {
    32,  85,   -88,  -66, -26, -113, -67, 109, -96, -73,  -12, 126, 89, 28,
    -40, -125, -79,  93,  -51, -59,  -14, -9,  11,  87,   106, 109, 91, -87,
    116, 105,  -60,  48,  -55, -75,  1,   -86, 50,  -121, 35,  23,  47, 103,
    120, 73,   -125, 122, 81,  -26,  106, 122, -45, 38,   -96, 96,  95, -54,
    -99, -126, -64,  116, 11,  84,   -34, 103, 97,  -43,  95,  102, 55, 35,
    111, -73,  -121, 4,   117, -25,  -23, -3,  6,   15};

const int8_t *const kernel1x1_stride_x_y_1_int4_input = kernel1x1_stride_x_y_1_int4_input_tensor;
