// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_int4_output[20] = {
    14, -27, 3,   -5,  1,  10,  -35, -7, -20, 10,
    6,  -51, -27, -23, 16, -12, -5,  11, -11, 1};

const int8_t *const kernel1x1_stride_x_y_1_int4_output_ref = kernel1x1_stride_x_y_1_int4_output;
