// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_int4_output_multiplier[5] = {
    1211932544, 1075524352, 1202657280, 1696518656, 2126691840};

const int32_t *const kernel1x1_stride_x_y_1_int4_output_mult = kernel1x1_stride_x_y_1_int4_output_multiplier;
