// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_3_input_bias[25] = {
    -125, 73, -69, -125, -81, -120, 39,  -61,  62,  10,   30,  94, -9,
    78,   -6, 112, -28,  -76, 97,   113, -118, -90, -116, -53, -57};

const int32_t *const fully_connected_int4_3_biases = fully_connected_int4_3_input_bias;
