// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_3_input_tensor[86] = {
    -95,  121, -42,  69,   -14, -116, -76, -85,  -59, 44,   -95, 25,  -51,
    50,   25,  -84,  -121, 19,  76,   38,  93,   16,  -19,  5,   68,  -59,
    -16,  -58, -117, -73,  -75, -97,  77,  37,   43,  -109, -21, -9,  96,
    59,   -27, 82,   -28,  -74, -10,  -76, -40,  -32, 109,  5,   64,  94,
    4,    -12, 2,    -111, -95, 122,  8,   92,   -62, -55,  37,  -54, -72,
    -104, 103, 120,  10,   -61, 76,   -35, -127, -40, -45,  -1,  -93, -19,
    -10,  27,  -58,  -78,  -92, -85,  21,  69};

const int8_t *const fully_connected_int4_3_input = fully_connected_int4_3_input_tensor;
