// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_3_output[25] = {
    14, 25, 27, 20, 16, -20, 4,  38, 31, 5, -16, -12, 13,
    8,  -9, 26, 18, -9, -12, -1, 24, 22, 0, 13,  10};

const int8_t *const fully_connected_int4_3_output_ref = fully_connected_int4_3_output;
