// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#include "config_data.h"
#include "input_bias.h"
#include "input_tensor.h"
#include "input_weights.h"
#include "output.h"
