// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once

#define TRANSPOSE_WCHN_IN_DIM                                                  \
    {                                                                          \
        4, 3, 3, 21,                                                           \
    }
#define TRANSPOSE_WCHN_PERM                                                    \
    {                                                                          \
        2, 3, 1, 0,                                                            \
    }
#define TRANSPOSE_WCHN_SIZE 756
#define TRANSPOSE_WCHN_PERM_SIZE 4
#define TRANSPOSE_WCHN_OUT_DIM                                                 \
    {                                                                          \
        3, 21, 3, 4,                                                           \
    }
