// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_5_int4_output[32] = {-65, -45, -28, -41, -37, -34, -56, -37,
                                       -25, -32, -18, -37, -1,  -47, -38, -31,
                                       -30, -36, -57, -34, -35, -11, -59, -72,
                                       -59, -4,  -42, -58, -41, -13, -30, -35};

const int8_t *const conv_5_int4_output_ref = conv_5_int4_output;
