// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t conv_5_int4_output_multiplier[1] = {1221544832};

const int32_t *const conv_5_int4_output_mult = conv_5_int4_output_multiplier;
