// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_int4_input_tensor[36] = {
    -60, -120, -124, -119, -113, -46, 11,  -55, -2,   26,  8,   -70,
    107, 74,   -9,   108,  33,   84,  27,  -62, -117, -43, 47,  -118,
    -95, 60,   -123, -89,  -104, 104, -47, -44, 89,   76,  101, -87};

const int8_t *const conv_out_activation_int4_input = conv_out_activation_int4_input_tensor;
