// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_int4_input_weights[36] = {
    134, 207, 232, 85,  39,  234, 50,  22,  108, 200, 228, 149,
    47,  122, 75,  40,  84,  91,  132, 68,  230, 43,  31,  102,
    137, 72,  75,  141, 236, 168, 76,  219, 221, 142, 146, 17};

const int8_t *const conv_out_activation_int4_weights = conv_out_activation_int4_input_weights;
