// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_int4_output[18] = {1,  -46, -2, -51, -4, -27,
                                                    -2, -42, 20, -48, -7, -41,
                                                    1,  6,   -1, -23, -3, -33};

const int8_t *const conv_out_activation_int4_output_ref = conv_out_activation_int4_output;
