// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras
// version 3.8.0). Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t int16xint8xint32_1_output[40] = {
    -9685,  -11154, -12650, 6618,  30557,  6725,  6402,   7395,  545,   -13266,
    -5726,  12395,  -10781, 15994, -11375, 1437,  -19522, 1356,  10375, -27393,
    2224,   32767,  -3267,  8264,  3177,   7192,  -14166, 17594, -5849, 14044,
    -17686, -2276,  3934,   9287,  -6158,  -4464, 25254,  15067, -1381, -4998};

const int16_t *const int16xint8xint32_1_output_ref = int16xint8xint32_1_output;
