// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_6_input_tensor[89] = {
    89,  -100, 118, -104, 21,  -25,  -45,  115,  21,  -19,  -72, -31, 32,
    -17, -31,  40,  18,   -18, -118, -98,  -77,  -75, -128, 1,   -51, 112,
    -72, -17,  103, -92,  -47, 48,   63,   4,    13,  118,  4,   29,  -115,
    41,  92,   -40, -38,  -39, -16,  -119, 114,  119, -67,  -38, -27, -105,
    89,  75,   -45, 119,  -5,  -41,  24,   10,   6,   47,   57,  100, 24,
    -68, 7,    43,  116,  57,  -110, -109, -37,  -54, 118,  19,  75,  -113,
    38,  -48,  -84, -32,  -56, -28,  -90,  -110, -68, 77,   15};

const int8_t *const fully_connected_int4_6_input = fully_connected_int4_6_input_tensor;
