// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.18.0 and revision
// v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_6_output[22] = {
    82, 127, 63, 99, 89, 81, 127, 58, 63,  126, 40,
    66, 65,  78, 59, 39, 89, 80,  76, 127, 42,  96};

const int8_t *const fully_connected_int4_6_output_ref = fully_connected_int4_6_output;
